Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Declaration_Completed__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>Declaration</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Equal_Opportunity_Completed__c.field-meta.xml
<CustomField>
    <fullName>Equal_Opportunity_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>Equal Opportunity</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CandidateIDlegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDlegacy__c</fullName>
    <description>this is used for candidate that are being migrated from other system but their original IDs must be preserved</description>
    <externalId>true</externalId>
    <inlineHelpText>IF a candidate must still be reference by an original ID (for payroll) used this field</inlineHelpText>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CitizenshipGroup__c.field-meta.xml
<CustomField>
    <fullName>IP_CitizenshipGroup__c</fullName>
    <label>Citizenship Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_StudentLoan__c.field-meta.xml
<CustomField>
    <fullName>IP_StudentLoan__c</fullName>
    <label>Student Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Medical_Completed__c.field-meta.xml
<CustomField>
    <fullName>Medical_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>Medical</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/New_Starter_Form__c.field-meta.xml
<CustomField>
    <fullName>New_Starter_Form__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>New Starter Declaration Form</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Candidate Requested P45?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/PORTW_Completed__c.field-meta.xml
<CustomField>
    <fullName>PORTW_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Completed. Gareth Rogan</description>
    <label>PORTW</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay - not enough</fullName>
            </value>
            <value>
                <fullName>Pay - incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable work</fullName>
            </value>
            <value>
                <fullName>Not enough work</fullName>
            </value>
            <value>
                <fullName>Work break</fullName>
            </value>
            <value>
                <fullName>Better opportunity</fullName>
            </value>
            <value>
                <fullName>Worker performance/compliance issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Sync_Pay_Profile__c.field-meta.xml
<CustomField>
    <fullName>Sync_Pay_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Pay Profile</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/TOE_Completed__c.field-meta.xml
<CustomField>
    <fullName>TOE_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>TOE</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/WTR_Completed__c.field-meta.xml
<CustomField>
    <fullName>WTR_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>WTR</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BuildingSocietyNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNumber__c</fullName>
    <label>Building Society Roll No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressCounty__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressCounty__c</fullName>
    <label>Business Address County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine1__c</fullName>
    <description>for recording the business address for the candidate, LTD, umbrella, etc. only is required</description>
    <label>Business Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine2__c</fullName>
    <label>Business Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressPostcode__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressPostcode__c</fullName>
    <label>Business Address Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressTown__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressTown__c</fullName>
    <label>Business Address Town</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_NewStarterTaxStatus__c.field-meta.xml
<CustomField>
    <fullName>IP_NewStarterTaxStatus__c</fullName>
    <label>New Starter Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_StudentLoan__c.field-meta.xml
<CustomField>
    <fullName>IP_StudentLoan__c</fullName>
    <label>Student Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leaver?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pay - Not Enough</fullName>
            </value>
            <value>
                <fullName>Pay - Incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable Work</fullName>
            </value>
            <value>
                <fullName>Not Enough Work</fullName>
            </value>
            <value>
                <fullName>Work Break</fullName>
            </value>
            <value>
                <fullName>Better Opportunity</fullName>
            </value>
            <value>
                <fullName>Worker Performance/Compliance Issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
            <value>
                <fullName>Dismissal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_payProfileProcessBuilder.cls
@isTest
public class Test_payProfileProcessBuilder {
     @testSetup 
    static void payprofileSetup() {
        Account acct1 = TestDataFactory.createCandidateAccount(1)[0]; 
        insert acct1;
         insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
  
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c= false);
        
        Contact cond1 = TestDataFactory.createCandidate(acct1.id, 1)[0];
        cond1.Sync_Pay_Profile__c=False;
        cond1.IP_CitizenshipGroup__c='Citizen of the UK';
        cond1.Equal_Opportunity_Completed__c = true;
        cond1.sirenum__National_Insurance__c='AA123456B';
        cond1.Birthdate=date.newInstance(1992, 04, 23);
        cond1.EEO_Gender__c = 'Male';
        cond1.Declaration_Completed__c = true;
        cond1.Medical_Completed__c = true;
        cond1.WTR_Completed__c = true;
        cond1.New_Starter_Form__c = true;
        cond1.TOE_Completed__c =true;
        cond1.PORTW_Completed__c = true;
        Insert cond1;
         system.debug('check contact'+cond1);
              
       
        RecordType condRec = [Select Id  From RecordType Where sObjectType = 'IP_PayProfile__c' And DeveloperName='PAYE'];
        
        IP_PayProfile__c pp1 = new IP_PayProfile__c(IP_Candidate__c=cond1.id,
                                                    IP_PaymentType__c='BACS', 
                                                    IP_Status__c='Active', 
                                                    RecordTypeId=condRec.id,
                                                    IP_LastPassedToTempest__c=system.today(),
                                                    IP_AccountNumber__c='21313212',
                                                    IP_BankAccountName__c='kbc',
                                                    IP_BusinessAddressTown__c='ddssd',  
                                                    IP_BuildingSocietyNumber__c='dcsd12',
                                                    IP_BusinessAddressCounty__c='sds',
                                                    IP_BusinessAddressLine1__c='bfg',
                                                    IP_BusinessAddressLine2__c='hhj',
                                                    IP_BusinessAddressPostcode__c='sfssd',
                                                    IP_SortCode__c='213123',
                                                    IP_NewStarterTaxStatus__c='A',
                                                    IP_StudentLoan__c='N',
                                                    IP_PayrollID__c='payprof1'
                                                   );      
        insert pp1;
        

        }
        @istest 
    static void processdata1() {
      
          IP_PayProfile__c pprof = [select id,P45_Requested__c,Reason_for_Leaving1__c,IP_PasstoTempest__c,IP_PayrollID__c  from IP_PayProfile__c where IP_PayrollID__c= 'payprof1'];
        
        pprof.P45_Requested__c = TRUE;
        pprof.Reason_for_Leaving1__c = 'Dismissal';
    
            update pprof;
    }
    
    @istest 
    static void processdata2() {
           insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
           insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c= true);
          RecordType AccRec = [Select Id  From RecordType Where sObjectType = 'Account' And DeveloperName= 'Candidate'];
      Account acc = new Account();
        acc.name = 'abctest';
        acc.RecordTypeId = AccRec.id;
        insert acc;
        RecordType condRec = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'Candidate'];
       
            Contact con = new Contact(AccountID = acc.id, 
                                          RecordTypeId=condRec.id,
                                          FirstName ='Taji',
                                          Salutation ='Mr',
                                          Email = 'riu@test76.com',
                                          MailingCity='ggn',
                                          MailingCountry='india',
                                          MailingPostalCode='110092',
                                          MailingState='Haryana',
                                          LastName ='tajicandidate23',  
                                          sirenum__National_Insurance__c='AA323232A', 
                                          IP_CandidateIDlegacy__c='test123',
                                          MailingStreet='abc',
                                          P45_Requested__c=true,
                                          PayrollLeaver__c=null,
                                          Title = 'TestLastName1',
                                          Initials__c = 'TestLastName1',
                                          Birthdate = Date.valueOf('1992-02-20'),
                                          Phone = '987999444',
                                          EEO_Gender__c = 'M',
                                          IP_CategoryOfWork__c='Catering' );
           
        insert con;
       
           
        id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('PAYE').getRecordTypeId();

         IP_PayProfile__c payprofile1 = new IP_PayProfile__c();
         payprofile1.RecordTypeId = payRTId;
          
       payprofile1.IP_Candidate__c = con.id;
         payprofile1.IP_CompanyName__c='sfdc';
         payprofile1.IP_Status__c = 'Inactive'; 
         payprofile1.IP_CompanyRegNo__c  = 'ad123456';
         payprofile1.IP_VATNumber__c     = '123456789';
         payprofile1.IP_PayrollID__c  = 't12786c3';
         payprofile1.IP_VATRegistered__c=true;
         payprofile1.IP_OkToSupply__c=1;
         payprofile1.IP_BusinessAddressLine1__c='test address 1';
         payprofile1.IP_BusinessAddressLine2__c='test address 2';
         payprofile1.IP_BusinessAddressTown__c='town city';
         payprofile1.IP_BusinessAddressPostcode__c='12345678';
         payprofile1.IP_PayFrequency__c='Weekly';
         payprofile1.IP_PaymentType__c='BACS';
      //  payprofile1
         insert payprofile1;
    }
    
    }