Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Declaration_Completed__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>Declaration</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Allpayprofiles__c.field-meta.xml
<CustomField>
    <fullName>IP_Allpayprofiles__c</fullName>
    <label>All Pay Profiles</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LCC__c.field-meta.xml
<CustomField>
    <fullName>IP_LCC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LCC</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LTDCount__c.field-meta.xml
<CustomField>
    <fullName>IP_LTDCount__c</fullName>
    <inlineHelpText>this is a count of active LTD company pay profiles</inlineHelpText>
    <label>LTD pay profile count</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>LTD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_StudentLoan__c.field-meta.xml
<CustomField>
    <fullName>IP_StudentLoan__c</fullName>
    <label>Student Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_WorkerStartDate__c.field-meta.xml
<CustomField>
    <fullName>IP_WorkerStartDate__c</fullName>
    <description>Date of the workers first paid work for the Agency</description>
    <inlineHelpText>Worker Start Date which is the first day of their first shift.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>Last Date Worked</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Candidate Requested P45?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Suppression_Reason__c.field-meta.xml
<CustomField>
    <fullName>P45_Suppression_Reason__c</fullName>
    <label>P45 Suppression Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Suppressed</fullName>
                <default>true</default>
                <label>Not Suppressed</label>
            </value>
            <value>
                <fullName>Long Term Sick</fullName>
            </value>
            <value>
                <fullName>Extended Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Employee Grievance</fullName>
            </value>
            <value>
                <fullName>Tribunal</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Pregnancy related absence due to sickness</fullName>
            </value>
            <value>
                <fullName>Public Duties</fullName>
            </value>
            <value>
                <fullName>Industrial Action</fullName>
            </value>
            <value>
                <fullName>Contractually Agreed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Person_Status__c.field-meta.xml
<CustomField>
    <fullName>Person_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/PORTW_Completed__c.field-meta.xml
<CustomField>
    <fullName>PORTW_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Completed. Gareth Rogan</description>
    <label>PORTW</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay - not enough</fullName>
            </value>
            <value>
                <fullName>Pay - incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable work</fullName>
            </value>
            <value>
                <fullName>Not enough work</fullName>
            </value>
            <value>
                <fullName>Work break</fullName>
            </value>
            <value>
                <fullName>Better opportunity</fullName>
            </value>
            <value>
                <fullName>Worker performance/compliance issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/WTR_Completed__c.field-meta.xml
<CustomField>
    <fullName>WTR_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>WTR</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Date_P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>Date_P45_Requested__c</fullName>
    <label>Leaver Requested Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BuildingSocietyNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNumber__c</fullName>
    <label>Building Society Roll No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_NewStarterTaxStatus__c.field-meta.xml
<CustomField>
    <fullName>IP_NewStarterTaxStatus__c</fullName>
    <label>New Starter Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_StudentLoan__c.field-meta.xml
<CustomField>
    <fullName>IP_StudentLoan__c</fullName>
    <label>Student Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>P45 Emailed Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leaver?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pay - Not Enough</fullName>
            </value>
            <value>
                <fullName>Pay - Incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable Work</fullName>
            </value>
            <value>
                <fullName>Not Enough Work</fullName>
            </value>
            <value>
                <fullName>Work Break</fullName>
            </value>
            <value>
                <fullName>Better Opportunity</fullName>
            </value>
            <value>
                <fullName>Worker Performance/Compliance Issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
            <value>
                <fullName>Dismissal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_P45_Internal__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_P45_Internal__c</fullName>
    <label>Reason for P45 (Internal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Declined work</fullName>
            </value>
            <value>
                <fullName>Other dismissal</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Transferred to LTD</fullName>
            </value>
            <value>
                <fullName>Branch Transfer/BM</fullName>
                <isActive>false</isActive>
                <label>Branch Transfer/BM</label>
            </value>
            <value>
                <fullName>Eight Week Leaver/PE</fullName>
                <isActive>false</isActive>
                <label>Eight Week Leaver/PE</label>
            </value>
            <value>
                <fullName>Payroll Leaver/PL</fullName>
                <isActive>false</isActive>
                <label>Payroll Leaver/PL</label>
            </value>
            <value>
                <fullName>Payroll holiday/PH</fullName>
                <isActive>false</isActive>
                <label>Payroll holiday/PH</label>
            </value>
            <value>
                <fullName>Payroll inactive/PI</fullName>
                <isActive>false</isActive>
                <label>Payroll inactive/PI</label>
            </value>
            <value>
                <fullName>T.U.P.E transfers/TU</fullName>
                <isActive>false</isActive>
                <label>T.U.P.E transfers/TU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/LTD.recordType-meta.xml
<RecordType>
    <fullName>LTD</fullName>
    <active>true</active>
    <label>LTD</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/Umbrella.recordType-meta.xml
<RecordType>
    <fullName>Umbrella</fullName>
    <active>true</active>
    <label>Umbrella</label>
</RecordType>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/ReinstateButtonLightning.cls
/**
 * MR: USE Schema classess to get RecordType Id instead of using SOQL as part of RJSPT-87 JIRA ticket.
 * CHANGE REQUIREMNTS: JIRA RJSPT-87: Reinstate Process - Not working for certain workers
 * DATE OF UPDATE: 23/07/2020
 */
public class ReinstateButtonLightning{
	@AuraEnabled
    public static IP_PayProfile__c getPayProfileDetail(String payProfileId) {
		IP_PayProfile__c payProfile = [Select id,IP_Status__c from IP_PayProfile__c where id=:payProfileId];
		return payProfile;
	}
	
	@AuraEnabled
    public static String updatedata(String payProfileId) {
    	System.debug('********Limits.getQueries()::::: '+Limits.getQueries());
		try {
			//ADDED FOLLOWING VAR TO BULKIFY THE CODE EXECUTION 
			Map<Id, ts2__Certification__c> allCerts = new  Map<Id, ts2__Certification__c>();
			List<sirenum__Ticket__c> allComps = new List<sirenum__Ticket__c>();
			List<IP_PayProfile__c> allPayProfiles = new List<IP_PayProfile__c>();

			List<ts2__Certification__c> certlist = new  List<ts2__Certification__c>();
			List<ts2__Certification__c> drivinglist = new  List<ts2__Certification__c>();
			List<ts2__Certification__c> certlistupdate = new  List<ts2__Certification__c>();
			List<sirenum__Ticket__c> comp = new List<sirenum__Ticket__c>();
			
			IP_PayProfile__c payrec = [Select id,RecordType.name,IP_Payroll_Leaver__c,IP_NewStarterTaxStatus__c,
									IP_Candidate__c,IP_Status__c,Date_P45_Requested__c,IP_StudentLoan__c,P45_Requested__c,
									P45_Date_by_Head_Office__c,Reason_for_Leaving1__c,Reason_for_P45_Internal__c,
									IP_PassToTempest__c,IP_LastPassedToTempest__c,IP_BankAccountName__c,IP_AccountNumber__c,
									IP_SortCode__c,IP_BuildingSocietyNumber__c from IP_PayProfile__c where id=:payProfileId];
			Date today = System.today();
			Date future = System.today().addDays(30);
			id contactid = payrec.IP_Candidate__c;
			String paystatus = payrec.IP_Status__c;
			string rectype = payrec.RecordType.name;
				
			Contact con = [Select ID,Person_Status__c,WTR_Completed__c,IP_Allpayprofiles__c,IP_WorkerStartDate__c,
							P45_Suppression_Reason__c,PORTW_Completed__c,IP_LCC__c,Declaration_Completed__c ,IP_LTDCount__c,
							IP_UmbCount__c,IP_ActivePAYEPayProfiles__c,Medical_Completed__c,TOE_Completed__c,New_Starter_Form__c,
							Equal_Opportunity_Completed__c,VISA_Expiration_Date__c from Contact where id=:contactid];
				
				if(paystatus == 'Inactive'){
					if(con.IP_Allpayprofiles__c == 0){
						drivinglist = [Select id,IP_Status__c,RecordType.Name,ts2__Contact__c from ts2__Certification__c 
										where ts2__Contact__c=:contactid and RecordType.Name in ('Driving Licence','DVLA Licence Check') 
										and IP_Status__c !='Lapsed'];
						if(drivinglist.size()>0){
							for(ts2__Certification__c c:drivinglist){
								c.IP_Status__c = 'Lapsed';
								allCerts.put(c.Id, c);
							}							
						}
						comp = [Select id,sirenum__TicketType__c,sirenum__TicketType__r.Name,sirenum__Valid__c,sirenum__Revoked__c,sirenum__Valid_until__c from sirenum__Ticket__c where sirenum__TicketType__r.Name in ('LGV C1 Licence','PCV Licence','PCV Licence (Minibus)','LGV C + E Licence (102 Restriction)','LGV C1+E Licence','LGV C Licence','LGV C + E Licence','Driving Licence (Standard)','LGV ADR C1 Licence','LGV HIAB C Licence','LGV ADR C1+E Licence','DVLA Licence Check')  and sirenum__Owner__c=:contactid];
						if(comp.size()>0){
							for(sirenum__Ticket__c t : comp){
								if(payrec.P45_Date_by_Head_Office__c != null){
									t.sirenum__Valid_until__c = payrec.P45_Date_by_Head_Office__c;
								}
								else{
									t.sirenum__Valid_until__c = System.today().addDays(-1);
								}
								allComps.add(t);
							}
						}
					}

					payrec.IP_NewStarterTaxStatus__c = null; 
					payrec.IP_Status__c = 'Active'; 
					payrec.Date_P45_Requested__c = null; 
					payrec.IP_StudentLoan__c =null; 
					payrec.P45_Requested__c =false; 
					payrec.P45_Date_by_Head_Office__c = null; 
					payrec.Reason_for_Leaving1__c =null;
					payrec.IP_PassToTempest__c = false; 
					payrec.IP_LastPassedToTempest__c = null; 
					payrec.IP_Payroll_Leaver__c = '';
					if(payrec.RecordType.name == 'PAYE' || payrec.RecordType.name == 'LTD'){
						payrec.IP_BankAccountName__c ='';
						payrec.IP_AccountNumber__c ='';
						payrec.IP_SortCode__c ='';
						payrec.IP_BuildingSocietyNumber__c = '';
					}
					allPayProfiles.add(payrec);

					system.debug('active pay profile1'+con.IP_Allpayprofiles__c);
					if(con.IP_Allpayprofiles__c == 0){
						system.debug('active pay profile'+con.IP_Allpayprofiles__c);
						con.IP_LCC__c =false;
						con.Declaration_Completed__c = false;
						con.Medical_Completed__c = false;
						con.TOE_Completed__c = false;
						con.New_Starter_Form__c = false;
						con.Person_Status__c = 'Active';
						con.IP_WorkerStartDate__c = null;
						con.P45_Suppression_Reason__c = null;
						con.WTR_Completed__c = false;               
					}   
					else{
						if(rectype == 'PAYE' && con.IP_LTDCount__c == 0 && con.IP_UmbCount__c == 0){
							con.TOE_Completed__c = false;
							con.New_Starter_Form__c = false;
							con.WTR_Completed__c =false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}   
						else if (rectype == 'PAYE' && con.IP_LTDCount__c > 0){
							con.TOE_Completed__c = false;
							con.WTR_Completed__c = false;
							con.New_Starter_Form__c = false;
						}
						else if(rectype == 'PAYE' && con.IP_UmbCount__c > 0 && con.IP_LTDCount__c == 0){
							con.TOE_Completed__c = false;
							con.New_Starter_Form__c = false;
							con.WTR_Completed__c =false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}
						else if(rectype == 'LTD' && con.IP_UmbCount__c == 0 && con.IP_ActivePAYEPayProfiles__c == 0){
							con.IP_LCC__c = false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}
						else if(rectype == 'LTD' && con.IP_ActivePAYEPayProfiles__c > 0){
							con.IP_LCC__c = false;
						}
						else if(rectype == 'LTD' && con.IP_UmbCount__c > 0 && con.IP_ActivePAYEPayProfiles__c == 0){
							con.IP_LCC__c = false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}
						else{
							system.debug('In Umbrella');
						}
					}
					
					if(con.IP_Allpayprofiles__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
								where ts2__Contact__c=:contactid and RecordType.name not in ('Right to Work','Equal Opportunities Question','WTRT- Driving') and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}else if(rectype == 'PAYE' && con.IP_UmbCount__c == 0 && con.IP_LTDCount__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
								where ts2__Contact__c=:contactid and RecordType.name in ('TOE','New Starter Declaration Form','Declaration','Medical','WTR') and IP_Status__c != 'Lapsed'];

						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else if(rectype == 'PAYE' && con.IP_LTDCount__c > 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
									where ts2__Contact__c=:contactid and RecordType.name in ('TOE','New Starter Declaration Form','WTR') and IP_Status__c != 'Lapsed'];

						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else if(rectype == 'PAYE' && con.IP_UmbCount__c > 0 && con.IP_LTDCount__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
									where ts2__Contact__c=:contactid and RecordType.name in ('TOE','New Starter Declaration Form','Declaration','Medical','WTR') and IP_Status__c != 'Lapsed'];

						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}           
					}
					else if(rectype == 'LTD' && con.IP_ActivePAYEPayProfiles__c == 0 && con.IP_UmbCount__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
						where ts2__Contact__c=:contactid and RecordType.name in ('Limited Company Contract','Declaration','Medical') and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else if(rectype == 'LTD' && con.IP_ActivePAYEPayProfiles__c > 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
							where ts2__Contact__c=:contactid and RecordType.name = 'Limited Company Contract' and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else if(rectype == 'LTD' && con.IP_UmbCount__c > 0 && con.IP_ActivePAYEPayProfiles__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
						where ts2__Contact__c=:contactid and RecordType.name in ('Limited Company Contract','Declaration','Medical') and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else{
						system.debug('In Umbrella');
					}            
				} 
				else{
					if(con.IP_Allpayprofiles__c == 1){
						drivinglist = [Select id,IP_Status__c,RecordType.Name,ts2__Contact__c from ts2__Certification__c where ts2__Contact__c=:contactid and RecordType.Name in ('Driving Licence','DVLA Licence Check') and IP_Status__c !='Lapsed'];
						if(drivinglist.size()>0){
							for(ts2__Certification__c c:drivinglist)						{
								c.IP_Status__c = 'Lapsed';
								allCerts.put(c.Id, c);
							}
						}
						comp = [Select id,sirenum__TicketType__c,sirenum__TicketType__r.Name,sirenum__Valid__c,sirenum__Revoked__c,
								sirenum__Valid_until__c from sirenum__Ticket__c where sirenum__TicketType__r.Name 
								in ('LGV C1 Licence','PCV Licence','PCV Licence (Minibus)','LGV C + E Licence (102 Restriction)','LGV C1+E Licence','LGV C Licence','LGV C + E Licence','Driving Licence (Standard)','LGV ADR C1 Licence','LGV HIAB C Licence','LGV ADR C1+E Licence','DVLA Licence Check')  and sirenum__Owner__c=:contactid];
						if(comp.size()>0){
							for(sirenum__Ticket__c t : comp){
								if(payrec.P45_Date_by_Head_Office__c != null){
									t.sirenum__Valid_until__c = payrec.P45_Date_by_Head_Office__c;
								}
								else{
									t.sirenum__Valid_until__c = System.today().addDays(-1);
								}
								allComps.add(t);
							}
						}
					}
					payrec.IP_NewStarterTaxStatus__c = null; 
					payrec.IP_Status__c = 'Active'; 
					payrec.Date_P45_Requested__c = null; 
					payrec.IP_StudentLoan__c =null; 
					payrec.P45_Requested__c =false; 
					payrec.P45_Date_by_Head_Office__c = null; 
					payrec.Reason_for_Leaving1__c =null;
					payrec.IP_PassToTempest__c = false; 
					payrec.IP_LastPassedToTempest__c = null; 
					payrec.IP_Payroll_Leaver__c = '';
					if(payrec.RecordType.name == 'PAYE' || payrec.RecordType.name == 'LTD'){
						payrec.IP_BankAccountName__c ='';
						payrec.IP_AccountNumber__c ='';
						payrec.IP_SortCode__c ='';
						payrec.IP_BuildingSocietyNumber__c = '';
					}
					allPayProfiles.add(payrec);
					if(con.IP_Allpayprofiles__c == 0){
					
						system.debug('active pay profile'+con.IP_Allpayprofiles__c);
						con.IP_LCC__c =false;
						con.Declaration_Completed__c = false;
						con.Medical_Completed__c = false;
						con.TOE_Completed__c = false;
						con.New_Starter_Form__c = false;
						con.Person_Status__c = 'Active';
						con.IP_WorkerStartDate__c = null;
						con.P45_Suppression_Reason__c = null;
						con.WTR_Completed__c = false;               
					}   
					else
					{
						if(rectype == 'PAYE' && con.IP_LTDCount__c == 0 && con.IP_UmbCount__c == 0)
						{
							con.TOE_Completed__c = false;
							con.New_Starter_Form__c = false;
							con.WTR_Completed__c =false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}   
						else if (rectype == 'PAYE' && con.IP_LTDCount__c > 0)
						{
							con.TOE_Completed__c = false;
							con.WTR_Completed__c =false;
							con.New_Starter_Form__c = false;
						}
						else if(rectype == 'PAYE' && con.IP_UmbCount__c > 0 && con.IP_LTDCount__c == 0)
						{
							con.TOE_Completed__c = false;
							con.New_Starter_Form__c = false;
							con.WTR_Completed__c =false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}
						else if(rectype == 'LTD' && con.IP_UmbCount__c == 0 && con.IP_ActivePAYEPayProfiles__c == 0)
						{
							con.IP_LCC__c = false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}
						else if(rectype == 'LTD' && con.IP_ActivePAYEPayProfiles__c > 0)
						{
							con.IP_LCC__c = false;
						}
						else if(rectype == 'LTD' && con.IP_UmbCount__c > 0 && con.IP_ActivePAYEPayProfiles__c == 0)
						{
							con.IP_LCC__c = false;
							con.Declaration_Completed__c = false;
							con.Medical_Completed__c = false;
						}
						else
						{
							system.debug('In Umbrella');
						}
					}
					
					if(con.IP_Allpayprofiles__c == 1){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c where ts2__Contact__c=:contactid and RecordType.name not in ('Right to Work','Equal Opportunities Question','WTRT- Driving') and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist)
						{
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					
					else if(rectype == 'PAYE' && con.IP_UmbCount__c == 0 && con.IP_LTDCount__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c where ts2__Contact__c=:contactid and RecordType.name in ('TOE','New Starter Declaration Form','Declaration','Medical','WTR') and IP_Status__c != 'Lapsed'];

						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}				
					}
					else if(rectype == 'PAYE' && con.IP_LTDCount__c > 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c where ts2__Contact__c=:contactid and RecordType.name in ('TOE','New Starter Declaration Form','WTR') and IP_Status__c != 'Lapsed'];
						
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else if(rectype == 'PAYE' && con.IP_UmbCount__c > 0 && con.IP_LTDCount__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c where ts2__Contact__c=:contactid and RecordType.name in ('TOE','New Starter Declaration Form','Declaration','Medical','WTR') and IP_Status__c != 'Lapsed'];

						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}           
					}
					else if(rectype == 'LTD' && con.IP_ActivePAYEPayProfiles__c == 0 && con.IP_UmbCount__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c 
						where ts2__Contact__c=:contactid and RecordType.name in ('Limited Company Contract','Declaration','Medical') and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else if(rectype == 'LTD' && con.IP_ActivePAYEPayProfiles__c > 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c where ts2__Contact__c=:contactid and RecordType.name = 'Limited Company Contract' and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else if(rectype == 'LTD' && con.IP_UmbCount__c > 0 && con.IP_ActivePAYEPayProfiles__c == 0){
						certlist = [Select id,ts2__Contact__c,IP_Status__c,Verfied__c from ts2__Certification__c where ts2__Contact__c=:contactid and RecordType.name in ('Limited Company Contract','Declaration','Medical') and IP_Status__c != 'Lapsed'];
						for(ts2__Certification__c c:certlist){
							c.IP_Status__c = 'Lapsed';
							allCerts.put(c.Id, c);
						}
					}
					else{
						system.debug('In Umbrella');
					}
				}
				//COMMITING ALL UPDATES AT TEH END
				update allPayProfiles;
				update allComps;
				System.debug('+++++ allCerts: '+allCerts);
				update new List<ts2__Certification__c>(allCerts.values());
				update con;
				update allPayProfiles; //MR: THIS UPDATE IS ADDED TO RE-CALCULATE THE FIELDS. NOT IDEAL BUT DOES THE JOB
				System.debug('********Limits.getQueries()::::: '+Limits.getQueries());
				return System.Label.Reinstate_Success;
        }
        catch (DmlException e) {
            return e.getMessage();
        }

   }
}