Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_18DigitID__c.field-meta.xml
<CustomField>
    <fullName>IP_18DigitID__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesforce 18 digit ID</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CandidateIDlegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDlegacy__c</fullName>
    <description>this is used for candidate that are being migrated from other system but their original IDs must be preserved</description>
    <externalId>true</externalId>
    <inlineHelpText>IF a candidate must still be reference by an original ID (for payroll) used this field</inlineHelpText>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Consent_from_Data_Store__c.field-meta.xml
<CustomField>
    <fullName>IP_Consent_from_Data_Store__c</fullName>
    <label>Consent Last Updated</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Criminal_Conviction__c.field-meta.xml
<CustomField>
    <fullName>IP_Criminal_Conviction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Criminal Conviction</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Email__c.field-meta.xml
<CustomField>
    <fullName>IP_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Equal_Ops__c.field-meta.xml
<CustomField>
    <fullName>IP_Equal_Ops__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Equal Ops</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Health_Reasonable_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>IP_Health_Reasonable_Adjustments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Health/Reasonable Adjustments</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Last_Consent_Requested__c.field-meta.xml
<CustomField>
    <fullName>IP_Last_Consent_Requested__c</fullName>
    <label>Last Consent Requested</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Last_Consent_Requested_By__c.field-meta.xml
<CustomField>
    <fullName>IP_Last_Consent_Requested_By__c</fullName>
    <label>Last Consent Requested by</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine1__c</fullName>
    <description>This is a system field to populate information into back office</description>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine2__c</fullName>
    <description>This is a system interface field as salesforce splits up the salesforce field address line information</description>
    <label>Mailing Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Medical_History__c.field-meta.xml
<CustomField>
    <fullName>IP_Medical_History__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical History</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Phone__c.field-meta.xml
<CustomField>
    <fullName>IP_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Phone</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Post__c.field-meta.xml
<CustomField>
    <fullName>IP_Post__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_SMS__c.field-meta.xml
<CustomField>
    <fullName>IP_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/UpdateDataStore.cls
public class UpdateDataStore
{
@future(callout=true)
public static void sendconsentdata(Set<id> consentupdates){
            String callresult;
                String callresult1;
        Requestbody.GdprData req = new Requestbody.GdprData();
        req.grant_type  = 'client_credentials';
        req.client_id = 'e7838bae08a24a08b51b0a0b378cfed363280d993367457689e008f74c46b3a1';
        req.client_secret = '33907fc327cd46e696f35dac31ac089c';
        
        String JSONBody = JSON.serialize(req); 
        
         System.debug('JSON Body-->'+JSONBody);
         string endpoint = 'https://prod-integration-dx.impellamapi.com/api/v1/oauth2/token';
         Map<String,String> loginheaders = new Map<String, String>();
         loginheaders.put('Content-Type', 'application/json;charset=UTF-8');
         
         HttpResponse res = RestCalloutUtil.MakeCallout(endpoint, 'POST', JSONBody, loginheaders);
        
        system.debug('@@response body '+res.getBody());
        ResponseParser.gdprResponse responsegdpr =(ResponseParser.gdprResponse)System.JSON.deserialize(res.getbody(), ResponseParser.gdprResponse.class);
        
         System.Debug('Respone--> '+responsegdpr);
         Contact con = [Select id,IP_18DigitID__c,FirstName,IP_Last_Consent_Requested_By__c,IP_Consent_from_Data_Store__c,IP_Last_Consent_Requested__c,IP_CandidateIDlegacy__c,IP_Phone__c,IP_Criminal_Conviction__c,IP_Email__c,IP_Equal_Ops__c,IP_Health_Reasonable_Adjustments__c,IP_Medical_History__c,IP_Post__c,IP_SMS__c,LastName,email,IP_MailingAddressLine1__c,IP_MailingAddressLine2__c,MailingCity,MailingState,MailingPostalcode,MobilePhone,Phone From Contact where id in :consentupdates];
         Requestbody.Candidatedata req1 = new Requestbody.Candidatedata();
          Requestbody.consentOption req2 = new Requestbody.consentOption();
           req2.Phone = con.IP_Phone__c;
           req2.SMS= con.IP_SMS__c;
           req2.Email = con.IP_Email__c;
           req2.Post = con.IP_Post__c;
           req2.CRBCHECK= con.IP_Criminal_Conviction__c;
           req2.MedicalOther= con.IP_Health_Reasonable_Adjustments__c;
           req2.MedicalHistory = con.IP_Medical_History__c;
           req2.EQUALOPS= con.IP_Equal_Ops__c;
            req1.brandName = 'Blue Arrow';
            req1.SourceIdentifier = con.IP_18DigitID__c; 
            req1.workerReference1 = con.IP_CandidateIDlegacy__c;
            req1.forename = con.Firstname;
            req1.surname = con.Lastname;
            req1.emailAddress = con.email;
            req1.addressLine1 = con.IP_MailingAddressLine1__c;
            req1.addressLine2 = con.IP_MailingAddressLine2__c;
            req1.city = con.MailingCity;
            req1.county = con.MailingState;
            req1.postcode = con.MailingPostalcode;
            req1.mobileNumber = con.MobilePhone;
            req1.telephoneNumber = con.Phone;
            req1.sendEmailRequest = false;
            req1.consentOptionsLastUpdateDate = con.IP_Consent_from_Data_Store__c;
            req1.consentOptions= req2;            
            String JSONBody1 = JSON.serialize(req1);
         Map<String,String> headers = new Map<String, String>();
         headers.put('Content-Type', 'application/json;charset=UTF-8');
         headers.put('Authorization', 'Bearer '+ responsegdpr.access_token);     
        System.debug('Request Body'+req1);
         string endpoint2 = 'https://prod-integration-dx.impellamapi.com/api/v1/consentregistrations/import';
        
         HttpResponse res1 = RestCalloutUtil.MakeCallout(endpoint2, 'POST', JSONBody1, headers); 
         System.debug('**Response check**'+res1.getStatusCode());
         System.debug('**Response Recieved**'+res1.getbody());    
         if(res1.getStatusCode() == 200)
         {           
         ResponseParser.Consentcallresponse responsestate =(ResponseParser.Consentcallresponse)System.JSON.deserialize(res1.getbody(), ResponseParser.Consentcallresponse.class);
         System.Debug('Respone-->'+responsestate);
         callresult = responsestate.registrationState;
         }
         else
         {
            ResponseParser.Consentcallresponse1 responsestate =(ResponseParser.Consentcallresponse1)System.JSON.deserialize(res1.getbody(), ResponseParser.Consentcallresponse1.class);
            callresult = responsestate.validationErrors[0]; 
         }
        // return callresult;    
         
        /* if(responsestate.validationErrors.size()>0 && res1.getStatusCode()!= 200)
         {
          callresult = responsestate.validationErrors[0];
         }
         else
         {
         callresult = responsestate.registrationState;
         }
         System.Debug('Variable-->'+callresult );
         System.Debug('Variable-->'+callresult1 );
         System.debug('check size'+responsestate.validationErrors.size());*/
         
}


}