Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_AvailableforRecontact__c.field-meta.xml
<CustomField>
    <fullName>IP_AvailableforRecontact__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Available for Recontact?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_DateAvailableforRecontact__c.field-meta.xml
<CustomField>
    <fullName>IP_DateAvailableforRecontact__c</fullName>
    <label>Date Available for Recontact</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/UpdaterecontacteddateCanddate.cls
global class UpdaterecontacteddateCanddate extends batchjobsch.BatchJobBase implements Database.Batchable<sObject>{

date dt = system.today();
 global Database.QueryLocator start(Database.BatchableContext BC){
 
   string query = 'select id, IP_DateAvailableforRecontact__c,IP_AvailableforRecontact__c from Contact where IP_DateAvailableforRecontact__c !=null and IP_DateAvailableforRecontact__c=:dt';
     return Database.getQueryLocator(query);
 }
 
 global void execute(Database.BatchableContext BC,List<Contact> scope){
 
 for(Contact c: scope)
 {     
         c.IP_AvailableforRecontact__c = true;    
 }
Database.update(scope,false);

}
 global void finish(Database.BatchableContext BC){
 super.finishBatch(BC);
}
}