Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_ActivePAYEPayProfiles__c.field-meta.xml
<CustomField>
    <fullName>IP_ActivePAYEPayProfiles__c</fullName>
    <label>Active PAYE Pay Profiles</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>PAYE</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_ActivePayProfiles__c.field-meta.xml
<CustomField>
    <fullName>IP_ActivePayProfiles__c</fullName>
    <label>Active Pay Profiles</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.P45_Requested__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Allpayprofiles__c.field-meta.xml
<CustomField>
    <fullName>IP_Allpayprofiles__c</fullName>
    <label>All Pay Profiles</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_EarliestExpiringComplianceDate__c.field-meta.xml
<CustomField>
    <fullName>IP_EarliestExpiringComplianceDate__c</fullName>
    <formula>IF( OR( Passport_Expiration_Date__c &lt;  VISA_Expiration_Date__c ,  ISNULL(VISA_Expiration_Date__c))  , Passport_Expiration_Date__c, VISA_Expiration_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Earliest Expiring Compliance Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LTDPayProfileCount__c.field-meta.xml
<CustomField>
    <fullName>IP_LTDPayProfileCount__c</fullName>
    <inlineHelpText>this is a count of active LTD company pay profiles</inlineHelpText>
    <label>LTD pay profile count</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>LTD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/Reinstatedtemplatedata.cls
public class Reinstatedtemplatedata{

public id con_Id{get; set;}
public boolean certcount{get;set;}
public boolean portwcount{get;set;}
public boolean payecount{get;set;}
public boolean ltdcount{get;set;}
public List<ts2__Certification__c> certlist = new List<ts2__Certification__c>();
public List<ts2__Certification__c> certlistall = new List<ts2__Certification__c>();
public List<ts2__Certification__c> portwcertlist = new List<ts2__Certification__c>();
public Contact conrec;
public Contact conrec1;
public integer allpaycount{get;set;}
public Date today = System.today();
public Date future = System.today().addDays(30);

public boolean getcertcount123()
{
certlist = [Select id,ts2__Contact__c from ts2__Certification__c where ts2__Contact__c = :con_Id and RecordType.name in ('Driving Licence') ];
certlistall = [Select id,ts2__Contact__c from ts2__Certification__c where ts2__Contact__c = :con_Id and RecordType.name in ('Driving Licence') and IP_Status__c = 'Lapsed'];

if(certlist.size()>0 && certlistall.size()>0)
{
if(certlist.size()==certlistall.size())
{
    certcount = true;
}
else
{
    certcount = false;
}
}
System.debug('check dvla count'+certcount);
return certcount;
}

public integer getallpaycount123()
{
conrec1 = [Select id,IP_ActivePAYEPayProfiles__c,IP_ActivePayProfiles__c,IP_LTDPayProfileCount__c,IP_Allpayprofiles__c from Contact where id=:con_Id];
allpaycount = Integer.valueOF(conrec1.IP_Allpayprofiles__c);

System.debug('paycount'+allpaycount);

return allpaycount;
}


public boolean getltdcount123()
{

conrec = [Select id,IP_ActivePAYEPayProfiles__c,IP_Allpayprofiles__c,IP_LTDPayProfileCount__c from Contact where id=:con_Id];
if(conrec.IP_LTDPayProfileCount__c == 1)
{
  ltdcount = true;  
}
else
{
    ltdcount = false;  
}
return payecount;
}

public boolean getpayecount123()
{

conrec = [Select id,IP_ActivePAYEPayProfiles__c,IP_ActivePayProfiles__c,IP_LTDPayProfileCount__c,IP_Allpayprofiles__c from Contact where id=:con_Id];
if(conrec.IP_ActivePAYEPayProfiles__c == 1)
{
  payecount = true;  
}
else
{
    payecount = false;  
}
return payecount;
}


public boolean getportwcount123()
{

portwcertlist = [Select id,ts2__Contact__r.IP_EarliestExpiringComplianceDate__c,ts2__Contact__c from ts2__Certification__c where ts2__Contact__c = :con_Id and RecordType.name = 'Right to Work' and (VISA_Type__c in ('Work Visa','Student Visa','Resident Card (with time limit)') OR Identification_Type__c  in ('Non EEA Passport','Leave to remain (Migration status document)','Certificate of Application or Application registration card and ECS check','ECS check') ) and ((ts2__Contact__r.IP_EarliestExpiringComplianceDate__c >=:today and  ts2__Contact__r.IP_EarliestExpiringComplianceDate__c <: future) OR ts2__Contact__r.IP_EarliestExpiringComplianceDate__c <:today) ];
if(portwcertlist.size()>0)
{
    portwcount = true;
}
else
{
    portwcount = false;
}
return portwcount;
}



}