Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_ActivePAYEPayProfiles__c.field-meta.xml
<CustomField>
    <fullName>IP_ActivePAYEPayProfiles__c</fullName>
    <label>Active PAYE Pay Profiles</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>PAYE</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Allpayprofiles__c.field-meta.xml
<CustomField>
    <fullName>IP_Allpayprofiles__c</fullName>
    <label>All Pay Profiles</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LTDPayProfileCount__c.field-meta.xml
<CustomField>
    <fullName>IP_LTDPayProfileCount__c</fullName>
    <inlineHelpText>this is a count of active LTD company pay profiles</inlineHelpText>
    <label>LTD pay profile count</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>LTD</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_UmbCount__c.field-meta.xml
<CustomField>
    <fullName>IP_UmbCount__c</fullName>
    <label>Umbrella pay profile count</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Umbrella</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_OkToSupply__c</field>
        <operation>equals</operation>
        <value>1</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Candidate Requested P45?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Person_Status__c.field-meta.xml
<CustomField>
    <fullName>Person_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay - not enough</fullName>
            </value>
            <value>
                <fullName>Pay - incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable work</fullName>
            </value>
            <value>
                <fullName>Not enough work</fullName>
            </value>
            <value>
                <fullName>Work break</fullName>
            </value>
            <value>
                <fullName>Better opportunity</fullName>
            </value>
            <value>
                <fullName>Worker performance/compliance issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Date_P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>Date_P45_Requested__c</fullName>
    <label>Leaver Requested Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leaver?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pay - Not Enough</fullName>
            </value>
            <value>
                <fullName>Pay - Incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable Work</fullName>
            </value>
            <value>
                <fullName>Not Enough Work</fullName>
            </value>
            <value>
                <fullName>Work Break</fullName>
            </value>
            <value>
                <fullName>Better Opportunity</fullName>
            </value>
            <value>
                <fullName>Worker Performance/Compliance Issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
            <value>
                <fullName>Dismissal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/CaptureReasonforLeavingcontroller.cls
public class CaptureReasonforLeavingcontroller{

   public String selectedleavingreason{get;set;}
   public String leavingreason{get;set;}
   public String currentRecordId {get;set;}
   List<IP_PayProfile__c> paylist = new List<IP_PayProfile__c>();
   List<IP_PayProfile__c> paylist1 = new List<IP_PayProfile__c>();
    List<Contact> conupdate= new List<Contact>();
    public string check1 {get;set;}
    public string check2 {get;set;}
    public CaptureReasonforLeavingcontroller() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        System.debug('Check id'+currentRecordId  );
        check1 = null;
        check2 = null;
    }

   
     public List<selectOption> allleavingreason{
        get {
          List<SelectOption> options = new List<SelectOption>(); 
        
        options.add(new SelectOption('Pay - Not Enough','Pay - Not Enough')); 
        options.add(new SelectOption('Pay - Incorrect','Pay - Incorrect')); 
        options.add(new SelectOption('Unsuitable Work','Unsuitable Work')); 
        options.add(new SelectOption('Not Enough Work','Not Enough Work')); 
        options.add(new SelectOption('Work Break','Work Break')); 
        options.add(new SelectOption('Better Opportunity','Better Opportunity')); 
        options.add(new SelectOption('Worker Performance/Compliance Issue','Worker Performance/Compliance Issue')); 
        options.add(new SelectOption('Employed by Client','Employed by Client')); 
        options.add(new SelectOption('Dismissal','Dismissal')); 
        
        return options;        
          }
        set;
    }
    public pagereference processprofiles()
    {
        if(selectedleavingreason == null)
        {
             ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR,System.Label.P45B2Ferror10);
             ApexPages.addMessage(myMsg1);
        }
        else
        {
    paylist = [select id,IP_Status__c,P45_Requested__c,Date_P45_Requested__c,RecordType.name,IP_LastPassedToTempest__c,Reason_for_Leaving1__c,IP_PasstoTempest__c  from IP_PayProfile__c where IP_Status__c = 'Active' and IP_Candidate__c =:currentRecordId];
    
    for(IP_PayProfile__c pay : paylist)
    {
        if(pay.IP_LastPassedToTempest__c == null)
        {
            pay.IP_Status__c = 'Inactive';
            pay.Reason_for_Leaving1__c = selectedleavingreason;
            pay.P45_Requested__c = TRUE;
            pay.Date_P45_Requested__c = System.today();
            check2 = 'false';
            
        }
        else
        {
            if(pay.RecordType.Name == 'PAYE')
            {
                pay.Reason_for_Leaving1__c = selectedleavingreason;
                pay.P45_Requested__c = TRUE;
                pay.Date_P45_Requested__c = System.today();
                pay.IP_PasstoTempest__c = TRUE;
                check1 = 'true';
                
            }
            else
            {
                pay.IP_Status__c = 'Inactive';
                pay.Reason_for_Leaving1__c = selectedleavingreason;
                pay.P45_Requested__c = TRUE;
                pay.Date_P45_Requested__c = System.today();
                check2 = 'false';
            }
        }
    }
    try{
    update paylist;
    }
    catch(DmlException e)
    {
        ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
        ApexPages.addMessage(myMsg1);
        system.debug('Inside Exception'+e.getMessage());
        check1 = null;
    }
    
    
    Contact con = [Select id,IP_Allpayprofiles__c,IP_UmbCount__c,IP_LTDPayProfileCount__c,IP_ActivePAYEPayProfiles__c  from Contact where id =:currentRecordId];
    system.debug('**Check count**'+con.IP_Allpayprofiles__c);
    if(con.IP_Allpayprofiles__c == 0)
    {
        con.Person_Status__c = 'Inactive';
        conupdate.add(con);
    }
    update conupdate;
    system.debug('check 1 value'+ check1);
    system.debug('check 2 value'+ check2);
    if(check1 == 'true')
    {
         ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.CONFIRM,System.Label.P45B2Ferror9);
         ApexPages.addMessage(myMsg1);
    }
    if(check2 == 'false' && check1 == null)
    {
        ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.CONFIRM,System.Label.P45B2Ferror8);
         ApexPages.addMessage(myMsg1);
    }
        }
     return null;
    }
}