Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Allpayprofiles__c.field-meta.xml
<CustomField>
    <fullName>IP_Allpayprofiles__c</fullName>
    <label>All Pay Profiles</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PrimaryPayMethod__c.field-meta.xml
<CustomField>
    <fullName>IP_PrimaryPayMethod__c</fullName>
    <description>count field to verify that there is &lt;=1 primary pay method for the worker</description>
    <label>Primary Pay Method</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_PrimaryPayMethod__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>Last Date Worked</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Person_Status__c.field-meta.xml
<CustomField>
    <fullName>Person_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/For_P45_batch__c.field-meta.xml
<CustomField>
    <fullName>For_P45_batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field to check that we do not face any issue with batch in the trigger of pay profile</description>
    <label>For P45 batch</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PrimaryPayMethod__c.field-meta.xml
<CustomField>
    <fullName>IP_PrimaryPayMethod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Pay Profile</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>P45 Emailed Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Initiated__c.field-meta.xml
<CustomField>
    <fullName>P45_Initiated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>P45 Initiated</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/P45DailyProfileProcessorBatch.cls
global class P45DailyProfileProcessorBatch implements Database.Batchable<sObject>,Database.Stateful{

datetime dt = system.now();
date today = system.today();
List<Contact> updatelist = new List<Contact>();
List<IP_PayProfile__c> updatepay = new List<IP_PayProfile__c>();
         global Database.QueryLocator start(Database.BatchableContext BC){
           String query ='Select id,name,IP_Status__c,P45_Date_by_Head_Office__c,IP_Candidate__r.Person_Status__c,P45_Initiated__c,IP_Candidate__c,IP_Candidate__r.IP_Allpayprofiles__c,IP_Payroll_Leaver__c,IP_LastPassedToTempest__c from IP_PayProfile__c where IP_LastPassedToTempest__c <=:dt and IP_Status__c =\'Active\' and IP_Payroll_Leaver__c = \'PL\'';
             return Database.getQueryLocator(query);
         
         }
           global void execute(Database.BatchableContext BC,List<IP_PayProfile__c > payprofile){
             for(IP_PayProfile__c pp: payprofile){
                    pp.IP_Status__c='Inactive';
                    pp.IP_PrimaryPayMethod__c=false;
                    pp.For_P45_batch__c = true;
                    updatepay.add(pp);
                     //Databse.update(payprofile,false);
                     System.debug('active pay profile count'+ pp.IP_Candidate__r.IP_Allpayprofiles__c);
                   if(pp.IP_Candidate__r.IP_Allpayprofiles__c == 1)
                   {
                       pp.IP_Candidate__r.Person_Status__c = 'Inactive';
                   }
                    updatelist.add(pp.IP_Candidate__r);
                }
          
          Database.update(updatelist,false);
          Database.update(updatepay,false);
           
              system.debug('after update payprofile'+payprofile);
           }
            global void finish(Database.BatchableContext BC){
            
            
        
        }
        }