Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_ConsultantsTempestID__c.field-meta.xml
<CustomField>
    <fullName>IP_ConsultantsTempestID__c</fullName>
    <formula>Owner.IP_TempestID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consultants Tempest ID</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine1__c</fullName>
    <description>This is a system field to populate information into back office</description>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine2__c</fullName>
    <description>This is a system interface field as salesforce splits up the salesforce field address line information</description>
    <label>Mailing Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine3__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine3__c</fullName>
    <label>Mailing Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_NewStartTaxStatus__c.field-meta.xml
<CustomField>
    <fullName>IP_NewStartTaxStatus__c</fullName>
    <description>New start tax status</description>
    <inlineHelpText>New Start Tax Status provided when the candidate complete a new starter form</inlineHelpText>
    <label>New Start Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP PayFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PresentedP45ReasonCode__c.field-meta.xml
<CustomField>
    <fullName>IP_PresentedP45ReasonCode__c</fullName>
    <formula>RIGHT(TEXT( Reason_for_P45__c ), 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Presented p45 reason code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <formula>TEXT(Owner.IP_TempestDivision__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tempest Division</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_WorkerLeavingDate__c.field-meta.xml
<CustomField>
    <fullName>IP_WorkerLeavingDate__c</fullName>
    <inlineHelpText>Date the worker wants to leave, must be greater than today unless auto P45</inlineHelpText>
    <label>P45 Requested Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_WorkerStartDate__c.field-meta.xml
<CustomField>
    <fullName>IP_WorkerStartDate__c</fullName>
    <description>Date of the workers first paid work for the Agency</description>
    <inlineHelpText>Worker Start Date which is the first day of their first shift.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Reason_for_P45__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_P45__c</fullName>
    <label>Reason for P45 (Internal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Declined work</fullName>
            </value>
            <value>
                <fullName>Other dismissal</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Transferred to LTD</fullName>
            </value>
            <value>
                <fullName>Branch Transfer/BM</fullName>
                <isActive>false</isActive>
                <label>Branch Transfer/BM</label>
            </value>
            <value>
                <fullName>Eight Week Leaver/PE</fullName>
                <isActive>false</isActive>
                <label>Eight Week Leaver/PE</label>
            </value>
            <value>
                <fullName>Payroll Holiday/PH</fullName>
                <isActive>false</isActive>
                <label>Payroll Holiday/PH</label>
            </value>
            <value>
                <fullName>Payroll Inactive/PI</fullName>
                <isActive>false</isActive>
                <label>Payroll Inactive/PI</label>
            </value>
            <value>
                <fullName>Payroll Leaver/PL</fullName>
                <isActive>false</isActive>
                <label>Payroll Leaver/PL</label>
            </value>
            <value>
                <fullName>T.U.P.E Transfers/TU</fullName>
                <isActive>false</isActive>
                <label>T.U.P.E Transfers/TU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Student</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Suppression_Code__c.field-meta.xml
<CustomField>
    <fullName>Suppression_Code__c</fullName>
    <formula>IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Not Suppressed&quot;), 0, 
 IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Long Term Sick&quot;), 1, 
 IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Extended Maternity Leave&quot;), 2 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Employee Grievance&quot;), 3 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Tribunal&quot;), 4 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Death&quot;), 5 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Pregnancy related absence due to sickness&quot;), 6 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Public Duties&quot;), 7 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Industrial Action&quot;), 8 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Contractually Agreed&quot;), 9 ,
IF(ISPICKVAL( P45_Suppression_Reason__c , &quot;Other&quot;), 10 ,0
)))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Suppression Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/ts2__EEO_Gender__c.field-meta.xml
<CustomField>
    <fullName>ts2__EEO_Gender__c</fullName>
    <label>EEO Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/ts2__Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>ts2__Preferred_Name__c</fullName>
    <label>Preferred Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/WTR_Completed__c.field-meta.xml
<CustomField>
    <fullName>WTR_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>WTR</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BuildingSocietyNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNumber__c</fullName>
    <label>Building Society Roll No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressCounty__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressCounty__c</fullName>
    <label>Business Address County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine1__c</fullName>
    <description>for recording the business address for the candidate, LTD, umbrella, etc. only is required</description>
    <label>Business Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine2__c</fullName>
    <label>Business Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressPostcode__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressPostcode__c</fullName>
    <label>Business Address Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressTown__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressTown__c</fullName>
    <label>Business Address Town</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyName__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyName__c</fullName>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_EmailPayslip__c.field-meta.xml
<CustomField>
    <fullName>IP_EmailPayslip__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Email Payslip</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_NewStarterTaxStatus__c.field-meta.xml
<CustomField>
    <fullName>IP_NewStarterTaxStatus__c</fullName>
    <label>New Starter Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_VATNumber__c</fullName>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/StandardInternalWorkerRest.cls
//FR05,6,7,8 on hold parameteres - /services/apexrest/StandardInternalWorker/branchCode/1069
@RestResource(urlMapping='/StandardInternalWorker/branchCode/*')
global class StandardInternalWorkerRest 
{
    @HttpGet
    global static ResponseClass doGet()
    {
        Set<String> ids = new Set<String>();   
        String[] uriKeys = RestContext.request.requestURI.split('/');          
        String branchCode = uriKeys.get(uriKeys.size()-1);    
        List<IP_PayProfile__c> ppUpdate = New List<IP_PayProfile__c>();
        List<IP_PayProfile__c> ppsend = New List<IP_PayProfile__c>();
        String qCondition1;
        String qCondition2;
        
        try{  
            List<IP_PayProfile__c> ppData = [select IP_BankAccountName__c,
                                             IP_AccountNumber__c,
                                             IP_BuildingSocietyNumber__c,
                                             IP_BusinessAddressCounty__c,
                                             IP_BusinessAddressLine1__c,
                                             IP_BusinessAddressLine2__c,
                                             IP_BusinessAddressPostcode__c,
                                             IP_BusinessAddressTown__c,
                                             IP_Candidate__r.Birthdate,
                                             IP_Candidate__r.IP_ConsultantsTempestID__c,
                                             IP_Candidate__r.Email,
                                             IP_Candidate__r.Firstname,
                                             IP_Candidate__r.IP_MailingAddressLine1__c,
                                             IP_Candidate__r.IP_MailingAddressLine2__c,
                                             IP_Candidate__r.IP_MailingAddressLine3__c,
                                             //IP_Candidate__r.IP_NewStartTaxStatus__c, modified at 22-8-17, Incidant-5764 
                                             IP_NewStarterTaxStatus__c,
                                             IP_Candidate__r.IP_TempestDepartment__c,
                                             IP_Candidate__r.IP_TempestDivision__c,
                                             IP_Candidate__r.IP_WorkerStartDate__c,
                                             IP_Candidate__r.IP_WorkerLeavingDate__c, 
                                             IP_Candidate__r.Lastname,
                                             IP_Candidate__r.MailingCity,
                                             IP_Candidate__r.MailingCountry,
                                             IP_Candidate__r.MailingState,
                                             IP_Candidate__r.MailingPostalCode,
                                             IP_Candidate__r.Phone,
                                             IP_Candidate__r.IP_PresentedP45ReasonCode__c, // added doc v9 29-8-2017
                                             IP_Candidate__r.Reason_for_P45__c,
                                             IP_Candidate__r.Salutation,
                                             IP_Candidate__r.ts2__EEO_Gender__c,
                                             IP_Candidate__r.Sirenum__National_Insurance__c,
                                             IP_Candidate__r.Student__c,
                                             IP_Candidate__r.TS2__Preferred_Name__c,
                                             IP_Candidate__r.WTR_Completed__c,  
                                             IP_Candidate__r.Suppression_Code__c, //p45
                                             IP_Candidate__c,
                                             IP_CompanyName__c,
                                             IP_CompanyRegNo__c,
                                             IP_EmailPayslip__c,
                                             IP_PaymentType__c,
                                             IP_PayrollID__c,
                                             IP_SortCode__c,
                                             IP_VATNumber__c,
                                             RecordType.Name, 
                                             IP_PayFrequency__c,
                                             IP_Candidate__r.IP_Department__c, //added at 17-8-2017 doc v7
                                             IP_Status__c,  //p45
                                             IP_Candidate__r.PayrollLeaver__c,  //p45
                                             IP_Candidate__r.P45_Requested__c,  //p45
                                             IP_SupplierReference__c,
                                             IP_StudentLoan__c,
                                             IP_LastPassedToTempest__c
                                             from IP_PayProfile__c 
                                             where IP_Candidate__r.IP_TempestDepartment__c=:branchCode and 
                                             IP_Candidate__r.RecordType.DeveloperName ='Candidate' and 
                                             IP_PassToTempest__c=true LIMIT 10];
            for(IP_PayProfile__c cnt: ppData){                  
                ids.add(cnt.IP_Candidate__c);                
            }             
            List<sirenum__Timesheet_Line__c> tsLine = [select ContactID__c from sirenum__Timesheet_Line__c where ContactID__c in:ids and IP_PassToTempest__c=true and sirenum__Timesheet__r.sirenum__Week_Ending__c < Today];
            Map<string, sirenum__Timesheet_Line__c> accMap = new Map<string, sirenum__Timesheet_Line__c>();
            for(sirenum__Timesheet_Line__c acc :tsLine){
                accMap.put(acc.ContactID__c,acc);
            }
            
            for(IP_PayProfile__c cnt: ppData){
                if(cnt.IP_LastPassedToTempest__c==null)
                {                    
                    if(accMap.get(cnt.IP_Candidate__c)!=null)
                    {                                        
                        if(cnt.IP_Candidate__c == accMap.get(cnt.IP_Candidate__c).ContactID__c)
                        {
                            ppsend.add(cnt);    
                            System.debug('last pass to tempest null-->'+ppsend);
                        }
                    }
                }else{
                    ppsend.add(cnt); 
                    System.debug('last pass to tempest not null-->'+ppsend); 
                }
                
            }
            system.debug('latest record set ---->'+ppsend);
            
            
            
            
            
            for(IP_PayProfile__c cnt: ppsend)
            {   
                if(cnt.RecordType.Name == 'PAYE' && cnt.IP_Status__c == 'Active' && cnt.IP_Candidate__r.P45_Requested__c  && cnt.IP_Candidate__r.PayrollLeaver__c ==null)
                {
                    cnt.IP_Candidate__r.PayrollLeaver__c = 'PL';
                }
                cnt.IP_PassToTempest__c=false;
                cnt.IP_LastPassedToTempest__c=system.now();
                ppUpdate.add(cnt);                                             
            }       
            Database.SaveResult[] srList = Database.update(ppUpdate, false);                      
            return new ResponseClass('true', 'Query executed successfully.', ppsend);           
        } catch (Exception e) {
            return new ResponseClass('false', e.getMessage(), null);
        }  
    }
    
    global class ResponseClass 
    {
        
        global String success;
        global String message;
        global List<IP_PayProfile__c> records;
        
        global ResponseClass(String success, String message, List<IP_PayProfile__c> records) 
        {
            
            
            this.success = success;
            this.message = message;
            this.records = records;
        }
    }
}