Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_EmergencyPull__c.field-meta.xml
<CustomField>
    <fullName>IP_EmergencyPull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Pull</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MissingPayrollDetail__c.field-meta.xml
<CustomField>
    <fullName>IP_MissingPayrollDetail__c</fullName>
    <description>List of missing fields for payroll integration

THL 31.03: Removed the 2nd Tier Candidate OR Statement
IF( ISPICKVAL( IP_BorrowedTemp__c , &quot;Yes&quot; ) || RecordType.Name = &quot;2nd Tier Candidate&quot;,</description>
    <formula>IF( ISPICKVAL( IP_BorrowedTemp__c , &quot;Yes&quot; ), IF( ISBLANK( IP_CandidateIDlegacy__c ) , &quot;Candidate ID&quot;, &quot;&quot;) ,&quot;&quot;) &amp; 
IF( ISBLANK( FirstName ) , &quot;First Name, &quot;, &quot;&quot;) &amp; 
IF( ISBLANK( Text(Salutation) ) , &quot;Title, &quot;, &quot;&quot;)&amp; 
/*IF( AND(ISBLANK( sirenum__National_Insurance__c ),RecordType.Name = &quot;2nd Tier Candidate&quot;) , &quot;NI, &quot;, &quot;&quot;)&amp;*/
IF(OR( ISBLANK( MailingPostalCode ), ISBLANK( IP_MailingAddressLine1__c ), ISBLANK( MailingCity )) , &quot;Address, &quot;, &quot;&quot;)&amp; 
/* If( AND( TOE_Completed__c = FALSE, IP_ActivePAYEPayProfiles__c = 1),&quot;TOE not complete, &quot;,&quot;&quot;)&amp; 
If( AND( New_Starter_Form__c = FALSE, IP_ActivePAYEPayProfiles__c = 1),&quot;New Starter Form, &quot;,&quot;&quot;)&amp; */
IF( ISBLANK( IP_WorkerStartDate__c ) , &quot;Start Date, &quot;, &quot;&quot;)&amp; 
IF( AND( IP_IncompleteActivePayProfiles__c &gt; 0, IP_ActivePayProfiles__c &gt; 0) ,&quot;Incomplete active pay profiles, &quot;,&quot;&quot;)&amp;
IF( AND(IP_ActivePayProfiles__c =0,
        NOT(RecordType.Name = &quot;2nd Tier Candidate&quot;),
	NOT(ISPICKVAL( IP_BorrowedTemp__c , &quot;Yes&quot;))
       ) , 
	&quot;No Active pay profile(s), &quot;, &quot;&quot;) &amp;
IF(AND(IP_IncompleteActivePayProfiles__c = IP_ActivePayProfiles__c, RecordType.Name = &quot;2nd Tier Candidate&quot;,ISPICKVAL( IP_BorrowedTemp__c , &quot;Yes&quot;) ),&quot;No completed pay profiles , &quot;,&quot;&quot;) &amp;

IF(AND(OR(RecordType.Name = &quot;2nd Tier Candidate&quot;,ISPICKVAL( IP_BorrowedTemp__c , &quot;Yes&quot;)),  IP_TempestDepartment__c ==&quot;0000&quot; ),&quot;Owner Not a Branch Staff  &quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>List of missing fields for payroll integration</inlineHelpText>
    <label>Missing Payroll Details</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP PayFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PrimaryPayMethod__c.field-meta.xml
<CustomField>
    <fullName>IP_PrimaryPayMethod__c</fullName>
    <description>count field to verify that there is &lt;=1 primary pay method for the worker</description>
    <label>Primary Pay Method</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_PrimaryPayMethod__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_StudentLoan__c.field-meta.xml
<CustomField>
    <fullName>IP_StudentLoan__c</fullName>
    <label>Student Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TimesheetIDLink__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetIDLink__c</fullName>
    <label>Timesheet ID Link</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>Last Date Worked</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Candidate Requested P45?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay - not enough</fullName>
            </value>
            <value>
                <fullName>Pay - incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable work</fullName>
            </value>
            <value>
                <fullName>Not enough work</fullName>
            </value>
            <value>
                <fullName>Work break</fullName>
            </value>
            <value>
                <fullName>Better opportunity</fullName>
            </value>
            <value>
                <fullName>Worker performance/compliance issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Date_P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>Date_P45_Requested__c</fullName>
    <label>Leaver Requested Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Derogated__c.field-meta.xml
<CustomField>
    <fullName>IP_Derogated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Derogated</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_EmailPayslip__c.field-meta.xml
<CustomField>
    <fullName>IP_EmailPayslip__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Email Payslip</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_EmergencyPull__c.field-meta.xml
<CustomField>
    <fullName>IP_EmergencyPull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Pull</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_GUID__c.field-meta.xml
<CustomField>
    <fullName>IP_GUID__c</fullName>
    <label>GUID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_MissingPayrollDetail__c.field-meta.xml
<CustomField>
    <fullName>IP_MissingPayrollDetail__c</fullName>
    <inlineHelpText>If there is missing payroll information this will be listed here</inlineHelpText>
    <label>Missing Payroll Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_NewStarterTaxStatus__c.field-meta.xml
<CustomField>
    <fullName>IP_NewStarterTaxStatus__c</fullName>
    <label>New Starter Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <label>Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PrimaryPayMethod__c.field-meta.xml
<CustomField>
    <fullName>IP_PrimaryPayMethod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Pay Profile</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_StudentLoan__c.field-meta.xml
<CustomField>
    <fullName>IP_StudentLoan__c</fullName>
    <label>Student Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_UmbrellaName__c.field-meta.xml
<CustomField>
    <fullName>IP_UmbrellaName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Umbrella Company</label>
    <referenceTo>IP_Umbrellalist__c</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>P45 Emailed Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Initiated__c.field-meta.xml
<CustomField>
    <fullName>P45_Initiated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>P45 Initiated</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leaver?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pay - Not Enough</fullName>
            </value>
            <value>
                <fullName>Pay - Incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable Work</fullName>
            </value>
            <value>
                <fullName>Not Enough Work</fullName>
            </value>
            <value>
                <fullName>Work Break</fullName>
            </value>
            <value>
                <fullName>Better Opportunity</fullName>
            </value>
            <value>
                <fullName>Worker Performance/Compliance Issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
            <value>
                <fullName>Dismissal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_P45_Internal__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_P45_Internal__c</fullName>
    <label>Reason for P45 (Internal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Declined work</fullName>
            </value>
            <value>
                <fullName>Other dismissal</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Transferred to LTD</fullName>
            </value>
            <value>
                <fullName>Branch Transfer/BM</fullName>
                <isActive>false</isActive>
                <label>Branch Transfer/BM</label>
            </value>
            <value>
                <fullName>Eight Week Leaver/PE</fullName>
                <isActive>false</isActive>
                <label>Eight Week Leaver/PE</label>
            </value>
            <value>
                <fullName>Payroll Leaver/PL</fullName>
                <isActive>false</isActive>
                <label>Payroll Leaver/PL</label>
            </value>
            <value>
                <fullName>Payroll holiday/PH</fullName>
                <isActive>false</isActive>
                <label>Payroll holiday/PH</label>
            </value>
            <value>
                <fullName>Payroll inactive/PI</fullName>
                <isActive>false</isActive>
                <label>Payroll inactive/PI</label>
            </value>
            <value>
                <fullName>T.U.P.E transfers/TU</fullName>
                <isActive>false</isActive>
                <label>T.U.P.E transfers/TU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/Umbrella.recordType-meta.xml
<RecordType>
    <fullName>Umbrella</fullName>
    <active>true</active>
    <label>Umbrella</label>
</RecordType>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/createpayumbpayprofile.cls
public class createpayumbpayprofile{

    public String recordtypeid{get;set;}
    public String profileName{get;set;}
    public  String parentId{get;set;}
    public String recordTypeName{get;set;}
    public String parentname {get;set;}
    public IP_PayProfile__c payrec{get;set;}

    public createpayumbpayprofile(ApexPages.StandardController controller) {
        payrec= new IP_PayProfile__c();
        Id profileId= userinfo.getProfileId();
        profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        if(ApexPages.currentPage().getParameters().get('conID') != null){
            parentId = ApexPages.currentPage().getParameters().get('conID');
            Contact con = [Select id,Name from COntact where id=:parentId];
            parentname= con.Name;
            payrec.IP_Candidate__c = con.ID;
        }
        if(ApexPages.currentPage().getParameters().get('recid') != null){
            recordtypeid = ApexPages.currentPage().getParameters().get('recid');
            RecordType rec = [Select id,Name from RecordType where id =: recordtypeid];
            recordTypeName = rec.Name;
            payrec.RecordTypeID = rec.id;
        }
    }

    public pageReference saveandredirect(){
        IP_PayProfile__c pay = new IP_PayProfile__c();
        pay.RecordTypeid = recordtypeid;
        pay.IP_candidate__c = payrec.IP_Candidate__c;
        pay.IP_MissingPayrollDetail__c = payrec.IP_MissingPayrollDetail__c;
        pay.IP_PayrollID__c = payrec.IP_PayrollID__c;       
        pay.IP_PrimaryPayMethod__c = payrec.IP_PrimaryPayMethod__c;
        if(recordTypeName.equals('Umbrella')){          
            pay.IP_UmbrellaName__c = payrec.IP_UmbrellaName__c;
            pay.IP_SupplierReference__c = payrec.IP_SupplierReference__c;
        }
        else if(recordTypeName.equals('PAYE')){
            pay.IP_PayFrequency__c = payrec.IP_PayFrequency__c;
            pay.IP_NewStarterTaxStatus__c   = payrec.IP_NewStarterTaxStatus__c;
            pay.IP_EmailPayslip__c = payrec.IP_EmailPayslip__c;
            pay.IP_StudentLoan__c   = payrec.IP_StudentLoan__c;
            pay.IP_Derogated__c = payrec.IP_Derogated__c;
            pay.P45_Requested__c = payrec.P45_Requested__c;
            pay.Date_P45_Requested__c   = payrec.Date_P45_Requested__c;
            pay.Reason_for_Leaving1__c = payrec.Reason_for_Leaving1__c;
            pay.P45_Date_by_Head_Office__c    = payrec.P45_Date_by_Head_Office__c ;
            pay.IP_Branch_Code__c = payrec.IP_Branch_Code__c;
            pay.IP_GUID__c = payrec.IP_GUID__c;
            pay.P45_Initiated__c   = payrec.P45_Initiated__c;
            pay.IP_EmergencyPull__c = payrec.IP_EmergencyPull__c;
            pay.Reason_for_P45_Internal__c   = payrec.Reason_for_P45_Internal__c;
            pay.IP_TimesheetIDLink__c = payrec.IP_TimesheetIDLink__c;
            pay.For_P45_batch__c   = payrec.For_P45_batch__c;
            pay.IP_Payroll_Leaver__c  = payrec.IP_Payroll_Leaver__c ;
        }
        pay.IP_Status__c = 'Active';
        pay.IP_PassToTempest__c = payrec.IP_PassToTempest__c;
        pay.IP_LastPassedToTempest__c = payrec.IP_LastPassedToTempest__c;

        try{
            insert pay;
            PageReference pageref = new PageReference('/'+pay.id);
            pageref.setRedirect(true);
            return pageref;
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }
    }
    
    public pageReference saveandredirectnewpage(){
        IP_PayProfile__c pay = new IP_PayProfile__c();
        pay.RecordTypeid = recordtypeid;
        pay.IP_candidate__c = payrec.IP_Candidate__c;
        pay.IP_MissingPayrollDetail__c = payrec.IP_MissingPayrollDetail__c;
        pay.IP_PayrollID__c = payrec.IP_PayrollID__c;       
        pay.IP_PrimaryPayMethod__c = payrec.IP_PrimaryPayMethod__c;
        if(recordTypeName.equals('Umbrella')){          
            pay.IP_UmbrellaName__c = payrec.IP_UmbrellaName__c;
            pay.IP_SupplierReference__c = payrec.IP_SupplierReference__c;
        }
        else if(recordTypeName.equals('PAYE')){
            pay.IP_PayFrequency__c = payrec.IP_PayFrequency__c;
            pay.IP_NewStarterTaxStatus__c   = payrec.IP_NewStarterTaxStatus__c;
            pay.IP_EmailPayslip__c = payrec.IP_EmailPayslip__c;
            pay.IP_StudentLoan__c   = payrec.IP_StudentLoan__c;
            pay.IP_Derogated__c = payrec.IP_Derogated__c;
            pay.P45_Requested__c = payrec.P45_Requested__c;
            pay.Date_P45_Requested__c   = payrec.Date_P45_Requested__c;
            pay.Reason_for_Leaving1__c = payrec.Reason_for_Leaving1__c;
            pay.P45_Date_by_Head_Office__c    = payrec.P45_Date_by_Head_Office__c ;
            pay.IP_Branch_Code__c = payrec.IP_Branch_Code__c;
            pay.IP_GUID__c = payrec.IP_GUID__c;
            pay.P45_Initiated__c   = payrec.P45_Initiated__c;
            pay.IP_EmergencyPull__c = payrec.IP_EmergencyPull__c;
            pay.Reason_for_P45_Internal__c   = payrec.Reason_for_P45_Internal__c;
            pay.IP_TimesheetIDLink__c = payrec.IP_TimesheetIDLink__c;
            pay.For_P45_batch__c   = payrec.For_P45_batch__c;
            pay.IP_Payroll_Leaver__c  = payrec.IP_Payroll_Leaver__c ;
        }
        pay.IP_Status__c = 'Active';
        pay.IP_PassToTempest__c = payrec.IP_PassToTempest__c;
        pay.IP_LastPassedToTempest__c = payrec.IP_LastPassedToTempest__c;

        try{
            insert pay;
            PageReference pageref = new PageReference('/apex/RecordTypeselection');
            pageref.setRedirect(true);
            return pageref;
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }
    }

    public pageReference cancelredirect(){
        Pagereference pagenew = new Pagereference('/'+parentID);
        pagenew.setRedirect(true);
        return pagenew;
    }

}