Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_GDPRContactedCandidate__c.field-meta.xml
<CustomField>
    <fullName>IP_GDPRContactedCandidate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field that identifies if a candidate has been contacted under the definition of GDPR.</description>
    <label>GDPR Contacted Candidate</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_GDPRWorkedCandidate__c.field-meta.xml
<CustomField>
    <fullName>IP_GDPRWorkedCandidate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field that identifies if a candidate has been worked under the definition for GDPR.</description>
    <label>GDPR Worked Candidate</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LastContactedGDPR__c.field-meta.xml
<CustomField>
    <fullName>IP_LastContactedGDPR__c</fullName>
    <description>System field that identifies the last time a candidate has had a GDPR ‘Meaningful contact’ interaction.</description>
    <label>Last contacted GDPR</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MarkedForDeletion__c.field-meta.xml
<CustomField>
    <fullName>IP_MarkedForDeletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field that identifies if the candidate needs to be deleted.</description>
    <label>Marked for deletion</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/IP_ImpellamGDPRSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the parameters for managing data retention within the system.</description>
    <label>RSSGlobal_GDPR_settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/fields/IP_UnworkedCandidateDataRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>IP_UnworkedCandidateDataRetentionPeriod__c</fullName>
    <description>Number of days an unworked candidates data is held in the system</description>
    <label>Unworked Candidate Data Retention Period</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/GDPRCandidateMarking_ScheduledBatch.cls
public without sharing class GDPRCandidateMarking_ScheduledBatch implements Database.Batchable<sObject>, Schedulable {
  private Integer retentionPeriodDays;
  private Date todayMinusRetentionPeriod;
  private IP_ImpellamGDPRSettings__c gdprSettings;

  public Boolean triggerException = false;

  public GDPRCandidateMarking_ScheduledBatch() {
    this.gdprSettings = IP_ImpellamGDPRSettings__c.getInstance(
      'Impellam GDPR settings'
    );
    this.retentionPeriodDays = Integer.valueOf(
      gdprSettings.IP_UnworkedCandidateDataRetentionPeriod__c
    );
    this.todayMinusRetentionPeriod = System.Today()
      .addDays(-retentionPeriodDays);
  }

  //Batch job execute
  public Database.QueryLocator start(Database.BatchableContext BC) {
    Id candidateRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
      .get('Candidate')
      .getRecordTypeId();

    //Any records returned from this query can be assumed to be ready for deletion
    String Query =
      ' SELECT id , recordtype.name ,IP_GDPRWorkedCandidate__c, IP_GDPRContactedCandidate__c ' +
      'FROM contact ' +
      'WHERE CreatedDate < :todayMinusRetentionPeriod ' +
      'AND (IP_LastContactedGDPR__c = Null OR IP_LastContactedGDPR__c < :todayMinusRetentionPeriod) ' +
      'AND recordTypeId=:candidateRecordTypeId AND IP_MarkedForDeletion__c = false AND IP_GDPRWorkedCandidate__c = false';

    system.debug('Query-->' + Query);
    return Database.getQueryLocator(Query);
  }
  public void execute(Database.BatchableContext BC, List<Contact> Candidates) {
    System.debug(BC);
    System.debug('Candidates-->' + Candidates);
    for (Contact candidate : Candidates) {
      candidate.IP_MarkedForDeletion__c = true;
    }

    try {
      if (Test.isRunningTest() && triggerException) {
        System.debug('DeletionException reached');
        throw new DeletionException('Test exception');
      }

      update Candidates;
    } catch (Exception e) {
      smagicinteract__Error_Log__c errorLog = new smagicinteract__Error_Log__c();
      errorLog.smagicinteract__Error_Message__c = e.getMessage();
      errorLog.smagicinteract__Line_number__c = e.getLineNumber();
      errorLog.smagicinteract__Error_Type__c = 'Generic';
      errorLog.smagicinteract__Class_name__c = 'GDPRCandidateMarking_ScheduledBatch';
      insert errorLog;
    }
  }
  public void finish(Database.BatchableContext BC) {
  }
  //Scheduled job execute
  public void execute(SchedulableContext sc) {
    Database.executeBatch(this, 10);
  }

  public class DeletionException extends Exception {
  }
}