Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LastPassedToTempest2ndTier__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest2ndTier__c</fullName>
    <label>Last Passed to Tempest (2nd Tier)</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Pass2ndTierToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_Pass2ndTierToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass 2nd tier to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_Externalworkerready.cls
@isTest
private class Test_Externalworkerready{

static testMethod void testDoGet() 
    {        
      
      test.startTest();
        String query = 'Select id from Contact limit 10';
        String GUID = 'ABCD';
        String Field1 = 'IP_Pass2ndTierToTempest__c';
        String Field2 = 'IP_LastPassedToTempest2ndTier__c';
        Database.executeBatch(new ExternalWorkerBatch(Query,Field1,Field2,GUID),100);
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/standard/v1/ready/externalworker/1069';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Externalworkerready.ResponseClass results = Externalworkerready.doGet();       
        System.assertEquals('false', results.success);  
        System.assertEquals('Not Ready', results.message);  
        test.stopTest();
    }
    static testMethod void testDoGet1() 

     {        
      
      test.startTest();
        String query = 'Select id from Contact limit 10';
        String GUID = 'ABCD';
        String Field1 = 'IP_Pass2ndTierToTempest__c';
        String Field2 = 'IP_LastPassedToTempest2ndTier__c';
        Database.executeBatch(new ExternalWorkerEmergencyBatch(Query,Field1,Field2,GUID),100);
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/emergency/v1/ready/externalworker/1069';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        ExternalworkerEmergencyready.ResponseClass results = ExternalworkerEmergencyready.doGet();       
        System.assertEquals('false', results.success);  
        System.assertEquals('Not Ready', results.message);  
        test.stopTest();
    }
    
}