Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PrimaryPayMethod__c.field-meta.xml
<CustomField>
    <fullName>IP_PrimaryPayMethod__c</fullName>
    <description>count field to verify that there is &lt;=1 primary pay method for the worker</description>
    <label>Primary Pay Method</label>
    <summaryFilterItems>
        <field>IP_PayProfile__c.IP_PrimaryPayMethod__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>IP_PayProfile__c.IP_Candidate__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumberSalted__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumberSalted__c</fullName>
    <defaultValue>&apos;12345678&apos;</defaultValue>
    <label>AccountNumberSalted</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BuildingSocietyNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNumber__c</fullName>
    <label>Building Society Roll No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PrimaryPayMethod__c.field-meta.xml
<CustomField>
    <fullName>IP_PrimaryPayMethod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Pay Profile</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCodeSalted__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCodeSalted__c</fullName>
    <defaultValue>&apos;123456&apos;</defaultValue>
    <label>SortCodeSalted</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/IP_Shift_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Shift Template</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/CPBankDetailController.cls
global without sharing class CPBankDetailController {
    
    @AuraEnabled
    Public Static List<IP_PayProfile__C> getDefaultBankDetail()
    { 
        
        List<IP_PayProfile__C> Lst = new List<IP_PayProfile__C>();
        List<IP_PayProfile__C> ppLst = [Select Id,Name,IP_AccountNumber__c,IP_BankAccountName__c,IP_SortCode__c,IP_BuildingSocietyNumber__c,RecordType.Name,IP_AccountNumberSalted__c,IP_SortCodeSalted__c	 from IP_PayProfile__C where IP_PrimaryPayMethod__c=true and IP_Candidate__c=:getUserId()];                            
        for(IP_PayProfile__C p:ppLst){  if(p.IP_SortCodeSalted__c!=null){  p.IP_SortCodeSalted__c = p.IP_SortCodeSalted__c.left(1) + '****' + p.IP_SortCodeSalted__c.right(1); }else{ p.IP_SortCodeSalted__c = '1****6'; } if(p.IP_AccountNumberSalted__c!=null){ p.IP_AccountNumberSalted__c = p.IP_AccountNumberSalted__c.left(2) + '****' + p.IP_AccountNumberSalted__c.right(2); }else{   p.IP_AccountNumberSalted__c = '1****8'; } Lst.add(p);    
                                     }     
        return Lst;        
        
    }
    
    @AuraEnabled
    Public Static List<IP_PayProfile__C> getPaymentType()
    {
        return [Select Id,Name,RecordType.Name,IP_PrimaryPayMethod__c from IP_PayProfile__C where IP_Candidate__c=:getUserId() and IP_Status__c='Active'];               
    }
    
    @AuraEnabled
    Public Static List<IP_PayProfile__C> BankDetail(String recordId)
    {              
        List<IP_PayProfile__C> Lst = new List<IP_PayProfile__C>();
        List<IP_PayProfile__C> ppLst = [Select Id,Name,IP_AccountNumber__c,IP_BankAccountName__c,IP_SortCode__c,IP_BuildingSocietyNumber__c,RecordType.Name,IP_AccountNumberSalted__c,IP_SortCodeSalted__c from IP_PayProfile__C where Id=:recordId];              
        for(IP_PayProfile__C p:ppLst){ 
            if(p.IP_SortCodeSalted__c!=null){
                p.IP_SortCodeSalted__c = p.IP_SortCodeSalted__c.left(1) + '****' + p.IP_SortCodeSalted__c.right(1);
            }else{
                p.IP_SortCodeSalted__c = '1****6';
            }
            if(p.IP_AccountNumberSalted__c!=null){
                p.IP_AccountNumberSalted__c = p.IP_AccountNumberSalted__c.left(2) + '****' + p.IP_AccountNumberSalted__c.right(2);
            }else{
                p.IP_AccountNumberSalted__c = '1****8';
            }
            Lst.add(p);    
        }              
        return Lst;
    }
    
    @AuraEnabled
    public static IP_PayProfile__C savePP(String Ids,String inputId,String part) 
    {
        Id templateId = [select id, name from EmailTemplate where developername = 'Candidate_Portal_Change_Bank_Details'].id;
        
        OrgWideEmailAddress owd = [select id, DisplayName,Address from OrgWideEmailAddress where Address ='no.reply@bluearrow.co.uk'];
        
        IP_PayProfile__C ToUpdate = [select Id,IP_Candidate__r.IP_TempestDepartment__c,IP_BankAccountName__c,IP_Candidate__c,IP_candidate__r.FirstName,IP_AccountNumber__c,IP_AccountNumberSalted__c,IP_SortCodeSalted__c,IP_SortCode__c,IP_BuildingSocietyNumber__c from IP_PayProfile__C where id=:Ids];
        if(part!=null && part=='ACCOUNTNAME'){
            ToUpdate.IP_BankAccountName__c=inputId;
            system.debug('================================================================ToUpdate-->'+ToUpdate);
        }
        if(part=='SORTCODE'){
            ToUpdate.IP_SortCodeSalted__c=inputId;
            ToUpdate.IP_SortCode__c=inputId;
        }
        if(part=='ACCOUNTNUMBER'){
            ToUpdate.IP_AccountNumber__c=inputId;
            ToUpdate.IP_AccountNumberSalted__c=inputId;
        }
        if(part=='BUILDINGSOCIETYREF'){
            ToUpdate.IP_BuildingSocietyNumber__c=inputId;
        }
        update ToUpdate;
        String department = ToUpdate.IP_Candidate__r.IP_TempestDepartment__c;
            IP_Shift_Template__c shiftemp1 = IP_Shift_Template__c.getValues(department);
             system.debug('================================================================shiftemp1-->'+shiftemp1);
            List<OrgWideEmailAddress> owd1;
            if(shiftemp1!=Null){
            owd1= [select id, DisplayName,Address from OrgWideEmailAddress where Address =:shiftemp1.Email__c];
            system.debug('================================================================OWD ID--->'+owd1);
            }
            
        
        
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();   
        system.debug('=======================================================email'+email);
        email.setTargetObjectId(ToUpdate.IP_Candidate__r.id);
        if(owd1.size()>0)
            {
            email.setOrgWideEmailAddressId(owd1[0].Id);
            }
            else
           {
			email.setOrgWideEmailAddressId(owd.Id);
               }
            
        email.setTemplateId(templateId); 
        email.saveAsActivity = false;
        Messaging.SendEmailResult [] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
         
        return ToUpdate;
        
    }
    
    public static String getUserId(){
        ID contactId = [Select contactid from User where id =: Userinfo.getUserid()].contactId;
        return contactId;
    }
}