Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/IP_Shift_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Shift Template</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/My_Blue_Arrow_Contact_cnt.cls
public class My_Blue_Arrow_Contact_cnt{
    
     @AuraEnabled
     public static Map<string,Object> getUsernfo(String site)
     {
      
      sirenum__Site__c siteObj = [select Id,Owner.Name, IP_TempestDepartment__c,IP_MainContact__c from sirenum__Site__c where Id=:site];
      
       Map<string,Object> UserMap = new Map<string,Object>();
       
      if(siteObj!=null )
      {
      
      	 UserMap.put('site',siteObj);
         Contact con = [select id,Name,IP_TempestDepartment__c from Contact where Id=:siteObj.IP_MainContact__c];
      
                 UserMap.put('User',con);
                 
                 if(siteObj.IP_TempestDepartment__c!=null)
                 {
                   IP_Shift_Template__c shiftemp = IP_Shift_Template__c.getValues(siteObj.IP_TempestDepartment__c);
                   UserMap.put('ShifTemp',shiftemp);
                 }
                 else
                 {
                   UserMap.put('ShifTemp',null);
                 }
              }   
                 return UserMap;
     }
 
}