Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/IP_Shift_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Shift Template</label>
</CustomObject>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/FairEmploymentQuestionnaireController.cls
/*
* Class Name: FairEmploymentQuestionnaireController
* Description: Class for Community Background Template
* Test Class : TestFairEmpQuestionnaireController
* Date : 21th Nov 2019
*/
public class FairEmploymentQuestionnaireController {
    public id record_Id{get; set;}
    public Contact conid{get; set;}
    public string department;
    public String branchphone{get;set;}
    
     /*
    * Method Name: getconid
    * Description: Method for Community Background Template
    * Parameters : none
    * Return Type: nothing
    */
    public Contact getconid(){
            system.debug('record_id ' + record_Id);
            if(record_Id != null){
            conid = [
                SELECT
                id,IP_TempestDepartment__c,FirstName FROM Contact 
                WHERE 
                Id = :record_Id
            ];system.debug('conid.FirstName ' + conid.FirstName );
            department = conid.IP_TempestDepartment__c;
            System.debug('check department'+department);
            IP_Shift_Template__c shiftemp = IP_Shift_Template__c.getValues(department); 
            branchphone = shiftemp.Phone__c;
        }
        return conid;
    }
}