Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TimesheetIDLink__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetIDLink__c</fullName>
    <label>Timesheet ID Link</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/IP_OutboundDataTransfer__c.object-meta.xml
<CustomObject>
    <description>Object that holds data for transfer out of the system</description>
    <label>Outbound Data Transfer</label>
    <nameField>
        <displayFormat>ODT-{0000000000}</displayFormat>
        <label>Outbound Data Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Data Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_OriginRecordID__c.field-meta.xml
<CustomField>
    <fullName>IP_OriginRecordID__c</fullName>
    <label>Origin Record ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_TransferType__c.field-meta.xml
<CustomField>
    <fullName>IP_TransferType__c</fullName>
    <label>Transfer Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_TimesheetIDLink__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetIDLink__c</fullName>
    <label>Timesheet ID Link</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/UpdateRelateddateLink.cls
public class UpdateRelateddateLink{
@future

public static void deleteupdatedata(Set<ID> deleterelatedsset)
{
List<sirenum__placement__c> Assignmentupdate = new List<sirenum__placement__c>();
List<IP_PayProfile__c> Profileupdate = new List<IP_PayProfile__c>();
List<Contact> Contactupdate = new List<Contact>();
    List<IP_OutboundDataTransfer__c> oblist1 = [Select id,IP_OriginRecordID__c,IP_TransferType__c from IP_OutboundDataTransfer__c where id in: deleterelatedsset];
    for(IP_OutboundDataTransfer__c ob: oblist1)
    {
        if(ob.IP_TransferType__c == 'Assignment')
        {
            sirenum__placement__c sp = new sirenum__placement__c(id=ob.IP_OriginRecordID__c,IP_TimesheetIDLink__c = '');
            Assignmentupdate.add(sp);
        }
        if(ob.IP_TransferType__c == 'Internal Worker')
        {
            IP_PayProfile__c sp = new IP_PayProfile__c(id=ob.IP_OriginRecordID__c,IP_TimesheetIDLink__c = '');
            Profileupdate.add(sp);
        }
        if(ob.IP_TransferType__c == 'External Worker')
        {
            Contact sp = new Contact(id=ob.IP_OriginRecordID__c,IP_TimesheetIDLink__c = '');
            Contactupdate.add(sp);
        }
    }
    delete oblist1;
    Update Assignmentupdate;
    Update Profileupdate;
    Update Contactupdate;
}

}