Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/IP_Shift_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Shift Template</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/Branch_Address__c.field-meta.xml
<CustomField>
    <fullName>Branch_Address__c</fullName>
    <label>Branch Street</label>
    <type>TextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_City__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_City__c</fullName>
    <label>Branch City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_Country__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_Country__c</fullName>
    <label>Branch Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_County__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_County__c</fullName>
    <label>Branch County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_Postal_Code__c</fullName>
    <label>Branch Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Site_Name__c.field-meta.xml
<CustomField>
    <fullName>IP_Site_Name__c</fullName>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Drivingletter.cls
public class Drivingletter
{
  ID conID;
  public String Sitename{get;set;}
  public String branchstreet{get;set;}
  public String branchcity{get;set;}
  public String branchCountry{get;set;}
  public String branchcounty{get;set;}
  public String branchpostal{get;set;}
  public String customsitename{get;set;}
  public String branchemail{get;set;}
  public String branchphone{get;set;}
  public String branchFax{get;set;}
  Public string department;

    public Drivingletter(ApexPages.StandardController controller) {
    conID = ApexPages.currentPage().getParameters().get('id');
    	System.debug('============= conid '+conID);
    Contact s = [Select id,name,IP_TempestDepartment__c from Contact where id=:conID];
        System.debug('============= s '+s);   
      department = String.valueOf(s.IP_TempestDepartment__c);
        System.debug('============= department '+department);   
      IP_Shift_Template__c shiftemp = IP_Shift_Template__c.getValues(department);
        System.debug('============= shiftemp '+shiftemp);   
      branchstreet= shiftemp.Branch_Address__c;
      branchcity= shiftemp.IP_Branch_City__c;
      branchCountry=shiftemp.IP_Branch_Country__c;
      branchpostal = shiftemp.IP_Branch_Postal_Code__c;
      branchcounty = shiftemp.IP_Branch_County__c;
      customsitename = shiftemp.IP_Site_Name__c;
      branchemail = shiftemp.Email__c;
      branchphone = shiftemp.Phone__c;
      branchFax = shiftemp.Fax__c;
      }
      }