Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/StagingJobApplication__c.object-meta.xml
<CustomObject>
    <label>Third Party Job Application</label>
    <nameField>
        <displayFormat>VMS-A-{YYYY}{MM}-{0}</displayFormat>
        <label>Staging Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/PORTW_Type__c.field-meta.xml
<CustomField>
    <fullName>PORTW_Type__c</fullName>
    <label>PORTW Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>British Passport</fullName>
            </value>
            <value>
                <fullName>British Birth / Adoption Certificate</fullName>
            </value>
            <value>
                <fullName>British Certificate of Naturalisation</fullName>
            </value>
            <value>
                <fullName>Irish Passport</fullName>
            </value>
            <value>
                <fullName>Irish Passport Card</fullName>
            </value>
            <value>
                <fullName>Irish Birth / Adoption Certificate</fullName>
            </value>
            <value>
                <fullName>Biometric Residence Permit / Card - No Time Limit</fullName>
            </value>
            <value>
                <fullName>Biometric Residence Permit / Card - Time Limit</fullName>
            </value>
            <value>
                <fullName>Certificate of Application / Application Registration Card plus ECS Check - Time Limited</fullName>
            </value>
            <value>
                <fullName>Crown Dependency Letter plus ECS Check - No Time Limit</fullName>
            </value>
            <value>
                <fullName>Crown Dependency Letter plus ECS Check - Time Limit</fullName>
            </value>
            <value>
                <fullName>ECS Check - Time Limit</fullName>
            </value>
            <value>
                <fullName>EUSS Family - No Time Limited</fullName>
            </value>
            <value>
                <fullName>EUSS Family - Time Limited</fullName>
            </value>
            <value>
                <fullName>Frontier Worker Permit - Time Limited</fullName>
            </value>
            <value>
                <fullName>Immigration Status Document - No Time Limit</fullName>
            </value>
            <value>
                <fullName>Immigration Status Document - Time Limit</fullName>
            </value>
            <value>
                <fullName>Online Right To Work Check - No Time Limit</fullName>
            </value>
            <value>
                <fullName>Online Right To Work Check - Time Limit</fullName>
            </value>
            <value>
                <fullName>Passport with Visa - No Time Limit</fullName>
            </value>
            <value>
                <fullName>Passport with Visa - Time Limit</fullName>
            </value>
            <value>
                <fullName>(A1) UK / EEA Passport</fullName>
                <isActive>false</isActive>
                <label>(A1) UK / EEA Passport</label>
            </value>
            <value>
                <fullName>(A3) Passport or National identity card, issued by EEA Agreement State</fullName>
                <isActive>false</isActive>
                <label>(A3) Passport or National identity card, issued by EEA Agreement State</label>
            </value>
            <value>
                <fullName>(A4) UK residence permit</fullName>
                <isActive>false</isActive>
                <label>(A4) UK residence permit</label>
            </value>
            <value>
                <fullName>(A6) Passport or other Travel doc. showing indefinite leave to enter/ remain in UK</fullName>
                <isActive>false</isActive>
                <label>(A6) Passport or other Travel doc. showing indefinite leave to enter/ remain in UK</label>
            </value>
            <value>
                <fullName>(A8) Registration card showing entitlement to take employment in UK</fullName>
                <isActive>false</isActive>
                <label>(A8) Registration card showing entitlement to take employment in UK</label>
            </value>
            <value>
                <fullName>NI NO. + (B) birth certificate issues in UK</fullName>
                <isActive>false</isActive>
                <label>NI NO. + (B) birth certificate issues in UK</label>
            </value>
            <value>
                <fullName>NI NO. + (C) birth certificate issues in the Channel Islands, Isle of Man, Ireland</fullName>
                <isActive>false</isActive>
                <label>NI NO. + (C) birth certificate issues in the Channel Islands, Isle of Man, Ireland</label>
            </value>
            <value>
                <fullName>NI NO. + (D) certificate of registration or naturalization as a British Citizen</fullName>
                <isActive>false</isActive>
                <label>NI NO. + (D) certificate of registration or naturalization as a British Citizen</label>
            </value>
            <value>
                <fullName>NI NO. + (E) letter issued by Home Office granting Indefinite Leave to enter or Remain in the UK</fullName>
                <isActive>false</isActive>
                <label>NI NO. + (E) letter issued by Home Office granting Indefinite Leave to enter or Remain in the UK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/Proof_of_ID__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of ID</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/References_Checked__c.field-meta.xml
<CustomField>
    <fullName>References_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>References Checked</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgAtsCandidateIntegrationRef__c.field-meta.xml
<CustomField>
    <fullName>stgAtsCandidateIntegrationRef__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Candidate</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>2nd Tier Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgAtsShiftIntegrationRef__c.field-meta.xml
<CustomField>
    <fullName>stgAtsShiftIntegrationRef__c</fullName>
    <label>stgAtsShiftIntegrationRef</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>stgFrontOfficeIntegrationSystem__c</fullName>
    <description>stgFrontOfficeIntegrationSystem in Integration Layer</description>
    <label>Brand</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgPayProfile__c.field-meta.xml
<CustomField>
    <fullName>stgPayProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pay Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.stgAtsCandidateIntegrationRef__c</field>
            <operation>equals</operation>
            <valueField>IP_PayProfile__c.IP_Candidate__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>IP_PayProfile__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsClientId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsClientId__c</fullName>
    <label>stgVmsClientId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsRoleId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsRoleId__c</fullName>
    <label>stgVmsRoleId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsShiftId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsShiftId__c</fullName>
    <label>stgVmsShiftId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/Visa_Type__c.field-meta.xml
<CustomField>
    <fullName>Visa_Type__c</fullName>
    <label>Visa Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multi</fullName>
            </value>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
            <value>
                <fullName>Tier 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/VmsCandidateMapping.cls
/**
 * Created by mrahman on 2020-11-11.
 * TEST CLASS: VmsSubmitCandidateTest
 * DESC: THIS IS SALESFORCE JS TO EVO APPLICATION/CANDIDATE SUBMISSION MAPPING
 *
 * Update by mrahman on 9/12/2020 to add more fields
 * DESC: Detals can be found in https://impellam.atlassian.net/browse/PT1-177
 */

public class VmsCandidateMapping {
    public VmsCandidateMapping(){}

    public String stgAtsApplicationId;
    public String stgFrontOfficeIntegrationSystem;
    public String stgVmsClientId;
    public String stgVmsRoleId;
    public String stgVmsShiftId;
    public String stgAtsShiftIntegrationRef;
    public String stgAtsAgencyRef;
    public String stgCandidateFirstName;
    public String stgCandidateLastName;
    public String stgCandidateEmail;
    public String stgCandidateNINumber;
    public String stgMailingStreet;
    public String stgMailingCity;
    public String stgMailingPostCode;
    public String stgProofofRTW;
    public String stgProofofIdentity;
    public String stgReferenceChecked;
    public String stgPORTWType;
    public Date stgVisaExpiryDate;
    public String stgVisaType;
    public List<CandidateDocument> stgCandidateDocuments;

    public VmsCandidateMapping(StagingJobApplication__c ja){
        this.stgAtsApplicationId = ja.Id;
        this.stgFrontOfficeIntegrationSystem = ja.stgFrontOfficeIntegrationSystem__c;
        this.stgVmsClientId = ja.stgVmsClientId__c;
        this.stgVmsRoleId = ja.stgVmsRoleId__c;
        this.stgVmsShiftId = ja.stgVmsShiftId__c;
        this.stgAtsShiftIntegrationRef  = ja.stgAtsShiftIntegrationRef__c;
        this.stgAtsAgencyRef  = ja.stgPayProfile__r.IP_PayrollID__c;
        this.stgCandidateFirstName  = ja.stgAtsCandidateIntegrationRef__r.FirstName;
        this.stgCandidateLastName  = ja.stgAtsCandidateIntegrationRef__r.LastName;
        this.stgCandidateEmail  = ja.stgAtsCandidateIntegrationRef__r.Email;
        this.stgCandidateNINumber  = ja.stgAtsCandidateIntegrationRef__r.sirenum__National_Insurance__c;
        this.stgMailingStreet = ja.stgAtsCandidateIntegrationRef__r.MailingStreet;
        this.stgMailingCity = ja.stgAtsCandidateIntegrationRef__r.MailingCity;
        this.stgMailingPostCode = ja.stgAtsCandidateIntegrationRef__r.MailingPostalCode;
        this.stgProofofRTW = ja.PORTW_Type__c.length()>0?'yes':'no'; // if PORTW_Type__c has a value then send yes else no
        this.stgPORTWType = ja.PORTW_Type__c;
        this.stgReferenceChecked = ja.References_Checked__c?'yes':'no'; //If References_Checked__c has a value then send yes else no
        this.stgProofofIdentity = ja.Proof_of_ID__c?'yes':'no'; //if Proof_of_ID__c has a value then send yes else no
        this.stgVisaExpiryDate = ja.Visa_Expiry_Date__c;
        this.stgVisaType = ja.Visa_Type__c;
        this.stgCandidateDocuments = getDocumentURL(ja.Id);
    }

    public class CandidateDocument {
        public String contentVersionId;
        public String fileType;
        public String fileExtension;
        public String title;
        public String versionNumber;
        public String pathOnClient;
    }

    public List<CandidateDocument> getDocumentURL(Id recordId){
        String docId;
        //String docUrl;
        List<CandidateDocument> cds = new List<CandidateDocument>();
        try{
            docId = [SELECT ContentDocumentId FROM ContentDocumentLink
            WHERE LinkedEntityId =: recordId LIMIT 1].ContentDocumentId;
            ContentVersion cv = [SELECT Id, FileType, FileExtension, Title,VersionNumber, PathOnClient
                                FROM ContentVersion
                                WHERE ContentDocumentId =: docId
                                AND IsLatest = true];
            CandidateDocument cd = new CandidateDocument();
            cd.contentVersionId = cv.Id;
            cd.fileType = cv.FileType;
            cd.fileExtension = cv.FileExtension;
            cd.title = cv.Title;
            cd.versionNumber = cv.VersionNumber;
            cd.pathOnClient = cv.PathOnClient;
            cds.add(cd);
            //docUrl = URL.getSalesforceBaseUrl().toExternalForm()
            //        + '/sfc/servlet.shepherd/document/download/' + docId;
        } catch(Exception ex){
            System.debug('Exception - ' + ex);
            System.debug('Application Record Id: '+ recordId +' does not have a CV to submit.');
        }
        return cds;
    }
}