Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/ts2__EEO_Gender__c.field-meta.xml
<CustomField>
    <fullName>ts2__EEO_Gender__c</fullName>
    <label>EEO Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/StagingJobApplication__c.object-meta.xml
<CustomObject>
    <label>Third Party Job Application</label>
    <nameField>
        <displayFormat>VMS-A-{YYYY}{MM}-{0}</displayFormat>
        <label>Staging Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/StagingJobOrder__c.field-meta.xml
<CustomField>
    <fullName>StagingJobOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Third_Party_Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgAtsCandidateIntegrationRef__c.field-meta.xml
<CustomField>
    <fullName>stgAtsCandidateIntegrationRef__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Candidate</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>2nd Tier Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>stgFrontOfficeIntegrationSystem__c</fullName>
    <description>stgFrontOfficeIntegrationSystem in Integration Layer</description>
    <label>Brand</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsClientId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsClientId__c</fullName>
    <label>stgVmsClientId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsRoleId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsRoleId__c</fullName>
    <label>stgVmsRoleId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsShiftId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsShiftId__c</fullName>
    <label>stgVmsShiftId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCandidateRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgCandidateRoleId__c</fullName>
    <label>StgCandidateRoleId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystem__c</fullName>
    <label>StgFrontOfficeIntegrationSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/VmsCopyMoveCandidateMappingCapita.cls
public with sharing class VmsCopyMoveCandidateMappingCapita {
    public String stgFrontOfficeIntegrationSystem;
    public String stgVmsClientId;
    public String stgVmsRoleId;
    public String stgVmsShiftId;
    public String stgAtsCandidateIntegrationRef;
    public String stgCandidateRoleId;
    public Date stgDateOfBirth;
    public String stgGender;
    public String stgTitle;
	public String stgMobileTel;
    // public String stgAddressline1;
    // public String stgTowncity;
    public String stgCounty;
    public String stgCountry;
    // public String stgPostcode;

    public VmsCopyMoveCandidateMappingCapita() {
    }

    public VmsCopyMoveCandidateMappingCapita(StagingJobApplication__c ja) {
        this.stgVmsClientId = ja.stgVmsClientId__c;
        this.stgVmsRoleId = ja.stgVmsRoleId__c;
        this.stgVmsShiftId = ja.stgVmsShiftId__c;
        this.stgAtsCandidateIntegrationRef = ja.Id;
        this.stgCandidateRoleId = ja.StagingJobOrder__r.stgCandidateRoleId__c;
        this.stgFrontOfficeIntegrationSystem  = ja.StgFrontOfficeIntegrationSystem__c;
        this.stgDateOfBirth = ja.stgAtsCandidateIntegrationRef__r.Birthdate;
        this.stgGender = ja.stgAtsCandidateIntegrationRef__r.ts2__EEO_Gender__c;
        this.stgTitle = ja.stgAtsCandidateIntegrationRef__r.Salutation;
        this.stgMobileTel = ja.stgAtsCandidateIntegrationRef__r.MobilePhone;//Jyothi
        // this.stgAddressline1 = ja.stgAtsCandidateIntegrationRef__r.MailingStreet;
        // this.stgTowncity = ja.stgAtsCandidateIntegrationRef__r.MailingCity;
        this.stgCounty = ja.stgAtsCandidateIntegrationRef__r.MailingState;
        this.stgCountry = ja.stgAtsCandidateIntegrationRef__r.MailingCountry;
        // this.stgPostcode = ja.stgAtsCandidateIntegrationRef__r.MailingPostalCode;
    }
}