Frankbelford/uatv1ba/force-app/main/default/objects/Driving_Settings__c/Driving_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Driving module.</description>
    <label>Driving Settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Driving_Settings__c/fields/Disable_Week_Generation__c.field-meta.xml
<CustomField>
    <fullName>Disable_Week_Generation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Week Generation</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/SirenumPlugin_Payroll.cls
/**
 * Created by akruv on 03/01/2018.
 */

global with sharing class SirenumPlugin_Payroll implements sirenum.TimesheetResultsListener {
    @testVisible private List<Id> timesheetIds = null;
    global SirenumPlugin_Payroll() {

    }

    global void handleEvent(Sirenum.TimesheetResultsEvent event) {
        if (!Driving_Settings__c.getOrgDefaults().Disable_Week_Generation__c) {
            Database.executeBatch(new DrivingDataGenerator_Batch(((this.timesheetIds != null) ? this.timesheetIds : event.getIds())));
        }
    }
}