Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(Owner.Brand__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <formula>TEXT(Owner.IP_TempestDivision__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tempest Division</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/Contact_Site_link__c.object-meta.xml
<CustomObject>
    <description>Link between Contacts and Sites allowing a many to many relationship</description>
    <label>Contact / Site link</label>
    <nameField>
        <displayFormat>LINKID-{000000}</displayFormat>
        <label>Contact / Site link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact / Site links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact / Site links</relationshipLabel>
    <relationshipName>Contact_Site_links</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>IP_Site__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Contact__c.field-meta.xml
<CustomField>
    <fullName>IP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact / Site links (Contact)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_PortalType__c.field-meta.xml
<CustomField>
    <fullName>IP_PortalType__c</fullName>
    <label>Portal Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Secondary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Escalation Hours Approver</fullName>
            </value>
            <value>
                <fullName>Viewer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>VMS - Hours Approver</fullName>
            </value>
            <value>
                <fullName>VMS - Authorised Booker</fullName>
            </value>
            <value>
                <fullName>VMS User</fullName>
                <isActive>false</isActive>
                <label>VMS User</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Site__c.field-meta.xml
<CustomField>
    <fullName>IP_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>sirenum__Site__c.sirenum__Operating_Company__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sirenum__Site__c</referenceTo>
    <relationshipLabel>Contact / Site links (Site2)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/IP_Shift_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Shift Template</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/Branch_Address__c.field-meta.xml
<CustomField>
    <fullName>Branch_Address__c</fullName>
    <label>Branch Street</label>
    <type>TextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_City__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_City__c</fullName>
    <label>Branch City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_Country__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_Country__c</fullName>
    <label>Branch Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_County__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_County__c</fullName>
    <label>Branch County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_Postal_Code__c</fullName>
    <label>Branch Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Site_Name__c.field-meta.xml
<CustomField>
    <fullName>IP_Site_Name__c</fullName>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <label>Tempest Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDivision</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Test_ClientNotification.cls
@isTest
public class Test_ClientNotification {

    @testSetup
    static void shiftSetup() {
        List<Contact> clientContacts = new List<Contact>();
        UserRole rId = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
        User u = new User(LastName = 'LIVESTON',FirstName='JASON',Alias = 'jliv',Email = 'mm.sf@outlook123.com',
                Username = 'dummydcwecweEmail6786367@email.com', ProfileId = p.id, TimeZoneSidKey = 'GMT',
                LanguageLocaleKey = 'en_US', EmailEncodingKey = 'UTF-8', LocaleSidKey = 'en_US',IP_TempestDepartment__c='1062',
                IP_TempestDivision__c='NTS',Department='1062',IP_PassToTempest__c=true, Brand__c='Blue Arrow', UserRoleId=rId.Id);
        insert u;
        System.runAs(u){
            insert new IP_Shift_Template__c(name = '1062', IP_Branch_City__c = 'test1',IP_Branch_Country__c='count1',IP_Branch_County__c='count2',IP_Branch_Postal_Code__c='B12 3SS',Branch_Address__c='street1',Email__c='singh.taji26@gmail.com',Fax__c='123456',Phone__c='54735622',IP_Site_Name__c='Name1');
            TestDataFactory.setupShifts();
            List<sirenum__Shift__c> unApprovedShifts = new List<sirenum__Shift__c>();
            for(sirenum__Shift__c s : [SELECT Id, Name, sirenum__Site__c, sirenum__Contact__c, sirenum__Scheduled_End_Time__c, sirenum__Cancelled__c, sirenum__Published__c, IP_ClientRejected__c, IP_CandidateApproved__c, IP_ClientApproved__c
                                        FROM sirenum__Shift__c LIMIT 10]){
                sirenum__Shift__c cs = s.clone();
                cs.sirenum__Cancelled__c  = false;
                cs.sirenum__Published__c = true;
                cs.IP_ClientRejected__c  = false;
                cs.IP_CandidateApproved__c = true;
                cs.IP_ClientApproved__c = false;
                cs.sirenum__Scheduled_Start_Time__c = Datetime.now().addDays(-7).addHours(-10);
                cs.sirenum__Scheduled_End_Time__c = Datetime.now().addDays(-7);
                cs.sirenum__Site__c = s.sirenum__Site__c;
                cs.sirenum__Contact__c = s.sirenum__Contact__c;
                unApprovedShifts.add(cs);
            }
            insert unApprovedShifts;
            Account client = [SELECT Id, Name FROM Account WHERE RecordType.Name = 'Account' LIMIT 1];
            Contact cc = TestDataFactory.createContact(client.Id, 1)[0];
            insert cc;
            List<Contact_Site_link__c> csls = new List<Contact_Site_link__c>();
            for(sirenum__Site__c s : [SELECT Id, Name, sirenum__Operating_Company__c FROM sirenum__Site__c WHERE sirenum__Operating_Company__c =: client.Id]){
                csls.add(new Contact_Site_link__c(Account__c=s.sirenum__Operating_Company__c
                        ,IP_Contact__c = cc.Id
                        ,IP_PortalType__c='Escalation Hours Approver'
                        ,IP_Site__c = s.Id)
                );
            }
            insert csls;
            clientContacts = [SELECT Id, FirstName, LastName, Email, Brand__c, Account.Name, AccountId FROM Contact WHERE Account.RecordType.Name = 'Account'];
        }
        ApexPages.currentPage().getParameters().put('id', String.valueOf(clientContacts[0].Id));
        CreateInstantPortalUserController.createUser();

        ApexPages.currentPage().getParameters().put('id', String.valueOf(clientContacts[1].Id));
        CreateInstantPortalUserController.createUser();
    }

    @IsTest
    static void testClientNotificationPortals(){
        Test.startTest();
            Database.executeBatch(new ClientNotificationPortals());
        Test.stoptest();
    }

    @IsTest
    static void testClientEscalarionNotificationPortals(){
        Test.startTest();
            ClientEscalarionNotificationPortals  b = new ClientEscalarionNotificationPortals ();
            id batchID =  Database.executeBatch(b,200);
        Test.stopTest();
    }
}