Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(Owner.Brand__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <label>GUID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_EmergencyPull__c.field-meta.xml
<CustomField>
    <fullName>IP_EmergencyPull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Pull</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP PayFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/Impellam_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RSS Global Settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>IP_Candidate__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine1__c</fullName>
    <description>for recording the business address for the candidate, LTD, umbrella, etc. only is required</description>
    <label>Business Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine2__c</fullName>
    <label>Business Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressPostcode__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressPostcode__c</fullName>
    <label>Business Address Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressTown__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressTown__c</fullName>
    <label>Business Address Town</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyName__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyName__c</fullName>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_EmergencyPull__c.field-meta.xml
<CustomField>
    <fullName>IP_EmergencyPull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Pull</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <label>Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_VATNumber__c</fullName>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/LTD.recordType-meta.xml
<RecordType>
    <fullName>LTD</fullName>
    <active>true</active>
    <label>LTD</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/Test_AssignmentRestNew.cls
@isTest
private class Test_AssignmentRestNew {
    
   /* @testsetup
    static void createAssignment()
    {   
        Account client = TestDataFactory.createClients(1)[0]; 
        Insert client;
        //Inserting Payroll records
        insert new Payroll_Swtich__c(Name='Stoppayroll',Batch_check__c=false);
        
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        Contact cont = TestDataFactory.createContact(client.id, 1)[0];
        Insert cont;
        
        Test.startTest();
        Account clientacc = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert clientacc;
        
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        
        Contact candidate = TestDataFactory.createCandidate(clientacc.id, 1)[0];
        Insert candidate;
        
        sirenum__ProActiveContract__c pac = TestDataFactory.sirenumProActiveContract(client.Id, candidate.Id, 1)[0];
        Insert pac;
        
        sirenum__Rota__c sector = TestDataFactory.createSector(1)[0]; 
        Insert sector;
        
        sirenum__Job_Type__c jobType =TestDataFactory.createJobType(sector.id, 1)[0];
        Insert jobType;
        
        sirenum__Team__c jrole = TestDataFactory.createJobRole(pac.Id, jobType.Id, 1)[0]; 
        Insert jrole;
        
        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        insert topaz;
        
        
        sirenum__Site__c site = TestDataFactory.createSites(client.Id,topaz.id,1)[0];
        site.IP_PassClientToTempest__c = false;
        site.IP_PassClientAddressToTempest__c = false;
        insert site;
        
        Profile p = [SELECT Id FROM Profile where name='System Administrator'];
        User usr = TestDataFactory.createUsers(p.Id,1)[0];
        usr.username = 'bhi@hgf.com';
        usr.IP_TempestDepartment__c='1062';
        insert usr; 
        sirenum__Placement__c splace = TestDataFactory.createSPlacement1(candidate.Id, pac.Id, jrole.Id,usr.Id, 1)[0]; 
        splace.name = 'TestPlace1';
        splace.sirenum__Site__c = site.id;
        splace.IP_EmergencyPull__c = TRUE;
        splace.IP_Costcode__c = '1062';
        splace.IP_PassToTempest__c = true;
        splace.IP_Consultant1LookupSplitShare__c = usr.Id;
        Insert splace;
        
        sirenum__Shift__c shift = TestDataFactory.createShift(splace.id,site.id,1)[0];
        shift.sirenum__Contact__c = candidate.Id;
        insert shift;
        
        sirenum__Timesheet__c sheet = TestDataFactory.createTimeSheet(client.Id,candidate.Id,1)[0];
        sheet.sirenum__Week_Ending__c = System.today().addDays(-2);
        insert sheet;
        Test.stopTest();
        
        sirenum__Timesheet_Line__c line = TestDataFactory.createTimeSheetLine(sheet.id,shift.id,1)[0];
        line.IP_PassToTempest__c = true;
        insert line;
    }*/
    
    @future
    public static void createTestUser(){
      Profile p = [SELECT Id FROM Profile where name='System Administrator'];  
    User usr = TestDataFactory.createUsers(p.Id,1)[0];
        usr.IP_TempestDepartment__c = '1062';
        usr.username = 'nbjudui453@mko.com';
        usr.Brand__c = 'MGG';
        usr.IsActive = true;
        //usr.ContactId= candidateId;
        insert usr;
    }
    
    @testsetup
    static void createWorker()
    {          
        createTestUser();
         Test.startTest();
        User usr = [SELECT Id,Name FROM User WHERE Profile.name='System Administrator' and isactive=true limit 1];
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name LIKE '%Customer Community User%' Limit 1];
       System.runAs(usr){
            
           Account client = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert client;
        
        Account act = TestDataFactory.createAccounts(1)[0]; 
        insert act;
        
          insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
                  insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= false);

         Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
        candidate.Firstname = 'RestCand1';
        candidate.GUID__c = 'XYZ';
           candidate.ownerid = usr.id;
    Insert candidate;
        //createTestUser(candidate.Id);
           
        //User user = TestDataFactory.createCommunityUser(candidate, portalProfile.Id);
         /*user.IP_TempestDepartment__c = '1062';
         insert user;
           candidate.OwnerId = user.id;
           update candidate;*/
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= false);
               id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('LTD').getRecordTypeId();
       
       
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());      

         IP_PayProfile__c payprofile = new IP_PayProfile__c();
         payprofile.RecordTypeId = payRTId;
          
       payprofile.IP_Candidate__c = candidate.id;
         payprofile.IP_CompanyName__c='sfdc';
         payprofile.IP_Status__c = 'Active'; 
         payprofile.IP_CompanyRegNo__c  = 'ad123456';
         payprofile.IP_VATNumber__c     = '123456789';
         payprofile.IP_PayrollID__c  = 'testpaynew';
         payprofile.IP_VATRegistered__c=true;
         payprofile.IP_OkToSupply__c=1;
         payprofile.IP_BusinessAddressLine1__c='test address 1';
         payprofile.IP_BusinessAddressLine2__c='test address 2';
         payprofile.IP_BusinessAddressTown__c='town city';
         payprofile.IP_BusinessAddressPostcode__c='12345678';
         payprofile.IP_PayFrequency__c='Weekly';
         payprofile.IP_PaymentType__c='BACS';
         payprofile.IP_PassToTempest__c=true;
        payprofile.IP_LastPassedToTempest__c = System.now();
        payprofile.IP_BankAccountName__c = 'Bank 1';
        payprofile.IP_AccountNumber__c = '89786756';
        payprofile.IP_SortCode__c = '998866';
        payprofile.IP_EmergencyPull__c = TRUE;
         
         insert payprofile; 
                sirenum__ProActiveContract__c pac = TestDataFactory.sirenumProActiveContract(client.Id, candidate.Id, 1)[0];
        Insert pac;
        
        sirenum__Rota__c sector = TestDataFactory.createSector(1)[0]; 
        Insert sector;
        
        sirenum__Job_Type__c jobType =TestDataFactory.createJobType(sector.id, 1)[0];
        Insert jobType;
        
        sirenum__Team__c jrole = TestDataFactory.createJobRole(pac.Id, jobType.Id, 1)[0]; 
        Insert jrole;
        
        
      /*User usr = TestDataFactory.createUsers(p.Id,1)[0];
        usr.IP_TempestDepartment__c = '1062';
        usr.username = 'nbjudui453@mko.com';
        insert usr; */
          IP_TopazGlobalClientInformation__c tpz = TestDataFactory.createTopaz(1)[0]; 
        insert tpz;    
        
        sirenum__Site__c ssite = TestDataFactory.createSites(act.id, tpz.id,1)[0];
        ssite.IP_PassClientToTempest__c = false;
    ssite.IP_PassClientAddressToTempest__c=false;
        insert ssite;
        
        sirenum__Placement__c splace = TestDataFactory.createSPlacement1(candidate.Id, pac.Id, jrole.Id,usr.Id, 1)[0]; 
        splace.sirenum__site__C = ssite.id;
        splace.IP_PassToTempest__c = true;
        splace.IP_EmergencyPull__c=true;
        Insert splace;
        
      
        Test.StopTest();
        sirenum__Shift__c shft = TestDataFactory.createShift(splace.id, ssite.id,1)[0]; 
            shft.sirenum__Contact__c = candidate.Id;
    insert shft;  
        
        
         sirenum__Timesheet__c sts = TestDataFactory.createTimeSheet(client.id, candidate.Id,1)[0]; 
        sts.IP_DuplicateCheckPassOK__c = TRUE;
        sts.sirenum__Week_Ending__c = Date.newInstance(2018, 02, 01);
        
        Insert sts;
      
        sirenum__Timesheet_Line__c stsl = TestDataFactory.createTimeSheetLine(sts.Id,shft.id,1)[0]; 
        stsl.IP_POErrorLogField__c = 'TestValue';
        Insert stsl;
         
           
        }
    }
    static testMethod void testDoGet() 
    {        
        test.startTest();
        User usr = [SELECT Id,Name,IP_TempestDepartment__c FROM User WHERE Profile.name='System Administrator' and isactive=true limit 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        Impellam_Settings__c set1 =  new Impellam_Settings__c(name = 'AssignmentRest', Limit__c = '20');
        insert set1;
        Integer limit1 = Integer.Valueof(set1.Limit__c);
        req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/standard/v1/collect/assignment/'+usr.IP_TempestDepartment__c+'/XYZ';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        List<sirenum__Timesheet_Line__c> tsline = [select id, name,IP_TempestDepartment__c,IP_PassToTempest__c,sirenum__shift__c,sirenum__Timesheet__r.sirenum__Week_Ending__c from sirenum__Timesheet_Line__c];
       System.debug('tsline :::'+tsline);
        AssignmentRest.ResponseClass results = AssignmentRest.doGet();          
        /*System.assertEquals('false', results.success);  
        System.assertEquals('Error in querying records', results.message);  */
        test.stopTest();        
    }   
    
   /* static testMethod void testDoGet() 
    {        
        test.startTest();
        User usr = [SELECT Id,Name,IP_TempestDepartment__c FROM User WHERE Profile.name='System Administrator' and isactive=true limit 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        Impellam_Settings__c set1 =  new Impellam_Settings__c(name = 'AssignmentRest', Limit__c = '100');
        insert set1;
        Integer limit1 = Integer.Valueof(set1.Limit__c);
        List<sirenum__Timesheet_Line__c> ids = [select id, name,IP_TempestDepartment__c,IP_PassToTempest__c,sirenum__shift__c,sirenum__Timesheet__r.sirenum__Week_Ending__c from sirenum__Timesheet_Line__c];
       System.debug('timesheet line:::'+ids);
        req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/standard/v1/collect/assignment/'+user.IP_TempestDepartment__c+'/XYZ';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        AssignmentRest.ResponseClass results = AssignmentRest.doGet();       
        System.assertEquals('true', results.success);  
        //System.assertEquals('Error in querying records', results.message);  
        System.assertEquals('Query executed successfully.', results.message);
        test.stopTest();
        
    }*/
     static testMethod void testDoGet1() 
    {        
        test.startTest();
        User usr = [SELECT Id,Name,IP_TempestDepartment__c FROM User WHERE Profile.name='System Administrator' and isactive=true limit 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        Impellam_Settings__c set1 =  new Impellam_Settings__c(name = 'AssignmentEmergencyRest', Limit__c = '20');
        insert set1;
        Integer limit1 = Integer.Valueof(set1.Limit__c);
        req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/standard/v1/collect/assignment/'+usr.IP_TempestDepartment__c+'/XYZ';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        List<sirenum__Timesheet_Line__c> tsline = [select id, name,IP_TempestDepartment__c,IP_PassToTempest__c,sirenum__shift__c,sirenum__Timesheet__r.sirenum__Week_Ending__c from sirenum__Timesheet_Line__c];
       System.debug('tsline :::'+tsline);
        AssignmentEmergencyRest.ResponseClass results = AssignmentEmergencyRest.doGet();          
        /*System.assertEquals('false', results.success);  
        System.assertEquals('Error in querying records', results.message);  */
        test.stopTest();        
        /*RestRequest req = new RestRequest(); 
         RestResponse res = new RestResponse();
        Impellam_Settings__c set1 =  new Impellam_Settings__c(name = 'AssignmentEmergencyRest', Limit__c = '100');
        insert set1;
        Integer limit1 = Integer.Valueof(set1.Limit__c);
        req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/emergency/v1/collect/assignment/1062/A123';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        AssignmentEmergencyRest.ResponseClass results = AssignmentEmergencyRest.doGet();       
        System.assertEquals('true', results.success);  
        //System.assertEquals('Error in querying records', results.message);  
        System.assertEquals('Query executed successfully.', results.message);
        test.stopTest();*/
        
    }
    }