Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(Owner.Brand__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/IP_2ndTierSupplier.recordType-meta.xml
<RecordType>
    <fullName>IP_2ndTierSupplier</fullName>
    <active>true</active>
    <label>2nd Tier Supplier</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CategoryOfWork__c.field-meta.xml
<CustomField>
    <fullName>IP_CategoryOfWork__c</fullName>
    <description>Which business areas does the person work in</description>
    <inlineHelpText>Which business areas does the person work in</inlineHelpText>
    <label>Category of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_EmergencyPull__c.field-meta.xml
<CustomField>
    <fullName>IP_EmergencyPull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Pull</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_FirstPassExternalWorker__c.field-meta.xml
<CustomField>
    <fullName>IP_FirstPassExternalWorker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Pass (External Worker)</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LastPassedToTempest2ndTier__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest2ndTier__c</fullName>
    <label>Last Passed to Tempest (2nd Tier)</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Pass2ndTierToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_Pass2ndTierToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass 2nd tier to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <formula>TEXT(Owner.IP_TempestDivision__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tempest Division</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TimesheetIDLink__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetIDLink__c</fullName>
    <label>Timesheet ID Link</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/PPE_Type__c.field-meta.xml
<CustomField>
    <fullName>PPE_Type__c</fullName>
    <label>PPE Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Safety Shoes/boots</fullName>
            </value>
            <value>
                <fullName>Hi vis</fullName>
            </value>
            <value>
                <fullName>Sweatshirt</fullName>
            </value>
            <value>
                <fullName>Polo shirt</fullName>
            </value>
            <value>
                <fullName>Trousers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/IP_2ndTierCandidate.recordType-meta.xml
<RecordType>
    <fullName>IP_2ndTierCandidate</fullName>
    <active>true</active>
    <label>2nd Tier Candidate</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/IP_BranchStatus__c.object-meta.xml
<CustomObject>
    <label>Branch Status List</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Status Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_BranchID__c.field-meta.xml
<CustomField>
    <fullName>IP_BranchID__c</fullName>
    <externalId>true</externalId>
    <label>Branch ID</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_CompanyCode__c/IP_CompanyCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Brand Company Code</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_CompanyCode__c/fields/IP_CompanyCodeValue__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyCodeValue__c</fullName>
    <label>Company Code Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/IP_ImpellamGlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Global Settings Outbound Transf</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/IP_LastTransmissionDate__c.field-meta.xml
<CustomField>
    <fullName>IP_LastTransmissionDate__c</fullName>
    <label>Last Transmission Date</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/IP_OutboundErrorEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>IP_OutboundErrorEmailAddress__c</fullName>
    <label>Outbound Error Email Address</label>
    <type>Email</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/IP_OutboundDataTransfer__c.object-meta.xml
<CustomObject>
    <description>Object that holds data for transfer out of the system</description>
    <label>Outbound Data Transfer</label>
    <nameField>
        <displayFormat>ODT-{0000000000}</displayFormat>
        <label>Outbound Data Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Data Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_EmergencyPull__c.field-meta.xml
<CustomField>
    <fullName>IP_EmergencyPull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Pull</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_OriginRecordID__c.field-meta.xml
<CustomField>
    <fullName>IP_OriginRecordID__c</fullName>
    <label>Origin Record ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Passed__c.field-meta.xml
<CustomField>
    <fullName>IP_Passed__c</fullName>
    <label>Passed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_TimesheetID__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetID__c</fullName>
    <label>Timesheet SF ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/TestValidation__c.field-meta.xml
<CustomField>
    <fullName>TestValidation__c</fullName>
    <label>TestValidation</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Parallel_Payroll_Check__c/IP_Parallel_Payroll_Check__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Parallel Payroll Check</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Parallel_Payroll_Check__c/fields/Run_Parallel_Payroll__c.field-meta.xml
<CustomField>
    <fullName>Run_Parallel_Payroll__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Parallel Payroll</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <label>Tempest Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDivision</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/User_Profile_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of frequently used profile Id&apos;s to use in apex or formula</description>
    <label>User Profile Id</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <label>Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_PassExternalWorker.cls
@isTest
public class Test_PassExternalWorker {
    @testSetup static void generateTestData() {
        insert new User_Profile_Id__c(
            Name = 'User Portal',
            Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'User Portal'].Id
        );

        IP_ImpellamGlobalSetting__c setting = new IP_ImpellamGlobalSetting__c();
        setting.IP_LastTransmissionDate__c = Date.newInstance(2019,07,01);
        setting.IP_OutboundErrorEmailAddress__c = 'test@test.com';
        insert setting;

        Profile p1 = [SELECT Name FROM Profile WHERE Name = 'User Portal'];
        User usr1 = new User(
            LastName = 'himanshu',
            FirstName = 'JASON',
            Alias = 'jliv1',
            Email = 'mm1.sf@outlook.com',
			Username = 'dummyEmail989@email.com',
            ProfileId = p1.Id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US',
            IP_TempestDepartment__c = '1062',
            Brand__c = 'Blue Arrow',
        	IP_TempestDivision__c = 'NTS',
            Department = '1062',
            IP_PassToTempest__c = true
        );
        insert usr1;

        insert new IP_CompanyCode__c(Name = 'CompanyCode', IP_CompanyCodeValue__c = 'BAL');
        insert new IP_Parallel_Payroll_Check__c(Name = 'RunParallelCheck', Run_Parallel_Payroll__c = false);

        IP_BranchStatus__c b = new IP_BranchStatus__c();
        b.IP_BranchID__c = '1062';
        b.Name = 'Test';
        insert b;

        insert new IP_JSToFrostSwtich__c(Name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(Name = 'Stoppayroll', Batch_check__c = false);

        RecordType maincondRec = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' And DeveloperName = 'Contact'];
        RecordType rtacc = [SELECT Id FROM RecordType WHERE SobjectType='Account' AND DeveloperName = 'IP_2ndTierSupplier'];
        RecordType rtcon = [SELECT Id FROM RecordType WHERE SobjectType='Contact' AND DeveloperName = 'IP_2ndTierCandidate'];
        RecordType accountRec1 = [SELECT Id FROM RecordType WHERE sObjectType = 'Account' And DeveloperName = 'Account'];

        Account acc1 = new Account(Name = 'Capita', RecordTypeId = accountRec1.Id);
        Account a = new Account(Name = 'Candidates', RecordTypeId = rtacc.Id);
        insert new List<Account> { acc1, a };

        Contact maincon = new Contact(
            RecordTypeId = maincondRec.id,
            FirstName = 'Test',
            LastName = 'Main Contact',
            PPE_Type__c = 'Polo shirt',
            AccountID = acc1.id
        );

        Contact c = new Contact();
        c.LastName = 'contacttest';
        c.IP_CategoryOfWork__c = 'Catering';
        c.RecordTypeId = rtcon.id;
        c.FirstName = 'test';
        c.AccountId = a.Id;
        c.sirenum__National_Insurance__c = 'TN013054M';
        c.IP_FirstPassExternalWorker__c = false;
        c.IP_EmergencyPull__c = false;
        c.PPE_Type__c = 'Polo shirt';
        c.OwnerId = usr1.Id;

        insert new List<Contact> { maincon, c };

        sirenum__ProActiveContract__c pac = TestDataFactory.sirenumProActiveContract(a.Id, c.Id, 1)[0];
        insert pac;

        sirenum__Rota__c sector = TestDataFactory.createSector(1)[0];
        insert sector;

        sirenum__Job_Type__c jobType = TestDataFactory.createJobType(sector.id, 1)[0];
        insert jobType;

        sirenum__Team__c jrole = TestDataFactory.createJobRole(pac.Id, jobType.Id, 1)[0];
        insert jrole;

        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        insert topaz;

        sirenum__Site__c site = new sirenum__Site__c();
        site.Name = 'testsite';
        site.sirenum__Operating_Company__c= acc1.id;
        site.IP_ClientIDLegacy__c = '123';
        site.IP_ClientInvoiceName__c = 'test abc';
        site.IP_PublicSector__c = 'No';
        site.IP_InvoiceContactText__c = 'Contact 1';
        insert site;

        sirenum__Placement__c splace1 = TestDataFactory.createSPlacement1(c.Id, pac.Id, jrole.Id, usr1.Id, 1)[0];
        splace1.sirenum__Site__c = site.id;
        insert splace1;

        sirenum__Shift__c shft1 = TestDataFactory.createShift(splace1.Id,site.id,1)[0]; 
        shft1.sirenum__Scheduled_Start_Time__c = System.now();
        shft1.sirenum__Scheduled_End_Time__c = System.now().addHours(2);
        shft1.sirenum__Contact__c = c.id;
        insert shft1;

        sirenum__Timesheet__c timesheet = new sirenum__Timesheet__c();
        timesheet.sirenum__Worker__c = c.id;
        timesheet.sirenum__Week_Ending__c = System.today();
        timesheet.sirenum__Non_Taxed_Expenses__c = 10.2;
        timesheet.sirenum__Taxed_Expenses__c = 20.1;
        timesheet.sirenum__Non_Taxed_Deductions__c = 10.5;
        timesheet.sirenum__Taxed_Deductions__c = 5.2;
        insert timesheet;

        List<sirenum__Timesheet_Line__c> tsl = TestDataFactory.createTimeSheetLine(timesheet.Id, shft1.id, 1);
        insert tsl;
    }

	static testmethod void validateFunctionality_Test_Case_One() {
        Contact theContact = [SELECT Id FROM Contact WHERE LastName = 'contacttest' LIMIT 1];
        sirenum__Timesheet__c theTimesheet = [SELECT Id FROM sirenum__Timesheet__c];

        IP_OutboundDataTransfer__c ob = new IP_OutboundDataTransfer__c();
        ob.IP_OriginRecordID__c = theContact.Id;
        ob.IP_TimesheetID__c = theTimesheet.Id;
        ob.IP_Passed__c = null;
        ob.TestValidation__c = 'test';
        insert ob;

        Test.startTest();

        theContact.IP_TimesheetIDLink__c = theTimesheet.Id;
        theContact.IP_LastPassedToTempest2ndTier__c = null;
        theContact.IP_Pass2ndTierToTempest__c = true;
        theContact.IP_FirstPassExternalWorker__c = true;
        theContact.IP_EmergencyPull__c = true;
        update theContact;

        Test.stopTest();
    }

	static testmethod void validateFunctionality_Test_Case_Two() {
		Contact theContact = [SELECT Id FROM Contact WHERE LastName = 'contacttest' LIMIT 1];

        Test.startTest();

        theContact.IP_TimesheetIDLink__c = [SELECT Id FROM sirenum__Timesheet__c].Id;
        theContact.IP_LastPassedToTempest2ndTier__c = null;
        theContact.IP_Pass2ndTierToTempest__c = true;
        theContact.IP_FirstPassExternalWorker__c = true;
        theContact.IP_EmergencyPull__c = true;
        update theContact;

        Test.stopTest();
    }

	static testmethod void validateFunctionality_Test_Case_Three() {
        Contact theContact = [SELECT Id FROM Contact WHERE LastName = 'contacttest' LIMIT 1];
        sirenum__Timesheet__c theTimesheet = [SELECT Id FROM sirenum__Timesheet__c];

        IP_OutboundDataTransfer__c ob = new IP_OutboundDataTransfer__c();
        ob.IP_OriginRecordID__c = theContact.Id;
        ob.IP_TimesheetID__c = theTimesheet.Id;
        ob.IP_Passed__c = null;
        ob.TestValidation__c = 'test';
        insert ob;

        Test.startTest();

        theContact.IP_TimesheetIDLink__c = theTimesheet.Id;
        theContact.IP_LastPassedToTempest2ndTier__c = null;
        theContact.IP_Pass2ndTierToTempest__c = true;
        theContact.IP_FirstPassExternalWorker__c = false;
        theContact.IP_EmergencyPull__c = true;
        update theContact;

        Test.stopTest();
    }

	static testmethod void validateFunctionality_Test_Case_Four() {
        Contact theContact = [SELECT Id FROM Contact WHERE LastName = 'contacttest' LIMIT 1];
        sirenum__Timesheet__c theTimesheet = [SELECT Id FROM sirenum__Timesheet__c];

        Test.startTest();

        theContact.IP_TimesheetIDLink__c = theTimesheet.Id;
        theContact.IP_LastPassedToTempest2ndTier__c = null;
        theContact.IP_Pass2ndTierToTempest__c = true;
        theContact.IP_FirstPassExternalWorker__c = false;
        theContact.IP_EmergencyPull__c = true;
        update theContact;

        Test.stopTest();
    }
}