Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Check_Top_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Check_Top_Prospect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Top Prospect</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Top_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Top_Prospect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Top Prospect</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/TopProspectCheck.cls
public class TopProspectCheck {
    
    public Account acct;
    public Id acctId{get; set;}
    public  boolean show {get; set;}
    public List<sirenum__Site__c> lstSites;
    private ApexPages.StandardController c;
    
    public TopProspectCheck(ApexPages.StandardController stdController){
        c = stdController;
        this.acct = (Account)stdController.getRecord();
        acctId = acct.id;
        lstSites = new List<sirenum__Site__c>();
        lstSites =  [Select Id,Name,Top_Prospect__c from sirenum__Site__c where sirenum__Operating_Company__c =:acct.id Limit 10000];
        Show=true;
    }
    
    public void updateTopProspect(){
        List<sirenum__Site__c> lstSitesToUpdate = new List<sirenum__Site__c>();
        if(!lstSites.isEmpty()){
            for(sirenum__Site__c site : lstSites){
                site.Top_Prospect__c = false;
                lstSitesToUpdate.add(site);
            }
        }
        update lstSitesToUpdate;
        
        acct.Check_Top_Prospect__c = true;
        update acct;
        Show = false;
    }
    
    
    public void revertTopProspect(){
        acct.Top_Prospect__c = true;
        update acct;
        
        Show = false; 
    }
    
}