Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_Business_Type__c.field-meta.xml
<CustomField>
    <fullName>IP_Business_Type__c</fullName>
    <description>Types of business the business undertakes</description>
    <inlineHelpText>Select the types of business the client will require our support for</inlineHelpText>
    <label>Business Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_InvoicingMethod__c.field-meta.xml
<CustomField>
    <fullName>IP_InvoicingMethod__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Hourly Percentage</fullName>
            </value>
            <value>
                <fullName>Hourly Commission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Managed_Account__c.field-meta.xml
<CustomField>
    <fullName>Managed_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to define managed accounts for validation rule purposes</description>
    <label>Rate Card Restriction</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/ProfilesUsed__c/ProfilesUsed__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ProfilesUsed</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <label>Tempest Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDivision</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestID__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestID__c</fullName>
    <description>ID need for passing to payroll</description>
    <externalId>true</externalId>
    <inlineHelpText>The ID needed for payroll detail passed</inlineHelpText>
    <label>Tempest ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/test_RateCardDeletePage.cls
@isTest
public class test_RateCardDeletePage {
    
    @isTest
    public static void deleteRateCardPageByAdmin(){
        Test.startTest();
        
        /*Profile JSId = [SELECT Id from Profile where Name='JS Recruiter - Hybrid' LIMIT 1];
        Profile BRId = [SELECT Id from Profile where Name='JS Admin (Branch Admin)' LIMIT 1];
        Profile BRMGId = [SELECT Id from Profile where Name='JS Admin Tier 1 (Branch Mgr)' LIMIT 1];
        Profile SAID = [SELECT Id from Profile where Name='Senior Admin' LIMIT 1];
        Profile BOID = [SELECT Id from Profile where Name='Back Office' LIMIT 1];*/
        
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Client'];
        
        Account acc = new Account();
        acc.IP_Business_Type__c='Catering';
        acc.Name='ClientNew';
        acc.IP_InvoicingMethod__c='Standard';
        acc.recordTypeId=accountRec.id;
        acc.Managed_Account__c = false;
        insert acc; 
        
        User user = [Select id from user where Id=:UserInfo.getuserId()];
        
        sirenum__Rate_Card__c rtc = new sirenum__Rate_Card__c();
        rtc.Name ='New Rate Card';
        rtc.IP_AcountLinkCustom__c= acc.id;
        insert rtc;
        
        sirenum__Rate_Card_Page__c rpc = new sirenum__Rate_Card_Page__c();
        rpc.Name ='Default';
        rpc.sirenum__Rate_Card__c = rtc.id;
        rpc.sirenum__SortOrder__c = 126;
        insert rpc;
        System.runAs(user){
            
            try{
            delete rpc;
            }catch(DMLException e){
                System.assert(e.getMessage().contains('You are not allowed to delete the Default Rate Card Page.'), 'You are not allowed to delete the Default Rate Card Page.'); 
            }
        }
       Test.stopTest();
                                  
    }
    
    @isTest
    public static void deleteRateCardPageByHybrid(){
        Test.startTest();
        
        /*Profile JSId = [SELECT Id from Profile where Name='JS Recruiter - Hybrid' LIMIT 1];
        Profile BRId = [SELECT Id from Profile where Name='JS Admin (Branch Admin)' LIMIT 1];
        Profile BRMGId = [SELECT Id from Profile where Name='JS Admin Tier 1 (Branch Mgr)' LIMIT 1];
        Profile SAID = [SELECT Id from Profile where Name='Senior Admin' LIMIT 1];
        Profile BOID = [SELECT Id from Profile where Name='Back Office' LIMIT 1];*/
        
        ProfilesUsed__c profileUsed = new ProfilesUsed__c();
        profileUsed.Name = 'JS Recruiter - Hybrid';
        insert profileUsed;
        
        Profile JSId = [SELECT Id from Profile where Name=:profileUsed.Name LIMIT 1];
        
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Client'];
        
        Account acc = new Account();
        acc.IP_Business_Type__c='Catering';
        acc.Name='ClientNew';
        acc.IP_InvoicingMethod__c='Standard';
        acc.recordTypeId=accountRec.id;
        acc.Managed_Account__c = false;
        insert acc; 
        
        User user = new User();
        DateTime dt = DateTime.newInstance(2017, 6, 23, 3, 3, 3);
        Long gettime = dt.getTime();
        user.LastName = 'Virmani';
        user.FirstName='Swati';
        user.Alias = 'svir';
        user.Email = 'swati.vir@outlook.com';
        user.Username = 'Email'+gettime+'@js.com';
        user.ProfileId = JSId.id; 
        user.TimeZoneSidKey = 'GMT';
        user.LanguageLocaleKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8'; 
        user.LocaleSidKey = 'en_US';
        /*user.IP_TempestDepartment__c='1287';
        user.IP_TempestId__c='1287';
        user.IP_TempestDivision__c='NTS';
        user.Department='1287';
        user.IP_PassToTempest__c=false;*/
        insert user;
        system.debug('Value in user'+ user);
        
        
        sirenum__Rate_Card__c rtc = new sirenum__Rate_Card__c();
        rtc.Name ='New Rate Card';
        rtc.IP_AcountLinkCustom__c= acc.id;
        insert rtc;
        
        sirenum__Rate_Card_Page__c rpc = new sirenum__Rate_Card_Page__c();
        rpc.Name ='Default';
        rpc.sirenum__Rate_Card__c = rtc.id;
        rpc.sirenum__SortOrder__c = 126;
        insert rpc;
        System.runAs(user){
            
            try{
            delete rpc;
            }catch(DMLException e){
                System.assert(e.getMessage().contains('You are not allowed to delete the Default Rate Card Page.'), 'You are not allowed to delete the Default Rate Card Page.'); 
            }
        }
       Test.stopTest();
                                  
    }
    
}