Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_Business_Type__c.field-meta.xml
<CustomField>
    <fullName>IP_Business_Type__c</fullName>
    <description>Types of business the business undertakes</description>
    <inlineHelpText>Select the types of business the client will require our support for</inlineHelpText>
    <label>Business Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CategoryOfWork__c.field-meta.xml
<CustomField>
    <fullName>IP_CategoryOfWork__c</fullName>
    <description>Which business areas does the person work in</description>
    <inlineHelpText>Which business areas does the person work in</inlineHelpText>
    <label>Category of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_GDPRWorkedCandidate__c.field-meta.xml
<CustomField>
    <fullName>IP_GDPRWorkedCandidate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field that identifies if a candidate has been worked under the definition for GDPR.</description>
    <label>GDPR Worked Candidate</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LastContactedGDPR__c.field-meta.xml
<CustomField>
    <fullName>IP_LastContactedGDPR__c</fullName>
    <description>System field that identifies the last time a candidate has had a GDPR ‘Meaningful contact’ interaction.</description>
    <label>Last contacted GDPR</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MarkedForDeletion__c.field-meta.xml
<CustomField>
    <fullName>IP_MarkedForDeletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field that identifies if the candidate needs to be deleted.</description>
    <label>Marked for deletion</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Person_Status__c.field-meta.xml
<CustomField>
    <fullName>Person_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/IP_ImpellamGDPRSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the parameters for managing data retention within the system.</description>
    <label>RSSGlobal_GDPR_settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/fields/IP_Scheduledeletionsize__c.field-meta.xml
<CustomField>
    <fullName>IP_Scheduledeletionsize__c</fullName>
    <label>Schedule deletion size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/fields/IP_UnworkedCandidateDataRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>IP_UnworkedCandidateDataRetentionPeriod__c</fullName>
    <description>Number of days an unworked candidates data is held in the system</description>
    <label>Unworked Candidate Data Retention Period</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/User_Profile_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of frequently used profile Id&apos;s to use in apex or formula</description>
    <label>User Profile Id</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <label>Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Schedule_DeletionCandidate_Test.cls
@isTest
public class Schedule_DeletionCandidate_Test {
  @TestSetup
  static void setupData() {
    IP_ImpellamGDPRSettings__c obj = new IP_ImpellamGDPRSettings__c(
      Name = 'Impellam GDPR settings',
      IP_UnworkedCandidateDataRetentionPeriod__c = 360,
      IP_Scheduledeletionsize__c = 500
    );
    insert obj;
    insert new Payroll_Swtich__c(Name = 'Stoppayroll', Batch_check__c = false);
  }
  public static testMethod void testschedule() {
    Test.StartTest();
    Schedule_DeletionCandidate sh1 = new Schedule_DeletionCandidate();
    String sch = '0 23 22 29 * ?';
    system.schedule('Test Deletion Candidate', sch, sh1);
    Test.stopTest();
  }

  @IsTest
  public static void ExecuteBatch() {
    Profile Prof = [
      SELECT Id
      FROM Profile
      WHERE Name = 'System Administrator'
      LIMIT 1
    ];
    Profile portalUserProfile = [
      SELECT Id
      FROM Profile
      WHERE Name = 'User Portal'
    ];
    User_Profile_Id__c UserPortalSetting = new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = portalUserProfile.Id
    );
    insert UserPortalSetting;

    Account acc1 = new Account();

    RecordType accountRec = [
      SELECT Id
      FROM RecordType
      WHERE sObjectType = 'Account' AND DeveloperName = 'Client'
    ];

    acc1.name = 'TestAccount1';
    acc1.Phone = '012034563433';
    acc1.BillingStreet = 'Street1';
    acc1.IP_Business_Type__c = 'catering';
    acc1.BillingCity = 'City1';
    acc1.BillingPostalCode = 'NW13JT';
    //acc1.BillingState = 'State1';
    //acc1.BillingCountry = 'Country1';
    acc1.RecordTypeId = accountRec.id;

    insert acc1;

    system.debug('Account Inserted');

    Account acc = new Account();

    RecordType accountRec1 = [
      SELECT Id
      FROM RecordType
      WHERE sObjectType = 'Account' AND DeveloperName = 'Candidate'
    ];

    acc.Name = 'Candidates';
    acc.RecordTypeId = accountRec1.id;
    acc.Phone = '012034563436';
    acc.BillingStreet = 'Street2';
    acc.BillingCity = 'City2';
    acc.BillingPostalCode = 'NW13JT';
   // acc.BillingState = 'State2';
    //acc.BillingCountry = 'Country2';

    insert acc;

    system.debug('Account Inserted');

    insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c = false);

    RecordType contRec = [
      SELECT Id
      FROM RecordType
      WHERE sObjectType = 'Contact' AND DeveloperName = 'Candidate'
    ];

    List<Contact> testContacts = new List<Contact>();
    for (Integer i = 0; i < 6; i++) {
      Contact contact = new Contact(
        Firstname = 'Test' + i,
        Lastname = 'Candidate' + i,
        accountId = acc.Id,
        Person_Status__c = 'Active',
        IP_CategoryOfWork__c = 'Catering',
        IP_GDPRWorkedCandidate__c = false,
        IP_LastContactedGDPR__c = null,
        IP_MarkedForDeletion__c = true,
        RecordTypeId = contRec.Id
      );

      testContacts.add(contact);
    }
    insert testContacts;

    Test.startTest();

    Schedule_DeletionCandidate batch = new Schedule_DeletionCandidate();
    Database.executeBatch(batch, 600);

    Test.stopTest();

    List<Contact> output = [SELECT Id FROM Contact WHERE Id IN :testContacts];

    System.assertEquals(0, output.size());
  }

  @IsTest
  public static void ExecuteBatchWithException() {
    Profile Prof = [
      SELECT Id
      FROM Profile
      WHERE Name = 'System Administrator'
      LIMIT 1
    ];
    Profile portalUserProfile = [
      SELECT Id
      FROM Profile
      WHERE Name = 'User Portal'
    ];
    User_Profile_Id__c UserPortalSetting = new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = portalUserProfile.Id
    );
    insert UserPortalSetting;

    Account acc1 = new Account();

    RecordType accountRec = [
      SELECT Id
      FROM RecordType
      WHERE sObjectType = 'Account' AND DeveloperName = 'Client'
    ];

    acc1.name = 'TestAccount1';
    acc1.Phone = '012034563433';
    acc1.BillingStreet = 'Street1';
    acc1.IP_Business_Type__c = 'catering';
    acc1.BillingCity = 'City1';
    acc1.BillingPostalCode = 'NW13JT';
    //acc1.BillingState = 'State1';
   // acc1.BillingCountry = 'Country1';
    acc1.RecordTypeId = accountRec.id;

    insert acc1;

    system.debug('Account Inserted');

    Account acc = new Account();

    RecordType accountRec1 = [
      SELECT Id
      FROM RecordType
      WHERE sObjectType = 'Account' AND DeveloperName = 'Candidate'
    ];

    acc.Name = 'Candidates';
    acc.RecordTypeId = accountRec1.id;
    acc.Phone = '012034563436';
    acc.BillingStreet = 'Street2';
    acc.BillingCity = 'City2';
    acc.BillingPostalCode = 'NW13JT';
    //acc.BillingState = 'State2';
    //acc.BillingCountry = 'Country2';

    insert acc;

    system.debug('Account Inserted');

    insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c = false);

    RecordType contRec = [
      SELECT Id
      FROM RecordType
      WHERE sObjectType = 'Contact' AND DeveloperName = 'Candidate'
    ];

    List<Contact> testContacts = new List<Contact>();
    for (Integer i = 0; i < 6; i++) {
      Contact contact = new Contact(
        Firstname = 'Test' + i,
        Lastname = 'Candidate' + i,
        accountId = acc.Id,
        Person_Status__c = 'Active',
        IP_CategoryOfWork__c = 'Catering',
        IP_GDPRWorkedCandidate__c = false,
        IP_LastContactedGDPR__c = null,
        IP_MarkedForDeletion__c = true,
        RecordTypeId = contRec.Id
      );

      testContacts.add(contact);
    }
    insert testContacts;

    try {
      Test.startTest();
      Schedule_DeletionCandidate batch = new Schedule_DeletionCandidate(true);
      Database.executeBatch(batch, 600);
      Test.stopTest();
    } catch (Schedule_DeletionCandidate.DeletionException e) {
      System.assertEquals('Test exception', e.getMessage());
    }
  }
}