Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <description>Billing system ID for client</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the Sales Ledger Number for the Account</inlineHelpText>
    <label>SL Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/Batch_header__c.object-meta.xml
<CustomObject>
    <label>Batch Header</label>
    <nameField>
        <displayFormat>Batch-{00000}</displayFormat>
        <label>Batch header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_BatchTitle__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchTitle__c</fullName>
    <externalId>true</externalId>
    <label>Batch Title</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_BatchType__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchType__c</fullName>
    <label>Batch type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/IP_BatchLine__c.object-meta.xml
<CustomObject>
    <label>Batch Line</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Batch Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/Check_status__c.field-meta.xml
<CustomField>
    <fullName>Check_status__c</fullName>
    <label>Check status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_BatchHeader__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchHeader__c</fullName>
    <label>Batch Header</label>
    <referenceTo>Batch_header__c</referenceTo>
    <relationshipLabel>Batch Lines</relationshipLabel>
    <relationshipName>Batch_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_CurrencyField1__c.field-meta.xml
<CustomField>
    <fullName>IP_CurrencyField1__c</fullName>
    <label>Currency field 1</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_CurrencyField2__c.field-meta.xml
<CustomField>
    <fullName>IP_CurrencyField2__c</fullName>
    <label>Currency field 2</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_ErrorReason__c.field-meta.xml
<CustomField>
    <fullName>IP_ErrorReason__c</fullName>
    <label>Error Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_LinkField1__c.field-meta.xml
<CustomField>
    <fullName>IP_LinkField1__c</fullName>
    <label>Link Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Number12d4Field1__c.field-meta.xml
<CustomField>
    <fullName>IP_Number12d4Field1__c</fullName>
    <label>Number 12,4 field 1</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Number12d4Field2__c.field-meta.xml
<CustomField>
    <fullName>IP_Number12d4Field2__c</fullName>
    <label>Number 12,4 field 2</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Number12d4Field3__c.field-meta.xml
<CustomField>
    <fullName>IP_Number12d4Field3__c</fullName>
    <label>Number 12,4 field 3</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField10__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField10__c</fullName>
    <label>Text field 10</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField1__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField1__c</fullName>
    <label>Text Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField2__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField2__c</fullName>
    <label>Text Field 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField3__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField3__c</fullName>
    <label>Text Field 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField4__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField4__c</fullName>
    <label>Text Field 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField5__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField5__c</fullName>
    <label>Text Field 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField6__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField6__c</fullName>
    <label>Text Field 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField7__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField7__c</fullName>
    <label>Text field 7</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField8__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField8__c</fullName>
    <label>Text field 8</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField9__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField9__c</fullName>
    <label>Text field 9</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_AccountBalance__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountBalance__c</fullName>
    <label>Account Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine1__c</fullName>
    <label>Address Line 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine2__c</fullName>
    <label>Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_County__c.field-meta.xml
<CustomField>
    <fullName>IP_County__c</fullName>
    <label>County</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_CreditLimit__c.field-meta.xml
<CustomField>
    <fullName>IP_CreditLimit__c</fullName>
    <label>Credit Limit</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_DivisionCode__c.field-meta.xml
<CustomField>
    <fullName>IP_DivisionCode__c</fullName>
    <label>Division Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_NetMonthlySettlementCode__c.field-meta.xml
<CustomField>
    <fullName>IP_NetMonthlySettlementCode__c</fullName>
    <label>Net Monthly (settlement code)</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_Postcode__c.field-meta.xml
<CustomField>
    <fullName>IP_Postcode__c</fullName>
    <label>Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <label>Sales Ledger Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_StatusID__c.field-meta.xml
<CustomField>
    <fullName>IP_StatusID__c</fullName>
    <label>Status ID</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_TopazUniquenumber__c.field-meta.xml
<CustomField>
    <fullName>IP_TopazUniquenumber__c</fullName>
    <label>Topaz Unique number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_Town__c.field-meta.xml
<CustomField>
    <fullName>IP_Town__c</fullName>
    <label>Town</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/TopazGlobalB2FUpdate.cls
global class TopazGlobalB2FUpdate extends batchjobsch.BatchJobBase implements Database.Batchable<sObject>, Database.Stateful {
  Set<ID> headerId = new Set<ID>();
  Map<id, IP_TopazGlobalClientInformation__c> TopazMap1 = new Map<id, IP_TopazGlobalClientInformation__c>();
  global Database.QueryLocator start(Database.BatchableContext BC) {
    String query = 'select id,IP_TextField1__c,IP_TextField2__c,IP_Number12d4Field1__c,IP_TextField6__c,IP_TextField7__c,IP_TextField8__c,IP_TextField9__c,IP_TextField10__c,IP_CurrencyField1__c,IP_Number12d4Field2__c,IP_TextField3__c,IP_TextField4__c,IP_Number12d4Field3__c,IP_TextField5__c,IP_CurrencyField2__c,IP_LinkField1__c,IP_Status__c,IP_BatchHeader__r.name from IP_BatchLine__c where IP_Status__c = \'open\' and IP_BatchHeader__r.IP_BatchType__c=\'Topaz Global Account\' And ((IP_BatchHeader__r.IP_State__c = \'Closed\' And IP_BatchHeader__r.IP_Status__c = \'Approved\') OR (IP_BatchHeader__r.IP_State__c = \'Processing\' AND IP_BatchHeader__r.IP_Status__c = \'Errored\') OR (IP_BatchHeader__r.IP_State__c = \'Processing\' AND IP_BatchHeader__r.IP_Status__c = \'Partial Complete\'))';
    return Database.getQueryLocator(query);
  }
  global void execute(
    Database.BatchableContext BC,
    List<IP_BatchLine__c> batchlinelist
  ) {
    Database.SaveResult[] sList;
    Database.SaveResult[] sList1;
    Map<Id, String> Errmsg = new Map<Id, String>();
    Map<Id, String> Errmsg1 = new Map<Id, String>();
    list<String> topaznumber = new List<String>();
    List<IP_TopazGlobalClientInformation__c> topazupdatelist = new List<IP_TopazGlobalClientInformation__c>();
    List<IP_TopazGlobalClientInformation__c> topazinsertlist = new List<IP_TopazGlobalClientInformation__c>();
    Map<String, IP_TopazGlobalClientInformation__c> topazmap = new Map<String, IP_TopazGlobalClientInformation__c>();
    for (IP_BatchLine__c bline : batchlinelist) {
      headerId.add(bline.IP_BatchHeader__c);
      if (bline.IP_TextField2__c == null) {
        bline.IP_Status__c = 'Errored';
        bline.IP_ErrorReason__c = 'Topaz Unique Number (Text Field 2) is blank';
      } else {
        topaznumber.add(bline.IP_TextField2__c);
      }
    }
    System.debug('check list-->' + topaznumber);
    for (IP_TopazGlobalClientInformation__c topazgloballist : [
      SELECT
        id,
        IP_TopazUniquenumber__c,
        IP_SalesLedgerNumber__c,
        Name,
        IP_AddressLine1__c,
        IP_AddressLine2__c,
        IP_Town__c,
        IP_County__c,
        IP_Postcode__c,
        IP_CreditLimit__c,
        IP_AccountBalance__c,
        IP_PaymentTerms__c,
        IP_NetMonthlySettlementCode__c,
        IP_CompanyRegNo__c,
        IP_StatusID__c,
        IP_DivisionCode__c
      FROM IP_TopazGlobalClientInformation__c
      WHERE
        IP_SalesLedgerNumber__c IN :topaznumber
        AND IP_SalesLedgerNumber__c != NULL
    ]) {
      topazmap.put(topazgloballist.IP_SalesLedgerNumber__c, topazgloballist);
    }
    System.debug('topaz map-->' + topazmap);
    for (IP_BatchLine__c batchline2 : batchlinelist) {
      if (batchline2.IP_Status__c != 'Errored') {
        if (
          topazmap.size() > 0 &&
          batchline2.IP_TextField2__c != null &&
          topazmap.containskey(batchline2.IP_TextField2__c)
        ) {
          String str = String.valueOf(
            topazmap.get(batchline2.IP_TextField2__c).id
          );
          batchline2.IP_LinkField1__c = str;
          batchline2.IP_Status__c = 'Linking';
          IP_TopazGlobalClientInformation__c topaz1 = new IP_TopazGlobalClientInformation__c();
          topaz1.id = String.valueOf(
            topazmap.get(batchline2.IP_TextField2__c).id
          );
          topaz1.IP_SalesLedgerNumber__c = batchline2.IP_TextField2__c;
          topaz1.Name = batchline2.IP_TextField1__c;
          topaz1.IP_AddressLine1__c = batchline2.IP_TextField6__c;
          topaz1.IP_AddressLine2__c = batchline2.IP_TextField7__c;
          topaz1.IP_Town__c = batchline2.IP_TextField8__c;
          topaz1.IP_County__c = batchline2.IP_TextField9__c;
          topaz1.IP_Postcode__c = batchline2.IP_TextField10__c;
          topaz1.IP_CreditLimit__c = batchline2.IP_CurrencyField1__c;
          topaz1.IP_AccountBalance__c = batchline2.IP_CurrencyField2__c;
          topaz1.IP_PaymentTerms__c = batchline2.IP_Number12d4Field2__c;
          topaz1.IP_NetMonthlySettlementCode__c = batchline2.IP_TextField3__c;
          topaz1.IP_CompanyRegNo__c = batchline2.IP_TextField4__c;
          topaz1.IP_StatusID__c = batchline2.IP_Number12d4Field3__c;
          topaz1.IP_DivisionCode__c = batchline2.IP_TextField5__c;
          if (!TopazMap1.containskey(topaz1.id)) {
            TopazMap1.put(topaz1.id, topaz1);
          }
        } else {
          IP_TopazGlobalClientInformation__c topaz2 = new IP_TopazGlobalClientInformation__c();
          topaz2.IP_TopazUniquenumber__c = Integer.valueOf(
            batchline2.IP_Number12d4Field1__c
          );
          topaz2.IP_SalesLedgerNumber__c = batchline2.IP_TextField2__c;
          topaz2.Name = batchline2.IP_TextField1__c;
          topaz2.IP_AddressLine1__c = batchline2.IP_TextField6__c;
          topaz2.IP_AddressLine2__c = batchline2.IP_TextField7__c;
          topaz2.IP_Town__c = batchline2.IP_TextField8__c;
          topaz2.IP_County__c = batchline2.IP_TextField9__c;
          topaz2.IP_Postcode__c = batchline2.IP_TextField10__c;
          topaz2.IP_CreditLimit__c = batchline2.IP_CurrencyField1__c;
          topaz2.IP_AccountBalance__c = batchline2.IP_CurrencyField2__c;
          topaz2.IP_PaymentTerms__c = batchline2.IP_Number12d4Field2__c;
          topaz2.IP_NetMonthlySettlementCode__c = batchline2.IP_TextField3__c;
          topaz2.IP_CompanyRegNo__c = batchline2.IP_TextField4__c;
          topaz2.IP_StatusID__c = batchline2.IP_Number12d4Field3__c;
          topaz2.IP_DivisionCode__c = batchline2.IP_TextField5__c;
          topazinsertlist.add(topaz2);
        }
      } else {
        batchline2.IP_Status__c = 'Errored';
        batchline2.IP_ErrorReason__c = 'Topaz Unique Number (Number Field 1) is blank';
      }
    }
    // topazupdatelist = [Select id,IP_TopazUniquenumber__c,IP_SalesLedgerNumber__c,Name,IP_AddressLine1__c,IP_AddressLine2__c,IP_Town__c,IP_County__c,IP_Postcode__c,IP_CreditLimit__c,IP_AccountBalance__c,IP_PaymentTerms__c,IP_NetMonthlySettlementCode__c,IP_CompanyRegNo__c,IP_StatusID__c,IP_DivisionCode__c from IP_TopazGlobalClientInformation__c where id in:TopazMap1.KeySet()];
    topazupdatelist.addAll(TopazMap1.values());
    if (topazupdatelist.size() > 0) {
      try {
        sList = Database.update(topazupdatelist, false);
      } catch (Exception DMLException) {
      }
      for (integer i = 0; i < sList.size(); i++) {
        if (sList[i].isSuccess()) {
          System.debug('Successfully updated topaz: ' + topazupdatelist[i].id);
          Errmsg.put(topazupdatelist[i].id, 'Success');
        } else {
          for (Database.Error err : sList[i].getErrors()) {
            Errmsg.put(topazupdatelist[i].id, err.getMessage());
          }
        }
      }

      for (IP_BatchLine__c batchstatus : batchlinelist) {
        for (IP_TopazGlobalClientInformation__c t : topazupdatelist) {
          System.debug('***Inside for loop***');
          if (
            batchstatus.IP_Status__c != 'Errored' &&
            batchstatus.IP_LinkField1__c == t.id
          ) {
            System.debug('***Inside if statement 1***');
            if (Errmsg.get(t.Id) != 'Success') {
              batchstatus.IP_Status__c = 'Errored';
              if (Errmsg.get(t.Id).length() > 255) {
                batchstatus.IP_ErrorReason__c = Errmsg.get(t.Id)
                  .substring(0, 255);
              } else {
                batchstatus.IP_ErrorReason__c = Errmsg.get(t.Id);
              }
            } else {
              System.debug('***Inside else***');
              batchstatus.IP_Status__c = 'Processed';
            }
          }
        }
      }
    }
    if (topazinsertlist.size() > 0) {
      try {
        sList1 = Database.insert(topazinsertlist, false);
      } catch (Exception DMLException) {
      }

      for (Database.SaveResult sr : sList1) {
        if (sr.isSuccess()) {
          System.debug('Successfully inserted Topaz: ' + sr.getId());
          Errmsg1.put(sr.getId(), 'Success');
        } else {
          for (Database.Error err : sr.getErrors()) {
            Errmsg1.put(sr.getId(), err.getMessage());
          }
        }
      }
      for (IP_BatchLine__c batchstatus : batchlinelist) {
        for (IP_TopazGlobalClientInformation__c t : topazinsertlist) {
          System.debug('***Inside for loop***');
          if (
            batchstatus.IP_Status__c != 'Errored' &&
            batchstatus.IP_TextField2__c == t.IP_SalesLedgerNumber__c
          ) {
            System.debug('***Inside if statement 1***');
            if (Errmsg1.get(t.Id) != 'Success') {
              batchstatus.IP_Status__c = 'Errored';
              if (Errmsg1.get(t.Id).length() > 255) {
                batchstatus.IP_ErrorReason__c = Errmsg1.get(t.Id)
                  .substring(0, 255);
              } else {
                batchstatus.IP_ErrorReason__c = Errmsg1.get(t.Id);
              }
            } else {
              System.debug('***Inside else***');
              batchstatus.IP_Status__c = 'Processed';
              batchstatus.IP_LinkField1__c = t.id;
            }
          }
        }
      }
    }
    update batchlinelist;
    TopazMap1.clear();
  }
  global void finish(Database.BatchableContext BC) {
    Map<Id, Integer> mapUnprocessedBatchHeader = new Map<Id, Integer>();
    Map<Id, Integer> mapErroredBatchHeader = new Map<Id, Integer>();
    for (Batch_header__c openStatusBatchHeader : [
      SELECT
        id,
        IP_Status__c,
        IP_State__c,
        Check_status__c,
        (
          SELECT id, IP_Status__c
          FROM Batch_Lines__r
          WHERE IP_Status__c = 'Open'
        )
      FROM Batch_header__c
      WHERE id = :headerId
    ]) {
      if (
        !openStatusBatchHeader.Batch_Lines__r.isEmpty() &&
        openStatusBatchHeader.Batch_Lines__r.size() > 0
      ) {
        mapUnprocessedBatchHeader.put(
          openStatusBatchHeader.id,
          openStatusBatchHeader.Batch_Lines__r.size()
        );
      }
    }
    System.debug('mapUnprocessedBatchHeader -- ' + mapUnprocessedBatchHeader);

    for (Batch_header__c erroredBatchHeader : [
      SELECT
        id,
        IP_Status__c,
        IP_State__c,
        Check_status__c,
        (
          SELECT id, IP_Status__c
          FROM Batch_Lines__r
          WHERE IP_Status__c = 'Errored'
          LIMIT 1
        )
      FROM Batch_header__c
      WHERE id = :headerId
    ]) {
      if (
        !erroredBatchHeader.Batch_Lines__r.isEmpty() &&
        erroredBatchHeader.Batch_Lines__r.size() > 0
      ) {
        mapErroredBatchHeader.put(
          erroredBatchHeader.id,
          erroredBatchHeader.Batch_Lines__r.size()
        );
      }
    }
    System.debug('mapErroredBatchHeader -- ' + mapErroredBatchHeader);

    List<Batch_header__c> listBatchHeaderUpdate = new List<Batch_header__c>();

    for (Batch_header__c batchHeader : [
      SELECT
        id,
        IP_BatchTitle__c,
        Name,
        IP_Status__c,
        IP_State__c,
        Check_status__c
      FROM Batch_header__c
      WHERE id = :headerId
    ]) {
      if (
        !mapUnprocessedBatchHeader.isEmpty() &&
        mapUnprocessedBatchHeader.get(batchHeader.id) > 0
      ) {
        batchHeader.IP_Status__c = 'Partial Complete';
        batchHeader.IP_State__c = 'Processing';
      } else if (
        !mapErroredBatchHeader.isEmpty() &&
        mapErroredBatchHeader.get(batchHeader.id) > 0
      ) {
        batchHeader.IP_Status__c = 'Errored';
        batchHeader.IP_State__c = 'Processing';
      } else {
        batchHeader.IP_Status__c = 'Processed';
        batchHeader.IP_State__c = 'Closed';
      }
      //  batchHeader.Check_status__c = '';
      listBatchHeaderUpdate.add(batchHeader);
    }
    System.debug('listBatchHeaderUpdate -- ' + listBatchHeaderUpdate);

    if (!listBatchHeaderUpdate.isEmpty()) {
      update listBatchHeaderUpdate;
    }
    super.finishBatch(BC);
  }
}