Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SupplierReference__c.field-meta.xml
<CustomField>
    <fullName>IP_SupplierReference__c</fullName>
    <label>2nd Tier Supplier Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CandidateIDlegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDlegacy__c</fullName>
    <description>this is used for candidate that are being migrated from other system but their original IDs must be preserved</description>
    <externalId>true</externalId>
    <inlineHelpText>IF a candidate must still be reference by an original ID (for payroll) used this field</inlineHelpText>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_ConsultantsTempestID__c.field-meta.xml
<CustomField>
    <fullName>IP_ConsultantsTempestID__c</fullName>
    <formula>Owner.IP_TempestID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consultants Tempest ID</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Department__c.field-meta.xml
<CustomField>
    <fullName>IP_Department__c</fullName>
    <formula>Owner.Department</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Department</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Email__c.field-meta.xml
<CustomField>
    <fullName>IP_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_FirstPassExternalWorker__c.field-meta.xml
<CustomField>
    <fullName>IP_FirstPassExternalWorker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Pass (External Worker)</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LastPassedToTempest2ndTier__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest2ndTier__c</fullName>
    <label>Last Passed to Tempest (2nd Tier)</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine1__c</fullName>
    <description>This is a system field to populate information into back office</description>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine2__c</fullName>
    <description>This is a system interface field as salesforce splits up the salesforce field address line information</description>
    <label>Mailing Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine3__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine3__c</fullName>
    <label>Mailing Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Pass2ndTierToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_Pass2ndTierToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass 2nd tier to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Phone__c.field-meta.xml
<CustomField>
    <fullName>IP_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Phone</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <formula>TEXT(Owner.IP_TempestDivision__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tempest Division</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TimesheetIDLink__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetIDLink__c</fullName>
    <label>Timesheet ID Link</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_WorkerStartDate__c.field-meta.xml
<CustomField>
    <fullName>IP_WorkerStartDate__c</fullName>
    <description>Date of the workers first paid work for the Agency</description>
    <inlineHelpText>Worker Start Date which is the first day of their first shift.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/IP_BranchStatus__c.object-meta.xml
<CustomObject>
    <label>Branch Status List</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Status Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_BranchID__c.field-meta.xml
<CustomField>
    <fullName>IP_BranchID__c</fullName>
    <externalId>true</externalId>
    <label>Branch ID</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_CompanyCode__c/IP_CompanyCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Brand Company Code</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_CompanyCode__c/fields/IP_CompanyCodeValue__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyCodeValue__c</fullName>
    <label>Company Code Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/IP_OutboundDataTransfer__c.object-meta.xml
<CustomObject>
    <description>Object that holds data for transfer out of the system</description>
    <label>Outbound Data Transfer</label>
    <nameField>
        <displayFormat>ODT-{0000000000}</displayFormat>
        <label>Outbound Data Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Data Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_2ndTierSupplier_Reference__c.field-meta.xml
<CustomField>
    <fullName>IP_2ndTierSupplier_Reference__c</fullName>
    <label>2nd Tier Supplier Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>IP_Birthdate__c</fullName>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_BrandCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>IP_BrandCompanyCode__c</fullName>
    <label>Brand Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_CandidateIDLegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDLegacy__c</fullName>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Consultants_Tempest_ID__c.field-meta.xml
<CustomField>
    <fullName>IP_Consultants_Tempest_ID__c</fullName>
    <label>Consultants Tempest ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Department__c.field-meta.xml
<CustomField>
    <fullName>IP_Department__c</fullName>
    <label>Department</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Email__c.field-meta.xml
<CustomField>
    <fullName>IP_Email__c</fullName>
    <label>Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_First_Name__c.field-meta.xml
<CustomField>
    <fullName>IP_First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>IP_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Mailing_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>IP_Mailing_Address_Line_1__c</fullName>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Mailing_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>IP_Mailing_Address_Line_2__c</fullName>
    <label>Mailing Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Mailing_Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>IP_Mailing_Address_Line_3__c</fullName>
    <label>Mailing Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>IP_Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>IP_Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Mailing_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>IP_Mailing_PostalCode__c</fullName>
    <label>Mailing PostalCode</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>IP_Mailing_State__c</fullName>
    <label>Mailing State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>IP_National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_OriginRecordID__c.field-meta.xml
<CustomField>
    <fullName>IP_OriginRecordID__c</fullName>
    <label>Origin Record ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Passed__c.field-meta.xml
<CustomField>
    <fullName>IP_Passed__c</fullName>
    <label>Passed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Pay_Frequency__c.field-meta.xml
<CustomField>
    <fullName>IP_Pay_Frequency__c</fullName>
    <label>Pay Frequency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Phone__c.field-meta.xml
<CustomField>
    <fullName>IP_Phone__c</fullName>
    <label>Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Salutation__c.field-meta.xml
<CustomField>
    <fullName>IP_Salutation__c</fullName>
    <label>Salutation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>IP_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Tempest_Department__c.field-meta.xml
<CustomField>
    <fullName>IP_Tempest_Department__c</fullName>
    <label>Tempest Department</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Tempest_Division__c.field-meta.xml
<CustomField>
    <fullName>IP_Tempest_Division__c</fullName>
    <label>Tempest Division</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_TimesheetID__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetID__c</fullName>
    <label>Timesheet SF ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_WTR__c.field-meta.xml
<CustomField>
    <fullName>IP_WTR__c</fullName>
    <label>WTR</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/PassExternalWorker.cls
public class PassExternalWorker {
    
    public static void passexternal(SObject so)
    {
         Boolean sendMail = false;
         String errorFile = 'Id,Error\n';
         Database.SaveResult[] sList;
         Contact tl = (Contact) so;
         List<Contact> supply = [select Account.IP_SupplierReference__c from Contact where Id=:tl.id];
         List<IP_OutboundDataTransfer__c> outbound = new List<IP_OutboundDataTransfer__c>();
         Map<Id,String> Errmsg = new Map<Id,String>();
        IP_CompanyCode__c Ccode = IP_CompanyCode__c.getValues('CompanyCode'); 
      List<IP_OutboundDataTransfer__c> existoutbound = [Select id,IP_TimesheetID__c ,IP_First_Name__c,IP_Last_Name__c,IP_Mailing_Address_Line_1__c,IP_Department__c,IP_Pay_Frequency__c,IP_WTR__c,IP_National_Insurance__c,IP_Salutation__c,IP_Phone__c,IP_Mailing_PostalCode__c,IP_Mailing_State__c,IP_Mailing_Country__c,IP_Mailing_City__c,IP_CandidateIDLegacy__c,IP_Start_Date__c,IP_Tempest_Division__c,IP_Tempest_Department__c,IP_Mailing_Address_Line_2__c,IP_Mailing_Address_Line_3__c,IP_Email__c,IP_Consultants_Tempest_ID__c,IP_Birthdate__c,IP_2ndTierSupplier_Reference__c from IP_OutboundDataTransfer__c where IP_OriginRecordID__c =: tl.id and IP_TimesheetID__c =: tl.IP_TimesheetIDLink__c and IP_Passed__c = Null];
   
        List<sirenum__Timesheet__c> listtime = [Select id from sirenum__Timesheet__c where id=: tl.IP_TimesheetIDLink__c];
         
        List<IP_BranchStatus__c> branchlist = [select id from IP_BranchStatus__c where IP_BranchID__c=: tl.IP_TempestDepartment__c];
        if(branchlist.size()>0)
        {      
       for(Contact c: supply){
          if(tl.IP_Pass2ndTierToTempest__c == True && tl.IP_LastPassedToTempest2ndTier__c == Null && tl.IP_FirstPassExternalWorker__c== True && existoutbound.size()>0)
        {
            for(IP_OutboundDataTransfer__c ob : existoutbound)
            {
             if(ob.IP_TimesheetID__c == tl.IP_TimesheetIDLink__c)
                {
      //  ob.IP_OriginRecordID__c = tl.Id;
        ob.IP_2ndTierSupplier_Reference__c = c.Account.IP_SupplierReference__c;
        ob.IP_Birthdate__c = tl.Birthdate;
        ob.IP_Consultants_Tempest_ID__c = tl.IP_ConsultantsTempestID__c;
        ob.IP_Email__c = tl.Email;
        ob.IP_First_Name__c = tl.FirstName;
        ob.IP_Last_Name__c   = tl.LastName;
        ob.IP_Mailing_Address_Line_1__c = tl.IP_MailingAddressLine1__c;
        ob.IP_Mailing_Address_Line_2__c = tl.IP_MailingAddressLine2__c;
        ob.IP_Mailing_Address_Line_3__c = tl.IP_MailingAddressLine3__c;
        ob.IP_Tempest_Department__c = tl.IP_TempestDepartment__c;
        ob.IP_Tempest_Division__c = tl.IP_TempestDivision__c;
        ob.IP_Start_Date__c = tl.IP_WorkerStartDate__c;
        ob.IP_CandidateIDLegacy__c = tl.IP_CandidateIDlegacy__c;   
        ob.IP_Mailing_City__c = tl.MailingCity;
        ob.IP_Mailing_Country__c = tl.MailingCountry;       
        ob.IP_Mailing_State__c = tl.MailingState;
        ob.IP_Mailing_PostalCode__c = tl.MailingPostalCode;
        ob.IP_Phone__c = tl.Phone;
        // ob.IP_BrandCompanyCode__c = Ccode.IP_CompanyCodeValue__c;
        ob.IP_Salutation__c = tl.Salutation;      
        ob.IP_National_Insurance__c = tl.Sirenum__National_Insurance__c;     
        if(tl.WTR_Completed__c == True){        ob.IP_WTR__c = 'True';}        else{ob.IP_WTR__c = 'False';}       
        ob.IP_Pay_Frequency__c = String.valueOf(tl.IP_PayFrequency__c);
        ob.IP_Department__c = tl.IP_Department__c;

            }
            }
        
        
        }
        else if(tl.IP_Pass2ndTierToTempest__c == True && ( (listtime != Null && listtime.size()>0 && tl.IP_TimesheetIDLink__c != NULL) || (tl.IP_TimesheetIDLink__c == NULL && tl.IP_LastPassedToTempest2ndTier__c  != Null)))
       {      
       
       
        IP_OutboundDataTransfer__c ob = new IP_OutboundDataTransfer__c();
        
        if(tl.IP_Pass2ndTierToTempest__c == True && tl.IP_LastPassedToTempest2ndTier__c  == Null && tl.IP_FirstPassExternalWorker__c == True )
        {
        system.debug('@@##');
        ob.IP_TimesheetID__c = tl.IP_TimesheetIDLink__c;}
        if(tl.IP_Pass2ndTierToTempest__c == True && tl.IP_LastPassedToTempest2ndTier__c != Null && tl.IP_FirstPassExternalWorker__c == False )
        {  ob.IP_Passed__c ='PASSING';}
        ob.IP_OriginRecordID__c = tl.Id;
        ob.IP_2ndTierSupplier_Reference__c = c.Account.IP_SupplierReference__c;
        ob.IP_Birthdate__c = tl.Birthdate;
        ob.IP_Consultants_Tempest_ID__c = tl.IP_ConsultantsTempestID__c;
        ob.IP_Email__c = tl.Email;
        ob.IP_First_Name__c = tl.FirstName;
        ob.IP_Last_Name__c   = tl.LastName;
        ob.IP_Mailing_Address_Line_1__c = tl.IP_MailingAddressLine1__c;
        ob.IP_Mailing_Address_Line_2__c = tl.IP_MailingAddressLine2__c;
        ob.IP_Mailing_Address_Line_3__c = tl.IP_MailingAddressLine3__c;
        ob.IP_Tempest_Department__c = tl.IP_TempestDepartment__c;
        ob.IP_Tempest_Division__c = tl.IP_TempestDivision__c;
        ob.IP_Start_Date__c = tl.IP_WorkerStartDate__c;
        ob.IP_CandidateIDLegacy__c = tl.IP_CandidateIDlegacy__c;   
        ob.IP_Mailing_City__c = tl.MailingCity;
        ob.IP_Mailing_Country__c = tl.MailingCountry;       
        ob.IP_Mailing_State__c = tl.MailingState;
        ob.IP_Mailing_PostalCode__c = tl.MailingPostalCode;
        ob.IP_Phone__c = tl.Phone;
        // ob.IP_BrandCompanyCode__c = Ccode.IP_CompanyCodeValue__c;
        ob.IP_Salutation__c = tl.Salutation;      
        ob.IP_National_Insurance__c = tl.Sirenum__National_Insurance__c;     
        if(tl.WTR_Completed__c == True){        ob.IP_WTR__c = 'True';}        else{ob.IP_WTR__c = 'False';}       
        ob.IP_Pay_Frequency__c = String.valueOf(tl.IP_PayFrequency__c);
        ob.IP_Department__c = tl.IP_Department__c;
       
        
        
        ob.IP_TransferType__c = 'External Worker';
          outbound.add(ob);        
          }      
       }
              
    }
        if(outbound.size()>0)
        {
           sList = Database.insert(outbound,false);
           
        
          List<Id> errorIds = new List<Id>();
        for (Database.SaveResult sr : sList) {
          if (sr.isSuccess()) {
                System.debug('Successfully inserted Data' );
                 
                    
            }
            else {
                      for(Database.Error err : sr.getErrors()) { 
                     errorIds.add(tl.id);                      Errmsg.put(tl.id,err.getMessage());
                       }
                      
                 }
                 }
           if(!errorIds.IsEmpty())
              {
                 for(integer i=0;i<errorIds.size();i++)
                   {
                        errorFile = errorFile + errorIds[i]+','+ Errmsg.get(errorIds[i]) + ',' +'\n';                            sendMail = true;
                    }
               }
               else
               {
               try{
                    IP_Parallel_Payroll_Check__c parallelcheck = IP_Parallel_Payroll_Check__c.getValues('RunParallelCheck'); 
                    if(parallelcheck.Run_Parallel_Payroll__c == false)
                    {
                     tl.IP_Pass2ndTierToTempest__c = false;
                  
                    }
                     if(tl.IP_LastPassedToTempest2ndTier__c != Null && tl.IP_FirstPassExternalWorker__c == False)
                   {
                   tl.IP_LastPassedToTempest2ndTier__c = System.now();
                   }
                   else{
                   tl.IP_FirstPassExternalWorker__c = false;}
                   }
                   catch(Exception e)
                   {
                   errorFile = errorFile + tl +',' +e +','+'\n';                   sendMail = true;
                   } 
               }
                  
                
          }
          else if(existoutbound.size()>0)
        {
           sList = Database.update(existoutbound,false);
           
        
          List<Id> errorIds = new List<Id>();
        for (Database.SaveResult sr : sList) {
          if (sr.isSuccess()) {
                System.debug('Successfully updated Data' );
                 
                    
            }
            else {
                      for(Database.Error err : sr.getErrors()) { 
                     errorIds.add(sr.id);                      Errmsg.put(sr.id,err.getMessage());
                       }
                      
                 }
                 }
           if(!errorIds.IsEmpty())
              {
                 for(integer i=0;i<errorIds.size();i++)
                   {
                        errorFile = errorFile + errorIds[i]+','+ Errmsg.get(errorIds[i]) + ',' +'\n';                        
                        sendMail = true;
                    }
               }
               else
               {
               try{
                    IP_Parallel_Payroll_Check__c parallelcheck = IP_Parallel_Payroll_Check__c.getValues('RunParallelCheck'); 
                   if(parallelcheck.Run_Parallel_Payroll__c == false){
                   tl.IP_Pass2ndTierToTempest__c = false;
                    
                   }
                   tl.IP_FirstPassExternalWorker__c = false;
                   }
                   catch(Exception e)
                   {
                   errorFile = errorFile + tl +',' +e +','+'\n';                   sendMail = true;
                   } 
               }
                  
   
          }
                   
             if(existoutbound.size()>0 || outbound.size()>0 ){
          /* Send email for error Ids */
           if(sendMail == true)
        {          
              String emailid = IP_ImpellamGlobalSetting__c.getInstance().IP_OutboundErrorEmailAddress__c;
            Messaging.EmailFileAttachment errAtt = new Messaging.EmailFileAttachment();                
            blob errBlob = blob.valueof(errorFile);    
            errAtt.setFileName('Failed_Records.csv');
            errAtt.setBody(errBlob);    
            Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage(); 
            String subject ='Outbound Data Failure - Internal Worker';
            email.setSubject(subject);
           // String[] toAddresses = new String[]{'tajinder.singh@espire.com'};
             String[] toAddresses = new String[] {emailid};
            email.setToAddresses(toAddresses);
            email.setPlainTextBody('Hello,\n\nPlease find attached the list of failed records.');
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{errAtt});
        
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
            
            }    
             }
             
    }
    
    
    public static void passExternalEmergency(SObject so)
    {
         Boolean sendMail = false;
         String errorFile = 'Id,Error\n';
         boolean checkpassed = false;
         IP_Parallel_Payroll_Check__c parallelcheck = IP_Parallel_Payroll_Check__c.getValues('RunParallelCheck'); 
         IP_CompanyCode__c Ccode = IP_CompanyCode__c.getValues('CompanyCode');
         Database.SaveResult[] sList;
         List<sirenum__Timesheet__c> listtime = new List<sirenum__Timesheet__c>();
          Contact tl = (Contact) so;
         List<Contact> supply = [select Account.IP_SupplierReference__c from Contact where Id=:tl.id];
        if(tl.IP_TimesheetIDLink__c != null){
         listtime = [Select id from sirenum__Timesheet__c where id=: tl.IP_TimesheetIDLink__c];}
         
         
     List<IP_OutboundDataTransfer__c> existoutbound = [Select id,IP_EmergencyPull__c,IP_TimesheetID__c ,IP_First_Name__c,IP_Last_Name__c,IP_Mailing_Address_Line_1__c,IP_Department__c,IP_Pay_Frequency__c,IP_WTR__c,IP_National_Insurance__c,IP_Salutation__c,IP_Phone__c,IP_Mailing_PostalCode__c,IP_Mailing_State__c,IP_Mailing_Country__c,IP_Mailing_City__c,IP_CandidateIDLegacy__c,IP_Start_Date__c,IP_Tempest_Division__c,IP_Tempest_Department__c,IP_Mailing_Address_Line_2__c,IP_Mailing_Address_Line_3__c,IP_Email__c,IP_Consultants_Tempest_ID__c,IP_Birthdate__c,IP_2ndTierSupplier_Reference__c from IP_OutboundDataTransfer__c where IP_OriginRecordID__c =: tl.id and IP_TimesheetID__c =: tl.IP_TimesheetIDLink__c and IP_Passed__c = Null];
       
         List<PermissionSetAssignment> checkpermission =  [SELECT Id, PermissionSet.Name,AssigneeId
                                                                FROM PermissionSetAssignment
                                                                WHERE AssigneeId = :Userinfo.getUserId()]; 
                                                                
   system.debug('check permission'+checkpermission);
    if(checkpermission.size()>0)
    {
        for(PermissionSetAssignment ps:checkpermission)
        {
            if(ps.PermissionSet.Name == 'Emergency_Payroll')
            {
                checkpassed = true;
            }
        }
    }
         
         List<IP_OutboundDataTransfer__c> outbound = new List<IP_OutboundDataTransfer__c>();
         Map<Id,String> Errmsg = new Map<Id,String>();
        
        List<IP_BranchStatus__c> branchlist = [select id from IP_BranchStatus__c where IP_BranchID__c=: tl.IP_TempestDepartment__c];
        if(branchlist.size()>0)
        {
         for(Contact c: supply){
        system.debug('tl.IP_Pass2ndTierToTempest__c'+tl.IP_Pass2ndTierToTempest__c);
             system.debug('tl.IP_EmergencyPull__c'+tl.IP_EmergencyPull__c);
             system.debug('existoutbound'+existoutbound);
        if(tl.IP_Pass2ndTierToTempest__c == True && tl.IP_EmergencyPull__c == true && existoutbound.size()>0)
        {
            for(IP_OutboundDataTransfer__c ob : existoutbound)
            {
                if(ob.IP_TimesheetID__c == tl.IP_TimesheetIDLink__c)
                {
                ob.IP_EmergencyPull__c = True;
                ob.IP_2ndTierSupplier_Reference__c = c.Account.IP_SupplierReference__c;
                ob.IP_Birthdate__c = tl.Birthdate;
                ob.IP_Consultants_Tempest_ID__c = tl.IP_ConsultantsTempestID__c;
                ob.IP_Email__c = tl.Email;
                ob.IP_First_Name__c = tl.FirstName;
                ob.IP_Last_Name__c   = tl.LastName;
                ob.IP_Mailing_Address_Line_1__c = tl.IP_MailingAddressLine1__c;
                ob.IP_Mailing_Address_Line_2__c = tl.IP_MailingAddressLine2__c;
                ob.IP_Mailing_Address_Line_3__c = tl.IP_MailingAddressLine3__c;
                ob.IP_Tempest_Department__c = tl.IP_TempestDepartment__c;
                ob.IP_Tempest_Division__c = tl.IP_TempestDivision__c;
                ob.IP_Start_Date__c = tl.IP_WorkerStartDate__c;
                ob.IP_CandidateIDLegacy__c = tl.IP_CandidateIDlegacy__c;   
                ob.IP_Mailing_City__c = tl.MailingCity;
                ob.IP_Mailing_Country__c = tl.MailingCountry;       
                ob.IP_Mailing_State__c = tl.MailingState;
                ob.IP_Mailing_PostalCode__c = tl.MailingPostalCode;
                ob.IP_Phone__c = tl.Phone;
                // ob.IP_BrandCompanyCode__c = Ccode.IP_CompanyCodeValue__c;
                ob.IP_Salutation__c = tl.Salutation;      
                ob.IP_National_Insurance__c = tl.Sirenum__National_Insurance__c;     
                    if(tl.WTR_Completed__c == True){        ob.IP_WTR__c = 'True';}        else{ob.IP_WTR__c = 'False';}       
                ob.IP_Pay_Frequency__c = String.valueOf(tl.IP_PayFrequency__c);
                ob.IP_Department__c = tl.IP_Department__c;
            
                 if(checkpassed == true)
                {
                    ob.IP_Passed__c = 'PASSING';
                    if(parallelcheck.Run_Parallel_Payroll__c == false)
                    {
                        tl.IP_LastPassedToTempest2ndTier__c = System.now();
                    }
                }
            
                ob.IP_TransferType__c = 'External Worker';
                }   
            }
            
        }
        else if(tl.IP_Pass2ndTierToTempest__c == True && tl.IP_EmergencyPull__c == True)
        {
         IP_OutboundDataTransfer__c ob = new IP_OutboundDataTransfer__c();
         ob.IP_EmergencyPull__c = True;
                ob.IP_OriginRecordID__c = tl.Id;
                ob.IP_2ndTierSupplier_Reference__c = c.Account.IP_SupplierReference__c;
                ob.IP_Birthdate__c = tl.Birthdate;
                ob.IP_Consultants_Tempest_ID__c = tl.IP_ConsultantsTempestID__c;
                ob.IP_Email__c = tl.Email;
                ob.IP_First_Name__c = tl.FirstName;
                ob.IP_Last_Name__c   = tl.LastName;
                ob.IP_Mailing_Address_Line_1__c = tl.IP_MailingAddressLine1__c;
                ob.IP_Mailing_Address_Line_2__c = tl.IP_MailingAddressLine2__c;
                ob.IP_Mailing_Address_Line_3__c = tl.IP_MailingAddressLine3__c;
                ob.IP_Tempest_Department__c = tl.IP_TempestDepartment__c;
                ob.IP_Tempest_Division__c = tl.IP_TempestDivision__c;
                ob.IP_Start_Date__c = tl.IP_WorkerStartDate__c;
                ob.IP_CandidateIDLegacy__c = tl.IP_CandidateIDlegacy__c;   
                ob.IP_Mailing_City__c = tl.MailingCity;
                ob.IP_Mailing_Country__c = tl.MailingCountry;       
                ob.IP_Mailing_State__c = tl.MailingState;
                ob.IP_Mailing_PostalCode__c = tl.MailingPostalCode;
                ob.IP_Phone__c = tl.Phone;
                // ob.IP_BrandCompanyCode__c = Ccode.IP_CompanyCodeValue__c;
                ob.IP_Salutation__c = tl.Salutation;      
                ob.IP_National_Insurance__c = tl.Sirenum__National_Insurance__c;     
                if(tl.WTR_Completed__c == True){        ob.IP_WTR__c = 'True';}        else{ob.IP_WTR__c = 'False';}       
                ob.IP_Pay_Frequency__c = String.valueOf(tl.IP_PayFrequency__c);
                ob.IP_Department__c = tl.IP_Department__c;
                if(checkpassed == true)
                {
                    ob.IP_Passed__c = 'PASSING';
                    if(parallelcheck.Run_Parallel_Payroll__c == false)
                    {
                        tl.IP_LastPassedToTempest2ndTier__c = System.now();
                    }
                }
        
                ob.IP_TransferType__c = 'External Worker';
                outbound.add(ob);        
        
          
        
        }
        }    
    }
        if(outbound.size()>0)
        {
           sList = Database.insert(outbound,false);
           
        
          List<Id> errorIds = new List<Id>();
        for (Database.SaveResult sr : sList) {
          if (sr.isSuccess()) {
                System.debug('Successfully inserted Data' );
                 
                    
            }
            else {
                      for(Database.Error err : sr.getErrors()) {                       errorIds.add(tl.id);                      Errmsg.put(tl.id,err.getMessage());
                       }
                      
                 }
        }
           if(!errorIds.IsEmpty())
              {
                 for(integer i=0;i<errorIds.size();i++)
                   {
                        errorFile = errorFile + errorIds[i]+','+ Errmsg.get(errorIds[i]) + ',' +'\n';                        
                        sendMail = true;
                    }
               }
               else
               {
               try{
                   
                    if(parallelcheck.Run_Parallel_Payroll__c == false)
                    {
                     tl.IP_Pass2ndTierToTempest__c = false;
                     tl.IP_EmergencyPull__c = false;
                  
                    }
                    if(tl.IP_FirstPassExternalWorker__c == true)
                    {
                        tl.IP_FirstPassExternalWorker__c = false;
                    }
                     if(tl.IP_LastPassedToTempest2ndTier__c != Null)
                   {
                        tl.IP_LastPassedToTempest2ndTier__c = System.now();
                   }
                
                  
                    
                   }
                   catch(Exception e)
                   {
                   errorFile = errorFile + tl +',' +e +','+'\n';                   sendMail = true;
                   } 
               }
                  
          
           
          /* Send email for error Ids */
          
          }
          else if(existoutbound.size()>0)
          {
        sList = Database.update(existoutbound,false);
            
           
        
          List<Id> errorIds = new List<Id>();
        for (Database.SaveResult sr : sList) {
          if (sr.isSuccess()) {
                System.debug('Successfully updated Data' );
                 
                    
            }
            else {
                      for(Database.Error err : sr.getErrors()) { 
                      errorIds.add(sr.id);
                      Errmsg.put(sr.id,err.getMessage());
                       }
                      
                 }
                 }
           if(!errorIds.IsEmpty())
              {
                 for(integer i=0;i<errorIds.size();i++)
                   {
                        errorFile = errorFile + errorIds[i]+','+ Errmsg.get(errorIds[i]) + ',' +'\n';                        
                        sendMail = true;
                    }
               }
               else
               {
               try{
                    if(parallelcheck.Run_Parallel_Payroll__c == false)
                    {
                       tl.IP_Pass2ndTierToTempest__c = false;
                       tl.IP_EmergencyPull__c = false;
                    }
                    if(tl.IP_FirstPassExternalWorker__c == true)
                    {
                        tl.IP_FirstPassExternalWorker__c = false;
                    }
                  
                   }
                   catch(Exception e)
                   {
                   errorFile = errorFile + tl +',' +e +','+'\n';                   sendMail = true;
                   } 
               }
                  
          
           
       
          }
          
          if(existoutbound.size()>0 || outbound.size()>0 ){
              
                      /* Send email for error Ids */
           if(sendMail == true)
        {    
             String emailid = IP_ImpellamGlobalSetting__c.getInstance().IP_OutboundErrorEmailAddress__c;
            Messaging.EmailFileAttachment errAtt = new Messaging.EmailFileAttachment();                
            blob errBlob = blob.valueof(errorFile);    
            errAtt.setFileName('Failed_Records.csv');
            errAtt.setBody(errBlob);    
            Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage(); 
            String subject ='Outbound Data Failure - Internal Worker';
            email.setSubject(subject);
              String[] toAddresses = new String[] {emailid};
            email.setToAddresses(toAddresses);
           // String[] toAddresses = new String[]{'tajinder.singh@espire.com'};
            email.setToAddresses(toAddresses);
            email.setPlainTextBody('Hello,\n\nPlease find attached the list of failed records.');
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{errAtt});
        
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
            
            }  
              
          }
      
             
    }

}