Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <description>Billing system ID for client</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the Sales Ledger Number for the Account</inlineHelpText>
    <label>SL Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_ContactType__c.field-meta.xml
<CustomField>
    <fullName>IP_ContactType__c</fullName>
    <description>Type of business contact</description>
    <inlineHelpText>What are the responsibilities the contact hold</inlineHelpText>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Contact</fullName>
            </value>
            <value>
                <fullName>Budget Holder</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Invoice Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/Contact_Site_link__c.object-meta.xml
<CustomObject>
    <description>Link between Contacts and Sites allowing a many to many relationship</description>
    <label>Contact / Site link</label>
    <nameField>
        <displayFormat>LINKID-{000000}</displayFormat>
        <label>Contact / Site link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact / Site links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact / Site links</relationshipLabel>
    <relationshipName>Contact_Site_links</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Contact__c.field-meta.xml
<CustomField>
    <fullName>IP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact / Site links (Contact)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_PortalType__c.field-meta.xml
<CustomField>
    <fullName>IP_PortalType__c</fullName>
    <label>Portal Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Secondary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Escalation Hours Approver</fullName>
            </value>
            <value>
                <fullName>Viewer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>VMS - Hours Approver</fullName>
            </value>
            <value>
                <fullName>VMS - Authorised Booker</fullName>
            </value>
            <value>
                <fullName>VMS User</fullName>
                <isActive>false</isActive>
                <label>VMS User</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Site__c.field-meta.xml
<CustomField>
    <fullName>IP_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>sirenum__Site__c.sirenum__Operating_Company__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sirenum__Site__c</referenceTo>
    <relationshipLabel>Contact / Site links (Site2)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <label>Sales Ledger Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/SiteContactLinkController_Test.cls
@isTest
public class SiteContactLinkController_Test {

    public static testmethod void contactsite1(){
        Account client1 = TestDataFactory.createClients(1)[0];
        insert client1;

        Account candacc = TestDataFactory.createCandidateAccount(1)[0];
        insert candacc;

        Account acccon = TestDataFactory.createAccounts(1)[0];
        insert acccon;

        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
        Contact candidateid = TestDataFactory.createCandidate(candacc.id,1)[0];
        insert candidateid;

        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
        Contact con = TestDataFactory.createContact(acccon.id,1)[0];
        //   con.IP_ContactType__c = 'Invoice Contact';
        insert con;

        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
        Contact con1 = TestDataFactory.createContact(acccon.id,1)[0];
        con1.FirstName = 'Test anc';
        con1.Lastname = 'test link';
        //  con1.IP_ContactType__c = 'Invoice Contact';
        con1.Email = 'test12313@ab.com';
        insert con1;

        Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
        User u = TestDataFactory.createUsers(p.id, 1)[0];
        u.username = 'Test.espiredevhdh@test.com';
        u.IP_TempestDepartment__c = '1062';
        insert u;

        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        topaz.IP_SalesLedgerNumber__c = '645628';
        insert topaz;

        sirenum__Site__c site1 = TestDataFactory.createSites(acccon.id,topaz.id,1)[0];
        site1.IP_ClientIDLegacy__c = '1234'; 
        site1.IP_ClientInvoiceName__c = 'Testname';
        site1.IP_InvoiceAddressStreet__c = 'street1';
        site1.IP_InvoiceAddressCity__c = 'city1';
        site1.IP_InvoiceAddressPostcode__c = '7554';
        site1.IP_PublicSector__c = 'No';
        site1.IP_MainContact__c = con.id;
        site1.IP_InvoiceContact__c = con.id;
        site1.IP_PassClientToTempest__c = false;
        insert site1;
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(site1);               
        SiteContactLinkController permgenerate = new SiteContactLinkController(sc);
        List<SelectOption> selectedcontact=permgenerate.allcontacts;
        // permgenerate.linksite2();
        permgenerate.createmyString='Primary Hours Approver';
        permgenerate.fname = 'abc';
        permgenerate.lname ='xyz';
        permgenerate.createlink();
        permgenerate.closepage();
        Test.stopTest();
    }
     
    public static testmethod void contactsite2(){
        Account client1 = TestDataFactory.createClients(1)[0];
        insert client1;

        Account candacc = TestDataFactory.createCandidateAccount(1)[0];
        insert candacc;

        Account acccon = TestDataFactory.createAccounts(1)[0];
        insert acccon;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact candidateid = TestDataFactory.createCandidate(candacc.id,1)[0];
        insert candidateid;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con = TestDataFactory.createContact(acccon.id,1)[0];
        //   con.IP_ContactType__c = 'Invoice Contact';
        insert con;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con1 = TestDataFactory.createContact(acccon.id,1)[0];
        con1.FirstName = 'Test anc';
        con1.Lastname = 'test link';
        //   con1.IP_ContactType__c = 'Invoice Contact';
        con1.email = 'test123@abc.com';
        insert con1;

        Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
        User u = TestDataFactory.createUsers(p.id, 1)[0];
        u.username = 'Test.espiwewredev@test.com';
        u.IP_TempestDepartment__c = '1062';
        insert u;

        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        topaz.IP_SalesLedgerNumber__c = '645628';
        insert topaz;

        sirenum__Site__c site1 = TestDataFactory.createSites(acccon.id,topaz.id,1)[0];
        site1.IP_ClientIDLegacy__c = '1234'; 
        site1.IP_ClientInvoiceName__c = 'Testname';
        site1.IP_InvoiceAddressStreet__c = 'street1';
        site1.IP_InvoiceAddressCity__c = 'city1';
        site1.IP_InvoiceAddressPostcode__c = '7554';
        site1.IP_PublicSector__c = 'No';
        site1.IP_MainContact__c = con.id;
        site1.IP_InvoiceContact__c = con.id;
        site1.IP_PassClientToTempest__c = false;
        insert site1;
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(site1);               
        SiteContactLinkController permgenerate = new SiteContactLinkController(sc);
        List<SelectOption> selectedcontact=permgenerate.allcontacts;
        permgenerate.selectedcontact = con1.Id;

        permgenerate.myString='Primary Hours Approver';
        permgenerate.createmyString='Primary Hours Approver';
        permgenerate.hidvalue = 'test@gmail.com';
        permgenerate.linksite2();
        permgenerate.fname = 'abc';
        permgenerate.createlink();
        permgenerate.closepage();
        Test.stopTest();
    }
    
    public static testmethod void contactsiteSelectedContactnull(){
        Account client1 = TestDataFactory.createClients(1)[0];
        insert client1;

        Account candacc = TestDataFactory.createCandidateAccount(1)[0];
        insert candacc;

        Account acccon = TestDataFactory.createAccounts(1)[0];
        insert acccon;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact candidateid = TestDataFactory.createCandidate(candacc.id,1)[0];
        insert candidateid;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con = TestDataFactory.createContact(acccon.id,1)[0];
        //   con.IP_ContactType__c = 'Invoice Contact';
        insert con;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con1 = TestDataFactory.createContact(acccon.id,1)[0];
        con1.FirstName = 'Test anc';
        con1.Lastname = 'test link';
        //   con1.IP_ContactType__c = 'Invoice Contact';
        con1.email = 'test123@abc.com';
        insert con1;

        Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
        User u = TestDataFactory.createUsers(p.id, 1)[0];
        u.username = 'Test.espiwewredev@test.com';
        u.IP_TempestDepartment__c = '1062';
        insert u;

        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        topaz.IP_SalesLedgerNumber__c = '645628';
        insert topaz;

        sirenum__Site__c site1 = TestDataFactory.createSites(acccon.id,topaz.id,1)[0];
        site1.IP_ClientIDLegacy__c = '1234'; 
        site1.IP_ClientInvoiceName__c = 'Testname';
        site1.IP_InvoiceAddressStreet__c = 'street1';
        site1.IP_InvoiceAddressCity__c = 'city1';
        site1.IP_InvoiceAddressPostcode__c = '7554';
        site1.IP_PublicSector__c = 'No';
        site1.IP_MainContact__c = con.id;
        site1.IP_InvoiceContact__c = con.id;
        site1.IP_PassClientToTempest__c = false;
        insert site1;
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(site1);               
        SiteContactLinkController permgenerate = new SiteContactLinkController(sc);
        List<SelectOption> selectedcontact=permgenerate.allcontacts;
        //permgenerate.selectedcontact = con1.Id;

        permgenerate.myString='Primary Hours Approver';
        permgenerate.createmyString='Primary Hours Approver';
        permgenerate.hidvalue = '';
        permgenerate.linksite2();
        permgenerate.fname = 'abc';
        permgenerate.createlink();
        permgenerate.closepage();
        Test.stopTest();
    }
       
    public static testmethod void contactsite3(){
        Account client1 = TestDataFactory.createClients(1)[0];
        insert client1;

        Account candacc = TestDataFactory.createCandidateAccount(1)[0];
        insert candacc;

        Account acccon = TestDataFactory.createAccounts(1)[0];
        insert acccon;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact candidateid = TestDataFactory.createCandidate(candacc.id,1)[0];
        insert candidateid;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con = TestDataFactory.createContact(acccon.id,1)[0];
        //   con.IP_ContactType__c = 'Invoice Contact';
        insert con;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con1 = TestDataFactory.createContact(acccon.id,1)[0];
        con1.FirstName = 'Test anc';
        con1.Lastname = 'test link';
        //   con1.IP_ContactType__c = 'Invoice Contact';

        insert con1;

        Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
        User u = TestDataFactory.createUsers(p.id, 1)[0];
        u.username = 'Test.espiwewredev@test.com';
        u.IP_TempestDepartment__c = '1062';
        insert u;

        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        topaz.IP_SalesLedgerNumber__c = '645628';
        insert topaz;

        sirenum__Site__c site1 = TestDataFactory.createSites(acccon.id,topaz.id,1)[0];
        site1.IP_ClientIDLegacy__c = '1234'; 
        site1.IP_ClientInvoiceName__c = 'Testname';
        site1.IP_InvoiceAddressStreet__c = 'street1';
        site1.IP_InvoiceAddressCity__c = 'city1';
        site1.IP_InvoiceAddressPostcode__c = '7554';
        site1.IP_PublicSector__c = 'No';
        site1.IP_MainContact__c = con.id;
        site1.IP_InvoiceContact__c = con.id;
        site1.IP_PassClientToTempest__c = false;
        insert site1;
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(site1);               
        SiteContactLinkController permgenerate = new SiteContactLinkController(sc);
        List<SelectOption> selectedcontact=permgenerate.allcontacts;
        permgenerate.selectedcontact = con1.Id;

        permgenerate.myString='Primary Hours Approver;Escalation Hours Approver';

        permgenerate.hidvalue = '';
        permgenerate.linksite2();
        permgenerate.fname = 'abc';
        //   permgenerate.createlink();
        //  permgenerate.closepage();
        Test.stopTest();
    }
    
    public static testmethod void contactsite4(){
        Account client1 = TestDataFactory.createClients(1)[0];
        insert client1;

        Account candacc = TestDataFactory.createCandidateAccount(1)[0];
        insert candacc;

        Account acccon = TestDataFactory.createAccounts(1)[0];
        insert acccon;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact candidateid = TestDataFactory.createCandidate(candacc.id,1)[0];
        insert candidateid;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con = TestDataFactory.createContact(acccon.id,1)[0];
        //   con.IP_ContactType__c = 'Invoice Contact';
        insert con;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con1 = TestDataFactory.createContact(acccon.id,1)[0];
        con1.FirstName = 'Test anc';
        con1.Lastname = 'test link';
        // con1.IP_ContactType__c = 'Invoice Contact';

        insert con1;

        Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
        User u = TestDataFactory.createUsers(p.id, 1)[0];
        u.username = 'Test.espiwewredev@test.com';
        u.IP_TempestDepartment__c = '1062';
        insert u;

        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        topaz.IP_SalesLedgerNumber__c = '645628';
        insert topaz;

        sirenum__Site__c site1 = TestDataFactory.createSites(acccon.id,topaz.id,1)[0];
        site1.IP_ClientIDLegacy__c = '1234'; 
        site1.IP_ClientInvoiceName__c = 'Testname';
        site1.IP_InvoiceAddressStreet__c = 'street1';
        site1.IP_InvoiceAddressCity__c = 'city1';
        site1.IP_InvoiceAddressPostcode__c = '7554';
        site1.IP_PublicSector__c = 'No';
        site1.IP_MainContact__c = con.id;
        site1.IP_InvoiceContact__c = con.id;
        site1.IP_PassClientToTempest__c = false;
        insert site1;
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(site1);               
        SiteContactLinkController permgenerate = new SiteContactLinkController(sc);
        List<SelectOption> selectedcontact=permgenerate.allcontacts;
        permgenerate.selectedcontact = con1.Id;

        permgenerate.createmyString='Primary Hours Approver;Escalation Hours Approver';

        permgenerate.hidvalue = '';
        //   permgenerate.linksite2();
        permgenerate.fname = 'abc';
        permgenerate.createlink();
        //  permgenerate.closepage();
        Test.stopTest();
    }
    
    public static testmethod void contactsite5(){
        Account client1 = TestDataFactory.createClients(1)[0];
        insert client1;

        Account candacc = TestDataFactory.createCandidateAccount(1)[0];
        insert candacc;

        Account acccon = TestDataFactory.createAccounts(1)[0];
        insert acccon;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact candidateid = TestDataFactory.createCandidate(candacc.id,1)[0];
        insert candidateid;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con = TestDataFactory.createContact(acccon.id,1)[0];
        //   con.IP_ContactType__c = 'Invoice Contact';
        insert con;

        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact con1 = TestDataFactory.createContact(acccon.id,1)[0];
        con1.FirstName = 'Test anc';
        con1.Lastname = 'test link';
        // con1.IP_ContactType__c = 'Invoice Contact';
        insert con1;    

        Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
        User u = TestDataFactory.createUsers(p.id, 1)[0];
        u.username = 'Test.espiwewredev@test.com';
        u.IP_TempestDepartment__c = '1062';
        insert u;

        IP_TopazGlobalClientInformation__c topaz = TestDataFactory.createTopaz(1)[0];
        topaz.IP_SalesLedgerNumber__c = '645628';
        insert topaz;

        sirenum__Site__c site1 = TestDataFactory.createSites(acccon.id,topaz.id,1)[0];
        site1.IP_ClientIDLegacy__c = '1234'; 
        site1.IP_ClientInvoiceName__c = 'Testname';
        site1.IP_InvoiceAddressStreet__c = 'street1';
        site1.IP_InvoiceAddressCity__c = 'city1';
        site1.IP_InvoiceAddressPostcode__c = '7554';
        site1.IP_PublicSector__c = 'No';
        site1.IP_MainContact__c = con.id;
        site1.IP_InvoiceContact__c = con.id;
        site1.IP_PassClientToTempest__c = false;
        insert site1;
        
        Contact_Site_link__c csl = new Contact_Site_link__c();
        csl.Account__c = acccon.id;
        csl.IP_Contact__c = con.id;
        csl.IP_PortalType__c = 'Primary Hours Approver';
        csl.IP_Site__c = site1.id;        
        insert csl;
        
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(site1);               
        SiteContactLinkController permgenerate = new SiteContactLinkController(sc);
        List<SelectOption> selectedcontact=permgenerate.allcontacts;
        permgenerate.selectedcontact = con1.Id;

        permgenerate.createmyString='Primary Hours Approver;Escalation Hours Approver';

        permgenerate.hidvalue = '';
        //   permgenerate.linksite2();
        permgenerate.fname = 'abc';
        permgenerate.createlink();
        //  permgenerate.closepage();
        Test.stopTest();
    }
}