Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <description>Billing system ID for client</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the Sales Ledger Number for the Account</inlineHelpText>
    <label>SL Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/VMS_Client__c.field-meta.xml
<CustomField>
    <fullName>VMS_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VMS Client</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/Contact_Site_link__c.object-meta.xml
<CustomObject>
    <description>Link between Contacts and Sites allowing a many to many relationship</description>
    <label>Contact / Site link</label>
    <nameField>
        <displayFormat>LINKID-{000000}</displayFormat>
        <label>Contact / Site link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact / Site links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_PortalType__c.field-meta.xml
<CustomField>
    <fullName>IP_PortalType__c</fullName>
    <label>Portal Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Secondary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Escalation Hours Approver</fullName>
            </value>
            <value>
                <fullName>Viewer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>VMS - Hours Approver</fullName>
            </value>
            <value>
                <fullName>VMS - Authorised Booker</fullName>
            </value>
            <value>
                <fullName>VMS User</fullName>
                <isActive>false</isActive>
                <label>VMS User</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <label>Sales Ledger Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/StagingJobApplication__c.object-meta.xml
<CustomObject>
    <label>Third Party Job Application</label>
    <nameField>
        <displayFormat>VMS-A-{YYYY}{MM}-{0}</displayFormat>
        <label>Staging Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/StagingJobOrder__c.field-meta.xml
<CustomField>
    <fullName>StagingJobOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Third_Party_Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgApplicationStatus__c.field-meta.xml
<CustomField>
    <fullName>stgApplicationStatus__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submission Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgAtsCandidateIntegrationRef__c.field-meta.xml
<CustomField>
    <fullName>stgAtsCandidateIntegrationRef__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Candidate</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>2nd Tier Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>stgFrontOfficeIntegrationSystem__c</fullName>
    <description>stgFrontOfficeIntegrationSystem in Integration Layer</description>
    <label>Brand</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgPayProfile__c.field-meta.xml
<CustomField>
    <fullName>stgPayProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pay Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.stgAtsCandidateIntegrationRef__c</field>
            <operation>equals</operation>
            <valueField>IP_PayProfile__c.IP_Candidate__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>IP_PayProfile__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSubmissionDatetime__c.field-meta.xml
<CustomField>
    <fullName>stgSubmissionDatetime__c</fullName>
    <label>Submission Date Time</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsClientId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsClientId__c</fullName>
    <label>stgVmsClientId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsRoleId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsRoleId__c</fullName>
    <label>stgVmsRoleId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClient_Id__c.field-meta.xml
<CustomField>
    <fullName>StgClient_Id__c</fullName>
    <label>StgClient Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystem__c</fullName>
    <label>StgFrontOfficeIntegrationSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/StagingShift__c.object-meta.xml
<CustomObject>
    <label>Staging Shift</label>
    <nameField>
        <label>Staging Shift</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgRoleId__c</fullName>
    <label>StgRoleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/User_Profile_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of frequently used profile Id&apos;s to use in apex or formula</description>
    <label>User Profile Id</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <label>Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/BlueBarCompControllerTest.cls
/**
 * Created by mrahman on 2020-09-09.
 */

@IsTest
private class BlueBarCompControllerTest {
    @TestSetup
    static void setupSiteContact(){
        Account client = TestDataFactory.createClients(1)[0];
        client.VMS_Client__c = true;
        Account candidateAccount = TestDataFactory.createCandidateAccount(1)[0];
        insert new List<Account> {candidateAccount, client};
        TestDataFactory.setupCustomSettings(candidateAccount.Id);
        TestDataFactory.setupUserProfileCustomSettings();

        Contact clientContact = TestDataFactory.createContact(client.Id, 1)[0];
        Contact worker = TestDataFactory.createCandidate(candidateAccount.Id, 1)[0];
        insert new List<Contact>{worker, clientContact};
        IP_PayProfile__c ppPAYE = TestDataFactory.createPayProfilePaye(worker.Id, 1)[0];
        insert ppPAYE;

        //TestDataFactory.setupShifts();
        StagingJobOrder__c sjobOrder = TestDataFactory.createStagingJobOrders(1)[0];
        insert sjobOrder;
        StagingShift__c sShift = TestDataFactory.createStagingShifts(sjobOrder, 1)[0];
        insert sShift;
        insert new StagingJobApplication__c(stgFrontOfficeIntegrationSystem__c = sjobOrder.StgFrontOfficeIntegrationSystem__c
                ,stgVmsClientId__c = sjobOrder.StgClient_Id__c
                ,stgVmsRoleId__c = sjobOrder.StgRoleId__c
                ,stgPayProfile__c = ppPAYE.Id
                ,stgAtsCandidateIntegrationRef__c = worker.Id
                ,stgApplicationStatus__c = 'New'
                ,stgSubmissionDatetime__c = Datetime.now().addDays(-3));

        //CONTSULTANT
        User consultantUser = [SELECT Id, Name, Username
        FROM User
        WHERE IsActive = true
        AND Profile.Id=: User_Profile_Id__c.getValues('JS Recruiter - Hybrid').Profile_Id__c LIMIT 1];

        //TOPAZ - IP_TopazGlobalClientInformation__c
        IP_TopazGlobalClientInformation__c topzClientInfo = TestDataFactory.createTopaz(1)[0];
        topzClientInfo.Name = client.Name;
        topzClientInfo.IP_SalesLedgerNumber__c='345432';
        insert topzClientInfo;

        sirenum__Site__c site = TestDataFactory.createSites(client.Id, topzClientInfo.Id, 1)[0];
        insert site;


        sirenum__ProActiveContract__c contract = TestDataFactory.sirenumProActiveContract(client.Id, clientContact.Id, 1)[0];
        insert  contract;

        Contact_Site_link__c csl = TestDataFactory.createSiteLinks(client.Id, site.Id, new List<Id>{clientContact.Id})[0];
        csl.IP_PortalType__c = 'VMS User';
        insert csl;

        Integer randomInt = (Math.random()*10000).intValue();
        Id cuProfileId = User_Profile_Id__c.getValues('Customer Portal Manager Custom').Profile_Id__c;
        User clientConUser = TestDataFactory.createUsers(cuProfileId,1)[0];
        clientConUser.ContactId = clientContact.Id;
        clientConUser.Username = 'test_'+randomInt+'_ccu@test.com';
        System.debug(clientContact.Id + ' <<< clientConUser >>> ' + clientConUser);
        TestDataFactory.insertUser(new List<String> {JSON.serialize(clientConUser)});

        //SECTOR - sirenum__Rota__c
        sirenum__Rota__c sector = TestDataFactory.createSector(1)[0];
        insert sector;

        //JOB TYPE - sirenum__Job_Type__c
        sirenum__Job_Type__c jobType = TestDataFactory.createJobType(sector.Id, 1)[0];
        insert jobType;

        //JOB ROLL - sirenum__Team__c
        sirenum__Team__c jobrole = TestDataFactory.createJobRole(contract.Id, jobType.Id, 1)[0];
        insert jobrole;

        sirenum__Placement__c sPlacement = new sirenum__Placement__c(
                Name = 'Sunday to Saturday Placement',
                IP_Consultant1LookupSplitShare__c= consultantUser.Id,
                sirenum__Contact__c = worker.Id,
                sirenum__Site__c= site.Id,
                sirenum__Job_Role__c = jobrole.Id,
                sirenum__Contract__c = contract.Id,
                sirenum__Status__c = 'Active',
                sirenum__Start_Date__c = Datetime.now().addDays(-60).date().toStartOfWeek(),
                IP_Consultant1PercentageSplit__c=100);
        insert sPlacement;
    }

    @IsTest
    static void doVMSUserTest() {
        //@TODO
        Account client = [SELECT Id, Name, (SELECT Id, Email FROM Contacts) FROM Account WHERE RecordType.Name='Account' LIMIT 1];
        //Contact clientContact = [SELECT Id, Email FROM Contact WHERE AccountId =:]
        User clientUser = [SELECT Id, Username FROM User WHERE ContactId =: client.Contacts[0].Id];
        Test.startTest();
        Boolean isVMSUser = BlueBarCompController.getVMSSubscriptoinFlag(clientUser.Id);
        Test.stopTest();
        System.assert(isVMSUser,'User expected to be VMS Site users and account is VMS enabled account');
    }

    @IsTest
    static void doGetUserSitesTest() {
        //@TODO
        Account client = [SELECT Id, Name, (SELECT Id, Email FROM Contacts) FROM Account WHERE RecordType.Name='Account' LIMIT 1];
        //Contact clientContact = [SELECT Id, Email FROM Contact WHERE AccountId =:]
        User clientUser = [SELECT Id, Username FROM User WHERE ContactId =: client.Contacts[0].Id];
        Test.startTest();
        List<sirenum__Site__c> sites = BlueBarCompController.getUserSites(clientUser.Id);
        Test.stopTest();
        System.assert(sites.size()>0,'No site found');
    }
}