Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SupplierReference__c.field-meta.xml
<CustomField>
    <fullName>IP_SupplierReference__c</fullName>
    <label>2nd Tier Supplier Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <label>Initials</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CategoryOfWork__c.field-meta.xml
<CustomField>
    <fullName>IP_CategoryOfWork__c</fullName>
    <description>Which business areas does the person work in</description>
    <inlineHelpText>Which business areas does the person work in</inlineHelpText>
    <label>Category of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>Phone_Type__c</fullName>
    <label>Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/ts2__EEO_Gender__c.field-meta.xml
<CustomField>
    <fullName>ts2__EEO_Gender__c</fullName>
    <label>EEO Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/IP_2ndTierCandidate.recordType-meta.xml
<RecordType>
    <fullName>IP_2ndTierCandidate</fullName>
    <active>true</active>
    <label>2nd Tier Candidate</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_UmbrellaName__c.field-meta.xml
<CustomField>
    <fullName>IP_UmbrellaName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Umbrella Company</label>
    <referenceTo>IP_Umbrellalist__c</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/Umbrella.recordType-meta.xml
<RecordType>
    <fullName>Umbrella</fullName>
    <active>true</active>
    <label>Umbrella</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/IP_Umbrellalist__c.object-meta.xml
<CustomObject>
    <label>Umbrella list</label>
    <nameField>
        <label>Umbrella Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Umbrella list</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine1__c</fullName>
    <label>Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine2__c</fullName>
    <label>Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_AddressLine3__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine3__c</fullName>
    <label>Address Line 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <label>Bank Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountNumber__c</fullName>
    <label>Bank Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BankSortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_BankSortCode__c</fullName>
    <label>Bank Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BuildingSocietyNo__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNo__c</fullName>
    <label>Building Society No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_SupplierReference__c.field-meta.xml
<CustomField>
    <fullName>IP_SupplierReference__c</fullName>
    <label>Supplier Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <label>VAT Registered</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Test_RetreiveFrostRecord.cls
@isTest
public class Test_RetreiveFrostRecord {
    
  /*  static testMethod void RetreiveFrostRecordsTest() 
    {
        Id recordTypeId = [select Id from RecordType where DeveloperName = 'IP_2ndTierCandidate' limit 1].Id;
        system.debug('recordType-->'+recordTypeId);
        Contact con = new Contact();
        con.LastName = 'TestLastName';
        con.Title = 'TestLastName';
        con.Initials__c = 'TestLastName';
        con.FirstName = 'TestLastName';
        con.sirenum__National_Insurance__c = 'AA123456A';
        con.Birthdate = Date.valueOf('1990-02-20');
        con.MailingStreet = 'TestLastName';
        con.MailingCity = 'TestLastName';
        con.MailingCountry = 'TestLastName';
        con.MailingPostalCode = 'TestLastName';
        con.Phone = '9879879877';
        con.Phone_Type__c = '1';
        con.Salutation = 'Mr.';
        con.RecordTypeId = recordTypeId;
        con.ts2__EEO_Gender__c = 'M';
        con.IP_CategoryOfWork__c='Catering;Industrial';        
        system.debug('contact created-->'+con);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        insert con;
        update con;
        //delete con;
        Test.stopTest();
    }*/
    
    static testMethod void RetreiveFrostRecordsPayProfileTest() 
    {
        List<Account> acc = TestDataFactory.createCandidateAccount(1);
        insert acc;
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();//[select Id from RecordType where DeveloperName = 'Candidate' and  limit 1].Id;
        Contact con = new Contact();
        con.LastName = 'TestLastName';
        con.Title = 'TestLastName';
        con.Initials__c = 'TestLastName';
        con.FirstName = 'TestLastName';
        con.sirenum__National_Insurance__c = 'AA123456A';
        con.Birthdate = Date.valueOf('1990-02-20');
        con.MailingStreet = 'TestLastName';
        con.MailingCity = 'TestLastName';
        con.MailingCountry = 'TestLastName';
        con.MailingPostalCode = 'TestLastName';
        con.Phone = '9879879877';
        //con.Phone_Type__c = '1';
        con.Salutation = 'Mr.';
        con.RecordTypeId = recordTypeId;
        con.ts2__EEO_Gender__c = 'M';
        con.IP_CategoryOfWork__c='Catering;Industrial';
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        insert con;
        
             insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= false);
        IP_PayProfile__c payProfile = new IP_PayProfile__c();
        payProfile.IP_Candidate__c = con.Id;
        payProfile.IP_CompanyRegNo__c= 'AS123456';
        //payProfile.IP_PayrollID__c = 'EL13063';
        insert payProfile;
        Test.stopTest();
    }
    static testMethod void RetreiveFrostRecordsCoverUpUpdateAndDelete() 
    {        
        List<Account> acc = TestDataFactory.createCandidateAccount(1);
        insert acc;
        
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();//[select Id from RecordType where DeveloperName = 'Candidate' and  limit 1].Id;
        Contact con = new Contact();
        con.LastName = 'TestLastName';
        con.Title = 'TestLastName';
        con.Initials__c = 'TestLastName';
        con.FirstName = 'TestLastName';
        con.sirenum__National_Insurance__c = 'AA123456A';
        con.Birthdate = Date.valueOf('1990-02-20');
        con.MailingStreet = 'TestLastName';
        con.MailingCity = 'TestLastName';
        con.MailingCountry = 'TestLastName';
        con.MailingPostalCode = 'TestLastName';
        con.Phone = '9879879877';
        //con.Phone_Type__c = '1';
        con.Salutation = 'Mr.';
        con.RecordTypeId = recordTypeId;
        con.ts2__EEO_Gender__c = 'M';
        con.IP_CategoryOfWork__c='Catering;Industrial';
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        insert con;
             insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
         insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= false);
       IP_PayProfile__c payProfile = new IP_PayProfile__c();
        payProfile.IP_Candidate__c = con.Id;
        payProfile.IP_CompanyRegNo__c= 'AS123456';
        payProfile.IP_VATRegistered__c = true;
        insert payProfile;
        update payProfile;
        delete payProfile;
        
        update con;
        delete con;
        Test.stopTest();
    }
     static testMethod void umbrellalist1() 
    {        
        List<Account> acc = TestDataFactory.createCandidateAccount(1);
        insert acc;
        
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();//[select Id from RecordType where DeveloperName = 'Candidate' and  limit 1].Id;
        Contact con = new Contact();
        con.LastName = 'TestLastNamedcs';
        con.Title = 'TestLastName';
        con.Initials__c = 'TestLastName';
        con.FirstName = 'TestLastNamesdcs';
        con.sirenum__National_Insurance__c = 'AA123456A';
        con.Birthdate = Date.valueOf('1990-02-20');
        con.MailingStreet = 'TestLastName';
        con.MailingCity = 'TestLastName';
        con.MailingCountry = 'TestLastName';
        con.MailingPostalCode = 'TestLastName';
        con.Phone = '69063679191';
        //con.Phone_Type__c = '1';
        con.Salutation = 'Mr.';
        con.RecordTypeId = recordTypeId;
        con.ts2__EEO_Gender__c = 'M';
        con.IP_CategoryOfWork__c='Catering;Industrial';
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        insert con;
		
		IP_Umbrellalist__c umblist = new IP_Umbrellalist__c();
		umblist.Name = 'Test Name';
		umblist.IP_AddressLine1__c = 'Line1';
		umblist.IP_AddressLine2__c = 'Line 2';
		umblist.IP_AddressLine3__c = 'Line3';
		umblist.IP_Postcode__c = '6gqjh7';
		umblist.IP_BankAccountName__c = 'Name1';
		umblist.IP_BankAccountNumber__c = '12345678';
		umblist.IP_BankSortCode__c = '123456';
		umblist.IP_BuildingSocietyNo__c = '12345n';
		umblist.IP_CompanyRegNo__c = '11111111';
		umblist.IP_OkToSupply__c = 1;
		umblist.IP_SupplierReference__c = '576';
		umblist.IP_VATRegistered__c = 1;
		umblist.VAT_Number__c = '123456789';
        umblist.IP_PaymentType__c = 'B';
		insert umblist;
        
        IP_Umbrellalist__c umblist1 = new IP_Umbrellalist__c();
		umblist1.Name = 'Test Name111';
		umblist1.IP_AddressLine1__c = 'Line1';
		umblist1.IP_AddressLine2__c = 'Line 2';
		umblist1.IP_AddressLine3__c = 'Line3';
		umblist1.IP_Postcode__c = '6gqjh7';
		umblist1.IP_BankAccountName__c = 'Name1';
		umblist1.IP_BankAccountNumber__c = '12345678';
		umblist1.IP_BankSortCode__c = '123456';
		umblist1.IP_BuildingSocietyNo__c = '12345n';
		umblist1.IP_CompanyRegNo__c = '11111111';
		umblist1.IP_OkToSupply__c = 1;
		umblist1.IP_SupplierReference__c = '576';
		umblist1.IP_VATRegistered__c = 1;
		umblist1.VAT_Number__c = '123456789';
        umblist1.IP_PaymentType__c = 'B';
		insert umblist1;
        		
      
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = false); 
    insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c= false);
        RecordType condRec1 = [Select Id  From RecordType Where sObjectType = 'IP_PayProfile__c' And DeveloperName='Umbrella'];
        
        IP_PayProfile__c pp1 = new IP_PayProfile__c();
        pp1.IP_Candidate__c=con.id;
        pp1.RecordTypeId = condRec1.id;
        pp1.IP_UmbrellaName__c = umblist.id;                                         
        
        insert pp1;
        pp1.IP_UmbrellaName__c = umblist1.id;
        update pp1;
     //   insert payProfile;
      //  update payProfile;
       // delete payProfile;
        
        update con;
        delete con;
        Test.stopTest();
    }
}