Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <description>Billing system ID for client</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the Sales Ledger Number for the Account</inlineHelpText>
    <label>SL Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Declaration_Completed__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>Declaration</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Equal_Opportunity_Completed__c.field-meta.xml
<CustomField>
    <fullName>Equal_Opportunity_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>Equal Opportunity</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Medical_Completed__c.field-meta.xml
<CustomField>
    <fullName>Medical_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>Medical</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/New_Starter_Form__c.field-meta.xml
<CustomField>
    <fullName>New_Starter_Form__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>New Starter Declaration Form</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/PORTW_Completed__c.field-meta.xml
<CustomField>
    <fullName>PORTW_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Completed. Gareth Rogan</description>
    <label>PORTW</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/TOE_Completed__c.field-meta.xml
<CustomField>
    <fullName>TOE_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>TOE</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <label>Sales Ledger Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_StatusID__c.field-meta.xml
<CustomField>
    <fullName>IP_StatusID__c</fullName>
    <label>Status ID</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Ctrl_ContactSearch_Test.cls
/**
 * Created by mrahman on 2021-02-05.
 */

@IsTest
private class Ctrl_ContactSearch_Test {
    @IsTest
    static void contactsearchtest() {
        TestDataFactory.setupUserProfileCustomSettings();
        //TestDataFactory.loadJSFormData();

        Test.starttest();
        Account client = TestDataFactory.createClients(1)[0];
        Insert client;
        Account account = TestDataFactory.createAccounts(1)[0];
        Insert account;
        Account accountcan = TestDataFactory.createCandidateAccount(1)[0];
        Insert accountcan;
        TestDataFactory.setupCustomSettings(accountcan.Id);
        Contact cont = TestDataFactory.createContact(client.id, 1)[0];
        cont.Sirenum__National_Insurance__c='AB123456C';
        Insert cont;

        Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
        candidate.PORTW_Completed__c =true;
        candidate.Medical_Completed__c =true;
        candidate.Declaration_Completed__c=true;
        candidate.TOE_Completed__c =true;
        candidate.New_Starter_Form__c=true;
        candidate.Equal_Opportunity_Completed__c=true;


        Insert candidate;

        IP_TopazGlobalClientInformation__c createtopaz = new IP_TopazGlobalClientInformation__c();
        createtopaz.name = 'TestClient2';
        createtopaz.IP_StatusID__c = 1;
        createtopaz.IP_SalesLedgerNumber__c='123456';
        insert createtopaz;

        id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('PAYE').getRecordTypeId();
        IP_PayProfile__c payprofile2 = new IP_PayProfile__c();
        payprofile2.RecordTypeId = payRTId;

        PageReference pageRef = Page.Contact_Search;

        Test.setCurrentPage(pageRef);
        Ctrl_ContactSearch testAccPlan = new Ctrl_ContactSearch();
        testAccPlan.firstname = cont.FirstName;
        testAccPlan.lastname = cont.lastname;
        testAccPlan.ni_number= cont.Sirenum__National_Insurance__c;
        testAccPlan.searchContacts();
        testAccPlan.Clearfilter();

        Test.stopTest();
    }
}