Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <description>Billing system ID for client</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the Sales Ledger Number for the Account</inlineHelpText>
    <label>SL Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/Batch_header__c.object-meta.xml
<CustomObject>
    <label>Batch Header</label>
    <nameField>
        <displayFormat>Batch-{00000}</displayFormat>
        <label>Batch header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_BatchType__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchType__c</fullName>
    <label>Batch type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/IP_BatchLine__c.object-meta.xml
<CustomObject>
    <label>Batch Line</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Batch Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_BatchHeader__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchHeader__c</fullName>
    <label>Batch Header</label>
    <referenceTo>Batch_header__c</referenceTo>
    <relationshipLabel>Batch Lines</relationshipLabel>
    <relationshipName>Batch_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Number12d4Field1__c.field-meta.xml
<CustomField>
    <fullName>IP_Number12d4Field1__c</fullName>
    <label>Number 12,4 field 1</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField1__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField1__c</fullName>
    <label>Text Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField2__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField2__c</fullName>
    <label>Text Field 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField3__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField3__c</fullName>
    <label>Text Field 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField6__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField6__c</fullName>
    <label>Text Field 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField7__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField7__c</fullName>
    <label>Text field 7</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_SalesLedgerNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_SalesLedgerNumber__c</fullName>
    <label>Sales Ledger Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_StatusID__c.field-meta.xml
<CustomField>
    <fullName>IP_StatusID__c</fullName>
    <label>Status ID</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_TopazUniquenumber__c.field-meta.xml
<CustomField>
    <fullName>IP_TopazUniquenumber__c</fullName>
    <label>Topaz Unique number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Test_TopazGlobalB2FUpdate.cls
@isTest
public class Test_TopazGlobalB2FUpdate {
  @testSetup
  static void dataSetUp() {
    IP_TopazGlobalClientInformation__c globalclient = new IP_TopazGlobalClientInformation__c();
    globalclient.Name = 'Test global topaz';
    globalclient.IP_StatusID__c = 2;
    globalclient.IP_SalesLedgerNumber__c = '134241';
    globalclient.IP_TopazUniquenumber__c = 156;
    insert globalclient;

    Batch_header__c batchheader = new Batch_header__c();
    batchheader.IP_Status__c = 'Approved';
    batchheader.IP_State__c = 'Closed';
    batchheader.IP_BatchType__c = 'Topaz Global Account';
    insert batchheader;

    IP_BatchLine__c batchline2 = new IP_BatchLine__c();
    batchline2.IP_BatchHeader__c = batchheader.id;
    batchline2.IP_Status__c = 'open';
    batchline2.IP_State__c = 'open';
    batchline2.IP_TextField2__c = '134241';
    batchline2.IP_TextField1__c = 'Name1';
    batchline2.IP_TextField6__c = 'Address1';
    batchline2.IP_TextField7__c = 'Address2';
    insert batchline2;
  }
  @istest
  static void BatchHeaderclassmethod1() {
    List<IP_BatchLine__c> listBatchLine = [
      SELECT
        id,
        IP_Status__c,
        IP_TextField2__c,
        IP_TextField6__c,
        IP_TextField1__c,
        IP_TextField7__c
      FROM IP_BatchLine__c
      WHERE IP_Status__c = 'open'
      LIMIT 1
    ];
    Test.startTest();
    Database.executeBatch(new TopazGlobalB2FUpdate(), 1);
    Test.stopTest();
  }
  @istest
  static void BatchHeaderclassmethod2() {
    List<IP_BatchLine__c> listBatchLine = [
      SELECT
        id,
        IP_Status__c,
        IP_Number12d4Field1__c,
        IP_TextField2__c,
        IP_TextField6__c,
        IP_TextField1__c,
        IP_TextField7__c
      FROM IP_BatchLine__c
      WHERE IP_Status__c = 'open'
      LIMIT 1
    ];
    List<IP_TopazGlobalClientInformation__c> topazlist = [
      SELECT id, IP_TopazUniquenumber__c, IP_SalesLedgerNumber__c
      FROM IP_TopazGlobalClientInformation__c
      LIMIT 1
    ];
    listBatchLine[0].IP_TextField2__c = topazlist[0].IP_SalesLedgerNumber__c;
    update listBatchLine;
    Test.startTest();
    Database.executeBatch(new TopazGlobalB2FUpdate(), 1);
    Test.stopTest();
  }
  @istest
  static void BatchHeaderclassmethod3() {
    List<IP_BatchLine__c> listBatchLine = [
      SELECT
        id,
        IP_Status__c,
        IP_Number12d4Field1__c,
        IP_TextField2__c,
        IP_TextField6__c,
        IP_TextField1__c,
        IP_TextField7__c
      FROM IP_BatchLine__c
      WHERE IP_Status__c = 'open'
      LIMIT 1
    ];
    listBatchLine[0].IP_TextField2__c = '111';
    update listBatchLine;
    Test.startTest();
    Database.executeBatch(new TopazGlobalB2FUpdate(), 1);
    Test.stopTest();
  }
  @istest
  static void testtopazschedule() {
    List<IP_BatchLine__c> listBatchLine = [
      SELECT
        id,
        IP_Status__c,
        IP_TextField2__c,
        IP_TextField3__c,
        IP_TextField6__c,
        IP_TextField1__c,
        IP_TextField7__c
      FROM IP_BatchLine__c
      WHERE IP_Status__c = 'open'
      LIMIT 1
    ];
    Test.StartTest();
    ScheduleTopazB2Fbatch sh1 = new ScheduleTopazB2Fbatch();
    String sch = '0 30 * * * ?';
    system.schedule('Test topaz', sch, sh1);
    Test.stopTest();
  }
}