Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/IP_SupplierReference__c.field-meta.xml
<CustomField>
    <fullName>IP_SupplierReference__c</fullName>
    <label>2nd Tier Supplier Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_UmbrellaName__c.field-meta.xml
<CustomField>
    <fullName>IP_UmbrellaName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Umbrella Company</label>
    <referenceTo>IP_Umbrellalist__c</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/Umbrella.recordType-meta.xml
<RecordType>
    <fullName>Umbrella</fullName>
    <active>true</active>
    <label>Umbrella</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/IP_Umbrellalist__c.object-meta.xml
<CustomObject>
    <label>Umbrella list</label>
    <nameField>
        <label>Umbrella Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Umbrella list</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine1__c</fullName>
    <label>Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine2__c</fullName>
    <label>Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_AddressLine3__c.field-meta.xml
<CustomField>
    <fullName>IP_AddressLine3__c</fullName>
    <label>Address Line 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <label>Bank Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountNumber__c</fullName>
    <label>Bank Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BankSortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_BankSortCode__c</fullName>
    <label>Bank Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_BuildingSocietyNo__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNo__c</fullName>
    <label>Building Society No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_SupplierReference__c.field-meta.xml
<CustomField>
    <fullName>IP_SupplierReference__c</fullName>
    <label>Supplier Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <label>VAT Registered</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Umbrellalist__c/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/UpdatePayProfile_test.cls
@istest
public class UpdatePayProfile_test{

    public static testmethod void payprofile()
    {
           insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
         insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c = false);
         Account acc =  TestDataFactory.createCandidateAccount(1)[0];
          insert acc;
         Contact con = TestDataFactory.createCandidate(acc.id,1)[0];
          insert con;
         IP_Umbrellalist__c ul = new IP_Umbrellalist__c ();
         ul.Name = 'ABC';
         ul.IP_AddressLine1__c = 'Line 1';
         ul.IP_AddressLine2__c = 'Line 2';
         ul.IP_AddressLine3__c = 'Line 3';
         ul.IP_BankAccountName__c   = 'Bank 1';
         ul.IP_BankAccountNumber__c = '12345678';
         ul.IP_BankSortCode__c = '123456';
         ul.IP_BuildingSocietyNo__c ='12344';
         ul.IP_CompanyRegNo__c = '12345678';
         ul.IP_OkToSupply__c = 1;
         ul.IP_PaymentType__c = 'B';
         ul.IP_Postcode__c = 'ABCD';
         ul.IP_SupplierReference__c = 'XYZ';
         ul.VAT_Number__c='123324578';
         ul.IP_VATRegistered__c =1;
         
         insert ul;
         IP_Umbrellalist__c ul1 = new IP_Umbrellalist__c ();
         ul1.Name = 'ABC';
         ul1.IP_AddressLine1__c = 'Line 1';
         ul1.IP_AddressLine2__c = 'Line 2';
         ul1.IP_AddressLine3__c = 'Line 3';
         ul1.IP_BankAccountName__c   = 'Bank 1';
         ul1.IP_BankAccountNumber__c = '12345678';
         ul1.IP_BankSortCode__c = '123456';
         ul1.IP_BuildingSocietyNo__c ='12344';
         ul1.IP_CompanyRegNo__c = '12345678';
         ul1.IP_OkToSupply__c = 1;
         ul1.IP_PaymentType__c = 'B';
         ul1.IP_Postcode__c = 'ABCD';
         ul1.IP_SupplierReference__c = 'XYZ';
         ul1.VAT_Number__c='';
         ul1.IP_VATRegistered__c =0;         
         insert ul1;
            insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= false);
         IP_PayProfile__c pf = new IP_PayProfile__c();
         RecordType condRec = [Select Id  From RecordType Where sObjectType = 'IP_PayProfile__c' And DeveloperName='Umbrella'];
         pf.IP_Candidate__c = con.id;
         pf.IP_UmbrellaName__c = ul.id;
         pf.RecordTypeid = condRec.id;
        IP_PayProfile__c pf1 = new IP_PayProfile__c();
         RecordType condRec1 = [Select Id  From RecordType Where sObjectType = 'IP_PayProfile__c' And DeveloperName='Umbrella'];
         pf1.IP_Candidate__c = con.id;
         pf1.IP_UmbrellaName__c = ul1.id;
         pf1.RecordTypeid = condRec1.id;
           test.startTest();
         insert pf;
       
        
         insert pf1;
        
         pf.IP_UmbrellaName__c = ul1.id;
        update pf;
          test.stopTest();
        }
    
 }