Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Managed_Account__c.field-meta.xml
<CustomField>
    <fullName>Managed_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to define managed accounts for validation rule purposes</description>
    <label>Rate Card Restriction</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <label>Tempest Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDivision</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestID__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestID__c</fullName>
    <description>ID need for passing to payroll</description>
    <externalId>true</externalId>
    <inlineHelpText>The ID needed for payroll detail passed</inlineHelpText>
    <label>Tempest ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_restrictRateCardPageAccessHandler.cls
@isTest
public class Test_restrictRateCardPageAccessHandler {
    
    static testMethod void testMethod1()
    {
        Profile Prof=[SELECT Id FROM Profile WHERE Name='JS Recruiter - Hybrid' limit 1];
        User user = [SELECT Id FROM User WHERE Profile.Name='JS Recruiter - Hybrid' and isActive = true limit 1];
      /*  DateTime dt2 = DateTime.newInstance(2017, 6, 23, 4, 2, 3);
        Long gettime = dt2.getTime();
        user.LastName = 'Data1';
        user.FirstName='TestUser';
        user.Alias = 'TstUrD';
        user.Email = 'abc.efg@GHI.com';
        user.Username = 'Email'+gettime+'@js.com.uk';
        user.ProfileId = Prof.id;
        user.TimeZoneSidKey = 'GMT';
        user.LanguageLocaleKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LocaleSidKey = 'en_US';
        user.IP_TempestDepartment__c='2043';
        user.IP_TempestID__c='1084675';
        user.IP_TempestDivision__c='NTS';
        user.Department='1069';
        user.IP_PassToTempest__c=true;
        insert user;*/
        
        Account acc1 = new Account();
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account'];
        acc1.name='TestAccount1';
        acc1.Phone='012034563433';
        acc1.BillingStreet='Street1';
        acc1.BillingCity ='City1';
        acc1.BillingPostalCode = 'BN18YL';
        acc1.BillingState='State1';
        acc1.BillingCountry='Country1';
        acc1.RecordTypeId=accountRec.id;
        acc1.Managed_Account__c=true;    
        insert acc1;
        system.debug('Account Inserted');
        sirenum__Rate_Card__c ratecard = new sirenum__Rate_Card__c();
        ratecard.Name='Test Rate Card';
        ratecard.IP_AcountLinkCustom__c=acc1.id;
        insert ratecard;
        
        
        
        test.startTest();
        try{
            system.runas(user)
            {
                
                sirenum__Rate_Card_Page__c  rateCardPage = new sirenum__Rate_Card_Page__c();    
                rateCardPage.Name='test RateCardPage';
                rateCardPage.sirenum__Rate_Card__c=ratecard.id;
                rateCardPage.sirenum__Rate_Type__c='Hourly';
                rateCardPage.sirenum__SortOrder__c=1;
                insert rateCardPage;
            }
        }
        catch(DMLException e)
        {
            System.assert(true,'Insertion Failed Appropriately');
        }
        test.stopTest();
        
        
    }
    static testMethod void testMethod2()
    {
        Profile Prof=[SELECT Id FROM Profile WHERE Name='JS Recruiter - Hybrid' limit 1];
       User user = [SELECT Id FROM User WHERE Profile.Name='JS Recruiter - Hybrid' and isActive = true limit 1];
      /*  DateTime dt2 = DateTime.newInstance(2017, 6, 23, 4, 2, 3);
        Long gettime = dt2.getTime();
        user.LastName = 'Data1';
        user.FirstName='TestUser';
        user.Alias = 'TstUrD';
        user.Email = 'abc.efg@GHI.com';
        user.Username = 'Email'+gettime+'@js.com.uk';
        user.ProfileId = Prof.id;
        user.TimeZoneSidKey = 'GMT';
        user.LanguageLocaleKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LocaleSidKey = 'en_US';
        user.IP_TempestDepartment__c='2043';
        user.IP_TempestID__c='1084675';
        user.IP_TempestDivision__c='NTS';
        user.Department='1069';
        user.IP_PassToTempest__c=true;
        insert user;*/
        
        Account acc1 = new Account();
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account'];
        acc1.name='TestAccount1';
        acc1.Phone='012034563433';
        acc1.BillingStreet='Street1';
        acc1.BillingCity ='City1';
        acc1.BillingPostalCode = 'BN18YL';
        acc1.BillingState='State1';
        acc1.BillingCountry='Country1';
        acc1.RecordTypeId=accountRec.id;
        acc1.Managed_Account__c=true;    
        insert acc1;
        system.debug('Account Inserted');
        
        
        sirenum__Rate_Card__c ratecard = new sirenum__Rate_Card__c();
        ratecard.Name='Test Rate Card';
        ratecard.IP_AcountLinkCustom__c=acc1.id;
        insert ratecard;
        
        sirenum__Rate_Card_Page__c  rateCardPage = new sirenum__Rate_Card_Page__c();    
        rateCardPage.Name='test RateCardPage';
        rateCardPage.sirenum__Rate_Card__c=ratecard.id;
        rateCardPage.sirenum__Rate_Type__c='Hourly';
        rateCardPage.sirenum__SortOrder__c=0;
        insert rateCardPage;
        
        
        test.startTest();
        try{
            system.runas(user)
            {
                rateCardPage.sirenum__SortOrder__c=1;
                update rateCardPage;
                
            }
        }
        catch(DMLException e)
        {
            System.assert(true,'Updation Failed Appropriately');
        }
        test.stopTest();
        
        
    }
    static testMethod void testMethod3()
    {
        Profile Prof=[SELECT Id FROM Profile WHERE Name='Back Office' limit 1];
        User user = [SELECT Id FROM User WHERE Profile.Name='JS Recruiter - Hybrid' and isActive = true limit 1];
      /*  DateTime dt2 = DateTime.newInstance(2017, 6, 23, 4, 2, 3);
        Long gettime = dt2.getTime();
        user.LastName = 'Data1';
        user.FirstName='TestUser';
        user.Alias = 'TstUrD';
        user.Email = 'abc.efg@GHI.com';
        user.Username = 'Email'+gettime+'@js.com.uk';
        user.ProfileId = Prof.id;
        user.TimeZoneSidKey = 'GMT';
        user.LanguageLocaleKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LocaleSidKey = 'en_US';
        user.IP_TempestDepartment__c='2043';
        user.IP_TempestID__c='1084675';
        user.IP_TempestDivision__c='NTS';
        user.Department='1069';
        user.IP_PassToTempest__c=true;
        insert user;*/
        
        Account acc1 = new Account();
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account'];
        acc1.name='TestAccount1';
        acc1.Phone='012034563433';
        acc1.BillingStreet='Street1';
        acc1.BillingCity ='City1';
        acc1.BillingPostalCode = 'BN18YL';
        acc1.BillingState='State1';
        acc1.BillingCountry='Country1';
        acc1.RecordTypeId=accountRec.id;
        acc1.Managed_Account__c=true;    
        insert acc1;
        system.debug('Account Inserted');
        
        
        sirenum__Rate_Card__c ratecard = new sirenum__Rate_Card__c();
        ratecard.Name='Test Rate Card';
        ratecard.IP_AcountLinkCustom__c=acc1.id;
        insert ratecard;
        
        sirenum__Rate_Card_Page__c  rateCardPage = new sirenum__Rate_Card_Page__c();    
        rateCardPage.Name='test RateCardPage';
        rateCardPage.sirenum__Rate_Card__c=ratecard.id;
        rateCardPage.sirenum__Rate_Type__c='Hourly';
        rateCardPage.sirenum__SortOrder__c=0;
        insert rateCardPage;
        
        
        test.startTest();
        try{
            system.runas(user)
            {
                delete rateCardPage;
                
            }
        }
        catch(DMLException e)
        {
            System.assert(true,'deletion Failed Appropriately');
        }
        test.stopTest();
        
        
    }
    static testMethod void testMethod4()
    {
        Profile Prof=[SELECT Id FROM Profile WHERE Name='Back Office' limit 1];
        User user = [SELECT Id FROM User WHERE Profile.Name='JS Recruiter - Hybrid' and isActive = true limit 1 ];
      /*  DateTime dt2 = DateTime.newInstance(2017, 6, 23, 4, 2, 3);
        Long gettime = dt2.getTime();
        user.LastName = 'Data1';
        user.FirstName='TestUser';
        user.Alias = 'TstUrD';
        user.Email = 'abc.efg@GHI.com';
        user.Username = 'Email'+gettime+'@js.com.uk';
        user.ProfileId = Prof.id;
        user.TimeZoneSidKey = 'GMT';
        user.LanguageLocaleKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LocaleSidKey = 'en_US';
        user.IP_TempestDepartment__c='2043';
        user.IP_TempestID__c='1084675';
        user.IP_TempestDivision__c='NTS';
        user.Department='1069';
        user.IP_PassToTempest__c=true;
        insert user;*/
        
        Account acc1 = new Account();
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account'];
        acc1.name='TestAccount1';
        acc1.Phone='012034563433';
        acc1.BillingStreet='Street1';
        acc1.BillingCity ='City1';
        acc1.BillingPostalCode = 'BN18YL';
        acc1.BillingState='State1';
        acc1.BillingCountry='Country1';
        acc1.RecordTypeId=accountRec.id;
        acc1.Managed_Account__c=false;    
        insert acc1;
        system.debug('Account Inserted');
        
        sirenum__Rate_Card__c ratecard = new sirenum__Rate_Card__c();
        ratecard.Name='Test Rate Card';
        ratecard.IP_AcountLinkCustom__c=acc1.id;
        insert ratecard;
        
        sirenum__Rate_Card_Page__c  rateCardPage = new sirenum__Rate_Card_Page__c();    
        rateCardPage.Name='test RateCardPage';
        rateCardPage.sirenum__Rate_Card__c=ratecard.id;
        rateCardPage.sirenum__Rate_Type__c='Hourly';
        rateCardPage.sirenum__SortOrder__c=0;
        insert rateCardPage;
        
        
        test.startTest();
        try{
            system.runas(user)
            {
                delete rateCardPage;
                
            }
        }
        catch(DMLException e)
        {
            System.assert(true,'deletion Failed Appropriately');
        }
        test.stopTest();
        
        
    }
    static testMethod void testMethod5()
    {
        Profile Prof=[SELECT Id FROM Profile WHERE Name='JS Recruiter - Hybrid' limit 1];
      User user = [SELECT Id FROM User WHERE Profile.Name='JS Recruiter - Hybrid' and isActive = true limit 1];
      /*  DateTime dt2 = DateTime.newInstance(2017, 6, 23, 4, 2, 3);
        Long gettime = dt2.getTime();
        user.LastName = 'Data1';
        user.FirstName='TestUser';
        user.Alias = 'TstUrD';
        user.Email = 'abc.efg@GHI.com';
        user.Username = 'Email'+gettime+'@js.com.uk';
        user.ProfileId = Prof.id;
        user.TimeZoneSidKey = 'GMT';
        user.LanguageLocaleKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LocaleSidKey = 'en_US';
        user.IP_TempestDepartment__c='2043';
        user.IP_TempestID__c='1084675';
        user.IP_TempestDivision__c='NTS';
        user.Department='1069';
        user.IP_PassToTempest__c=true;
        insert user;*/
        
        Account acc1 = new Account();
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account'];
        acc1.name='TestAccount1';
        acc1.Phone='012034563433';
        acc1.BillingStreet='Street1';
        acc1.BillingCity ='City1';
        acc1.BillingPostalCode = 'BN18YL';
        acc1.BillingState='State1';
        acc1.BillingCountry='Country1';
        acc1.RecordTypeId=accountRec.id;
        acc1.Managed_Account__c=true;    
        insert acc1;
        system.debug('Account Inserted');
        
        sirenum__Rate_Card__c ratecard = new sirenum__Rate_Card__c();
        ratecard.Name='Test Rate Card';
        ratecard.IP_AcountLinkCustom__c=acc1.id;
        insert ratecard;
        
        sirenum__Rate_Card_Page__c  rateCardPage = new sirenum__Rate_Card_Page__c();    
        rateCardPage.Name='test RateCardPage';
        rateCardPage.sirenum__Rate_Card__c=ratecard.id;
        rateCardPage.sirenum__Rate_Type__c='Hourly';
        rateCardPage.sirenum__SortOrder__c=0;
        insert rateCardPage;
        
        
        test.startTest();
        try{
            system.runas(user)
            {
                delete rateCardPage;
                
            }
        }
        catch(DMLException e)
        {
            System.assert(true,'deletion Failed Appropriately');
        }
        test.stopTest();
        
        
    }
}