Frankbelford/uatv1ba/force-app/main/default/objects/Account/fields/Unit_ID__c.field-meta.xml
<CustomField>
    <fullName>Unit_ID__c</fullName>
    <description>Unit Id to populate</description>
    <label>Unit ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP PayFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/Contact_Site_link__c.object-meta.xml
<CustomObject>
    <description>Link between Contacts and Sites allowing a many to many relationship</description>
    <label>Contact / Site link</label>
    <nameField>
        <displayFormat>LINKID-{000000}</displayFormat>
        <label>Contact / Site link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact / Site links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact / Site links</relationshipLabel>
    <relationshipName>Contact_Site_links</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Contact__c.field-meta.xml
<CustomField>
    <fullName>IP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact / Site links (Contact)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Site__c.field-meta.xml
<CustomField>
    <fullName>IP_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>sirenum__Site__c.sirenum__Operating_Company__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sirenum__Site__c</referenceTo>
    <relationshipLabel>Contact / Site links (Site2)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine1__c</fullName>
    <description>for recording the business address for the candidate, LTD, umbrella, etc. only is required</description>
    <label>Business Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine2__c</fullName>
    <label>Business Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressPostcode__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressPostcode__c</fullName>
    <label>Business Address Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressTown__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressTown__c</fullName>
    <label>Business Address Town</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyName__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyName__c</fullName>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <label>Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_VATNumber__c</fullName>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/LTD.recordType-meta.xml
<RecordType>
    <fullName>LTD</fullName>
    <active>true</active>
    <label>LTD</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/User_Profile_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of frequently used profile Id&apos;s to use in apex or formula</description>
    <label>User Profile Id</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <label>Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/PortalV2SiteAssignmentControllerTest.cls
@IsTest
public with sharing class PortalV2SiteAssignmentControllerTest {
  @TestSetup
  static void setup() {
    Payroll_Swtich__c objCustomPayrol = new Payroll_Swtich__c();
    objCustomPayrol.Batch_check__c = false;
    objCustomPayrol.Name = 'Stoppayroll';
    insert objCustomPayrol;

    IP_JSToFrostSwtich__c FrostIntegration = new IP_JSToFrostSwtich__c(
      Name = 'JSToFrost',
      IP_RunJSToFrost__c = false
    );
    insert FrostIntegration;
    // insert new User_Profile_Id__c(
    //   Name = 'User Portal',
    //   Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'User Portal']
    //   .Id
    // );
  }

  @IsTest
  public static void GetSites() {
    insert new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'User Portal']
      .Id
    );

    /*
            Setup 
        */
    Account acc = new Account(Name = 'Test Account');
    insert acc;

    Account acc2 = new Account(Name = 'Test Account 2');
    insert acc2;

    sirenum__Site__c site = new sirenum__Site__c(
      Name = 'Test Site',
      sirenum__Operating_Company__c = acc.Id,
      IP_ClientInvoiceName__c = 'Test Account'
    );
    insert site;

    sirenum__Site__c site2 = new sirenum__Site__c(
      Name = 'Test Site 2',
      sirenum__Operating_Company__c = acc.Id,
      IP_ClientInvoiceName__c = 'Test Account'
    );
    insert site2;

    //Belongs to a different account
    sirenum__Site__c site3 = new sirenum__Site__c(
      Name = 'Test Site 3',
      sirenum__Operating_Company__c = acc2.Id,
      IP_ClientInvoiceName__c = 'Test Account'
    );
    insert site3;

    /*
            Execution
        */
    List<sirenum__Site__c> output = PortalV2SiteAssignmentController.getAccountSites(
      acc.Id
    );

    /*
            Assertions
        */
    System.assertEquals(2, output.size());
  }

  @IsTest
  public static void GetContacts() {
    /*
            Setup 
        */

    insert new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'User Portal']
      .Id
    );
    Account acc = new Account(Name = 'Test Account');
    insert acc;

    Account acc2 = new Account(Name = 'Test Account 2');
    insert acc2;

    Contact con1 = new Contact(
      FirstName = 'Test',
      LastName = 'Test',
      AccountId = acc.Id
    );
    insert con1;

    Contact con2 = new Contact(
      FirstName = 'Test',
      LastName = 'Test2',
      AccountId = acc.Id
    );
    insert con2;

    //Belongs to another account
    Contact con3 = new Contact(
      FirstName = 'Test',
      LastName = 'Test3',
      AccountId = acc2.Id
    );
    insert con3;

    /*
            Execution
        */
    List<Contact> output = PortalV2SiteAssignmentController.getAccountContacts(
      acc.Id
    );

    /*
            Assertions
        */
    System.assertEquals(2, output.size());
  }

  @IsTest
  public static void GetSiteAssignments() {
    /*
            Setup 
        */
    insert new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'User Portal']
      .Id
    );
    Account acc = new Account(Name = 'Test Account');
    insert acc;

    sirenum__Site__c site = new sirenum__Site__c(
      Name = 'Test Site',
      sirenum__Operating_Company__c = acc.Id,
      IP_ClientInvoiceName__c = 'Test Account'
    );
    insert site;

    sirenum__Site__c site2 = new sirenum__Site__c(
      Name = 'Test Site 2',
      sirenum__Operating_Company__c = acc.Id,
      IP_ClientInvoiceName__c = 'Test Account'
    );
    insert site2;

    Contact con1 = new Contact(
      FirstName = 'Test',
      LastName = 'Test',
      AccountId = acc.Id
    );
    insert con1;

    Contact con2 = new Contact(
      FirstName = 'Test',
      LastName = 'Test2',
      AccountId = acc.Id
    );
    insert con2;

    Contact_Site_link__c link = new Contact_Site_link__c(
      IP_Site__c = site.Id,
      IP_Contact__c = con1.Id,
      Account__c = acc.Id
    );
    insert link;
    /*
            Execution
        */
    List<Contact_Site_link__c> output1 = PortalV2SiteAssignmentController.getSiteAssignments(
      new List<Id>{ con1.Id }
    );
    List<Contact_Site_link__c> output2 = PortalV2SiteAssignmentController.getSiteAssignments(
      new List<Id>{ con2.Id }
    );

    /*
            Assertions
        */
    System.assertEquals(1, output1.size());
    System.assertEquals(0, output2.size());
  }

  @IsTest
  public static void GetTimesheetsWithPONumber() {
    /*
            Setup
        */
    insert new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'User Portal']
      .Id
    );
    Account client = TestDataFactory.createCandidateAccount(1)[0];
    insert client;

    Account act = TestDataFactory.createAccounts(1)[0];
    insert act;

    //insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);

    Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
    insert candidate;
    //  insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
    // id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('LTD').getRecordTypeId();
    IP_PayProfile__c payprofile = new IP_PayProfile__c();
    //  payprofile.RecordTypeId = payRTId;
    payprofile.IP_Candidate__c = candidate.id;
    payprofile.IP_CompanyName__c = 'sfdc';
    payprofile.IP_Status__c = 'Active';
    payprofile.IP_CompanyRegNo__c = 'ad123456';
    payprofile.IP_VATNumber__c = '123456789';
    payprofile.IP_PayrollID__c = 'testpay1';
    payprofile.IP_VATRegistered__c = true;
    payprofile.IP_OkToSupply__c = 1;
    payprofile.IP_BusinessAddressLine1__c = 'test address 1';
    payprofile.IP_BusinessAddressLine2__c = 'test address 2';
    payprofile.IP_BusinessAddressTown__c = 'town city';
    payprofile.IP_BusinessAddressPostcode__c = '12345678';
    payprofile.IP_PayFrequency__c = 'Weekly';
    payprofile.IP_PaymentType__c = 'BACS';
    //  payprofile.IP_PassToTempest__c=true;
    payprofile.IP_BankAccountName__c = 'Test name1';
    payprofile.IP_AccountNumber__c = '98567497';
    payprofile.IP_SortCode__c = '645362';
    insert payprofile;

    sirenum__ProActiveContract__c pac = TestDataFactory.sirenumProActiveContract(
      act.Id,
      candidate.Id,
      1
    )[0];
    insert pac;

    sirenum__Rota__c sector = TestDataFactory.createSector(1)[0];
    insert sector;

    sirenum__Job_Type__c jobType = TestDataFactory.createJobType(
      sector.id,
      1
    )[0];
    insert jobType;

    sirenum__Team__c jrole = TestDataFactory.createJobRole(
      pac.Id,
      jobType.Id,
      1
    )[0];
    insert jrole;

    Profile p = [SELECT Id FROM Profile WHERE name = 'System Administrator'];
    User usr = TestDataFactory.createUsers(p.Id, 1)[0];
    usr.username = 'acfgd.test@test.com';
    insert usr;
    // IP_TopazGlobalClientInformation__c tpz = TestDataFactory.createTopaz(1)[0];
    // insert tpz;

    sirenum__Site__c ssite = TestDataFactory.createSites(act.id, null, 1)[0];
    insert ssite;

    sirenum__Placement__c splace = TestDataFactory.createSPlacement1(
      candidate.Id,
      pac.Id,
      jrole.Id,
      usr.Id,
      1
    )[0];
    splace.IP_PayMethod__c = payprofile.id;
    splace.sirenum__site__c = ssite.id;
    insert splace;

    sirenum__Shift__c shft = TestDataFactory.createShift(
      splace.id,
      ssite.id,
      1
    )[0];
    shft.sirenum__Contact__c = candidate.id;
    shft.sirenum__Team__c = jrole.id;
    insert shft;

    sirenum__Timesheet__c sts = TestDataFactory.createTimeSheet(
      client.id,
      candidate.Id,
      1
    )[0];
    sts.sirenum__Week_Ending__c = date.newInstance(2017, 12, 31);
    sts.IP_Client_Invoice_PO__c = '12345';
    insert sts;

    sirenum__Timesheet_Line__c stsl = TestDataFactory.createTimeSheetLine(
      sts.Id,
      shft.id,
      1
    )[0];
    insert stsl;

    /*
            Execution
        */
    List<sirenum__Timesheet__c> poNumberOutput = PortalV2SiteAssignmentController.getTimesheets(
      '12345',
      null
    );

    /*
            Assertions  
        */
    System.assertEquals(1, poNumberOutput.Size());
  }

  @IsTest
  public static void GetTimesheetsWithUnitId() {
    /*
            Setup
        */
    insert new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = [SELECT Id FROM Profile WHERE Name = 'User Portal']
      .Id
    );
    Account client = TestDataFactory.createCandidateAccount(1)[0];
    insert client;

    Account act = TestDataFactory.createAccounts(1)[0];
    insert act;

    //insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);

    Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
    insert candidate;
    //  insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
    // id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('LTD').getRecordTypeId();
    IP_PayProfile__c payprofile = new IP_PayProfile__c();
    //  payprofile.RecordTypeId = payRTId;
    payprofile.IP_Candidate__c = candidate.id;
    payprofile.IP_CompanyName__c = 'sfdc';
    payprofile.IP_Status__c = 'Active';
    payprofile.IP_CompanyRegNo__c = 'ad123456';
    payprofile.IP_VATNumber__c = '123456789';
    payprofile.IP_PayrollID__c = 'testpay1';
    payprofile.IP_VATRegistered__c = true;
    payprofile.IP_OkToSupply__c = 1;
    payprofile.IP_BusinessAddressLine1__c = 'test address 1';
    payprofile.IP_BusinessAddressLine2__c = 'test address 2';
    payprofile.IP_BusinessAddressTown__c = 'town city';
    payprofile.IP_BusinessAddressPostcode__c = '12345678';
    payprofile.IP_PayFrequency__c = 'Weekly';
    payprofile.IP_PaymentType__c = 'BACS';
    //  payprofile.IP_PassToTempest__c=true;
    payprofile.IP_BankAccountName__c = 'Test name1';
    payprofile.IP_AccountNumber__c = '98567497';
    payprofile.IP_SortCode__c = '645362';
    insert payprofile;

    sirenum__ProActiveContract__c pac = TestDataFactory.sirenumProActiveContract(
      act.Id,
      candidate.Id,
      1
    )[0];
    insert pac;

    sirenum__Rota__c sector = TestDataFactory.createSector(1)[0];
    insert sector;

    sirenum__Job_Type__c jobType = TestDataFactory.createJobType(
      sector.id,
      1
    )[0];
    insert jobType;

    sirenum__Team__c jrole = TestDataFactory.createJobRole(
      pac.Id,
      jobType.Id,
      1
    )[0];
    insert jrole;

    Profile p = [SELECT Id FROM Profile WHERE name = 'System Administrator'];
    User usr = TestDataFactory.createUsers(p.Id, 1)[0];
    usr.username = 'acfgd.test@test.com';
    insert usr;
    // IP_TopazGlobalClientInformation__c tpz = TestDataFactory.createTopaz(1)[0];
    // insert tpz;

    sirenum__Site__c ssite = TestDataFactory.createSites(act.id, null, 1)[0];
    ssite.Unit_Id__c = '12345';
    insert ssite;

    sirenum__Placement__c splace = TestDataFactory.createSPlacement1(
      candidate.Id,
      pac.Id,
      jrole.Id,
      usr.Id,
      1
    )[0];
    splace.IP_PayMethod__c = payprofile.id;
    splace.sirenum__site__c = ssite.id;
    insert splace;

    sirenum__Shift__c shft = TestDataFactory.createShift(
      splace.id,
      ssite.id,
      1
    )[0];
    shft.sirenum__Contact__c = candidate.id;
    shft.sirenum__Team__c = jrole.id;
    insert shft;

    sirenum__Timesheet__c sts = TestDataFactory.createTimeSheet(
      client.id,
      candidate.Id,
      1
    )[0];
    sts.sirenum__Site__c = ssite.id;
    sts.sirenum__Week_Ending__c = date.newInstance(2017, 12, 31);

    insert sts;

    sirenum__Timesheet_Line__c stsl = TestDataFactory.createTimeSheetLine(
      sts.Id,
      shft.id,
      1
    )[0];
    insert stsl;

    /*
            Execution
        */
    List<sirenum__Timesheet__c> poNumberOutput = PortalV2SiteAssignmentController.getTimesheets(
      null,
      '12345'
    );

    /*
            Assertions  
        */
    System.assertEquals(1, poNumberOutput.Size());
  }
}