Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/IP_ImpellamGDPRSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the parameters for managing data retention within the system.</description>
    <label>RSSGlobal_GDPR_settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/fields/IP_ActivityTypesThatQualifyAsContact__c.field-meta.xml
<CustomField>
    <fullName>IP_ActivityTypesThatQualifyAsContact__c</fullName>
    <description>Types of recorded activities that count as contact with a candidate</description>
    <inlineHelpText>Comma separated list like “ Type1,Type2,….”</inlineHelpText>
    <label>Activity Types That Qualify As Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/fields/IP_UncontactedCandidateRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>IP_UncontactedCandidateRetentionPeriod__c</fullName>
    <description>Number of days an uncontacted candidates data is held in the system.</description>
    <label>Uncontacted Candidate Retention Period</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/ScheduleUncontactedCandidateRemoval_Test.cls
@isTest
public class ScheduleUncontactedCandidateRemoval_Test {
     @TestSetup static void setupData() {
  IP_ImpellamGDPRSettings__c obj = new IP_ImpellamGDPRSettings__c (Name='Impellam GDPR settings',IP_ActivityTypesThatQualifyAsContact__c='Visit,Registration,General Call ,Send Email ,Send Contract',IP_UncontactedCandidateRetentionPeriod__c=-10); 
   insert obj;
 }
   public static testMethod void testschedule(){
     
          Test.StartTest();
        ScheduleUncontactedCandidateRemoval sh1 = new ScheduleUncontactedCandidateRemoval();
        String sch = '0 47 21 29 * ?';
        system.schedule('Test GDPRUncontacted', sch, sh1);
        Test.stopTest();

    }
}