Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/StagingJobApplication__c.object-meta.xml
<CustomObject>
    <label>Third Party Job Application</label>
    <nameField>
        <displayFormat>VMS-A-{YYYY}{MM}-{0}</displayFormat>
        <label>Staging Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/StagingJobOrder__c.field-meta.xml
<CustomField>
    <fullName>StagingJobOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Third_Party_Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>stgFrontOfficeIntegrationSystem__c</fullName>
    <description>stgFrontOfficeIntegrationSystem in Integration Layer</description>
    <label>Brand</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsClientId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsClientId__c</fullName>
    <label>stgVmsClientId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsRoleId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsRoleId__c</fullName>
    <label>stgVmsRoleId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsShiftId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsShiftId__c</fullName>
    <label>stgVmsShiftId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCandidateRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgCandidateRoleId__c</fullName>
    <label>StgCandidateRoleId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystem__c</fullName>
    <label>StgFrontOfficeIntegrationSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/VmsCopyMoveCandidateMapping.cls
/**
* Created by mrahman on 2021-01-20.
*/
public with sharing class VmsCopyMoveCandidateMapping {
    public String stgFrontOfficeIntegrationSystem;
    public String stgVmsClientId;
    public String stgVmsRoleId;
    public String stgVmsShiftId;
    public String stgAtsCandidateIntegrationRef;
    public String stgCandidateRoleId;

    public VmsCopyMoveCandidateMapping(){
    }

    public VmsCopyMoveCandidateMapping(StagingJobApplication__c ja) {
        this.stgVmsClientId = ja.stgVmsClientId__c;
        this.stgVmsRoleId = ja.stgVmsRoleId__c;
        this.stgVmsShiftId = ja.stgVmsShiftId__c;
        this.stgAtsCandidateIntegrationRef = ja.Id;
        this.stgCandidateRoleId = ja.StagingJobOrder__r.stgCandidateRoleId__c;
        this.stgFrontOfficeIntegrationSystem  = ja.StgFrontOfficeIntegrationSystem__c;
    }
}