Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/Contact_Site_link__c.object-meta.xml
<CustomObject>
    <description>Link between Contacts and Sites allowing a many to many relationship</description>
    <label>Contact / Site link</label>
    <nameField>
        <displayFormat>LINKID-{000000}</displayFormat>
        <label>Contact / Site link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact / Site links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact / Site links</relationshipLabel>
    <relationshipName>Contact_Site_links</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Contact__c.field-meta.xml
<CustomField>
    <fullName>IP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact / Site links (Contact)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_PortalType__c.field-meta.xml
<CustomField>
    <fullName>IP_PortalType__c</fullName>
    <label>Portal Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Secondary Hours Approver</fullName>
            </value>
            <value>
                <fullName>Escalation Hours Approver</fullName>
            </value>
            <value>
                <fullName>Viewer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>VMS - Hours Approver</fullName>
            </value>
            <value>
                <fullName>VMS - Authorised Booker</fullName>
            </value>
            <value>
                <fullName>VMS User</fullName>
                <isActive>false</isActive>
                <label>VMS User</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Site__c.field-meta.xml
<CustomField>
    <fullName>IP_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>sirenum__Site__c.sirenum__Operating_Company__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sirenum__Site__c</referenceTo>
    <relationshipLabel>Contact / Site links (Site2)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/NI_Number__c.field-meta.xml
<CustomField>
    <fullName>NI_Number__c</fullName>
    <label>NI Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/User_Image__c.field-meta.xml
<CustomField>
    <fullName>User_Image__c</fullName>
    <label>User Image</label>
    <type>Url</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/User_Image_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>User_Image_Uploaded__c</fullName>
    <label>User Image Uploaded</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/MyProfileComponentController.cls
/**
   *  @Name: MyProfileComponentController>   
   *  @Date Created: <04/04/2019>
   *  @Description: <Class to get LoggedIn User Information>
 */
public without sharing class MyProfileComponentController {
    
    /**
        *  Description : Method to get Sites Name
        *  @name : getSitesOfLoggedInUser
        *  @param : None
        *  @return : List<sirenum__Site__c>
        *  @throws exception-none
    */
    @AuraEnabled
    public static List<sirenum__Site__c> getSitesOfLoggedInUser() {
        Integer lmt = Limits.getLimitQueryRows() - Limits.getQueryRows();
       Id loggedInUserId = UserInfo.getUserId();
        User u = [SELECT id,ContactId FROM User WHERE id = :loggedInUserId Limit 1];
        Contact cont = [SELECT id,AccountId FROM Contact WHERE id =:u.contactId];
        
        List < Id > siteIds = new List < Id > ();
        List<Contact_Site_link__c> lstContactList = [SELECT Id,Account__c, IP_Site__c,IP_Site__r.id, IP_Contact__c FROM Contact_Site_link__c
                                                     WHERE IP_Contact__r.Id=:cont.id AND Account__r.Id=:cont.AccountId AND IP_PortalType__c!=null];
        System.debug(lstContactList.size()+'==lstContactList=='+lstContactList);
        for(Contact_Site_link__c conSiteLink : lstContactList){
            siteIds.add(conSiteLink.IP_Site__r.id);
        }
        Map<Id,Sirenum__Site__c> mapIdSiteList = new Map<Id,Sirenum__Site__c>([SELECT Id,Name, sirenum__Operating_Company__c FROM sirenum__Site__c WHERE 
                                                                               id IN: siteIds ORDER BY name ASC limit: lmt]);
        System.debug('sitesList--->>>'+mapIdSiteList);
        return mapIdSiteList.values();
    }
    
    /**
        *  Description : Method to get Logged-In User Information
        *  @name : fetchUserInformation
        *  @param : None
        *  @return : User
        *  @throws exception-none
    */
    @AuraEnabled
    public static User fetchUserInformation() {
        return getUserInformation();
    }
    
    /**
        *  Description : Method to Update Logged-In User Information
        *  @name : updateUserInformation
        *  @param : None
        *  @return : Nothing
        *  @throws exception-none
    */
    @AuraEnabled
    public static String updateUserInformation(String firstname,String lastname,String title,String email,String mobilephone,
                                            String phone,String street,String addressline,String state,String city,String country,String postalCode) {
        try{    
            Boolean checkUserNameExist = checkUsernameEmailOfUser(email);
            if(!checkUserNameExist){
                User user = getUserInformation();
                user.firstname = firstname;
                user.lastname = lastname;
                user.title = title;
                user.email = email;
                user.username = email;
                user.mobilephone = mobilephone;
                user.phone  = phone;
                user.street = street;
                user.Address_Line_2__c = addressline;
                user.state = state;
                user.city = city;
                user.country = country;
                user.postalCode = postalCode;
                update user;
                return 'User Updated Successfully';
            }
            else{
                return Label.EmailAlreadyExist;
            }
        }
        catch(Exception e){
            system.debug('+++++++++++++++++++'+e.getmessage());
            return Label.EmailAlreadyExist;
        }
    }
    
    /**
        *  Description : Method to get Logged-In User Information
        *  @name : getUserInformation
        *  @param : None
        *  @return : User
        *  @throws exception-none
    */
    private static User getUserInformation() {
        User user = [SELECT id, ContactId,email, Name,username, usertype, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                street, city, country, postalcode,User_Image_Uploaded__c, Address_Line_2__c,User_Image__c,state, localesidkey, mobilephone, extension, fax, contact.email
                FROM User WHERE id = :UserInfo.getUserId()];
        return User;
    }
    
    /**
        *  Description : Method to check email, username already exist
        *  @name : checkUsernameEmailOfUser
        *  @param : Email
        *  @return : Boolean
        *  @throws exception-none
    */
    private static Boolean checkUsernameEmailOfUser(String email) {
        Boolean userExist = false;
        User user = getUserInformation();
        List<User> userEmailUserName = [Select id,City,Phone,street,state,PostalCode,Country,NI_Number__c,MobilePhone,FirstName,LastName,Email from user where Email=:email and username=:email and ContactId!=:user.ContactId and (Profile.Name='Customer Portal Manager Custom') limit 1];
        if(!userEmailUserName.isEmpty() && userEmailUserName!=null){
            userExist = true;
        }
        else{
            userExist = false;
        }
        return userExist;
    }
}