Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

DFfullcopybackup/force-app/main/default/objects/Order/fields/Ship_To_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account_Number__c</fullName>
    <formula>ShipToAccountId__r.AccountNumber</formula>
    <label>Ship-To Account Number</label>
    <type>Text</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Order/fields/ShipToAccountId__c.field-meta.xml
<CustomField>
    <fullName>ShipToAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To)</relationshipLabel>
    <relationshipName>OrdersShipTo</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Order/fields/SoldToAccountId__c.field-meta.xml
<CustomField>
    <fullName>SoldToAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>OrdersSoldTo</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Order/fields/ST_SAP_SO_Number__c.field-meta.xml
<CustomField>
    <fullName>ST_SAP_SO_Number__c</fullName>
    <label>SAP SO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Order/fields/Total_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Net_Price__c</fullName>
    <label>Total Net Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Order/fields/Total_Weight_lb__c.field-meta.xml
<CustomField>
    <fullName>Total_Weight_lb__c</fullName>
    <label>Total Weight (lb)</label>
    <summarizedField>OrderItem.Total_Weight_lb__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/OrderItem/fields/Notes_Est_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Notes_Est_Delivery__c</fullName>
    <label>Notes / Est. Delivery</label>
    <type>TextArea</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/OrderItem/fields/Total_Weight_lb__c.field-meta.xml
<CustomField>
    <fullName>Total_Weight_lb__c</fullName>
    <label>Total Weight (lb)</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

Kitz America DF/DFpartialcopy/force-app/main/default/classes/OrderpdfgeneratorVFController.cls
public with sharing class OrderpdfgeneratorVFController {

    public Order ord { get; private set; }
    public List<OrderItem> items { get; private set; }

    public Contact billToContact { get; private set; }
    public User salesRep { get; private set; }
    
    public Id orderId { get; private set; }

   
    public OrderpdfgeneratorVFController() {

       // Id orderId = ApexPages.currentPage().getParameters().get('id');
       orderId = ApexPages.currentPage().getParameters().get('id');
        if(orderId == null) {
            orderId = ApexPages.currentPage().getParameters().get('recordId');
        }
        System.debug('Order Id from VF: ' + orderId);
     //   Id orderId     ='801VG00000o7fGWYAY';
        ord = [
            SELECT Id,
                   OrderNumber,
                   ST_SAP_SO_Number__c,
            	   PoNumber,
                   EffectiveDate,
                   BillToContactId,
                   BillToContact.Name,
                   BillToContact.Email,
                   SBQQ__Quote__r.SBQQ__SalesRep__c,
                   SBQQ__Quote__r.SBQQ__SalesRep__r.Email,
                   SBQQ__Quote__r.SBQQ__SalesRep__r.Name,
                   Ship_To_Account_Number__c,
                   SoldToAccountId__c,
                   ShipToAccountId__c,
                   ShippingAddress,
                   BillingAddress,
                   Total_Weight_lb__c,
                   Total_Net_Price__c
            FROM Order
            WHERE Id = :orderId
        ];

        items = [
            SELECT Quantity,
                   OrderItemNumber,
                   Product2.Name,
                   Product2.ProductCode,
                   Product_Description__c,
                   Notes_Est_Delivery__c,
                   UnitPrice,
                   TotalPrice
            FROM OrderItem
            WHERE OrderId = :orderId
            ORDER BY OrderItemNumber
        ];

        billToContact = ord.BillToContact;
        salesRep = ord.SBQQ__Quote__r.SBQQ__SalesRep__r;
    }
}