Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Subscriptions__c/Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB{000000000}</displayFormat>
        <label>Subscriptions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Subscriptions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribers</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Subscriptions__c/fields/Job_Order__c.field-meta.xml
<CustomField>
    <fullName>Job_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Order</label>
    <referenceTo>sirenum__JobOrder__c</referenceTo>
    <relationshipName>Notification_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Subscriptions__c/fields/Supplier_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supplier Email Sent</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Subscriptions__c/fields/Supplier_SLA_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Supplier_SLA_Email_Date__c</fullName>
    <formula>Job_Order__r.SLA__c + (Supplier_Link__r.SLA__c /24)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier SLA Email Date</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Subscriptions__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/JobOrderNotification.cls
/**
 * Created by mrahman on 2020-08-26.
 */

public with sharing class JobOrderNotification {

    public static void notify2ndTierSupplier(){
        Map<Id, List<Subscriptions__c>> contSubs = getSubscribers();
        System.debug('contSubs::>> '+contSubs.size());
        if(contSubs.size()==0){
            System.debug('There are no emails to be processed');
            return;
        }
        Map<Id, Contact> contacts = new Map<Id, Contact>([SELECT Id, Name, email
                                                                    ,FirstName
                                                            FROM Contact
                                                            WHERE Id IN :contSubs.keySet()]);
        List<String> emailAddress = new List<String>();
        for(Contact c :[SELECT Id, Name, email
                                            ,FirstName
                                    FROM Contact
                                    WHERE Id IN :contSubs.keySet()]) {
            emailAddress.add(c.email);
        }

        Id templateId = [select id, name from EmailTemplate where developername = 'Supplier_notification_2nd_Tier'].id;
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        msg.setBccAddresses(emailAddress);
        msg.setTargetObjectId(contacts.values()[0].Id);
        msg.setWhatId(contSubs.values()[0][0].Id);
        msg.setTemplateId(templateId);

        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{msg});
        System.debug('List of emails ware sent::>> ' + msg);

        List<Subscriptions__c> subscriptions = new List<Subscriptions__c>();
        for(Id contactId : contSubs.keySet()){
            for(Subscriptions__c s : contSubs.get(contactId)){
                s.Supplier_Email_Sent__c = true;
                subscriptions.add(s);
            }
        }
        update subscriptions;
    }

    public static Map<Id, List<Subscriptions__c>> getSubscribers(){
        Datetime lastExecTime = Datetime.now().addMinutes(-5);
        Map<Id, List<Subscriptions__c>> contSubs = new Map<Id, List<Subscriptions__c>>();
        for(Subscriptions__c subs : [SELECT Id, Name
                                            ,User__c
                                            ,User__r.ContactId
                                            ,Account__r.Id
                                            ,Supplier_Email_Sent__c
                                            ,Supplier_SLA_Email_Date__c
                                            ,Job_Order__r.Name
                                            ,Job_Order__r.sirenum__StartDate__c
                                            ,Job_Order__r.sirenum__EndDate__c
                                        FROM Subscriptions__c
                                        WHERE Supplier_Email_Sent__c = false]) {
            if(subs.Supplier_SLA_Email_Date__c < Datetime.now()){
                if(contSubs.containsKey(subs.User__r.ContactId)){
                    contSubs.get(subs.User__r.ContactId).add(subs);
                } else {
                    contSubs.put(subs.User__r.ContactId, new List<Subscriptions__c>{subs});
                }
            }
        }
        return contSubs;
    }
}