Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/Impellam_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RSS Global Settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/ScheduleShiftAutoApprovalMonday_5pm.cls
global class ScheduleShiftAutoApprovalMonday_5pm implements schedulable{
    
    global void execute(SchedulableContext sc){
        Impellam_Settings__c batchSize = Impellam_Settings__c.getValues('ShiftAutoApproval'); 
        Integer limit1 = Integer.Valueof(batchSize.Limit__c);
        ShiftAutoApprovalMonday_5pm CA = new ShiftAutoApprovalMonday_5pm();
        database.executebatch(CA,limit1);
        
    }
    
}