Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/Impellam_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RSS Global Settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/Schedule_ClientNotification_Test.cls
@isTest
public class Schedule_ClientNotification_Test {
     
        public static testMethod void testschedule(){
          Impellam_Settings__c set1 =  new Impellam_Settings__c(name = 'ClientPortalNotification', Limit__c = '50');
        insert set1;
        Test.StartTest();
        Schedule_ClientNotification sh1 = new Schedule_ClientNotification();
        String sch = '0 23 22 29 * ?';
        system.schedule('Test Notification', sch, sh1);
        Test.stopTest();
        
        
        }

}