Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/Impellam_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RSS Global Settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Schedule_ClientNotification.cls
global class Schedule_ClientNotification implements Schedulable{
 Impellam_Settings__c set1 = Impellam_Settings__c.getValues('ClientPortalNotification'); 
             Integer limit1 = Integer.Valueof(set1.Limit__c);
    global void execute(SchedulableContext sc) {
        ClientNotificationPortals batchInstance = new ClientNotificationPortals(); 
        database.executebatch(batchInstance,limit1);
    }
}