Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/IP_OutboundDataTransfer__c.object-meta.xml
<CustomObject>
    <description>Object that holds data for transfer out of the system</description>
    <label>Outbound Data Transfer</label>
    <nameField>
        <displayFormat>ODT-{0000000000}</displayFormat>
        <label>Outbound Data Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Data Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_RowCount__c.field-meta.xml
<CustomField>
    <fullName>IP_RowCount__c</fullName>
    <label>Row count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_TimesheetID__c.field-meta.xml
<CustomField>
    <fullName>IP_TimesheetID__c</fullName>
    <label>Timesheet SF ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/UpdateTimesheetrowcount.cls
public class UpdateTimesheetrowcount {
    
    public static void updatedata(List<sirenum__Timesheet_Line__c> tllist)
    {
        Set<id> outboundid = new Set<id>();
        Set<id> timeid = new Set<id>();
        Map<id,Decimal> TLAppCountMap = new Map<id,Decimal>();
        for(sirenum__Timesheet_Line__c tl: tllist)
        {
            outboundid.add(tl.IP_OutboundID__c);
            timeid.add(tl.sirenum__timesheet__c);
        }
      //  List<sirenum__Timesheet_Line__c> totalines = [Select id,IP_OutboundID__c,sirenum__timesheet__c from sirenum__Timesheet_Line__c where sirenum__Timesheet__c in:outmap.values()];
      
      AggregateResult[] groupedResults  = [SELECT sirenum__timesheet__c timerecid, count(id) childcount FROM sirenum__Timesheet_Line__c where sirenum__timesheet__c in:timeid GROUP BY sirenum__timesheet__c];
        for (AggregateResult ar : groupedResults)  {
            Id timesheetid = (Id) ar.get('timerecid');
            Integer numlines = (Integer) ar.get('childcount');
            TLAppCountMap.put(timesheetid,numlines);
        }
        system.debug('map check'+TLAppCountMap);
        List<IP_OutboundDataTransfer__c> oblist = [Select id,IP_RowCount__c,IP_TimesheetID__c from IP_OutboundDataTransfer__c where id in:outboundid];
        for(IP_OutboundDataTransfer__c ob: oblist)
        {
            ob.IP_RowCount__c = TLAppCountMap.get(ob.IP_TimesheetID__c);
        }
        update oblist;
    }
}