Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/Batch_header__c.object-meta.xml
<CustomObject>
    <label>Batch Header</label>
    <nameField>
        <displayFormat>Batch-{00000}</displayFormat>
        <label>Batch header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_BatchTitle__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchTitle__c</fullName>
    <externalId>true</externalId>
    <label>Batch Title</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_BatchType__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchType__c</fullName>
    <label>Batch type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/IP_BatchLine__c.object-meta.xml
<CustomObject>
    <label>Batch Line</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Batch Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/Check_status__c.field-meta.xml
<CustomField>
    <fullName>Check_status__c</fullName>
    <label>Check status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_BatchHeader__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchHeader__c</fullName>
    <label>Batch Header</label>
    <referenceTo>Batch_header__c</referenceTo>
    <relationshipLabel>Batch Lines</relationshipLabel>
    <relationshipName>Batch_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_ErrorReason__c.field-meta.xml
<CustomField>
    <fullName>IP_ErrorReason__c</fullName>
    <label>Error Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_LinkField1__c.field-meta.xml
<CustomField>
    <fullName>IP_LinkField1__c</fullName>
    <label>Link Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField10__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField10__c</fullName>
    <label>Text field 10</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField11__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField11__c</fullName>
    <label>Text Field 11</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField12__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField12__c</fullName>
    <label>Text Field 12</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField13__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField13__c</fullName>
    <label>Text Field 13</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField14__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField14__c</fullName>
    <label>Text Field 14</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField1__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField1__c</fullName>
    <label>Text Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField2__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField2__c</fullName>
    <label>Text Field 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField3__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField3__c</fullName>
    <label>Text Field 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField4__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField4__c</fullName>
    <label>Text Field 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField5__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField5__c</fullName>
    <label>Text Field 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField6__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField6__c</fullName>
    <label>Text Field 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField7__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField7__c</fullName>
    <label>Text field 7</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField8__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField8__c</fullName>
    <label>Text field 8</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField9__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField9__c</fullName>
    <label>Text field 9</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/SiteB2FUpdate.cls
global class SiteB2FUpdate extends batchjobsch.BatchJobBase implements Database.Batchable<sObject>,Database.Stateful{

    Set<ID> headerId = new Set<ID>();
    Map<id,sirenum__site__c> SiteMap1 = new Map<id,sirenum__site__c>();  
   global Database.QueryLocator start(Database.BatchableContext BC){
     String query ='select id,IP_TextField1__c,IP_TextField2__c,IP_TextField3__c,IP_TextField6__c,IP_TextField7__c,IP_TextField8__c,IP_TextField14__c,IP_TextField4__c,IP_TextField9__c,IP_TextField10__c,IP_TextField13__c,IP_TextField5__c,IP_TextField11__c,IP_TextField12__c,IP_LinkField1__c,IP_Status__c,IP_BatchHeader__r.name from IP_BatchLine__c where IP_Status__c = \'open\' and IP_BatchHeader__r.IP_BatchType__c=\'Site Update\' And ((IP_BatchHeader__r.IP_State__c = \'Closed\' And IP_BatchHeader__r.IP_Status__c = \'Approved\') OR (IP_BatchHeader__r.IP_State__c = \'Processing\' AND IP_BatchHeader__r.IP_Status__c = \'Errored\') OR (IP_BatchHeader__r.IP_State__c = \'Processing\' AND IP_BatchHeader__r.IP_Status__c = \'Partial Complete\'))';
        return Database.getQueryLocator(query);   
   }
   
   global void execute(Database.BatchableContext BC,List<IP_BatchLine__c> batchlinelist){
        Database.SaveResult[] sList;
        Map<Id,String> Errmsg = new Map<Id,String>();
        list<string> SitelegacyID = new list<string>();
        List<sirenum__site__c> siteupdatelist = new List<sirenum__site__c>();
        Map<String,sirenum__site__c> sitemap = new Map<String,sirenum__site__c>();
        for(IP_BatchLine__c bline : batchlinelist){
            headerId.add(bline.IP_BatchHeader__c);
            if(bline.IP_TextField1__c == null)
            {
                bline.IP_Status__c = 'Errored';   
                bline.IP_ErrorReason__c = 'Location ID(Text Field 1) is blank';
            }
            else
            {
                SitelegacyID.add(bline.IP_TextField1__c);
            }
        }
    for(sirenum__site__c sitelist : [Select id,IP_ClientIDLegacy__c,IP_SLNUpdateValue__c,IP_ClientInvoiceName__c,IP_InvoiceAddressStreet__c,IP_InvoiceAddressCity__c,IP_InvoiceAddressCounty__c,IP_InvoiceAddressPostcode__c,IP_InvoiceContactText__c,IP_InvoiceAddressLine4__c,IP_InvoiceAddressLine5__c,IP_InvoiceAddressCountry__c,IP_InvoiceContactEmail__c,IP_InvoiceContactMobile__c,IP_InvoiceContactPhone__c from sirenum__site__c where IP_ClientIDLegacy__c in:SitelegacyID and IP_ClientIDLegacy__c!=null]){
         sitemap.put(sitelist.IP_ClientIDLegacy__c,sitelist);
    }
    
    for(IP_BatchLine__c batchline2 : batchlinelist){
        if(batchline2.IP_Status__c != 'Errored')
        {
    if(sitemap.size()>0 && batchline2.IP_TextField1__c !=null && sitemap.containskey(batchline2.IP_TextField1__c))
    {
        batchline2.IP_LinkField1__c = sitemap.get(batchline2.IP_TextField1__c).id; 
        batchline2.IP_Status__c ='Linking';
        sirenum__site__c site1 = new sirenum__site__c();
        site1.id = sitemap.get(batchline2.IP_TextField1__c).id;
        if(batchline2.IP_TextField2__c != null)
        {
        site1.IP_SLNUpdateValue__c = batchline2.IP_TextField2__c.TRIM();     
        }
        else
        {
        site1.IP_SLNUpdateValue__c = batchline2.IP_TextField2__c;
        }   
        site1.IP_ClientInvoiceName__c = batchline2.IP_TextField3__c;
        site1.IP_InvoiceAddressStreet__c = batchline2.IP_TextField6__c;
        site1.IP_InvoiceAddressCity__c = batchline2.IP_TextField7__c;
        site1.IP_InvoiceAddressCounty__c = batchline2.IP_TextField8__c;
        if(batchline2.IP_TextField14__c != null)
        {
        site1.IP_InvoiceAddressPostcode__c = batchline2.IP_TextField14__c.TRIM();
        }
        else
        {
        site1.IP_InvoiceAddressPostcode__c = batchline2.IP_TextField14__c;
        }
        site1.IP_InvoiceContactText__c = batchline2.IP_TextField4__c;
        site1.IP_InvoiceAddressLine4__c = batchline2.IP_TextField9__c;
        site1.IP_InvoiceAddressLine5__c = batchline2.IP_TextField10__c;
        site1.IP_InvoiceAddressCountry__c =  batchline2.IP_TextField13__c;
        site1.IP_InvoiceContactEmail__c = batchline2.IP_TextField5__c;
        site1.IP_InvoiceContactMobile__c = batchline2.IP_TextField11__c;
        site1.IP_InvoiceContactPhone__c = batchline2.IP_TextField12__c;
        if(!SiteMap1.containskey(site1.id)){           
            SiteMap1.put(site1.id,site1);
            System.debug('check Map in if'+SiteMap1);
         }          
    }
    else
    {
          batchline2.IP_Status__c = 'Errored';   
          batchline2.IP_ErrorReason__c = 'Site not found';
    }
    }
    else
    {
        batchline2.IP_Status__c = 'Errored';   
        batchline2.IP_ErrorReason__c = 'Location ID(Text Field 1) is blank';
    }
    }
  //  siteupdatelist = [Select id,IP_ClientIDLegacy__c,IP_SLNUpdateValue__c,IP_ClientInvoiceName__c,IP_InvoiceAddressStreet__c,IP_InvoiceAddressCity__c,IP_InvoiceAddressCounty__c,IP_InvoiceAddressPostcode__c,IP_InvoiceContactText__c,IP_InvoiceAddressLine4__c,IP_InvoiceAddressLine5__c,IP_InvoiceAddressCountry__c,IP_InvoiceContactEmail__c,IP_InvoiceContactMobile__c,IP_InvoiceContactPhone__c from sirenum__site__c where id in:SiteMap1.keyset()];
  /*  for(Id sitel : SiteMap1.keyset())
    {
       siteupdatelist.addall(SiteMap1.get(sitel));
       System.debug('check final list'+siteupdatelist);
    }*/
    siteupdatelist.addAll(SiteMap1.values());
     if(siteupdatelist.size()>0)
     {
     try{ 
            
                sList=  Database.update(siteupdatelist,false);
            
        }
                  
        catch(Exception DMLException){  }
        
        for (integer i=0; i<sList.size();i++) 
            {
                     
                if(sList[i].isSuccess())
                    {
                       // successIds.add(payprofile[i].id);
                       System.debug('Successfully updated site: ' + siteupdatelist[i].id);
                        Errmsg.put(siteupdatelist[i].id,'Success');
                    }
                else
                    {
                        //errorIds.add(payprofile[i].id);      
                        for(Database.Error err : sList[i].getErrors())
                        {
                           // errMsgs = errMsgs + '  ' + err.getMessage();   
                            Errmsg.put(siteupdatelist[i].id,err.getMessage());      
                        }
                        // errMessage.put(payprofile[i].Id,errMsgs);                           
                    }
            }  
     }
        for(IP_BatchLine__c batchstatus : batchlinelist){
                for(sirenum__site__c t : siteupdatelist){
                    System.debug('***Inside for loop***');
                    If(batchstatus.IP_Status__c!='Errored' && batchstatus.IP_LinkField1__c ==t.id){
                    System.debug('***Inside if statement 1***');
                        If(Errmsg.get(t.Id)!='Success'){
                            batchstatus.IP_Status__c='Errored';
                            if(Errmsg.get(t.Id).length()<255){
                                batchstatus.IP_ErrorReason__c=Errmsg.get(t.Id);
                            }
                            else{
                                batchstatus.IP_ErrorReason__c=Errmsg.get(t.Id).substring(0,255);
                            }
                        }
                        else
                        {
                            System.debug('***Inside else***');
                            batchstatus.IP_Status__c='Processed';    
                        }
                        
                    }
                }
            }
        
        update batchlinelist;
        SiteMap1.clear();
   }
       global void finish(Database.BatchableContext BC){
            Map<Id,Integer> mapUnprocessedBatchHeader = new Map<Id,Integer>();
            Map<Id,Integer> mapErroredBatchHeader = new Map<Id,Integer>(); 
            for(Batch_header__c openStatusBatchHeader : [Select id,IP_Status__c,IP_State__c,Check_status__c,(Select id,IP_Status__c from Batch_Lines__r 
                                                    where IP_Status__c = 'Open') from Batch_header__c  where id=:headerId]){
            if(!openStatusBatchHeader.Batch_Lines__r.isEmpty() && openStatusBatchHeader.Batch_Lines__r.size()>0){
                mapUnprocessedBatchHeader.put(openStatusBatchHeader.id,openStatusBatchHeader.Batch_Lines__r.size());
            }           
        }
        System.debug('mapUnprocessedBatchHeader -- '+mapUnprocessedBatchHeader);
        
        for(Batch_header__c  erroredBatchHeader : [Select id,IP_Status__c,IP_State__c,Check_status__c,(Select id,IP_Status__c from Batch_Lines__r 
                                                    where IP_Status__c = 'Errored' Limit 1) from Batch_header__c  where id=:headerId]){
            if(!erroredBatchHeader.Batch_Lines__r.isEmpty() && erroredBatchHeader.Batch_Lines__r.size()>0){
                mapErroredBatchHeader.put(erroredBatchHeader.id,erroredBatchHeader.Batch_Lines__r.size());
            }           
        }
        System.debug('mapErroredBatchHeader -- '+mapErroredBatchHeader);
        
        List<Batch_header__c> listBatchHeaderUpdate = new List<Batch_header__c>();
        
        for(Batch_header__c  batchHeader : [Select id,IP_BatchTitle__c,Name,IP_Status__c,IP_State__c,Check_status__c 
                                                from Batch_header__c  where id=:headerId]){
            if(!mapUnprocessedBatchHeader.isEmpty() && mapUnprocessedBatchHeader.get(batchHeader.id)>0){
                batchHeader.IP_Status__c = 'Partial Complete';
                batchHeader.IP_State__c = 'Processing';
            }
            else if(!mapErroredBatchHeader.isEmpty() && mapErroredBatchHeader.get(batchHeader.id)>0){
                batchHeader.IP_Status__c = 'Errored';
                batchHeader.IP_State__c = 'Processing';
            }
            else{
                  batchHeader.IP_Status__c = 'Processed';
                  batchHeader.IP_State__c = 'Closed';
            }
          //  batchHeader.Check_status__c = '';
            listBatchHeaderUpdate.add(batchHeader);
        }
        System.debug('listBatchHeaderUpdate -- '+listBatchHeaderUpdate);        
        
        if(!listBatchHeaderUpdate.isEmpty()){
            update listBatchHeaderUpdate;
        }
         super.finishBatch(BC);
    }
}