Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/Batch_header__c.object-meta.xml
<CustomObject>
    <label>Batch Header</label>
    <nameField>
        <displayFormat>Batch-{00000}</displayFormat>
        <label>Batch header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_BatchType__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchType__c</fullName>
    <label>Batch type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CandidateIDlegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDlegacy__c</fullName>
    <description>this is used for candidate that are being migrated from other system but their original IDs must be preserved</description>
    <externalId>true</externalId>
    <inlineHelpText>IF a candidate must still be reference by an original ID (for payroll) used this field</inlineHelpText>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>Last Date Worked</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Reason_for_P45__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_P45__c</fullName>
    <label>Reason for P45 (Internal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Declined work</fullName>
            </value>
            <value>
                <fullName>Other dismissal</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Transferred to LTD</fullName>
            </value>
            <value>
                <fullName>Branch Transfer/BM</fullName>
                <isActive>false</isActive>
                <label>Branch Transfer/BM</label>
            </value>
            <value>
                <fullName>Eight Week Leaver/PE</fullName>
                <isActive>false</isActive>
                <label>Eight Week Leaver/PE</label>
            </value>
            <value>
                <fullName>Payroll Holiday/PH</fullName>
                <isActive>false</isActive>
                <label>Payroll Holiday/PH</label>
            </value>
            <value>
                <fullName>Payroll Inactive/PI</fullName>
                <isActive>false</isActive>
                <label>Payroll Inactive/PI</label>
            </value>
            <value>
                <fullName>Payroll Leaver/PL</fullName>
                <isActive>false</isActive>
                <label>Payroll Leaver/PL</label>
            </value>
            <value>
                <fullName>T.U.P.E Transfers/TU</fullName>
                <isActive>false</isActive>
                <label>T.U.P.E Transfers/TU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/IP_BatchLine__c.object-meta.xml
<CustomObject>
    <label>Batch Line</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Batch Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_BatchHeader__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchHeader__c</fullName>
    <label>Batch Header</label>
    <referenceTo>Batch_header__c</referenceTo>
    <relationshipLabel>Batch Lines</relationshipLabel>
    <relationshipName>Batch_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_DateField1__c.field-meta.xml
<CustomField>
    <fullName>IP_DateField1__c</fullName>
    <label>Date Field 1</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_ErrorReason__c.field-meta.xml
<CustomField>
    <fullName>IP_ErrorReason__c</fullName>
    <label>Error Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField1__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField1__c</fullName>
    <label>Text Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>P45 Emailed Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_P45_Internal__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_P45_Internal__c</fullName>
    <label>Reason for P45 (Internal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Declined work</fullName>
            </value>
            <value>
                <fullName>Other dismissal</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Transferred to LTD</fullName>
            </value>
            <value>
                <fullName>Branch Transfer/BM</fullName>
                <isActive>false</isActive>
                <label>Branch Transfer/BM</label>
            </value>
            <value>
                <fullName>Eight Week Leaver/PE</fullName>
                <isActive>false</isActive>
                <label>Eight Week Leaver/PE</label>
            </value>
            <value>
                <fullName>Payroll Leaver/PL</fullName>
                <isActive>false</isActive>
                <label>Payroll Leaver/PL</label>
            </value>
            <value>
                <fullName>Payroll holiday/PH</fullName>
                <isActive>false</isActive>
                <label>Payroll holiday/PH</label>
            </value>
            <value>
                <fullName>Payroll inactive/PI</fullName>
                <isActive>false</isActive>
                <label>Payroll inactive/PI</label>
            </value>
            <value>
                <fullName>T.U.P.E transfers/TU</fullName>
                <isActive>false</isActive>
                <label>T.U.P.E transfers/TU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/LTD.recordType-meta.xml
<RecordType>
    <fullName>LTD</fullName>
    <active>true</active>
    <label>LTD</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/BatchHeaderP45sync.cls
global class BatchHeaderP45sync implements Database.Batchable<sObject>,Database.Stateful{
    set<String>payrollID = new Set<String>();
    List<id> errorIds = new List<id>();
List<id> successIds = new List<id>();
String errorFile = 'Id,Error\n'; 
Map<id,String> errMessage = new Map<id,String>();
String errMsgs = '';   

 global Database.QueryLocator start(Database.BatchableContext BC){
  String  query = 'select id,IP_TextField1__c,IP_DateField1__c,IP_ErrorReason__c,IP_BatchLine__c.IP_BatchHeader__c  ,IP_Status__c from IP_BatchLine__c where IP_Status__c = \'open\' and IP_BatchHeader__r.IP_BatchType__c = \'P45 Sync\' and IP_BatchHeader__r.IP_State__c = \'Closed\' and IP_BatchHeader__r.IP_Status__c = \'Approved\'';
  return Database.getQueryLocator(query);
 }

  global void execute(Database.BatchableContext BC,List<IP_BatchLine__c> batchlinelist){
    Set<ID> headerId = new Set<ID>();
    String bheadername;
    for(IP_BatchLine__c bline : batchlinelist){                    
    headerId.add(bline.IP_BatchHeader__c);                  
  }
  List<IP_BatchLine__c> batchlinelistToUpdate = new List<IP_BatchLine__c>();
  List<String> legacyCandidateId = new List<String>();
  Map<ID,IP_BatchLine__c> ContactIDBatchLine = new Map<ID,IP_BatchLine__c>();
  Map<String,Date> CandidateIdEndDateMap = new Map<String,Date>();
 // list<IP_BatchLine__c> batchlinelist = [select id,IP_TextField1__c,IP_DateField1__c,IP_ErrorReason__c,IP_Status__c from IP_BatchLine__c where IP_Status__c =: 'open' and IP_BatchHeader__c In :P45Sync ];
 // system.debug('inside execute method batchline'+batchlinelist );
 
   for(IP_BatchLine__c batchline : batchlinelist ){
            if(batchline.IP_TextField1__c!=null && batchline.IP_DateField1__c!=null)
                legacyCandidateId.add(batchline.IP_TextField1__c);
            CandidateIdEndDateMap.put(batchline.IP_TextField1__c, batchline.IP_DateField1__c);
        }
   List<IP_PayProfile__c> payprofile =[Select id, IP_PayrollID__c, IP_Candidate__c,P45_Date_by_Head_Office__c from IP_PayProfile__c where IP_PayrollID__c In: legacyCandidateId and (RecordType.developername='PAYE' OR RecordType.developername='LTD')]; 
        List<Id> conId = new List<Id>();
        for(IP_PayProfile__c p : payprofile )
        {
            conId.add(p.IP_Candidate__c);
            
        }
         list<Contact> contactList = [select id,name,IP_CandidateIDlegacy__c,Reason_for_P45__c,P45_Date_by_Head_Office__c from Contact where Id In :conId ];
    
        system.debug('payprofile-->'+payprofile );
        system.debug('contactList-->'+contactList );
        for(IP_BatchLine__c batchline : batchlinelist ){
            Boolean candidateFound = false;
           // Boolean result;
            for(Integer i=0;i<payprofile.size();i++){
                for(Integer j =0;j<contactList.size();j++){
                if(batchline.IP_TextField1__c == payprofile[i].IP_PayrollID__c){
                  system.debug('IF1 '+payprofile[i].P45_Date_by_Head_Office__c);  
                      system.debug('IF2 '+batchline.IP_DateField1__c); 
                      system.debug('IF3 '+contactList[j].P45_Date_by_Head_Office__c); 
                    if(payprofile[i].P45_Date_by_Head_Office__c == batchline.IP_DateField1__c && payprofile[i].IP_Candidate__c ==  contactList[j].id && contactList[j].P45_Date_by_Head_Office__c != NULL ){
                        system.debug('LWD-->' );
                        batchline.IP_Status__c = 'Errored';
                        batchline.IP_ErrorReason__c = 'Candidate with Payroll ID as '+batchline.IP_TextField1__c + ' already has \'Date P45 Processed by Head Office\'';
                        batchlinelistToUpdate.add(batchline);
                        break;
                    }
                    else If(payprofile[i].IP_Candidate__c ==  contactList[j].id && (!payrollId.contains(batchline.IP_TextField1__c))){
                    payrollId.add(batchline.IP_TextField1__c);
                        contactList[j].P45_Date_by_Head_Office__c = CandidateIdEndDateMap.get(payprofile[i].IP_PayrollID__c);
                        payprofile[i].P45_Date_by_Head_Office__c = CandidateIdEndDateMap.get(payprofile[i].IP_PayrollID__c);
                    //  System.debug('@@ contactList[j].Reason_for_P45__c '+contactList[j].Reason_for_P45__c);                        
                        If(contactList[j].Reason_for_P45__c ==null)
                        {
                       payprofile[i].Reason_for_P45_Internal__c= 'Automatic';
                       contactList[j].Reason_for_P45__c = 'Automatic';
                        }
                        ContactIDBatchLine.put(contactList[j].id, batchline);
                        candidateFound = true;
                        break;
                    }
                }
            }
            }
            if(!candidateFound){
                if(batchline.IP_Status__c == 'Open'){
                    batchline.IP_Status__c = 'Errored';
                    batchline.IP_ErrorReason__c = 'Candidate with Payroll ID as '+batchline.IP_TextField1__c + ' not found';
                    batchlinelistToUpdate.add(batchline);
                }
            }
        }
        Database.SaveResult[] payList = Database.update(payprofile, false);

                for (integer i=0; i<payList.size();i++) 
                {
                     
                    if(payList[i].isSuccess())
                    {
                        successIds.add(payprofile[i].id);
                    }
                    else
                    {
                        errorIds.add(payprofile[i].id);       for(Database.Error err : payList[i].getErrors())
                        {
                            errMsgs = errMsgs + '  ' + err.getMessage();       
                        }
                         errMessage.put(payprofile[i].Id,errMsgs);                         errMsgs ='';   
                    }
                }        
        Database.SaveResult[] srList = Database.update(contactList, false);
      for (integer i=0; i<srList.size();i++) 
                {
                    // String errMsgs = '';
                    if(srList[i].isSuccess())
                    {
                        successIds.add(contactList[i].id);
                    }
                    else
                    {
                        errorIds.add(contactList[i].id);        for(Database.Error err : srList[i].getErrors())
                        {                            errMsgs = errMsgs + '  ' + err.getMessage();       
                        }
                         errMessage.put(contactList[i].Id,errMsgs);                         errMsgs ='';   
                    }
                }      
                System.debug('$$Error Message Map'+errMessage);
                System.debug('$$Error ID List'+errorIds);
                System.debug('$$SucessID List'+successIds);
                  for(integer i=0;i<errorIds.size();i++)                {                    errorFile = errorFile + errorIds[i]+','+ errMessage.get(errorIds[i]) + ',' +'\n';                 }
        for (Integer i = 0; i < srList.size(); i++) {
            Database.SaveResult sr = srList[i];
            if (sr.isSuccess()) {
                System.debug('sr.getID  ' + sr.getID());
                System.debug('ContactIDBatchLine  ' + ContactIDBatchLine);
                IP_BatchLine__c bl = ContactIDBatchLine.get(sr.getID());
                if(bl!=null && bl.IP_Status__c == 'Open'){
                    bl.IP_Status__c = 'Closed';
                    batchlinelistToUpdate.add(bl);
                }
            }
            else {
                String errorMessage = '';
                System.debug('sr.getID  ' + sr.getID());
                System.debug('ContactIDBatchLine  ' + ContactIDBatchLine);
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Contact fields that affected this error: ' + err.getFields());
                    errorMessage += err.getMessage();
                }
                IP_BatchLine__c bl = ContactIDBatchLine.get(contactList[i].id);
                System.debug('bl error: ' + bl);
                if(bl!=null){
                    bl.IP_Status__c = 'Errored';                    bl.IP_ErrorReason__c = errorMessage;                    batchlinelistToUpdate.add(bl);
                }
            }
        }
        system.debug('batchlinelistToUpdate-->'+batchlinelistToUpdate );
        update batchlinelistToUpdate;
        system.debug('batchlinelistToUpdate-->'+batchlinelistToUpdate );
        List<Batch_header__c> batchheaderlistUpdateStatus = [select id,name,(select id, IP_Status__c from Batch_Lines__r),IP_Status__c from Batch_header__c where id in:headerId]; 
        for(Batch_header__c bh: batchheaderlistUpdateStatus){
            IP_BatchLine__c[] bl = bh.Batch_Lines__r;
            Boolean success = false;
            Boolean failed = false;
            for(IP_BatchLine__c bline: bl){
                if(bline.IP_Status__c == 'Errored'){
                    failed = true;
                }
                else if(bline.IP_Status__c == 'Closed'){
                    success = true;
                }
            }
            if(success && failed){
                bh.IP_Status__c = 'Partial Error';
            }
            else if(success && !failed){                bh.IP_Status__c = 'Completed';
            }
            else if(!success && failed){
                bh.IP_Status__c = 'Rejected';
            }
        }
        update batchheaderlistUpdateStatus;
        system.debug('batchheaderlistUpdateStatus-->'+batchheaderlistUpdateStatus );

}

   global void finish(Database.BatchableContext BC){
   if(errorIds.size()>0)
   {
    Messaging.EmailFileAttachment errAtt = new Messaging.EmailFileAttachment(); 
    System.debug('$$InsideFinishMethod'+errorFile);   
            blob errBlob = blob.valueof(errorFile);                errAtt.setFileName('Failed_Records.csv');            errAtt.setBody(errBlob);
            Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage(); 
          /*  List<String>  toAddresses = new List<String>();
            List<User> userList = new List<User>();
            userList = [SELECT Id,Email,IsActive FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = True] ; 
            for (User u : userList)
            {
            toAddresses.add(u.email);
            } */
            String subject ='P45 Batch Failure';            email.setSubject(subject);            String[] toAddress = new String[] {System.Label.BASupportEmail};
            email.setToAddresses(toAddress);
            email.setPlainTextBody('Hello,\n\nPlease find attached the list of failed records.');
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{errAtt});
        
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }
    }
    
}