Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/For_P45_batch__c.field-meta.xml
<CustomField>
    <fullName>For_P45_batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field to check that we do not face any issue with batch in the trigger of pay profile</description>
    <label>For P45 batch</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/LTD.recordType-meta.xml
<RecordType>
    <fullName>LTD</fullName>
    <active>true</active>
    <label>LTD</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/Umbrella.recordType-meta.xml
<RecordType>
    <fullName>Umbrella</fullName>
    <active>true</active>
    <label>Umbrella</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/PayProfileOkToSupply.cls
public class PayProfileOkToSupply {

    public static void method1(IP_PayProfile__c payprofile)
    {
     if(checkRecursive.runOnce())
    {       
    Payroll_Swtich__c Payroll = Payroll_Swtich__c.getValues('Stoppayroll'); 
    if( !Payroll.Batch_check__c)
    { 
     
        set<Boolean> test= new set<Boolean>();
       
        test.add(payprofile.For_P45_batch__c);
           
        for(Boolean b : test)
        {
        if(b==false)
        {
               
        //Process Builder name : update field for Shift Creation
        set<id> setid1= new set<id>();
        set<id> setid2= new set<id>();
         set<id> setid3= new set<id>();
        Id devRecordTypeId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('LTD').getRecordTypeId();
        Id devRecordTypeId1 = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('PAYE').getRecordTypeId();
        Id devRecordTypeId2 = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('Umbrella').getRecordTypeId();
        
           if(payprofile.RecordTypeId == devRecordTypeId && payprofile.IP_Status__c == 'Active' && payprofile.IP_OkToSupply__c == 1 )
            { 
                setid1.add(payprofile.IP_Candidate__c);
            }
            else if ((payprofile.RecordTypeId == devRecordTypeId1|| payprofile.RecordTypeId == devRecordTypeId2) &&  payprofile.IP_Status__c== 'Active')
            {
                setid2.add(payprofile.IP_Candidate__c);
            }
            else
            {
               setid3.add(payprofile.IP_Candidate__c);
            }
      
        if(setid1.size()>0)
        {
            payProfileProcessBuilder.updateOkToSupply(setid1);
        }
         if(setid2.size()>0)
        {
            payProfileProcessBuilder.updateOkToSupply(setid2);
        }
       if(setid3.size()>0)
       {
 		payProfileProcessBuilder.updateOkToSupplyToNo(setid3);           
       }
                
     
        }
        }
     
    }
    }
    }
}