Frankbelford/uatv1ba/force-app/main/default/objects/Brand__mdt/Brand__mdt.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <pluralLabel>Brands</pluralLabel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/Email_Template_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>All active and inactive custom email templates in Jobscience</description>
    <label>Email Template Mapping</label>
    <pluralLabel>Email Template Mapping</pluralLabel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Brand__mdt</referenceTo>
    <relationshipLabel>Email Template Mapping</relationshipLabel>
    <relationshipName>Email_Template_Mapping</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/Brand_Logo__c.field-meta.xml
<CustomField>
    <fullName>Brand_Logo__c</fullName>
    <inlineHelpText>Static Resource Name where resource type is image. For Example Blue_Arrow_new_logo</inlineHelpText>
    <label>Brand Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <inlineHelpText>SF record ID of the actual email template. This Filed value needs remain unchanged as it will be used to refer from code to identify appropriate template.</inlineHelpText>
    <label>TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/UtilTest.cls
/**
 * Created by mrahman on 2021-03-15.
 */

@IsTest
private class UtilTest {
    @IsTest
    static void testGetWeekDayStrOrNum() {
        Datetime dt = Datetime.now();
        String strOrNum = '0';
        System.assert(Util.getWeekDayStrOrNum(dt, strOrNum) != null);
    }

    @IsTest
    static void testIsLastWeekendDate(){
        Date d = Datetime.now().date();
        System.assert(Util.isLastWeekendDate(d) != null);
    }

    @IsTest
    static void testNotifyAdminByEmail() {
        String subject = 'Test';
        String body = 'Test body';
        Util.notifyAdminByEmail(subject, body);
    }

    @IsTest
    static void testGetEmailTemplateMapping(){
        String brand='Blue Arrow';
        Email_Template_Mapping__mdt etm = [SELECT Id, Label, DeveloperName, TemplateId__c, Brand__c, Brand__r.Label, Brand_Logo__c
                                            FROM Email_Template_Mapping__mdt
                                            WHERE Brand__r.Label =: brand LIMIT 1];
        String templateName=etm.Label;

        System.assert(Util.getEmailTemplateMapping(brand, templateName) != null);
    }
}