Frankbelford/uatv1ba/force-app/main/default/objects/Brand__mdt/Brand__mdt.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <pluralLabel>Brands</pluralLabel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/Email_Template_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>All active and inactive custom email templates in Jobscience</description>
    <label>Email Template Mapping</label>
    <pluralLabel>Email Template Mapping</pluralLabel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Brand__mdt</referenceTo>
    <relationshipLabel>Email Template Mapping</relationshipLabel>
    <relationshipName>Email_Template_Mapping</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/Brand_Logo__c.field-meta.xml
<CustomField>
    <fullName>Brand_Logo__c</fullName>
    <inlineHelpText>Static Resource Name where resource type is image. For Example Blue_Arrow_new_logo</inlineHelpText>
    <label>Brand Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <inlineHelpText>SF record ID of the actual email template. This Filed value needs remain unchanged as it will be used to refer from code to identify appropriate template.</inlineHelpText>
    <label>TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/sendautoresponse.cls
public class sendautoresponse {
    public static void sendmail(Set<id> sendapp){

        Id templateId;
        //Email_Template_Mapping__mdt
        //templateId = [select id, name from EmailTemplate where developername = 'Auto_Responder_e_mail'].id;
        Map<String, String> brandTemplate = new Map<String, String>();
        for(Email_Template_Mapping__mdt etm : [SELECT TemplateId__c, Brand_Logo__c, Brand__r.Label
                                                FROM Email_Template_Mapping__mdt
                                                WHERE Label = 'Auto rejection e-mail']){
            brandTemplate.put(etm.Brand__r.Label, etm.TemplateId__c);
        }
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        for(ts2__Application__c a: [Select id,ts2__Candidate_Contact__c,ts2__Candidate_Contact__r.Email, ts2__PrimaryRecruiter__r.Brand__c
                                        from ts2__Application__c where id in:sendapp]) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTemplateId(brandTemplate.get(a.ts2__PrimaryRecruiter__r.Brand__c));
            mail.setTargetObjectId(a.ts2__Candidate_Contact__c);
            mail.setWhatid(a.id);
            mail.setSaveasActivity(true);
            emailList.add(mail);
        }
        if(emailList.size() > 0) {
            Messaging.sendEmail(emailList);
        }
    }
}