Frankbelford/uatv1ba/force-app/main/default/objects/Brand__mdt/Brand__mdt.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <pluralLabel>Brands</pluralLabel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/Email_Template_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>All active and inactive custom email templates in Jobscience</description>
    <label>Email Template Mapping</label>
    <pluralLabel>Email Template Mapping</pluralLabel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Brand__mdt</referenceTo>
    <relationshipLabel>Email Template Mapping</relationshipLabel>
    <relationshipName>Email_Template_Mapping</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/Brand_Logo__c.field-meta.xml
<CustomField>
    <fullName>Brand_Logo__c</fullName>
    <inlineHelpText>Static Resource Name where resource type is image. For Example Blue_Arrow_new_logo</inlineHelpText>
    <label>Brand Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Email_Template_Mapping__mdt/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <inlineHelpText>SF record ID of the actual email template. This Filed value needs remain unchanged as it will be used to refer from code to identify appropriate template.</inlineHelpText>
    <label>TemplateId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Util.cls
public class Util {
  public static boolean stopFrostRunAgain = true;
  public static boolean stopQueueableRunAgain = true;

  /**
   * Supply a date to receive either the Weekday name like Monday or Weekday number like 0
   *
   * @param dt
   * @param strOrNum
   *
   * @return
   */
  @AuraEnabled
  public static String getWeekDayStrOrNum(Datetime dt, String strOrNum){
    System.debug('Day from Now: ' + dt.Day());
    System.debug('Week Day from Now: ' + dt.format('EEEE'));
    strOrNum = StrOrNum.toUpperCase();
    if(strOrNum == 'STR' || strOrNum == 'STRING'){
      return dt.format('EEEE');
    } else if(strOrNum == 'NUM' || strOrNum == 'NUMBER' || strOrNum == 'NO'){
      return String.valueOf(dt.day());
    } else {
      return 'Error: unknown request. Expected Str or Num';
    }
  }

  public static Boolean isLastWeekendDate(Date d){
    return true;
  }

  public static Email_Template_Mapping__mdt getEmailTemplateMapping(String brand, String templateName){
    Email_Template_Mapping__mdt etm = [SELECT Id, DeveloperName, TemplateId__c, Brand__c, Brand__r.Label, Brand_Logo__c
                      FROM Email_Template_Mapping__mdt
                      WHERE Brand__r.Label =: brand AND Label =: templateName LIMIT 1];
    return etm;
  }

  public static void notifyAdminByEmail(String subject, String body){
    Messaging.SingleEmailMessage[] sEmails = new Messaging.SingleEmailMessage[0];
    String strAdminEmails = System.Label.AdminEmail;
    if(String.isBlank(strAdminEmails)){
      return ;
    }

    List<String> emailAddress = new List<String>();
    for(String e : strAdminEmails.split(',')){
      emailAddress.add(e.trim());
    }

    Messaging.SingleEmailMessage sEmail = new Messaging.SingleEmailMessage();
    sEmail.setToAddresses(emailAddress);
    sEmail.setSubject(subject);
    sEmail.setPlainTextBody(body);
    sEmails.add(sEmail);
    Messaging.sendEmail(sEmails);
  }
}