Frankbelford/uatv1ba/force-app/main/default/objects/Integration_Error_Log__c/Integration_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Error Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Vms Integration Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Integration_Error_Log__c/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>CallType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Integration_Error_Log__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>JSON or SOAP Payload</description>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCandidateRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgCandidateRoleId__c</fullName>
    <label>StgCandidateRoleId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClient_Id__c.field-meta.xml
<CustomField>
    <fullName>StgClient_Id__c</fullName>
    <label>StgClient Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClientName__c.field-meta.xml
<CustomField>
    <fullName>StgClientName__c</fullName>
    <label>StgClientName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>StgCreatedDate__c</fullName>
    <label>StgCreatedDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgEndDate__c.field-meta.xml
<CustomField>
    <fullName>StgEndDate__c</fullName>
    <label>StgEndDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgEndTime__c.field-meta.xml
<CustomField>
    <fullName>StgEndTime__c</fullName>
    <label>StgEndTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystem__c</fullName>
    <label>StgFrontOfficeIntegrationSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgHasShifts__c.field-meta.xml
<CustomField>
    <fullName>StgHasShifts__c</fullName>
    <label>StgHasShifts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgJobTitle__c.field-meta.xml
<CustomField>
    <fullName>StgJobTitle__c</fullName>
    <label>StgJobTitle</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgLocationId__c.field-meta.xml
<CustomField>
    <fullName>StgLocationId__c</fullName>
    <label>StgLocationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgLocationName__c.field-meta.xml
<CustomField>
    <fullName>StgLocationName__c</fullName>
    <label>StgLocationName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgQuantity__c.field-meta.xml
<CustomField>
    <fullName>StgQuantity__c</fullName>
    <label>StgQuantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgRequiredStaff__c.field-meta.xml
<CustomField>
    <fullName>StgRequiredStaff__c</fullName>
    <label>StgRequiredStaff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgRoleRequirement__c.field-meta.xml
<CustomField>
    <fullName>StgRoleRequirement__c</fullName>
    <label>StgRoleRequirement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgSourceSystem__c.field-meta.xml
<CustomField>
    <fullName>StgSourceSystem__c</fullName>
    <label>StgSourceSystem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgStartDate__c.field-meta.xml
<CustomField>
    <fullName>StgStartDate__c</fullName>
    <label>StgStartDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgStartTime__c.field-meta.xml
<CustomField>
    <fullName>StgStartTime__c</fullName>
    <label>StgStartTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/StagingShift__c.object-meta.xml
<CustomObject>
    <label>Staging Shift</label>
    <nameField>
        <label>Staging Shift</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/Staging_Job_Order__c.field-meta.xml
<CustomField>
    <fullName>Staging_Job_Order__c</fullName>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Staging Shifts</relationshipLabel>
    <relationshipName>Staging_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgClientID__c.field-meta.xml
<CustomField>
    <fullName>StgClientID__c</fullName>
    <label>StgClientID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgClientName__c.field-meta.xml
<CustomField>
    <fullName>StgClientName__c</fullName>
    <label>StgClientName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgFrontOfficeIntegrationSystemEntity__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystemEntity__c</fullName>
    <label>StgFrontOfficeIntegrationSystemEntity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgJobTitle__c.field-meta.xml
<CustomField>
    <fullName>StgJobTitle__c</fullName>
    <label>StgJobTitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgPlacement__c.field-meta.xml
<CustomField>
    <fullName>StgPlacement__c</fullName>
    <label>StgPlacement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleEndDate__c.field-meta.xml
<CustomField>
    <fullName>StgRoleEndDate__c</fullName>
    <label>StgRoleEndDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgRoleId__c</fullName>
    <label>StgRoleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleStartDate__c.field-meta.xml
<CustomField>
    <fullName>StgRoleStartDate__c</fullName>
    <label>StgRoleStartDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgSector__c.field-meta.xml
<CustomField>
    <fullName>StgSector__c</fullName>
    <label>StgSector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftEndTime__c.field-meta.xml
<CustomField>
    <fullName>StgShiftEndTime__c</fullName>
    <label>StgShiftEndTime</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftId__c.field-meta.xml
<CustomField>
    <fullName>StgShiftId__c</fullName>
    <label>StgShiftId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftStartTime__c.field-meta.xml
<CustomField>
    <fullName>StgShiftStartTime__c</fullName>
    <label>StgShiftStartTime</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftStatus__c.field-meta.xml
<CustomField>
    <fullName>StgShiftStatus__c</fullName>
    <label>StgShiftStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgSourceSystem__c.field-meta.xml
<CustomField>
    <fullName>StgSourceSystem__c</fullName>
    <label>StgSourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>StgUpdatedDate__c</fullName>
    <label>StgUpdatedDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/VmsJobOrderRESTService.cls
/**
 * Created by mrahman on 2020-11-04.
 * This API will only handle GET and POST request.
 * Upsert and Update is handled in Flow which processes the Staging Job Order and Staging Shift to JS Job Order and JS Shift
 * Delete is out of scope of this implementation
 */

@RestResource(urlMapping='/vms-job-order/*')
global with sharing class VmsJobOrderRESTService {
    @HttpGet
    global static StagingJobOrder__c getJobOrderById(){
        RestRequest request = RestContext.request;
        String stgRoleId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        System.debug('stgRoleId >> '+stgRoleId);
        StagingJobOrder__c stgJobOrder = [SELECT Id, Name,
                                                 StgSourceSystem__c
                                                ,StgClientName__c
                                                ,StgClient_Id__c
                                                ,StgRoleId__c
                                                ,StgJobTitle__c
                                                ,StgQuantity__c
                                                ,StgStartDate__c
                                                ,StgEndDate__c
                                                ,StgStartTime__c
                                                ,StgEndTime__c
                                                ,StgLocationId__c
                                                ,StgLocationName__c
                                                ,StgHasShifts__c
                                                ,StgCandidateRoleId__c
                                                ,(SELECT Id, Name,
                                                         StgSourceSystem__c
                                                        ,StgClientName__c
                                                        ,StgClientID__c
                                                        ,StgRoleId__c
                                                        ,StgShiftId__c
                                                        ,StgJobTitle__c
                                                        ,StgQuantity__c
                                                        ,StgRoleStartDate__c
                                                        ,StgRoleEndDate__c
                                                        ,StgShiftStartTime__c
                                                        ,StgShiftEndTime__c
                                                        ,StgLocationId__c
                                                        ,StgLocationName__c
                                                        ,StgCreatedDate__c
                                                        ,StgUpdatedDate__c
                                                        ,StgShiftStatus__c
                                                        ,StgFrontOfficeIntegrationSystem__c
                                                        ,StgFrontOfficeIntegrationSystemEntity__c
                                                        ,StgSector__c
                                                        ,StgPlacement__c
                                                    FROM Staging_Shifts__r)
                                                ,StgCreatedDate__c
                                                ,StgUpdatedDate__c
                                                ,StgFrontOfficeIntegrationSystem__c
                                                ,StgRoleRequirement__c
                                                ,StgRequiredStaff__c
                                            FROM StagingJobOrder__c
                                            WHERE Id=:stgRoleId
                                            LIMIT 1];
        String joJSONString = JSON.serializePretty(stgJobOrder);
        return stgJobOrder;
    }

    //INSERT
    @HttpPost
    global static String createJobOrder(){
        //StagingJobOrder__c jobOrder = [SELECT Id FROM StagingJobOrder__c LIMIT 1];
        RestRequest request = RestContext.request;
        String reqString = request.requestBody.toString();
        System.debug('reqString' + reqString);
        String response;
        try{
            VmsJobOrderHelper vmsJo = (VmsJobOrderHelper) JSON.deserialize(reqString, VmsJobOrderHelper.class);
            System.debug('vmsJo>> ' + vmsJo);
            response = VmsJobOrderRequestHandler.doInsertStagingJobOrder(vmsJo, reqString); 
        } catch(Exception ex) {
            return response = ex.getMessage();
        } finally {
            //Insert into Integration error log if the response is not an instance of Id
            if(!(response InstanceOf Id)){
                insert new Integration_Error_Log__c(End_Point__c = URL.getSalesforceBaseUrl().toExternalForm() + '/vms-job-order/'
                                                    ,Payload__c=reqString
                                                    ,CallType__c='Inbound'
                                                    ,Error__c=response);
            }
        }
        return response;
    }
}