Frankbelford/uatv1ba/force-app/main/default/objects/Integration_Error_Log__c/Integration_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Error Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Vms Integration Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClient_Id__c.field-meta.xml
<CustomField>
    <fullName>StgClient_Id__c</fullName>
    <label>StgClient Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClientName__c.field-meta.xml
<CustomField>
    <fullName>StgClientName__c</fullName>
    <label>StgClientName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>StgCreatedDate__c</fullName>
    <label>StgCreatedDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgEndDate__c.field-meta.xml
<CustomField>
    <fullName>StgEndDate__c</fullName>
    <label>StgEndDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgEndTime__c.field-meta.xml
<CustomField>
    <fullName>StgEndTime__c</fullName>
    <label>StgEndTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystem__c</fullName>
    <label>StgFrontOfficeIntegrationSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgHasShifts__c.field-meta.xml
<CustomField>
    <fullName>StgHasShifts__c</fullName>
    <label>StgHasShifts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgJobTitle__c.field-meta.xml
<CustomField>
    <fullName>StgJobTitle__c</fullName>
    <label>StgJobTitle</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgLocationId__c.field-meta.xml
<CustomField>
    <fullName>StgLocationId__c</fullName>
    <label>StgLocationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgLocationName__c.field-meta.xml
<CustomField>
    <fullName>StgLocationName__c</fullName>
    <label>StgLocationName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgQuantity__c.field-meta.xml
<CustomField>
    <fullName>StgQuantity__c</fullName>
    <label>StgQuantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgRequiredStaff__c.field-meta.xml
<CustomField>
    <fullName>StgRequiredStaff__c</fullName>
    <label>StgRequiredStaff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgRoleRequirement__c.field-meta.xml
<CustomField>
    <fullName>StgRoleRequirement__c</fullName>
    <label>StgRoleRequirement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgSourceSystem__c.field-meta.xml
<CustomField>
    <fullName>StgSourceSystem__c</fullName>
    <label>StgSourceSystem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgStartDate__c.field-meta.xml
<CustomField>
    <fullName>StgStartDate__c</fullName>
    <label>StgStartDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgStartTime__c.field-meta.xml
<CustomField>
    <fullName>StgStartTime__c</fullName>
    <label>StgStartTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/StagingShift__c.object-meta.xml
<CustomObject>
    <label>Staging Shift</label>
    <nameField>
        <label>Staging Shift</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/Staging_Job_Order__c.field-meta.xml
<CustomField>
    <fullName>Staging_Job_Order__c</fullName>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Staging Shifts</relationshipLabel>
    <relationshipName>Staging_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgClientID__c.field-meta.xml
<CustomField>
    <fullName>StgClientID__c</fullName>
    <label>StgClientID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgClientName__c.field-meta.xml
<CustomField>
    <fullName>StgClientName__c</fullName>
    <label>StgClientName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgFrontOfficeIntegrationSystemEntity__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystemEntity__c</fullName>
    <label>StgFrontOfficeIntegrationSystemEntity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgJobTitle__c.field-meta.xml
<CustomField>
    <fullName>StgJobTitle__c</fullName>
    <label>StgJobTitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgPlacement__c.field-meta.xml
<CustomField>
    <fullName>StgPlacement__c</fullName>
    <label>StgPlacement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleEndDate__c.field-meta.xml
<CustomField>
    <fullName>StgRoleEndDate__c</fullName>
    <label>StgRoleEndDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgRoleId__c</fullName>
    <label>StgRoleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleStartDate__c.field-meta.xml
<CustomField>
    <fullName>StgRoleStartDate__c</fullName>
    <label>StgRoleStartDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgSector__c.field-meta.xml
<CustomField>
    <fullName>StgSector__c</fullName>
    <label>StgSector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftEndTime__c.field-meta.xml
<CustomField>
    <fullName>StgShiftEndTime__c</fullName>
    <label>StgShiftEndTime</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftId__c.field-meta.xml
<CustomField>
    <fullName>StgShiftId__c</fullName>
    <label>StgShiftId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftStartTime__c.field-meta.xml
<CustomField>
    <fullName>StgShiftStartTime__c</fullName>
    <label>StgShiftStartTime</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftStatus__c.field-meta.xml
<CustomField>
    <fullName>StgShiftStatus__c</fullName>
    <label>StgShiftStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgSourceSystem__c.field-meta.xml
<CustomField>
    <fullName>StgSourceSystem__c</fullName>
    <label>StgSourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>StgUpdatedDate__c</fullName>
    <label>StgUpdatedDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/VmsJobOrderRESTServiceTest.cls
/**
 * Created by mrahman on 2020-11-06.
 */

@IsTest
private class VmsJobOrderRESTServiceTest {
    @TestSetup
    static void setupTestData(){
        insert new Payroll_Swtich__c(Name = 'Stoppayroll', Batch_check__c = false);

        StagingJobOrder__c sjobOrder = TestDataFactory.createStagingJobOrders(1)[0];
        insert sjobOrder;

        StagingShift__c sShift = TestDataFactory.createStagingShifts(sjobOrder, 1)[0];
        insert sShift;
    }

    @IsTest
    static void testGetJobOrderById() {
        StagingJobOrder__c jobOrder = [SELECT Id, Name
                                             ,StgSourceSystem__c
                                             ,StgClientName__c
                                        FROM StagingJobOrder__c LIMIT 1];
        RestRequest request = new RestRequest();
        request.requestURI = 'https//'+URL.getSalesforceBaseUrl().getHost() + '/vms-job-order/' + jobOrder.Id;
        request.httpMethod = 'GET';
        RestContext.request = request;

        StagingJobOrder__c response = VmsJobOrderRESTService.getJobOrderById();
        System.assert(response != null, 'Response should not be null');
    }

    @IsTest
    static void testCreateJobOrder(){
        VmsJobOrderHelper j = getRequestJO();
        String reqBody = JSON.serializePretty(j);

        RestRequest request = new RestRequest();
        request.requestURI = 'https//'+URL.getSalesforceBaseUrl().getHost() + '/vms-job-order/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(reqBody);
        RestContext.request = request;

        String response = VmsJobOrderRESTService.createJobOrder();
        System.assert(String.isNotBlank(response), 'Response is null/blank');
    }

    @IsTest
    static void testSubmitInvalidJobOrder(){
        VmsJobOrderHelper j =  new VmsJobOrderHelper();//getRequestJO();
        //j.StgRoleId = null;
        String reqBody = JSON.serializePretty(j);

        RestRequest request = new RestRequest();
        request.requestURI = 'https//'+URL.getSalesforceBaseUrl().getHost() + '/vms-job-order/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(reqBody);
        RestContext.request = request;

        String response = VmsJobOrderRESTService.createJobOrder();
        System.debug('response >> ' + response);
        List<Integration_Error_Log__c> iels = [SELECT Id, Name FROM Integration_Error_Log__c];
        System.debug('Error log >>> ' +iels);
        System.assert(iels.size()>0, 'Expected log an error');
        System.assert(String.isNotBlank(response), 'Response is null/blank');
    }

    private static VmsJobOrderHelper getRequestJO(){
        StagingJobOrder__c sj = [SELECT Id, Name,
                StgSourceSystem__c
                ,StgClientName__c
                ,StgClient_Id__c
                ,StgRoleId__c
                ,StgJobTitle__c
                ,StgQuantity__c
                ,StgStartDate__c
                ,StgEndDate__c
                ,StgStartTime__c
                ,StgEndTime__c
                ,StgLocationId__c
                ,StgLocationName__c
                ,StgHasShifts__c
                ,(SELECT Id, Name,
                StgSourceSystem__c
                ,StgClientName__c
                ,StgClientID__c
                ,StgRoleId__c
                ,StgShiftId__c
                ,StgJobTitle__c
                ,StgQuantity__c
                ,StgRoleStartDate__c
                ,StgRoleEndDate__c
                ,StgShiftStartTime__c
                ,StgShiftEndTime__c
                ,StgLocationId__c
                ,StgLocationName__c
                ,StgCreatedDate__c
                ,StgUpdatedDate__c
                ,StgShiftStatus__c
                ,StgFrontOfficeIntegrationSystem__c
                ,StgFrontOfficeIntegrationSystemEntity__c
                ,StgSector__c
                ,StgPlacement__c
        FROM Staging_Shifts__r)
                ,StgCreatedDate__c
                ,StgUpdatedDate__c
                ,StgFrontOfficeIntegrationSystem__c
                ,StgRoleRequirement__c
                ,StgRequiredStaff__c
        FROM StagingJobOrder__c
        LIMIT 1];
        VmsJobOrderHelper.VmsShift s = new VmsJobOrderHelper.VmsShift();
        s.StgSourceSystem=sj.StgSourceSystem__c;
        s.StgClientName=sj.StgClientName__c;
        s.StgClientID=sj.StgClient_Id__c;
        s.StgRoleId=sj.StgRoleId__c;
        s.StgShiftId=sj.Staging_Shifts__r[0].StgShiftId__c;
        s.StgJobTitle=sj.StgJobTitle__c;
        s.StgQuantity=sj.StgQuantity__c;
        s.StgRoleStartDate=sj.Staging_Shifts__r[0].StgRoleStartDate__c;
        s.StgRoleEndDate=sj.Staging_Shifts__r[0].StgRoleEndDate__c;
        s.StgShiftStartTime=sj.Staging_Shifts__r[0].StgShiftStartTime__c;
        s.StgShiftEndTime=sj.Staging_Shifts__r[0].StgShiftEndTime__c;
        s.StgLocationId=sj.StgLocationId__c;
        s.StgLocationName=sj.StgLocationName__c;
        s.StgCreatedDate=sj.StgCreatedDate__c;
        s.StgUpdatedDate=sj.StgUpdatedDate__c;
        s.StgShiftStatus=sj.Staging_Shifts__r[0].StgShiftStatus__c;
        s.StgFrontOfficeIntegrationSystem=sj.StgFrontOfficeIntegrationSystem__c;
        s.StgFrontOfficeIntegrationSystemEntity=sj.Staging_Shifts__r[0].StgFrontOfficeIntegrationSystemEntity__c;
        s.StgSector=sj.Staging_Shifts__r[0].StgSector__c;
        s.StgPlacement=sj.Staging_Shifts__r[0].StgPlacement__c;

        VmsJobOrderHelper j = new VmsJobOrderHelper();
        j.StgSourceSystem = sj.StgSourceSystem__c;
        j.StgClientName = sj.StgClientName__c;
        j.StgClientId = sj.StgClient_Id__c;
        j.StgRoleId = sj.StgRoleId__c;
        j.StgJobTitle = sj.StgJobTitle__c;
        j.StgQuantity = sj.StgQuantity__c;
        j.StgStartDate = sj.StgStartDate__c;
        j.StgEndDate = sj.StgEndDate__c;
        j.StgStartTime = sj.StgStartTime__c;
        j.StgEndTime = sj.StgEndTime__c;
        j.StgLocationId = sj.StgLocationId__c;
        j.StgLocationName = sj.StgLocationName__c;
        j.StgHasShifts = sj.StgHasShifts__c;
        j.StgCreatedDate = sj.StgCreatedDate__c;
        j.StgUpdatedDate = sj.StgUpdatedDate__c;
        j.StgFrontOfficeIntegrationSystem = sj.StgFrontOfficeIntegrationSystem__c;
        j.StgRoleRequirement = sj.StgRoleRequirement__c;
        j.StgRequiredStaff = sj.StgRequiredStaff__c;
        j.stgShifts.add(s);
        return j;
    }
}