Frankbelford/uatv1ba/force-app/main/default/objects/Integration_Error_Log__c/Integration_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Error Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Vms Integration Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Integration_Error_Log__c/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>CallType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Integration_Error_Log__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>JSON or SOAP Payload</description>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/SnapLogic_Endpoint__mdt/SnapLogic_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>List of partial endpoint URL for Evo VMS Integration solution</description>
    <label>SnapLogic Endpoint</label>
    <pluralLabel>SnapLogic Endpoints</pluralLabel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/SnapLogic_Endpoint__mdt/fields/Endpoint_Name__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Name__c</fullName>
    <label>Endpoint Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/SnapLogic_Endpoint__mdt/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/StagingJobApplication__c.object-meta.xml
<CustomObject>
    <label>Third Party Job Application</label>
    <nameField>
        <displayFormat>VMS-A-{YYYY}{MM}-{0}</displayFormat>
        <label>Staging Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>External ID such as the application ID in Evolution (Candidate Role ID)</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/StagingJobOrder__c.field-meta.xml
<CustomField>
    <fullName>StagingJobOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Third_Party_Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgApplicationStatus__c.field-meta.xml
<CustomField>
    <fullName>stgApplicationStatus__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submission Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSPlacementId__c.field-meta.xml
<CustomField>
    <fullName>stgSPlacementId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>S-Placement</label>
    <referenceTo>sirenum__Placement__c</referenceTo>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSPlacementSubmitted__c.field-meta.xml
<CustomField>
    <fullName>stgSPlacementSubmitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>S-Placement Submitted</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSubmissionDatetime__c.field-meta.xml
<CustomField>
    <fullName>stgSubmissionDatetime__c</fullName>
    <label>Submission Date Time</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSubmissionError__c.field-meta.xml
<CustomField>
    <fullName>stgSubmissionError__c</fullName>
    <description>API call error log</description>
    <label>stgSubmissionError</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSubmissionStatus__c.field-meta.xml
<CustomField>
    <fullName>stgSubmissionStatus__c</fullName>
    <description>API submission status</description>
    <label>Submission Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>S-Placement Submitted</fullName>
            </value>
            <value>
                <fullName>Application Submission Failed</fullName>
            </value>
            <value>
                <fullName>S-Placement Submission Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSubmittedJSON__c.field-meta.xml
<CustomField>
    <fullName>stgSubmittedJSON__c</fullName>
    <label>stgSubmittedJSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgMoveOrCopy__c.field-meta.xml
<CustomField>
    <fullName>StgMoveOrCopy__c</fullName>
    <label>Stg Move Or Copy</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgSourceSystem__c.field-meta.xml
<CustomField>
    <fullName>StgSourceSystem__c</fullName>
    <label>StgSourceSystem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/VmsSubmitCandidate.cls
public class VmsSubmitCandidate {
    private static String endPointString;
    private static String token;
    private static Map<String, String> header = new Map<String, String>{
		'Content-Type' => 'application/json;charset=UTF-8',
		'Authorization' => 'Bearer ' + token
    };
    private static String jsonReqBody;
    private static StagingJobApplication__c stgJA;
    private static Map<Id, StagingJobApplication__c> stgApps = new Map<Id, StagingJobApplication__c>();
    private static List<Integration_Error_Log__c> errorLogs = new List<Integration_Error_Log__c>();
    private static Boolean isSPlacement = false;
    private static Boolean isSandbox = [SELECT IsSandbox FROM Organization].IsSandbox;
    private static Map<String, String> theSourceSystems = new Map<String, String> {
        isSandbox ? Label.VMS_Lunar_Sandbox_Database_Name : Label.VMS_Lunar_Production_Database_Name => 'Lunar',
        isSandbox ? Label.VMS_Capita_Sandbox_Database_Name : Label.VMS_Capita_Production_Database_Name => 'Capita'
    };
    private static Map<String, String> theNamedCredentials = new Map<String, String> {
        'Lunar' => 'callout:Evo_SnapLogic',
        'Capita' => 'callout:Evo_SnapLogic_Capita'
    };
    private static Map<String, Map<String, String>> theCustomMetadata = new Map<String, Map<String, String>> {
        'Capita' => new Map<String, String> {
            'CopyCandidateCallBackAPI' => 'Capita_CopyCandidateCallBackAPI',
            'CandidateSubmissionAPI' => 'Capita_CandidateSubmissionAPI',
            'PlaceBookingCallBackAPI' => 'Capita_PlaceBookingCallBackAPI'
        },
        'Lunar' => new Map<String, String> {
            'CopyCandidateCallBackAPI' => 'CopyCandidateCallBackAPI',
            'CandidateSubmissionAPI' => 'CandidateSubmissionAPI',
            'PlaceBookingCallBackAPI' => 'PlaceBookingCallBackAPI'
        }
	};

    @future(callout=true)
    public static void doSubmitApplication(List<String> stgJAJSONs) {
        for(String stgJAJSON : stgJAJSONs) {
            stgJA = (StagingJobApplication__c)JSON.deserialize(stgJAJSON, StagingJobApplication__c.class);

            String isCopyMove = stgJA.StagingJobOrder__r.StgMoveOrCopy__c;
			String theTargetSystemName = theSourceSystems.get(stgJA.StagingJobOrder__r.StgSourceSystem__c);
            Map<String, String> theMetadataRecords = theCustomMetadata.get(theTargetSystemName);

            if(stgJA.stgApplicationStatus__c == 'New' && isCopyMove == 'Copy') {
                SnapLogic_Endpoint__mdt ep = getEndpointDetails(theMetadataRecords.get('CopyCandidateCallBackAPI'));
                endPointString = theNamedCredentials.get(theTargetSystemName) + ep.Endpoint_Name__c;
                token = ep.Token__c;
                header.put('Authorization', 'Bearer ' + token);
                if(theTargetSystemName == 'Capita') {
                	VmsCopyMoveCandidateMappingCapita vcmCapita = new VmsCopyMoveCandidateMappingCapita(stgJA);
                	jsonReqBody = JSON.serializePretty(vcmCapita);
                }
                else {
                	VmsCopyMoveCandidateMapping vcmLunar = new VmsCopyMoveCandidateMapping(stgJA);
					jsonReqBody = JSON.serializePretty(vcmLunar);
                }
                handleCallout();
            }
            else if(stgJA.stgApplicationStatus__c == 'New' && String.isBlank(isCopyMove)) {
                SnapLogic_Endpoint__mdt ep = getEndpointDetails(theMetadataRecords.get('CandidateSubmissionAPI'));
                endPointString = theNamedCredentials.get(theTargetSystemName) + ep.Endpoint_Name__c;
                token = ep.Token__c;
                header.put('Authorization', 'Bearer ' + token);
                if(theTargetSystemName == 'Capita') {
                    VmsCandidateMappingCapita vcmCapita = new VmsCandidateMappingCapita(stgJA);
                    jsonReqBody = JSON.serializePretty(vcmCapita);
                }
                else {
                    VmsCandidateMapping vcmLunar = new VmsCandidateMapping(stgJA);
                    jsonReqBody = JSON.serializePretty(vcmLunar);
                }
                handleCallout();
            }
            else if(
                stgJA.stgApplicationStatus__c == 'Accepted' &&
                String.isNotBlank(stgJA.stgSPlacementId__c) &&
				stgJA.stgSPlacementSubmitted__c == false &&
				String.isBlank(isCopyMove)
            ) {
                isSPlacement = true;
                SnapLogic_Endpoint__mdt ep = getEndpointDetails(theMetadataRecords.get('PlaceBookingCallBackAPI'));
                endPointString = theNamedCredentials.get(theTargetSystemName) + ep.Endpoint_Name__c;
                token = ep.Token__c;
                header.put('Authorization', 'Bearer ' + token);
				if(theTargetSystemName == 'Capita') {
                    VmsEvoSPlacementMappingCapita vespmCapita = new VmsEvoSPlacementMappingCapita(stgJA);
                    jsonReqBody = JSON.serializePretty(vespmCapita);
                }
				else {
                    VmsEvoSPlacementMapping vespm = new VmsEvoSPlacementMapping(stgJA);
                    jsonReqBody = JSON.serializePretty(vespm);
                }
                handleCallout();
            }
            else if(stgJA.stgApplicationStatus__c != 'New' && isCopyMove == 'Move') {
                // Don't need to send any data for this at present.
            }
            else {
                String msg = 'WARNING: >>> INTEGRATION CALL WAS NOT MADE DUE THE REQUEST REQUIREMENT';
                stgJA.stgSubmissionError__c = msg;
                stgJA.stgSubmissionDatetime__c = Datetime.now();
                stgApps.put(stgJA.Id, stgJA);
                errorLogs.add(new Integration_Error_Log__c(
                    End_Point__c = endPointString,
                    Payload__c = jsonReqBody,
                    CallType__c = 'Outbound',
                    Error__c = 'Response Status:: ' + msg
                ));
            }
        }

        if(stgApps.size() > 0) {
            update stgApps.values();
        }

        if(errorLogs.size() > 0) {
            insert errorLogs;
        }
    }

    private static SnapLogic_Endpoint__mdt getEndpointDetails(String epName) {
        SnapLogic_Endpoint__mdt ep = [SELECT DeveloperName, MasterLabel, Label, Endpoint_Name__c, Token__c
									  FROM SnapLogic_Endpoint__mdt
                                      WHERE DeveloperName = :epName];
        system.debug('SnapLogic_Endpoint__mdt======================================' +ep);
		return ep;
    }

    private static void handleCallout() {
        HttpResponse response = null;
        try {
			response = RestCalloutUtil.MakeCallout(endPointString, 'POST', jsonReqBody, header);

            VmsSnapLogicResParser.Response parsedResp = VmsSnapLogicResParser.parseResponse(response.getBody());
            if(response.getStatusCode() == 200 && parsedResp.status.uncapitalize() == 'success') {
                stgJA.stgSubmittedJSON__c = jsonReqBody;
                stgJA.stgSubmissionDatetime__c = Datetime.now();
                stgJA.stgApplicationStatus__c = isSPlacement? stgJA.stgApplicationStatus__c : 'Submitted';
                stgJA.stgSubmissionStatus__c = isSPlacement? 'S-Placement Submitted' : 'Application Submitted';
                stgJA.stgSPlacementSubmitted__c = isSPlacement;
                stgJA.External_ID__c = parsedResp.VmsCandidateRoleId;
                stgApps.put(stgJA.Id, stgJA);
            }
            else {
                errorLogs.add(new Integration_Error_Log__c(
                    End_Point__c = endPointString,
                    Payload__c = jsonReqBody,
                    CallType__c = 'Outbound',
                    Error__c = 'Response Status:: ' + response.getStatus() + '\n' + response.getBody()
                ));
    
                stgJA.stgSubmittedJSON__c = jsonReqBody;
                stgJA.stgSubmissionDatetime__c = Datetime.now();
                stgJA.stgApplicationStatus__c = isSPlacement? stgJA.stgApplicationStatus__c : 'Submission Failed';
                stgJA.stgSubmissionStatus__c = isSPlacement? 'S-Placement Submission Failed' : 'Application Submission Failed';
                stgJA.stgSubmissionError__c = response.getStatus() + '\n' + response.getBody();
                stgApps.put(stgJA.Id, stgJA);
            }
        }
        catch(Exception theException) {
			String errorMessage = (theException.getMessage() == 'No content to map to Object due to end of input') ? 'No response received.' : theException.getMessage();
            errorLogs.add(new Integration_Error_Log__c(
                End_Point__c = endPointString,
                Payload__c = jsonReqBody,
                CallType__c = 'Outbound',
				Error__c = 'Error - ' + errorMessage + '\n\n' + 'Response - ' + response.getBody()
            ));
        }
    }

}