Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/IP_InvoiceQuery__c.object-meta.xml
<CustomObject>
    <label>Invoice Query</label>
    <nameField>
        <displayFormat>INQ-{000000}</displayFormat>
        <label>Invoice Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_Account__c.field-meta.xml
<CustomField>
    <fullName>IP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Queries</relationshipLabel>
    <relationshipName>Invoice_Queries</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_BranchCode__c.field-meta.xml
<CustomField>
    <fullName>IP_BranchCode__c</fullName>
    <label>Branch Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_QueryDescription__c.field-meta.xml
<CustomField>
    <fullName>IP_QueryDescription__c</fullName>
    <label>Query Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_QueryValue__c.field-meta.xml
<CustomField>
    <fullName>IP_QueryValue__c</fullName>
    <label>Query Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/Test_Invoicequeryupdatecontrller.cls
@isTest
public class Test_Invoicequeryupdatecontrller {

    static testMethod void creditcheck1(){
     RecordType accountRec1 = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account']; 
        
        Account acc1 = new Account(Name='Account name 1',RecordTypeId=accountRec1.id);
        insert acc1;
        
       Group testGroup = new Group(Name='1062 - BAL Newbury', Type='Queue');
        insert testGroup;
      /*  System.runAs(new User(Id=UserInfo.getUserId()))
        {
            QueueSObject testQueue = new QueueSObject(QueueID = testGroup.id, SobjectType = 'Case');
            insert testQueue;
        }*/
      //  List<IP_InvoiceQuery__c> invlist = new List<IP_InvoiceQuery__c>();
        IP_InvoiceQuery__c inv = new IP_InvoiceQuery__c();
        inv.IP_Account__c = acc1.id;
        inv.IP_QueryValue__c = 100;
        inv.IP_AccountNumber__c = '1417261';
        inv.IP_BranchCode__c = '1062';
        inv.IP_InvoiceNumber__c = '62332812';
        inv.IP_QueryDescription__c = 'test';
        //invlist.add(inv);
        insert inv;
        
       // insert invlist;
        
        
        Test.StartTest();
        Invoicequeryupdatecontrller.getInvoicedetails(inv.id);
        Invoicequeryupdatecontrller.getInvoicerecorddetails(inv.id);
        Invoicequeryupdatecontrller.Updaterecordandsendemail('6374283','tesaqywd',inv.id);
        Test.stopTest();
      }
}