Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/APTS_AllCost__c.object-meta.xml
<CustomObject>
    <description>Custom object to consolidate all contractual costs and material costs from SAP table for quoting</description>
    <label>All Cost</label>
    <nameField>
        <displayFormat>CST-{00000}</displayFormat>
        <label>Cost ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_Cost__c.field-meta.xml
<CustomField>
    <fullName>APTS_Cost__c</fullName>
    <description>Contractual cost or material cost value from SAP</description>
    <inlineHelpText>Contractual cost or material cost value from SAP</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_Invalid__c.field-meta.xml
<CustomField>
    <fullName>APTS_Invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if setup data is in error</description>
    <inlineHelpText>True if setup data is in error</inlineHelpText>
    <label>Invalid</label>
    <type>Checkbox</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_Material_Number__c.field-meta.xml
<CustomField>
    <fullName>APTS_Material_Number__c</fullName>
    <description>Material Number of the Product sourced from SAP</description>
    <inlineHelpText>Material Number of the Product sourced from SAP</inlineHelpText>
    <label>Material Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_PriceList__c.field-meta.xml
<CustomField>
    <fullName>APTS_PriceList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the Price List object to capture price list</description>
    <inlineHelpText>Reference to the Price List object to capture price list</inlineHelpText>
    <label>Price List</label>
    <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
    <relationshipLabel>All Costs</relationshipLabel>
    <relationshipName>All_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>APTS_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the Product object to capture Product record</description>
    <inlineHelpText>Reference to the Product object to capture Product record</inlineHelpText>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>All Costs</relationshipLabel>
    <relationshipName>All_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_Sold_To_Account__c.field-meta.xml
<CustomField>
    <fullName>APTS_Sold_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the Account object to capture Sold-To</description>
    <inlineHelpText>Reference to the Account object to capture Sold-To</inlineHelpText>
    <label>Sold-To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>All Costs</relationshipLabel>
    <relationshipName>All_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_Valid_From_Date__c.field-meta.xml
<CustomField>
    <fullName>APTS_Valid_From_Date__c</fullName>
    <description>Valid From Date for the Contractual/Material Cost</description>
    <inlineHelpText>Valid From Date for the Contractual/Material Cost</inlineHelpText>
    <label>Valid From Date</label>
    <type>Date</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/APTS_AllCost__c/fields/APTS_Valid_Until_Date__c.field-meta.xml
<CustomField>
    <fullName>APTS_Valid_Until_Date__c</fullName>
    <description>Valid Until Date for the Contractual/Material Cost</description>
    <inlineHelpText>Valid Until Date for the Contractual/Material Cost</inlineHelpText>
    <label>Valid Until Date</label>
    <type>Date</type>
</CustomField>

DFfullcopybackup/force-app/main/default/classes/CustomCostHelperTest.cls
@isTest
public class CustomCostHelperTest {
  
    @isTest
    public static void testMethod1(){
        Account acc = Testutility.createAccount();
        insert acc;
        
        Account acc2 = Testutility.createAccount();
        acc2.Name = 'test 2';
        acc2.ParentId = acc.Id;
        insert acc2;
        
        Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c();
        pricelist.Name =  'Standard USD PriceList';
        insert priceList;
        
        Product2 prod = Testutility.createProduct();
        prod.APTS_Material_Num__c = '01A1A84040a';
        
        insert prod;
        
        Apttus_Proposal__Proposal__c testProposal = Testutility.createProposal(acc.Id);
        insert testProposal;
        
        Apttus_Config2__ProductConfiguration__c prodConfig = Testutility.createProductConfig(acc.Id, testProposal.Id);
        insert prodConfig;        
        List<Apttus_Config2__LineItem__c> lineItemList = new List<Apttus_Config2__LineItem__c>();
        Apttus_Config2__LineItem__c lineItem = Testutility.createLineItem(prodConfig.Id, prod.Id);
        lineItem.Apttus_Config2__PriceListId__c = priceList.Id;
        lineItem.Apttus_Config2__ShipToAccountId__c = acc2.Id;
        lineItem.APTS_Material_Num__c = '01A1A84040';
        insert lineItem;
        
        Apttus_Config2__LineItem__c lineItem2 = Testutility.createLineItem(prodConfig.Id, prod.Id);
        lineItem2.Apttus_Config2__PriceListId__c = priceList.Id;
        lineItem2.Apttus_Config2__ShipToAccountId__c = acc2.Id;
        lineItem2.APTS_Material_Num__c = 'RR282';
        insert lineItem2;
        
        lineItemList.add(lineItem);
        lineItemList.add(lineItem2);
        
        APTS_AllCost__c allCost = new APTS_AllCost__c();
        allCost.APTS_Material_Number__c = lineItem.APTS_Material_Num__c;
        allCost.APTS_Valid_From_Date__c = System.today() - 7;
        allCost.APTS_Valid_Until_Date__c = System.today() + 7;
        allCost.APTS_PriceList__c = lineItem.Apttus_Config2__PriceListId__c;
        allCost.APTS_Invalid__c = False;
        allCost.APTS_Product_Name__c  = prod.Id;
        allCost.APTS_Cost__c = 100;
        insert allCost;
        
        APTS_AllCost__c allCost2 = new APTS_AllCost__c();
        allCost2.APTS_Material_Number__c = lineItem2.APTS_Material_Num__c;
        allCost2.APTS_Valid_From_Date__c = System.today() - 7;
        allCost2.APTS_Valid_Until_Date__c = System.today() + 7;
        allCost2.APTS_Sold_To_Account__c = acc2.id;
        allCost2.APTS_PriceList__c = lineItem2.Apttus_Config2__PriceListId__c;
        allCost2.APTS_Invalid__c = False;
        allCost2.APTS_Product_Name__c  = prod.Id;
        allCost2.APTS_Cost__c = 100;
        insert allCost2;
        
        list<APTS_AllCost__c> allCostlst = new list<APTS_AllCost__c>();
        allCostlst.add(allCost);
        allCostlst.add(allCost2);
        CustomCostHelper helperTest = new CustomCostHelper();
        
        helperTest.beginToPopulateCostOnLineItems(lineItemList,allCostlst);
        helperTest.populateCostOnLineItems(lineItemList);
    }
}