Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/AddOrInsertRecordTest.cls
@IsTest
public class AddOrInsertRecordTest {

    @IsTest
    static void testAddOrInsertRecord() {
        
        Payroll_Swtich__c ps = new Payroll_Swtich__c();
        ps.Batch_check__c = true;
        ps.Name = 'Stoppayroll';
        insert ps;
        
        // Test the AddOrInsertRecord method here
        // Example: Calling the method with different parameters and verifying the results
		RecordType accountRec1 = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account']; 
          RecordType maincondRec = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'Contact'];
       
        Account acc1 = new Account(Name='Capita',RecordTypeId=accountRec1.id);
          insert acc1;
          Contact maincon = new Contact(RecordTypeId=maincondRec.id,FirstName='Test',LastName= 'Main COntact', AccountID=acc1.id);
          insert maincon; 
        List<SObject> inputCollection = new List<SObject>();
        inputCollection.add(maincon);

        AddOrInsertRecord.Requests request = new AddOrInsertRecord.Requests();
        request.inputCollection = inputCollection;
        request.inputRecord = maincon;
        request.index = 0;

        List<AddOrInsertRecord.Results> results = AddOrInsertRecord.addOrInsertRecord(new List<AddOrInsertRecord.Requests>{request});

        System.assertEquals(2, results[0].outputCollection.size(), 'The output collection should have two records.');
    }
}