Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <label>Initials</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CandidateIDlegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDlegacy__c</fullName>
    <description>this is used for candidate that are being migrated from other system but their original IDs must be preserved</description>
    <externalId>true</externalId>
    <inlineHelpText>IF a candidate must still be reference by an original ID (for payroll) used this field</inlineHelpText>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CategoryOfWork__c.field-meta.xml
<CustomField>
    <fullName>IP_CategoryOfWork__c</fullName>
    <description>Which business areas does the person work in</description>
    <inlineHelpText>Which business areas does the person work in</inlineHelpText>
    <label>Category of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP PayFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>Last Date Worked</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Candidate Requested P45?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/PayrollLeaver__c.field-meta.xml
<CustomField>
    <fullName>PayrollLeaver__c</fullName>
    <label>Payroll Leaver</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BuildingSocietyNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNumber__c</fullName>
    <label>Building Society Roll No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine1__c</fullName>
    <description>for recording the business address for the candidate, LTD, umbrella, etc. only is required</description>
    <label>Business Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine2__c</fullName>
    <label>Business Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressPostcode__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressPostcode__c</fullName>
    <label>Business Address Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressTown__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressTown__c</fullName>
    <label>Business Address Town</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyName__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyName__c</fullName>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <label>Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_VATNumber__c</fullName>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>P45 Emailed Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leaver?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/Umbrella.recordType-meta.xml
<RecordType>
    <fullName>Umbrella</fullName>
    <active>true</active>
    <label>Umbrella</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/PayProfileTrigger_Test.cls
@istest
public class PayProfileTrigger_Test {

    public static testmethod void CreatePayrofile1(){
 RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Candidate']; 

        Account account1 = new Account(Name='Candidates',RecordTypeId=accountRec.id);
        insert account1;

        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = false);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c = true);

        RecordType condRec = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'Candidate'];

        Contact con = new Contact(AccountID = account1.id, 
            RecordTypeId=condRec.id,
            FirstName ='ABC',
            Salutation ='Mr',
            MailingCity='ggn',
            MailingCountry='india',
            MailingPostalCode='110092',
            MailingState='Haryana',
            LastName ='XYZ',  
            sirenum__National_Insurance__c='AA323232A', 
            IP_CandidateIDlegacy__c='test123',
            MailingStreet='abc',
            P45_Requested__c=true,
            PayrollLeaver__c=null,
            Title = 'TestLastName1',
            Initials__c = 'TestLastName1',
            Birthdate = Date.valueOf('1992-02-20'),
            Phone = '9879879877',
            EEO_Gender__c = 'M',
            // P45_Date_by_Head_Office__c= System.today(),
            IP_CategoryOfWork__c='Catering' );

        insert con;
        
        id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('PAYE').getRecordTypeId();
        RecordType rec = [Select id,Name from RecordType where id =: payRTId];

        IP_PayProfile__c payprofile = new IP_PayProfile__c();
        payprofile.RecordTypeId = payRTId;
        payprofile.IP_Candidate__c = con.id;
        payprofile.IP_CompanyName__c='sfdc';
        payprofile.IP_Status__c = 'Active'; 
        payprofile.IP_CompanyRegNo__c  = 'ad123456';
        payprofile.IP_VATNumber__c     = '123456789';
        payprofile.IP_PayrollID__c  = 'testpay1';
        payprofile.IP_VATRegistered__c=true;
        payprofile.IP_OkToSupply__c=1;
        payprofile.IP_BuildingSocietyNumber__c='23123';
        payprofile.IP_BusinessAddressLine1__c='test address 1';
        payprofile.IP_BusinessAddressLine2__c='test address 2';
        payprofile.IP_BusinessAddressTown__c='town city';
        payprofile.IP_BusinessAddressPostcode__c='12345678';
        payprofile.IP_PayFrequency__c='Weekly';
        payprofile.IP_PaymentType__c='BACS';
        payprofile.IP_BankAccountName__c = 'testname';
        payprofile.IP_AccountNumber__c = '98958987';
        payprofile.IP_SortCode__c = '887788';
        //payprofile.IP_PassToTempest__c=true;
        insert payprofile;
        
        Test.startTest();

        Test.setCurrentPageReference(new PageReference('Page.PayeandUmbPage')); 
        System.currentPageReference().getParameters().put('recid', payRTId);
        System.currentPageReference().getParameters().put('conID', con.id);     
        ApexPages.StandardController sc = new ApexPages.StandardController(payprofile);
        createpayumbpayprofile  permgenerate = new createpayumbpayprofile (sc);
        // List<SelectOption> selectedrecordtype=permgenerate.allrecordtype;
        permgenerate.recordTypeName = rec.Name;
        permgenerate.saveandredirect();
        permgenerate.cancelredirect();   
        permgenerate.saveandredirectnewpage();
        Test.stopTest();
    }
    
    public static testmethod void CreatePayrofile2(){
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Candidate']; 

        Account account1 = new Account(Name='Candidates',RecordTypeId=accountRec.id);
        insert account1;

         insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = false);
         insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c = true);

        RecordType condRec = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'Candidate'];
        

        Contact con = new Contact(AccountID = account1.id, 
            RecordTypeId=condRec.id,
            FirstName ='ABC',
            Salutation ='Mr',
            MailingCity='ggn',
            MailingCountry='india',
            MailingPostalCode='110092',
            MailingState='Haryana',
            LastName ='XYZ',  
            sirenum__National_Insurance__c='AA323232A', 
            IP_CandidateIDlegacy__c='test123',
            MailingStreet='abc',
            P45_Requested__c=true,
            PayrollLeaver__c=null,
            Title = 'TestLastName1',
            Initials__c = 'TestLastName1',
            Birthdate = Date.valueOf('1992-02-20'),
            Phone = '9879879877',
            EEO_Gender__c = 'M',
            // P45_Date_by_Head_Office__c= System.today(),
            IP_CategoryOfWork__c='Catering' );

        insert con;
        
        id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('PAYE').getRecordTypeId();
        RecordType rec = [Select id,Name from RecordType where id =: payRTId];

        IP_PayProfile__c payprofile = new IP_PayProfile__c();
        payprofile.RecordTypeId = payRTId;

        payprofile.IP_Candidate__c = con.id;
        payprofile.IP_CompanyName__c='sfdc';
        payprofile.IP_Status__c = 'Active'; 
        payprofile.IP_CompanyRegNo__c  = 'ad123456';
        payprofile.IP_VATNumber__c     = '123456789';
        payprofile.IP_PayrollID__c  = 'testpay1';
        payprofile.IP_VATRegistered__c=true;
        payprofile.IP_OkToSupply__c=1;
        payprofile.IP_BuildingSocietyNumber__c='23123';
        payprofile.IP_BusinessAddressLine1__c='test address 1';
        payprofile.IP_BusinessAddressLine2__c='test address 2';
        payprofile.IP_BusinessAddressTown__c='town city';
        payprofile.IP_BusinessAddressPostcode__c='12345678';
        payprofile.IP_PayFrequency__c='Weekly';
        payprofile.IP_PaymentType__c='BACS';
        payprofile.IP_BankAccountName__c = 'testname';
        payprofile.IP_AccountNumber__c = '98958987';
        payprofile.IP_SortCode__c = '887788';
        //payprofile.IP_PassToTempest__c=true;
        insert payprofile;
        
        con.AccountId = account1.id;
        update con;
        
        Test.startTest();

        Test.setCurrentPageReference(new PageReference('Page.PayeandUmbPage')); 
        System.currentPageReference().getParameters().put('conID', con.id);   
        ApexPages.StandardController sc = new ApexPages.StandardController(payprofile);
        createpayumbpayprofile permgenerate = new createpayumbpayprofile (sc);
        permgenerate.recordTypeName = rec.Name;
        // List<SelectOption> selectedrecordtype=permgenerate.allrecordtype;        
        permgenerate.saveandredirect();
        permgenerate.cancelredirect();   
        permgenerate.saveandredirectnewpage();
        Test.stopTest();

    }
    
    public static testmethod void CreatePayrofileUmbrella(){
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Candidate']; 

        Account account1 = new Account(Name='Candidates',RecordTypeId=accountRec.id);
        insert account1;

         insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = false);
         insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c = true);

        RecordType condRec = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'Candidate'];
        

        Contact con = new Contact(AccountID = account1.id, 
            RecordTypeId=condRec.id,
            FirstName ='ABC',
            Salutation ='Mr',
            MailingCity='ggn',
            MailingCountry='india',
            MailingPostalCode='110092',
            MailingState='Haryana',
            LastName ='XYZ',  
            sirenum__National_Insurance__c='AA323232A', 
            IP_CandidateIDlegacy__c='test123',
            MailingStreet='abc',
            P45_Requested__c=true,
            PayrollLeaver__c=null,
            Title = 'TestLastName1',
            Initials__c = 'TestLastName1',
            Birthdate = Date.valueOf('1992-02-20'),
            Phone = '9879879877',
            EEO_Gender__c = 'M',
            // P45_Date_by_Head_Office__c= System.today(),
            IP_CategoryOfWork__c='Catering' );

        insert con;
        
        id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('Umbrella').getRecordTypeId();
        RecordType rec = [Select id,Name from RecordType where id =: payRTId];

        IP_PayProfile__c payprofile = new IP_PayProfile__c();
        payprofile.RecordTypeId = payRTId;

        payprofile.IP_Candidate__c = con.id;
        payprofile.IP_CompanyName__c='sfdc';
        payprofile.IP_Status__c = 'Active'; 
        payprofile.IP_CompanyRegNo__c  = 'ad123456';
        payprofile.IP_VATNumber__c     = '123456789';
        payprofile.IP_PayrollID__c  = 'testpay1';
        payprofile.IP_VATRegistered__c=true;
        payprofile.IP_OkToSupply__c=1;
        payprofile.IP_BuildingSocietyNumber__c='23123';
        payprofile.IP_BusinessAddressLine1__c='test address 1';
        payprofile.IP_BusinessAddressLine2__c='test address 2';
        payprofile.IP_BusinessAddressTown__c='town city';
        payprofile.IP_BusinessAddressPostcode__c='12345678';
        payprofile.IP_PayFrequency__c='Weekly';
        payprofile.IP_PaymentType__c='BACS';
        payprofile.IP_BankAccountName__c = 'testname';
        payprofile.IP_AccountNumber__c = '98958987';
        payprofile.IP_SortCode__c = '887788';
        //payprofile.IP_PassToTempest__c=true;
        insert payprofile;
        
        con.AccountId = account1.id;
        update con;
        
        Test.startTest();

        Test.setCurrentPageReference(new PageReference('Page.PayeandUmbPage')); 
        System.currentPageReference().getParameters().put('conID', con.id);   
        ApexPages.StandardController sc = new ApexPages.StandardController(payprofile);
        createpayumbpayprofile permgenerate = new createpayumbpayprofile (sc);
        permgenerate.recordTypeName = rec.Name;
        // List<SelectOption> selectedrecordtype=permgenerate.allrecordtype;        
        permgenerate.saveandredirect();
        permgenerate.cancelredirect();   
        permgenerate.saveandredirectnewpage();
        Test.setCurrentPageReference(new PageReference('Page.RecordTypeselection'));
        Test.setCurrentPageReference(new PageReference(payprofile.id));
        Test.stopTest();

    }
    
}