Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/IP_Shift_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Shift Template</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/Branch_Address__c.field-meta.xml
<CustomField>
    <fullName>Branch_Address__c</fullName>
    <label>Branch Street</label>
    <type>TextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_City__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_City__c</fullName>
    <label>Branch City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_Country__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_Country__c</fullName>
    <label>Branch Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_County__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_County__c</fullName>
    <label>Branch County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Branch_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>IP_Branch_Postal_Code__c</fullName>
    <label>Branch Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/fields/IP_Site_Name__c.field-meta.xml
<CustomField>
    <fullName>IP_Site_Name__c</fullName>
    <label>Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/CandidateDetails_Test.cls
@isTest
public class CandidateDetails_Test {
public static testmethod void testEmailComp()
{
    Payroll_Swtich__c pay = new Payroll_Swtich__c();
        pay.Name = 'Stoppayroll'; // Match the name expected by the trigger
        pay.Batch_check__c = true;
        insert pay;
          
insert new IP_Shift_Template__c(name = '0000', IP_Branch_City__c = 'test1',IP_Branch_Country__c='count1',IP_Branch_County__c='count2',IP_Branch_Postal_Code__c='1234',Branch_Address__c='street1',Email__c='test@abc.com',Fax__c='123456',Phone__c='54735622',IP_Site_Name__c='Name1');
Account acc =  TestDataFactory.createCandidateAccount(1)[0];
insert acc;
Contact con = TestDataFactory.createCandidate(acc.id,1)[0];
insert con;

sirenum__ProActiveContract__c ct = TestDataFactory.sirenumProActiveContract(acc.id,con.id,1)[0];
insert ct;

sirenum__Rota__c sec = TestDataFactory.createSector(1)[0];
insert sec;

sirenum__Job_Type__c jobcate = TestDataFactory.createJobType(sec.id,1)[0];
insert jobcate;

sirenum__Team__c job = TestDataFactory.createJobRole(ct.id,jobcate.id,1)[0];
insert job;

Profile p = [Select id from Profile where Name = 'System Administrator' LIMIT 1];
User u = TestDataFactory.createUsers(p.id,1)[0];
u.username = 'jhy@123.com';
insert u;

IP_TopazGlobalClientInformation__c tpz = TestDataFactory.createTopaz(1)[0];
insert tpz;

sirenum__site__c site = TestDataFactory.createSites(acc.id,tpz.id,1)[0];
insert site;
    
sirenum__Placement__c ps = TestDataFactory.createSPlacement1(con.id, ct.id, job.id, u.id, 1)[0];
ps.sirenum__site__c = site.id;
insert ps;
    system.debug('$$Placement created'+ps);
    
    sirenum__Shift__c shft = TestDataFactory.createShift(ps.id,site.id,1)[0];
    shft.sirenum__Rota__c = sec.id;
    insert shft;

           Test.startTest();
           Candidatedetails obj = new Candidatedetails();
    obj.record_id=ps.id;
           obj.getplaceid();
           Test.stopTest();

}
}