Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_GDPRWorkedCandidate__c.field-meta.xml
<CustomField>
    <fullName>IP_GDPRWorkedCandidate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field that identifies if a candidate has been worked under the definition for GDPR.</description>
    <label>GDPR Worked Candidate</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LastContactedGDPR__c.field-meta.xml
<CustomField>
    <fullName>IP_LastContactedGDPR__c</fullName>
    <description>System field that identifies the last time a candidate has had a GDPR ‘Meaningful contact’ interaction.</description>
    <label>Last contacted GDPR</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MarkedForDeletion__c.field-meta.xml
<CustomField>
    <fullName>IP_MarkedForDeletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System field that identifies if the candidate needs to be deleted.</description>
    <label>Marked for deletion</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/IP_ImpellamGDPRSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines the parameters for managing data retention within the system.</description>
    <label>RSSGlobal_GDPR_settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGDPRSettings__c/fields/IP_UnworkedCandidateDataRetentionPeriod__c.field-meta.xml
<CustomField>
    <fullName>IP_UnworkedCandidateDataRetentionPeriod__c</fullName>
    <description>Number of days an unworked candidates data is held in the system</description>
    <label>Unworked Candidate Data Retention Period</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/User_Profile_Id__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of frequently used profile Id&apos;s to use in apex or formula</description>
    <label>User Profile Id</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/User_Profile_Id__c/fields/Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Profile_Id__c</fullName>
    <label>Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/GDPRCandidateMarking_Test.cls
@IsTest
public class GDPRCandidateMarking_Test {
  @TestSetup
  static void makeData() {
    IP_ImpellamGDPRSettings__c gdprSettings = new IP_ImpellamGDPRSettings__c(
      name = 'Impellam GDPR settings',
      IP_UnworkedCandidateDataRetentionPeriod__c = 360
    );
    insert gdprSettings;
    insert new Payroll_Swtich__c(Name = 'Stoppayroll', Batch_check__c = true);
    insert new User_Profile_Id__c(
      Name = 'User Portal',
      Profile_Id__c = '00e0Y000000QNyxQAG'
    );

    //Account
    Account candidateAccount = TestDataFactory.createCandidateAccount(1)[0];
    insert candidateAccount;
    //Contact
    Contact candidate = TestDataFactory.createCandidate(
      candidateAccount.Id,
      1
    )[0];

    insert candidate;
    Test.setCreatedDate(candidate.Id, System.now().addDays(-1000));
  }

  @IsTest
  static void UnworkedCandidateToBeDeleted() {
    //!Setup
    Contact candidate = [
      SELECT Id, IP_GDPRWorkedCandidate__c, IP_LastContactedGDPR__c
      FROM Contact
    ];
    candidate.IP_GDPRWorkedCandidate__c = false;
    candidate.IP_LastContactedGDPR__c = null; //System.Today().addDays(-600);
    update candidate;

    Test.startTest();
    //!Execution
    Database.executeBatch(new GDPRCandidateMarking_ScheduledBatch());
    Test.stopTest();
    //!Assertion
    List<Contact> toBeDeleted = [
      SELECT Id, IP_MarkedForDeletion__c
      FROM Contact
    ];

    for (Contact con : toBeDeleted) {
      System.debug(con);
      System.assertEquals(true, con.IP_MarkedForDeletion__c);
    }
  }

  @IsTest
  static void UnworkedCandidateToBeDeletedLastContactedSet() {
    //!Setup
    Contact candidate = [
      SELECT Id, IP_GDPRWorkedCandidate__c, IP_LastContactedGDPR__c
      FROM Contact
    ];
    candidate.IP_GDPRWorkedCandidate__c = false;
    candidate.IP_LastContactedGDPR__c = System.Today().addDays(-600);
    update candidate;

    Test.startTest();
    //!Execution
    Database.executeBatch(new GDPRCandidateMarking_ScheduledBatch());
    Test.stopTest();
    //!Assertion
    List<Contact> toBeDeleted = [
      SELECT Id, IP_MarkedForDeletion__c
      FROM Contact
    ];

    for (Contact con : toBeDeleted) {
      System.debug(con);
      System.assertEquals(true, con.IP_MarkedForDeletion__c);
    }
  }

  @IsTest
  static void UnworkedCandidateToNotBeDeletedLastContactedRecent() {
    //!Setup
    Contact candidate = [
      SELECT Id, IP_GDPRWorkedCandidate__c, IP_LastContactedGDPR__c
      FROM Contact
    ];
    candidate.IP_GDPRWorkedCandidate__c = false;
    candidate.IP_LastContactedGDPR__c = System.Today().addDays(-30);
    update candidate;

    Test.startTest();
    //!Execution
    Database.executeBatch(new GDPRCandidateMarking_ScheduledBatch());
    Test.stopTest();
    //!Assertion
    List<Contact> toBeDeleted = [
      SELECT Id, IP_MarkedForDeletion__c
      FROM Contact
    ];

    for (Contact con : toBeDeleted) {
      System.debug(con);
      System.assertEquals(false, con.IP_MarkedForDeletion__c);
    }
  }

  @IsTest
  static void WorkedCandidateToNotBeDeleted() {
    //!Setup
    Contact candidate = [
      SELECT Id, IP_GDPRWorkedCandidate__c, IP_LastContactedGDPR__c
      FROM Contact
    ];
    candidate.IP_GDPRWorkedCandidate__c = true;
    candidate.IP_LastContactedGDPR__c = null;
    update candidate;

    Test.startTest();
    //!Execution
    Database.executeBatch(new GDPRCandidateMarking_ScheduledBatch());
    Test.stopTest();
    //!Assertion
    List<Contact> toBeDeleted = [
      SELECT Id, IP_MarkedForDeletion__c
      FROM Contact
    ];

    for (Contact con : toBeDeleted) {
      System.debug(con);
      System.assertEquals(false, con.IP_MarkedForDeletion__c);
    }
  }

  @IsTest
  static void TriggerException() {
    //!Setup
    Contact candidate = [
      SELECT Id, IP_GDPRWorkedCandidate__c, IP_LastContactedGDPR__c
      FROM Contact
    ];
    candidate.IP_GDPRWorkedCandidate__c = false;
    candidate.IP_LastContactedGDPR__c = null; //System.Today().addDays(-600);
    update candidate;

    try {
      Test.startTest();
      //!Execution
      GDPRCandidateMarking_ScheduledBatch batch = new GDPRCandidateMarking_ScheduledBatch();
      batch.triggerException = true;
      Database.executeBatch(batch);
      Test.stopTest();
    } catch (Exception e) {
      //!Assertion
      System.assertEquals(e.getMessage(), 'Test exception');
    }
  }
}