Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CandidateIDlegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDlegacy__c</fullName>
    <description>this is used for candidate that are being migrated from other system but their original IDs must be preserved</description>
    <externalId>true</externalId>
    <inlineHelpText>IF a candidate must still be reference by an original ID (for payroll) used this field</inlineHelpText>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_LastPassedToTempest2ndTier__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest2ndTier__c</fullName>
    <label>Last Passed to Tempest (2nd Tier)</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine1__c</fullName>
    <description>This is a system field to populate information into back office</description>
    <label>Mailing Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine2__c</fullName>
    <description>This is a system interface field as salesforce splits up the salesforce field address line information</description>
    <label>Mailing Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_MailingAddressLine3__c.field-meta.xml
<CustomField>
    <fullName>IP_MailingAddressLine3__c</fullName>
    <label>Mailing Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Pass2ndTierToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_Pass2ndTierToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass 2nd tier to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP PayFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_WorkerStartDate__c.field-meta.xml
<CustomField>
    <fullName>IP_WorkerStartDate__c</fullName>
    <description>Date of the workers first paid work for the Agency</description>
    <inlineHelpText>Worker Start Date which is the first day of their first shift.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/smagicinteract__SMSOptOut__c.field-meta.xml
<CustomField>
    <fullName>smagicinteract__SMSOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field contains the value to mark the contact as OptOut.</description>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/WTR_Completed__c.field-meta.xml
<CustomField>
    <fullName>WTR_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Compliance Process Field. Gareth Rogan</description>
    <label>WTR</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/IP_2ndTierCandidate.recordType-meta.xml
<RecordType>
    <fullName>IP_2ndTierCandidate</fullName>
    <active>true</active>
    <label>2nd Tier Candidate</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/Test_ExternalWorkerBatch.cls
@istest
private class Test_ExternalWorkerBatch{

    @isTest
static void testexecute1() 
    {   
        String query = 'Select id from Contact limit 10';
        String GUID = 'ABCD';
        String Field1 = 'IP_Pass2ndTierToTempest__c';
        String Field2 = 'IP_LastPassedToTempest2ndTier__c';  
           
 
        Account acc =  TestDataFactory.create2ndTierSupplierAccount(1)[0];
        insert acc;
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
       RecordType condRecord = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'IP_2ndTierCandidate'];
       Date myDate = Date.newInstance(1980, 2, 17);
       //List<Contact> clist = new List<Contact>();
       //Inserting Payroll records
        insert new Payroll_Swtich__c(Name='Stoppayroll',Batch_check__c=false);
       Contact con = new Contact(Birthdate=myDate,
                                          Email='mm@gmail.com',
                                          FirstName='manish',
                                          LastName='mishra',
                                          IP_MailingAddressLine1__c='c260',
                                          IP_MailingAddressLine2__c='c2',
                                          IP_MailingAddressLine3__c='c3',
                                          IP_CandidateIDlegacy__c='d6tf233',
                                          IP_WorkerStartDate__c=system.today(),
                                          WTR_Completed__c=true,  
                                          MailingCity='ballia', 
                                          MailingCountry='india',
                                          MailingState='up',
                                          MailingPostalCode='277211',
                                          Salutation='Mr',
                                          Sirenum__National_Insurance__c='AA123456A',
                                          IP_PayFrequency__c=342,
                                          RecordTypeId = condRecord.Id,
                                          AccountID = acc.id,      
                                          IP_Pass2ndTierToTempest__c=true,
                                          MailingStreet = 'Mailing Street details',
                                		  smagicinteract__SMSOptOut__c = true,Phone = '+447890789065');
                    
       insert con;       
       
        test.startTest(); 
         ExternalWorkerBatch b = new ExternalWorkerBatch(query,Field1,Field2,GUID);    
        Database.executeBatch(b,1);
         ExternalWorkerEmergencyBatch b1 = new ExternalWorkerEmergencyBatch(query,Field1,Field2,GUID);    
        Database.executeBatch(b1,1);
       
        test.stopTest();
        
       }
    
    
}