Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/StagingJobApplication__c.object-meta.xml
<CustomObject>
    <label>Third Party Job Application</label>
    <nameField>
        <displayFormat>VMS-A-{YYYY}{MM}-{0}</displayFormat>
        <label>Staging Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/StagingJobOrder__c.field-meta.xml
<CustomField>
    <fullName>StagingJobOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Third_Party_Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgApplicationStatus__c.field-meta.xml
<CustomField>
    <fullName>stgApplicationStatus__c</fullName>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submission Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgAtsCandidateIntegrationRef__c.field-meta.xml
<CustomField>
    <fullName>stgAtsCandidateIntegrationRef__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Candidate</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>2nd Tier Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>stgFrontOfficeIntegrationSystem__c</fullName>
    <description>stgFrontOfficeIntegrationSystem in Integration Layer</description>
    <label>Brand</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgPayProfile__c.field-meta.xml
<CustomField>
    <fullName>stgPayProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pay Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.stgAtsCandidateIntegrationRef__c</field>
            <operation>equals</operation>
            <valueField>IP_PayProfile__c.IP_Candidate__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>IP_PayProfile__c</referenceTo>
    <relationshipLabel>Third Party Job Applications</relationshipLabel>
    <relationshipName>Staging_Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgRejectionReason__c.field-meta.xml
<CustomField>
    <fullName>stgRejectionReason__c</fullName>
    <label>Rejection Reason</label>
    <type>TextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSubmissionDatetime__c.field-meta.xml
<CustomField>
    <fullName>stgSubmissionDatetime__c</fullName>
    <label>Submission Date Time</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgSubmittedJSON__c.field-meta.xml
<CustomField>
    <fullName>stgSubmittedJSON__c</fullName>
    <label>stgSubmittedJSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsClientId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsClientId__c</fullName>
    <label>stgVmsClientId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobApplication__c/fields/stgVmsRoleId__c.field-meta.xml
<CustomField>
    <fullName>stgVmsRoleId__c</fullName>
    <label>stgVmsRoleId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClient_Id__c.field-meta.xml
<CustomField>
    <fullName>StgClient_Id__c</fullName>
    <label>StgClient Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystem__c</fullName>
    <label>StgFrontOfficeIntegrationSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/StagingShift__c.object-meta.xml
<CustomObject>
    <label>Staging Shift</label>
    <nameField>
        <label>Staging Shift</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgRoleId__c</fullName>
    <label>StgRoleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/VmsJobApplicationRespTest.cls
/**
 * Created by mrahman on 2020-11-09.
 */

@IsTest
private class VmsJobApplicationRespTest {
    @TestSetup
    static void setupApplicationData(){
        Account candidateAccount = TestDataFactory.createCandidateAccount(1)[0];
        insert candidateAccount;
        TestDataFactory.setupCustomSettings(candidateAccount.Id);
        TestDataFactory.setupUserProfileCustomSettings();

        Contact worker = TestDataFactory.createCandidate(candidateAccount.Id, 1)[0];
        insert worker;
        IP_PayProfile__c ppPAYE = TestDataFactory.createPayProfilePaye(worker.Id, 1)[0];
        insert ppPAYE;
        
        //TestDataFactory.setupShifts();
        StagingJobOrder__c sjobOrder = TestDataFactory.createStagingJobOrders(1)[0];
        insert sjobOrder;
        StagingShift__c sShift = TestDataFactory.createStagingShifts(sjobOrder, 1)[0];
        insert sShift;
        insert new StagingJobApplication__c(stgFrontOfficeIntegrationSystem__c = sjobOrder.StgFrontOfficeIntegrationSystem__c
                                            ,stgVmsClientId__c = sjobOrder.StgClient_Id__c
                                            ,stgVmsRoleId__c = sjobOrder.StgRoleId__c
                                            ,stgPayProfile__c = ppPAYE.Id
                                            ,stgAtsCandidateIntegrationRef__c = worker.Id
                                            ,stgApplicationStatus__c = 'New'
                                            ,stgSubmissionDatetime__c = Datetime.now().addDays(-3));

        //,stgRejectionReason__c = sjobOrder.stgRejectionReason__c
        //,stgSubmittedJSON__c = sjobOrder.stgSubmittedJSON__c
        //,stgPayProfile__c = sjobOrder.stgPayProfile__c);
    }
    @IsTest
    static void testUpdateApplicationStatusSuccess() {
        StagingJobApplication__c sja = [SELECT Id FROM StagingJobApplication__c LIMIT 1];
        RequestBodyStructure rbs = new RequestBodyStructure();
        rbs.stgAtsApplicationId = sja.Id;
        rbs.stgRejectionReason = 'Test rejection';
        rbs.stgApplicationStatus = 'Rejected';
        RestRequest request = new RestRequest();
        request.requestURI = 'https//'+URL.getSalesforceBaseUrl().getHost() + '/vms-job-application-response/';
        request.httpMethod = 'GET';
        System.debug('response \n' + JSON.serializePretty(rbs));
        request.requestBody = Blob.valueOf(JSON.serializePretty(rbs));
        RestContext.request = request;
        String response = VmsJobApplicationResponse.updateApplicationStatus();
        System.assert(String.isNotBlank(response), 'No response received');
    }

    @IsTest
    static void testUpdateApplicationStatusFailure() {
        StagingJobApplication__c sja = [SELECT Id FROM StagingJobApplication__c LIMIT 1];
        RequestBodyStructure rbs = new RequestBodyStructure();
        rbs.stgAtsApplicationId = sja.Id;
        //rbs.stgRejectionReason = 'Test rejection';
        rbs.stgApplicationStatus = 'Accepted';
        RestRequest request = new RestRequest();
        request.requestURI = 'https//'+URL.getSalesforceBaseUrl().getHost() + '/vms-job-application-response/';
        request.httpMethod = 'GET';
        request.requestBody = Blob.valueOf(JSON.serializePretty(rbs));
        RestContext.request = request;
        String response = VmsJobApplicationResponse.updateApplicationStatus();
        System.assert(String.isNotBlank(response), 'No response received');
    }

    class RequestBodyStructure{
        String stgApplicationStatus;
        String stgRejectionReason;
        String stgAtsApplicationId;
    }
}