Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/Batch_header__c.object-meta.xml
<CustomObject>
    <label>Batch Header</label>
    <nameField>
        <displayFormat>Batch-{00000}</displayFormat>
        <label>Batch header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <label>Batch check</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_BatchType__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchType__c</fullName>
    <label>Batch type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Batch_header__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <defaultValue>1</defaultValue>
    <label>IP PayFrequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/IP_BatchLine__c.object-meta.xml
<CustomObject>
    <label>Batch Line</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Batch Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_BatchHeader__c.field-meta.xml
<CustomField>
    <fullName>IP_BatchHeader__c</fullName>
    <label>Batch Header</label>
    <referenceTo>Batch_header__c</referenceTo>
    <relationshipLabel>Batch Lines</relationshipLabel>
    <relationshipName>Batch_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_DateField1__c.field-meta.xml
<CustomField>
    <fullName>IP_DateField1__c</fullName>
    <label>Date Field 1</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Number12d4Field1__c.field-meta.xml
<CustomField>
    <fullName>IP_Number12d4Field1__c</fullName>
    <label>Number 12,4 field 1</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_State__c.field-meta.xml
<CustomField>
    <fullName>IP_State__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField10__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField10__c</fullName>
    <label>Text field 10</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField11__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField11__c</fullName>
    <label>Text Field 11</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField12__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField12__c</fullName>
    <label>Text Field 12</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField13__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField13__c</fullName>
    <label>Text Field 13</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField1__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField1__c</fullName>
    <label>Text Field 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField2__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField2__c</fullName>
    <label>Text Field 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField3__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField3__c</fullName>
    <label>Text Field 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField4__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField4__c</fullName>
    <label>Text Field 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField6__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField6__c</fullName>
    <label>Text Field 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BatchLine__c/fields/IP_TextField7__c.field-meta.xml
<CustomField>
    <fullName>IP_TextField7__c</fullName>
    <label>Text field 7</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BankAccountName__c.field-meta.xml
<CustomField>
    <fullName>IP_BankAccountName__c</fullName>
    <description>This is the name on the account</description>
    <inlineHelpText>This is the name on the account</inlineHelpText>
    <label>Account Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BuildingSocietyNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_BuildingSocietyNumber__c</fullName>
    <label>Building Society Roll No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine1__c</fullName>
    <description>for recording the business address for the candidate, LTD, umbrella, etc. only is required</description>
    <label>Business Address Line 1</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressLine2__c</fullName>
    <label>Business Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressPostcode__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressPostcode__c</fullName>
    <label>Business Address Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_BusinessAddressTown__c.field-meta.xml
<CustomField>
    <fullName>IP_BusinessAddressTown__c</fullName>
    <label>Business Address Town</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyName__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyName__c</fullName>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_OkToSupply__c.field-meta.xml
<CustomField>
    <fullName>IP_OkToSupply__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Ok to Supply</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayFrequency__c.field-meta.xml
<CustomField>
    <fullName>IP_PayFrequency__c</fullName>
    <label>Pay Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_SortCode__c.field-meta.xml
<CustomField>
    <fullName>IP_SortCode__c</fullName>
    <label>Sort Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_VATNumber__c</fullName>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/LTD.recordType-meta.xml
<RecordType>
    <fullName>LTD</fullName>
    <active>true</active>
    <label>LTD</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/Test_ltdcompanyB2FUpdate.cls
@isTest

public class Test_ltdcompanyB2FUpdate{
 @testSetup static void dataSetUp(){   
    Account client1 = TestDataFactory.createClients(1)[0];
    insert client1;
    
    Account candacc = TestDataFactory.createCandidateAccount(1)[0];
    insert candacc;
    
    Account acccon = TestDataFactory.createAccounts(1)[0];
    insert acccon;
    
    insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

    Contact candidateid = TestDataFactory.createCandidate(candacc.id,1)[0];
    insert candidateid;
    
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
    RecordType maincondRec = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'Contact'];
       
    Contact con = new Contact(RecordTypeId=maincondRec.id,FirstName='Test',LastName= 'Main COntact', AccountID=acccon.id);
   insert con;
    id payRTId = Schema.SObjectType.IP_PayProfile__c.getRecordTypeInfosByName().get('LTD').getRecordTypeId();

        IP_PayProfile__c payprofile = new IP_PayProfile__c();
        payprofile.RecordTypeId = payRTId;
        payprofile.IP_Candidate__c = candidateid.id;
        payprofile.IP_CompanyName__c='sfdc';
        payprofile.IP_Status__c = 'Active'; 
        payprofile.IP_CompanyRegNo__c  = 'ad123456';
        payprofile.IP_VATNumber__c     = '123456789';
        payprofile.IP_PayrollID__c  = 'testpay1';
        payprofile.IP_VATRegistered__c=true;
        payprofile.IP_OkToSupply__c=1;
        payprofile.IP_BuildingSocietyNumber__c='23123';
        payprofile.IP_BusinessAddressLine1__c='test address 1';
        payprofile.IP_BusinessAddressLine2__c='test address 2';
        payprofile.IP_BusinessAddressTown__c='town city';
        payprofile.IP_BusinessAddressPostcode__c='12345678';
        payprofile.IP_PayFrequency__c='Weekly';
        payprofile.IP_PaymentType__c='BACS';
        payprofile.IP_BankAccountName__c = 'testname';
        payprofile.IP_AccountNumber__c = '98958987';
        payprofile.IP_SortCode__c = '887788';
        //payprofile.IP_PassToTempest__c=true;
        insert payprofile;
        
        Batch_header__c batchheader = new Batch_header__c();
    batchheader.IP_Status__c = 'Approved';
    batchheader.IP_State__c ='Closed';
    batchheader.IP_BatchType__c ='Ltd Co Pay Profile';
    insert batchheader;


        IP_BatchLine__c batchline2 = new IP_BatchLine__c();
        batchline2.IP_BatchHeader__c = batchheader.id;
        batchline2.IP_Status__c = 'open';
        batchline2.IP_State__c  = 'open';
        batchline2.IP_TextField2__c= 'Company name 1';
        batchline2.IP_TextField3__c= '12345678';
        batchline2.IP_Number12d4Field1__c = 1;
        insert batchline2; // legacycon
  } 
   
   @istest static void BatchHeaderclassmethod1(){
        List<IP_BatchLine__c> listBatchLine = [Select id,IP_Status__c,IP_TextField1__c,IP_TextField2__c,IP_TextField3__c,IP_Number12d4Field1__c from IP_BatchLine__c where IP_Status__c = 'open' limit 1];
        Test.startTest();
        Database.executeBatch(new LTDpayprofileB2FUpdate(),1);
        Test.stopTest();    
    }
    
    @istest static void BatchHeaderclassmethod2(){
        List<IP_BatchLine__c> listBatchLine = [Select id,IP_Status__c,IP_TextField3__c,IP_TextField4__c,IP_TextField1__c,IP_DateField1__c from IP_BatchLine__c where IP_Status__c = 'open' limit 1];
        listBatchLine[0].IP_TextField1__c= 'testpay1';
        listBatchLine[0].IP_TextField10__c = 'Name1';
        listBatchLine[0].IP_TextField11__c =  '12345678';
        listBatchLine[0].IP_TextField12__c = '111222';
        listBatchLine[0].IP_TextField13__c = 'ba1';
        update listBatchLine;
        Test.startTest();
        Database.executeBatch(new LTDpayprofileB2FUpdate(),1);
        Test.stopTest();    
    }
    @istest static void BatchHeaderclassmethod3(){
        List<IP_BatchLine__c> listBatchLine = [Select id,IP_Status__c,IP_TextField3__c,IP_TextField4__c,IP_TextField1__c,IP_DateField1__c from IP_BatchLine__c where IP_Status__c = 'open' limit 1];
        listBatchLine[0].IP_TextField1__c= 'test4263527';
        update listBatchLine;
        Test.startTest();
        Database.executeBatch(new LTDpayprofileB2FUpdate(),1);
        Test.stopTest();    
    }
     @istest static void testltdschedule(){
        
                List<IP_BatchLine__c> listBatchLine = [Select id,IP_Status__c,IP_TextField2__c,IP_TextField3__c,IP_TextField6__c,IP_TextField1__c,IP_TextField7__c from IP_BatchLine__c where IP_Status__c = 'open' limit 1];
        Test.StartTest();
        ScheduleLTDB2Fbatch sh1 = new ScheduleLTDB2Fbatch();
        String sch = '0 30 * * * ?';
        system.schedule('Test ltd', sch, sh1);
        Test.stopTest();
    }
    
    }