Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CategoryOfWork__c.field-meta.xml
<CustomField>
    <fullName>IP_CategoryOfWork__c</fullName>
    <description>Which business areas does the person work in</description>
    <inlineHelpText>Which business areas does the person work in</inlineHelpText>
    <label>Category of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>Last Date Worked</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/DefaultAccounts__c/DefaultAccounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of all Default account Id such as Candidate account Id</description>
    <label>Default Accounts</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <formula>Contact.Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID</label>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/TestResetPasswordController.cls
@isTest
public class TestResetPasswordController{
    @TestSetup
    static void setupTestData(){
        Account candidateAcc = TestDataFactory.createCandidateAccount(1)[0];
        Insert candidateAcc;
        TestDataFactory.setupUserProfileCustomSettings();
        insert new DefaultAccounts__c (Name='Candidates',Account_Id__c=candidateAcc.Id);
    }
    
    
    private static testMethod void ResetPassword1(){
        Account acc = TestDataFactory.createClients(1)[0];
        acc.OwnerId = UserInfo.getUserId();
        insert acc; 

        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
        Contact c = new Contact();
        c.FirstName='Con';
        c.lastName='Test Contact';
        c.IP_CategoryOfWork__c='Industrial';
        c.sirenum__National_Insurance__c='AA123456A';
        c.P45_Date_by_Head_Office__c=system.today();
        c.AccountID=acc.id;
        insert c;
        
        Test.StartTest();
        ResetPasswordController restcontrller = new ResetPasswordController();
        ResetPasswordController.resetPasswordForClient(c.id);
        Test.StopTest();
    }
    
    
    private static testMethod void ResetPassword2(){
        Account acc = TestDataFactory.createClients(1)[0];
        acc.OwnerId = UserInfo.getUserId();
        insert acc;
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
        Contact c = new Contact();
        c.FirstName='Con';
        c.email = 'test123@gmail.com';
        c.lastName='Test Contact';
        c.IP_CategoryOfWork__c='Industrial';
        c.sirenum__National_Insurance__c='AA123456A';
        c.P45_Date_by_Head_Office__c=system.today();
        c.AccountID=acc.id;
        insert c;
        
        Test.StartTest();
        ResetPasswordController restcontrller = new ResetPasswordController();
        ResetPasswordController.resetPasswordForClient(c.id);
        Test.StopTest();
    }
    
    private static testMethod void ResetPassword3(){
        Set<String> customerUserTypes = new Set<String> {'CSPLiteUser', 'PowerPartner', 'PowerCustomerSuccess',   'CustomerSuccess'};
        
        Account acc = TestDataFactory.createClients(1)[0];
        acc.OwnerId = UserInfo.getUserId();
        insert acc;
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

        Contact c = new Contact();
        c.FirstName='Con';
        c.email = 'test123@gmail.com';
        c.lastName='Test Contact';
        c.IP_CategoryOfWork__c='Industrial';
        c.sirenum__National_Insurance__c='AA123456A';
        c.P45_Date_by_Head_Office__c=system.today();
        c.AccountID=acc.id;
        insert c;

        User thisUser = [ select Id,UserType from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
            UserRole ur = new UserRole();
            if(acc.isCustomerPortal)
                ur = [Select Id,Name from UserRole Where Name =:acc.name+' Customer User'];

            Profile p = [select Id,name from Profile where UserType in :customerUserTypes limit 1];

            User newUser = new User(
                UserRoleId = ur.Id,
                profileId = p.id,
                contactId = c.id,
                Username = c.email ,
                street = c.mailingstreet,
                city = c.mailingcity,
                postalcode = c.mailingpostalcode,
                state = c.mailingstate,
                country = c.mailingcountry,
                Alias = c.firstName.substring(0,1)+c.LastName.substring(0,3),
                Email=c.email,
                EmailEncodingKey='UTF-8',
                Firstname=c.firstName,
                Lastname=c.LastName,
                LanguageLocaleKey='en_GB',
                LocaleSidKey='en_GB',
                TimeZoneSidKey='Europe/London'
            );
            Database.insert(newUser);  
        }
        Test.StartTest();
        ResetPasswordController restcontrller = new ResetPasswordController();
        ResetPasswordController.resetPasswordForClient(c.id);
        Test.StopTest();
    }
}