Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay - not enough</fullName>
            </value>
            <value>
                <fullName>Pay - incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable work</fullName>
            </value>
            <value>
                <fullName>Not enough work</fullName>
            </value>
            <value>
                <fullName>Work break</fullName>
            </value>
            <value>
                <fullName>Better opportunity</fullName>
            </value>
            <value>
                <fullName>Worker performance/compliance issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>IP_PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
                <default>true</default>
                <label>BACS</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_VATNumber__c</fullName>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_Leaving1__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leaving1__c</fullName>
    <label>Reason for Leaving</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pay - Not Enough</fullName>
            </value>
            <value>
                <fullName>Pay - Incorrect</fullName>
            </value>
            <value>
                <fullName>Unsuitable Work</fullName>
            </value>
            <value>
                <fullName>Not Enough Work</fullName>
            </value>
            <value>
                <fullName>Work Break</fullName>
            </value>
            <value>
                <fullName>Better Opportunity</fullName>
            </value>
            <value>
                <fullName>Worker Performance/Compliance Issue</fullName>
            </value>
            <value>
                <fullName>Employed by Client</fullName>
            </value>
            <value>
                <fullName>Dismissal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/Reason_for_P45_Internal__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_P45_Internal__c</fullName>
    <label>Reason for P45 (Internal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>Declined work</fullName>
            </value>
            <value>
                <fullName>Other dismissal</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Transferred to LTD</fullName>
            </value>
            <value>
                <fullName>Branch Transfer/BM</fullName>
                <isActive>false</isActive>
                <label>Branch Transfer/BM</label>
            </value>
            <value>
                <fullName>Eight Week Leaver/PE</fullName>
                <isActive>false</isActive>
                <label>Eight Week Leaver/PE</label>
            </value>
            <value>
                <fullName>Payroll Leaver/PL</fullName>
                <isActive>false</isActive>
                <label>Payroll Leaver/PL</label>
            </value>
            <value>
                <fullName>Payroll holiday/PH</fullName>
                <isActive>false</isActive>
                <label>Payroll holiday/PH</label>
            </value>
            <value>
                <fullName>Payroll inactive/PI</fullName>
                <isActive>false</isActive>
                <label>Payroll inactive/PI</label>
            </value>
            <value>
                <fullName>T.U.P.E transfers/TU</fullName>
                <isActive>false</isActive>
                <label>T.U.P.E transfers/TU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Test_RequestP45Ext.cls
@isTest
private class Test_RequestP45Ext {
    
    @isTest 
    static void leaverPositiveCase() 
    {
        //static Account account;
        Account account = TestDataFactory.createCandidateAccount(1)[0]; 
        insert account; 
        
        Contact cont = TestDataFactory.createCandidate(account.id, 1)[0];
        insert cont;
  //  insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
              
         RecordType rt=[SELECT Id FROM RecordType WHERE SobjectType = 'IP_PayProfile__c' AND DeveloperName = 'PAYE'];
       insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        IP_PayProfile__c pay= new IP_PayProfile__c();
        pay.RecordTypeId=rt.id;
        pay.IP_PayrollID__c='Testpayrol';
        pay.IP_Status__c='InActive';
        pay.IP_Candidate__c=cont.Id;
        pay.IP_CompanyRegNo__c='12345678';
        pay.IP_VATRegistered__c=true;
        pay.IP_VATNumber__c='123456789';
        
        
        insert pay;
        
        
        Test.StartTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(cont);
        
        
        RequestP45Ext testAccPlan = new RequestP45Ext(sc);
        RequestP45Ext.wraperpp wr = new RequestP45Ext.wraperpp(pay);
        testAccPlan.ppList = testAccPlan.getpps();
       // testAccPlan.ppList[0].selected=True; 
        testAccPlan.Finish();
        testAccPlan.closeme();
       
      
            
        PageReference pageRef = Page.RequestP45Page;
        pageRef.getParameters().put('id', String.valueOf(cont.Id));
        Test.setCurrentPage(pageRef);
        
        //System.assert(ApexPages.hasMessages(ApexPages.SEVERITY.WARNING));
        
        
        test.stopTest();
        
    }
    
    @isTest 
    static void leaverNegativeCase() 
    {
        //static Account account;
        Account account = TestDataFactory.createCandidateAccount(1)[0]; 
        insert account; 
        
        Contact cont = TestDataFactory.createCandidate(account.id, 1)[0];
        insert cont;
        
        /*RecordType condRec = [Select Id  From RecordType Where sObjectType = 'IP_PayProfile__c' And DeveloperName='PAYE'];
IP_PayProfile__c pp = new IP_PayProfile__c(IP_Candidate__c=cont.id,
IP_PaymentType__c='BACS', 
IP_Status__c='Active', 
RecordTypeId=condRec.id,
Reason_for_P45_Internal__c='',
Reason_for_Leaving1__c=''
); */

 insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
              
         RecordType rt=[SELECT Id FROM RecordType WHERE SobjectType = 'IP_PayProfile__c' AND DeveloperName = 'PAYE'];
       insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        IP_PayProfile__c pay= new IP_PayProfile__c();
        pay.RecordTypeId=rt.id;
        pay.IP_PayrollID__c='Testpayrol';
        pay.IP_Status__c='Active';
        pay.IP_Candidate__c=cont.Id;
        pay.IP_CompanyRegNo__c='12345678';
        pay.IP_VATRegistered__c=true;
        pay.IP_VATNumber__c='123456789';
        
        
        insert pay;
        
        
        Test.StartTest();
          ApexPages.StandardController sc = new ApexPages.StandardController(cont);
        
        
        RequestP45Ext testAccPlan = new RequestP45Ext(sc);
        RequestP45Ext.wraperpp wr = new RequestP45Ext.wraperpp(pay);
        testAccPlan.ppList = testAccPlan.getpps();
        testAccPlan.ppList[0].selected=True; 
        testAccPlan.Finish();
        testAccPlan.closeme();
       
      
            
        PageReference pageRef = Page.RequestP45Page;
        pageRef.getParameters().put('id', String.valueOf(cont.Id));
        Test.setCurrentPage(pageRef);
        /*
        PageReference testPage = new pagereference('/apex/RequestP45Page'); 
        ApexPages.currentPage().getParameters().put( 'id', cont.Id );     
        ApexPages.currentPage().getParameters().put('sx', '1');  
        ApexPages.StandardController sc = new ApexPages.StandardController(cont);   
        RequestP45Ext MyControllerObj = new RequestP45Ext(sc);
        MyControllerObj.getpps();  
        RequestP45Ext.wraperpp wrapper= new RequestP45Ext.wraperpp(pay);
        
        List<RequestP45Ext.wraperpp> tgetpps=  MyControllerObj.getpps(); 
        
        PageReference pageref1 = MyControllerObj.Finish();
        PageReference pageref2 = MyControllerObj.closeme(); 
        */
        //System.assert(ApexPages.hasMessages(ApexPages.SEVERITY.WARNING));
        
        
        test.stopTest();
        
    }
    
}