Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/IP_InvoiceQuery__c.object-meta.xml
<CustomObject>
    <label>Invoice Query</label>
    <nameField>
        <displayFormat>INQ-{000000}</displayFormat>
        <label>Invoice Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_Account__c.field-meta.xml
<CustomField>
    <fullName>IP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Queries</relationshipLabel>
    <relationshipName>Invoice_Queries</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_BranchCode__c.field-meta.xml
<CustomField>
    <fullName>IP_BranchCode__c</fullName>
    <label>Branch Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_QueryDescription__c.field-meta.xml
<CustomField>
    <fullName>IP_QueryDescription__c</fullName>
    <label>Query Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_InvoiceQuery__c/fields/IP_QueryValue__c.field-meta.xml
<CustomField>
    <fullName>IP_QueryValue__c</fullName>
    <label>Query Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_InvoiceDetailsfromTask.cls
@isTest
public class Test_InvoiceDetailsfromTask {

    static testMethod void creditcheck1(){
     RecordType accountRec1 = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Account']; 
    id recID = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Invoice Query').getRecordTypeId();     
        Account acc1 = new Account(Name='Account name 1',RecordTypeId=accountRec1.id);
        insert acc1;
        
   /*    Group testGroup = new Group(Name='1062 - BAL Newbury', Type='Queue');
        insert testGroup;
        System.runAs(new User(Id=UserInfo.getUserId()))
        {
            QueueSObject testQueue = new QueueSObject(QueueID = testGroup.id, SobjectType = 'Task');
            insert testQueue;
        } */
        
        IP_InvoiceQuery__c inv = new IP_InvoiceQuery__c();
        inv.IP_Account__c = acc1.id;
        inv.IP_QueryValue__c = 100;
        inv.IP_AccountNumber__c = '1417261';
        inv.IP_BranchCode__c = '1062';
        inv.IP_InvoiceNumber__c = '62332812';
        inv.IP_QueryDescription__c = 'gwke';
        insert inv;
        
           Task tsk = new Task();
                    tsk.recordtypeid = recID;
                    tsk.Subject = ' - Invoice Query';
                    tsk.WhatID = inv.id;
                    tsk.IP_TaskType__c = 'Invoice Query';
        insert tsk;
      //  Task tsk = [Select id from Task where Whatid =: inv.id];
      
      IP_InvoiceQuery__c inv1 = new IP_InvoiceQuery__c();
        inv1.IP_Account__c = acc1.id;
        inv1.IP_QueryValue__c = 100;
        inv1.IP_AccountNumber__c = '1417261';
        inv1.IP_BranchCode__c = '1062';
        inv1.IP_InvoiceNumber__c = '62332812';
        inv1.IP_QueryDescription__c = 'gwke';
        insert inv1;
        
           Task tsk1 = new Task();
                    tsk1.recordtypeid = recID;
                    tsk1.Subject = '723298 - Invoice Query';
                    tsk1.WhatID = inv1.id;
                    tsk1.IP_TaskType__c = 'Invoice Query';
        insert tsk1;
        
        Test.StartTest();
        InvoiceDetailsfromTask.Taskdetails(tsk.id);
        InvoiceDetailsfromTask.getTaskrecdetails(tsk.id);
        InvoiceDetailsfromTask.Updaterecordandemail('6374283','tesaqywd',tsk.id);
        InvoiceDetailsfromTask.Updateinvoicewithfile('6374283','tesaqywd',tsk1.id,'wetyw','26378hs','text/plain');
        Test.stopTest();
      }
}