Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Case/fields/Subject_Query__c.field-meta.xml
<CustomField>
    <fullName>Subject_Query__c</fullName>
    <label>Subject Query</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pay Query</fullName>
            </value>
            <value>
                <fullName>Shift Query</fullName>
            </value>
            <value>
                <fullName>Holiday Query</fullName>
            </value>
            <value>
                <fullName>General Query</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <formula>TEXT(Owner.IP_TempestDepartment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Cost Code</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/DefaultAccounts__c/DefaultAccounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of all Default account Id such as Candidate account Id</description>
    <label>Default Accounts</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Shift_Template__c/IP_Shift_Template__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Shift Template</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <formula>Contact.Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID</label>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/ContactUsControllerTest.cls
@isTest
public class ContactUsControllerTest{
    @istest 
    static void testMethodOne() {
        //Create portal account owner
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
                                            UserRoleId = portalRole.Id,
                                            ProfileId = profile1.Id,
                                            Username = 'test123'+System.now().millisecond() + 'test12345@test234.com',
                                            Alias = 'batman',
                                            Email='test123'+System.now().millisecond() + 'test12345@test234.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce',
                                            Lastname='Wayne',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            TimeZoneSidKey='America/Chicago',
                                            IP_TempestDepartment__c = '1062'
                                            );
        Database.insert(portalAccountOwner1);
        Contact contact1 ;
        Contact contact2 ;
        Contact contact3 ;
        System.runAs(portalAccountOwner1) {
            //Create account
            Account candidateAcc = TestDataFactory.createCandidateAccount(1)[0];
            Insert candidateAcc;
            TestDataFactory.setupUserProfileCustomSettings();
            TestDataFactory.getEmailTemplate();
            insert new DefaultAccounts__c (Name='Candidates',Account_Id__c=candidateAcc.Id);
            insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
            insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
            insert new IP_Shift_Template__c(name = '1062', Email__c = 'singh.taji26@gmail.com');

            Account portalAccount1 = new Account(
                                                Name = 'TestAccount',
                                                OwnerId = portalAccountOwner1.Id
                                                );
            Database.insert(portalAccount1);

            //Create contact
            contact1 = new Contact(
                                    FirstName = 'Test1',
                                    Lastname = 'McTesty',
                                    AccountId = portalAccount1.Id,
                                    Email = System.now().millisecond() + 'test@test.com'
                                    );
            insert new Payroll_Swtich__c (Name='Stoppayroll',Batch_check__c=false);
            Database.insert(contact1);
            //Create contact
            contact2 = new Contact(
                                    FirstName = 'Test2',
                                    Lastname = 'McTesty2',
                                    AccountId = portalAccount1.Id,
                                    Email = 'test2'+System.now().millisecond() + 'test2@test.com'
                                    );
            Database.insert(contact2);
            //Create contact
            contact3 = new Contact(
                                    FirstName = 'Test3',
                                    Lastname = 'McTesty3',
                                    AccountId = portalAccount1.Id,
                                    Email = 'test3'+System.now().millisecond() + 'test3@test.com'
                                    );
            Database.insert(contact3);
        }
        //Create user
        String userPortal = System.Label.Candidate_Portal_User_Portal;
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name =: userPortal Limit 1];
        User user1 = new User(
                                Username = 'test124'+System.now().millisecond() + 'test12345@test4234.com',
                                ContactId = contact1.Id,
                                ProfileId = portalProfile.Id,
                                Alias = 'test123',
                                Email = 'test124'+System.now().millisecond() + 'test12345@test4234.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        Database.insert(user1);
        Case c = new Case();
        System.runas(User1){
        ContactUsController.getSitesOfLoggedInUser();
        ContactUsController.getUserInformation();
        ContactUsController.getselectOptionsClient(c,'Subject_Query__c');
        ContactUsController.fetchUser();
        ContactUsController.caseInsertSendEmail('General Query', 'Test Mail',null);
        }
       
    }
    
    @istest 
    static void testMethodTwo() {
        //Create portal account owner
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
                                            UserRoleId = portalRole.Id,
                                            ProfileId = profile1.Id,
                                            Username = 'test125'+System.now().millisecond() + 'test12345@test4234.com',
                                            Alias = 'batman',
                                            Email='test125'+System.now().millisecond() + 'test12345@test4234.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce',
                                            Lastname='Wayne',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            TimeZoneSidKey='America/Chicago',
                                            IP_TempestDepartment__c = '1062'
                                            );
        Database.insert(portalAccountOwner1);
        Contact contact1 ;
        Contact contact2 ;
        Contact contact3 ;
        System.runAs(portalAccountOwner1) {
            //Create account
            Account candidateAcc = TestDataFactory.createCandidateAccount(1)[0];
            Insert candidateAcc;
            TestDataFactory.setupUserProfileCustomSettings();
            TestDataFactory.getEmailTemplate();
            insert new DefaultAccounts__c (Name='Candidates',Account_Id__c=candidateAcc.Id);
            insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
            insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
            insert new IP_Shift_Template__c(name = '1062', Email__c = 'singh.taji26@gmail.com');

            Account portalAccount1 = new Account(
                                                    Name = 'TestAccount',
                                                    OwnerId = portalAccountOwner1.Id
                                                    );
            Database.insert(portalAccount1);

            //Create contact
            contact1 = new Contact(
                                    FirstName = 'Test1',
                                    Lastname = 'McTesty',
                                    AccountId = portalAccount1.Id,
                                    Email = System.now().millisecond() + 'test@test.com'
                                    );
            insert new Payroll_Swtich__c (Name='Stoppayroll',Batch_check__c=false);
            Database.insert(contact1);
            //Create contact
            contact2 = new Contact(
                                    FirstName = 'Test2',
                                    Lastname = 'McTesty2',
                                    AccountId = portalAccount1.Id,
                                    Email = 'test2'+System.now().millisecond() + 'test2@test.com'
                                    );
            Database.insert(contact2);
            //Create contact
            contact3 = new Contact(
                                    FirstName = 'Test3',
                                    Lastname = 'McTesty3',
                                    AccountId = portalAccount1.Id,
                                    Email = 'test3'+System.now().millisecond() + 'test3@test.com'
                                    );
            Database.insert(contact3);
        }
        //Create user
        String clientPortalUserProfile = System.Label.Client_Portal_User_Profile;
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name =: clientPortalUserProfile Limit 1];
        User user1 = new User(
                                Username = 'test126'+System.now().millisecond() + 'test12345@test4234.com',
                                ContactId = contact1.Id,
                                ProfileId = portalProfile.Id,
                                Alias = 'test123',
                                Email = 'test126'+System.now().millisecond() + 'test12345@test4234.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        Database.insert(user1);
        Case c = new Case();
        System.runas(User1){
        ContactUsController.getSitesOfLoggedInUser();
        ContactUsController.getUserInformation();
        ContactUsController.getselectOptionsClient(c,'Subject_Query__c');
        ContactUsController.fetchUser();
        ContactUsController.caseInsertSendEmail('General Query', 'Test Mail',null);
        }
    }
}