Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyName__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyName__c</fullName>
    <label>Company Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/LTD.recordType-meta.xml
<RecordType>
    <fullName>LTD</fullName>
    <active>true</active>
    <label>LTD</label>
</RecordType>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/SendemailController.cls
global class SendemailController {


 webservice static void sendEmailFunction(id pid){
 
       
        
        try {
        
        
                IP_PayProfile__c p = [select id ,IP_PayrollID__c,IP_CompanyName__c ,IP_Candidate__c from IP_PayProfile__c where id =: pid];
                
               contact con = [select id,account.name,name,Owner.name from contact where id = : p.IP_Candidate__c ];
                
               // Note note1  = [SELECT Body,Id,ParentId FROM Note where ParentId = : p.id];
                 
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {System.Label.BAPayrollEmail};//{'bluearrowpayroll@impellam.com'};
                mail.setToAddresses(toAddresses);
                mail.setSenderDisplayName('Name');
                mail.setSubject('New Ltd Company');
                  String body = '<p>Dear Payroll, </p>';
                  body += 'Please find attached documentation for the Ltd Company "'+ p.IP_CompanyName__c + '"';
                  body += ', payroll ID "'+ p.IP_PayrollID__c+ '"';
                 // body += '<p> NOTE: '+ note1.Body;  
                  body += '<BR></BR>Kind regards<BR>';
                  body += con.Owner.name;
                  
                  
                  
                  mail.setHtmlBody(body);
               
              // mail.setPlainTextBody('<table><tr><td>Dear Payroll,</td></tr><tr><td> Please find attached documentation for the Ltd Company {!con.account.name}, payroll ID {!p.id}</td></tr></table>');
                //mail.setHtmlBody('<b> This is HTML body </b>' );
                
                List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
                for (Attachment a : [select Name, Body, BodyLength from Attachment where ParentId = :pid]){
                Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                efa.setFileName(a.Name);
                efa.setBody(a.Body);
                fileAttachments.add(efa);
                //mail.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
        }
        
            mail.setFileAttachments(fileAttachments);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            
            } catch(Exception e) {}
            }
        
        
}