Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/Pricing_Matrix__c.object-meta.xml
<CustomObject>
    <label>Pricing Matrix</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Pricing Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Matrix</relationshipLabel>
    <relationshipName>Pricing_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/fields/NET_Price__c.field-meta.xml
<CustomField>
    <fullName>NET_Price__c</fullName>
    <label>NET Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Matrix (Bill To Account)</relationshipLabel>
    <relationshipName>Pricing_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pricing Matrix</relationshipLabel>
    <relationshipName>Pricing_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/fields/SAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number__c</fullName>
    <label>SAP Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/fields/SAP_Account_Number_Child__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Number_Child__c</fullName>
    <label>SAP Account Number Child</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Pricing_Matrix__c/fields/SAP_Material_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Material_Number__c</fullName>
    <label>SAP Material Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DFfullcopybackup/force-app/main/default/classes/PricingMatrixLookupBatchTest.cls
@IsTest
public class PricingMatrixLookupBatchTest {

    @IsTest
    static void testPricingMatrixLookupBatch() {

        /* --------- Accounts --------- */

        Account parentAcc = new Account(
            Name = 'Parent SAP Account',
            AccountNumber = '30T2359'
        );
        insert parentAcc;

        Account childAcc = new Account(
            Name = 'Child SAP Account',
            AccountNumber = '30S0001',
            ParentId =parentAcc.id
        );
        insert childAcc;

        /* --------- Product --------- */

        Product2 prod = new Product2(
            Name = 'Test Product',
            IsActive = true,
            APTS_Material_Num__c = '01K1A4S020'
        );
        insert prod;

        /* --------- Pricing Matrix --------- */

        Pricing_Matrix__c pm = new Pricing_Matrix__c(
            Active__c = true,
            Valid_From__c = System.today().addDays(-10),
            Valid_Till__c = System.today().addYears(10),
            SAP_Account_Number__c = '30T2359',
            SAP_Account_Number_Child__c = '30S0001',
            SAP_Material_Number__c = '01K1A4S020',
            NET_Price__c = 7.06
        );
        insert pm;

        /* --------- Execute Batch --------- */

        Test.startTest();
        Database.executeBatch(new PricingMatrixLookupBatch(), 200);
        Test.stopTest();

        /* --------- Assertions --------- */

        Pricing_Matrix__c result = [
            SELECT Parent_Account__c,
                   Customer_Account__c,
                   Product__c
            FROM Pricing_Matrix__c
            WHERE Id = :pm.Id
        ];

        System.assertEquals(
            parentAcc.Id,
            result.Parent_Account__c,
            'Parent account should be mapped correctly'
        );

        System.assertEquals(
            childAcc.Id,
            result.Customer_Account__c,
            'Customer account should be mapped correctly'
        );

        System.assertEquals(
            prod.Id,
            result.Product__c,
            'Product should be mapped correctly'
        );
    }
    
    @IsTest
    static void testScheduler() {

        Test.startTest();
        String cronExp = '0 0 0 1 1 ? 2099';
        System.schedule(
            'Test Pricing Matrix Scheduler',
            cronExp,
            new PricingMatrixLookupScheduler()
        );
        Test.stopTest();

        
    }
}