Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

DFfullcopybackup/force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DFfullcopybackup/force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account (Ship-to) for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/classes/QuoteTriggerTest.cls
@IsTest
public class QuoteTriggerTest {

    @testSetup
    static void setupData() {

        // Sold-To Account
        Account soldTo = new Account(
            Name = 'Sold To Account',
            APTS_Pricing_Notes__c = 'Special pricing applies'
        );
        insert soldTo;

        // Ship-To Account
        Account shipTo = new Account(
            Name = 'Ship To Account',
            ParentId = soldTo.Id,
            ShippingStreet = '123 Main St',
            ShippingCity = 'Bangalore',
            ShippingState = 'KA',
            ShippingPostalCode = '560001',
            ShippingCountry = 'India'
        );
        insert shipTo;

        // Another account for update scenario
        Account newShipTo = new Account(
            Name = 'New Ship To',
            ShippingStreet = '456 Market St',
            ShippingCity = 'Mumbai',
            ShippingState = 'MH',
            ShippingPostalCode = '400001',
            ShippingCountry = 'India'
        );
        insert newShipTo;
    }

    /* -----------------------------------------
       TEST: BEFORE INSERT
    ------------------------------------------*/
    @IsTest
    static void testBeforeInsert() {

        Account shipTo =
            [SELECT Id FROM Account WHERE Name = 'Ship To Account' LIMIT 1];

        SBQQ__Quote__c quote = new SBQQ__Quote__c(
           SBQQ__Status__c = 'Draft',
            SBQQ__Account__c = shipTo.Id
        );

        insert quote;

       

     
    }

  
}