Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/TestCandidateConsentCallLightning.cls
@isTest

public class TestCandidateConsentCallLightning {
    @isTest static  void testGetCallout() {
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= true);

        // Contact candidate = [Select id from contact limit 1];
        Account client = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert client;         
        Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
        Insert candidate;

        Test.setMock(HttpCalloutMock.class, new CandidateconsentCallMock1 ());

        Test.startTest();
        CandidateConsentCallLightning.sendcall(candidate.id);
        Test.stopTest();
        //   string s =    CandidateConsentcall.sendrequest1('tasdgw',candidate.id);
        // system.debug('string returned: ' + s);          
    }

    @isTest static  void testGetCallout1() {
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= true);

        // Contact candidate = [Select id from contact limit 1];
        Account client = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert client;         
        Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
        Insert candidate;

        Test.setMock(HttpCalloutMock.class, new CandidateconsentCallMock1 ());

        Test.startTest();
        CandidateConsentCallLightning.updateContact(candidate.id);
        Test.stopTest();
        //   string s =    CandidateConsentcall.sendrequest1('tasdgw',candidate.id);
        // system.debug('string returned: ' + s);          
    }
    
    @isTest static  void testGetCallout2() {
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= true);

        // Contact candidate = [Select id from contact limit 1];
        Account client = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert client;         
        Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
        Insert candidate;

        Test.setMock(HttpCalloutMock.class, new CandidateconsentCallMock1 ());

        Test.startTest();
        CandidateConsentCallLightning.getContact(candidate.id);
        Test.stopTest();
        //   string s =    CandidateConsentcall.sendrequest1('tasdgw',candidate.id);
        // system.debug('string returned: ' + s);          
    }
    
    @isTest static  void testGetCallout3() {
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c= true);

        // Contact candidate = [Select id from contact limit 1];
        Account client = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert client;         
        Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
        candidate.email = 'testuse@gmail.com';
        Insert candidate;

        Test.setMock(HttpCalloutMock.class, new CandidateconsentCallMock1 ());

        Test.startTest();
        CandidateConsentCallLightning.sendcall(candidate.id);
        Test.stopTest();
        //   string s =    CandidateConsentcall.sendrequest1('tasdgw',candidate.id);
        // system.debug('string returned: ' + s);          
    }
    
}