Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_Last_Consent_Requested__c.field-meta.xml
<CustomField>
    <fullName>IP_Last_Consent_Requested__c</fullName>
    <label>Last Consent Requested</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/Test_ConsentRecieve.cls
@isTest
public class Test_ConsentRecieve{
 @isTest static  void testGetCallout1() {
        
        Account client = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert client;     
                insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
    
         Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
     candidate.IP_Last_Consent_Requested__c = System.now();
       Insert candidate;
     
      
   
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new CandidateconsentCallMock(candidate.id));
        ScheduleConsentReceivedate sh1 = new ScheduleConsentReceivedate();
        
        String sch = '0 31 * * * ?'; 
        system.schedule('Test Shift batch', sch, sh1); 
     Test.stopTest();          
    }
    
}