Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/Contact_Site_link__c.object-meta.xml
<CustomObject>
    <description>Link between Contacts and Sites allowing a many to many relationship</description>
    <label>Contact / Site link</label>
    <nameField>
        <displayFormat>LINKID-{000000}</displayFormat>
        <label>Contact / Site link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact / Site links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact / Site links</relationshipLabel>
    <relationshipName>Contact_Site_links</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Contact__c.field-meta.xml
<CustomField>
    <fullName>IP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact / Site links (Contact)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact_Site_link__c/fields/IP_Site__c.field-meta.xml
<CustomField>
    <fullName>IP_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>sirenum__Site__c.sirenum__Operating_Company__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sirenum__Site__c</referenceTo>
    <relationshipLabel>Contact / Site links (Site2)</relationshipLabel>
    <relationshipName>Contact_Site_links1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/CreateContactSiteLinkController.cls
public class CreateContactSiteLinkController {

    public Id contactId{get;set;}
    public Contact_Site_Link__c newContactSiteLink{get;set;}
    public Boolean saveNewValue;
    public Contact contact{get;set;}

    public CreateContactSiteLinkController(ApexPages.StandardController controller) {    
        contactId = ApexPages.CurrentPage().getparameters().get('Id');
        system.debug('++++++++++contactId'+contactId );
        saveNewValue = false;
        newContactSiteLink = new Contact_Site_Link__c();
        contact = [Select id,Name,AccountId,Account.Name from Contact where Id=:contactId];
        newContactSiteLink.IP_Contact__c = contactId;
        newContactSiteLink.Account__c = Contact.AccountId;
    }
    
    @AuraEnabled
    public static Contact getSiteContactLink(String contactId){
        if(contactId.contains('&uid')){
            contactId = contactId.removeEnd('&uid');
        }
        Contact conRecord = [Select Id,AccountId from Contact where Id=:contactId];
        return conRecord;
    }
    
    @AuraEnabled
    Public Static String saveNewRecord(Contact_Site_link__c siteContactData,String siteId){
        try{
            system.debug('++++++siteContactData++++++'+siteContactData);
            siteContactData.IP_Site__c = siteId;
            insert siteContactData;            
            return siteContactData.id+'success';
        }
        catch(Exception e){
            String message = 'Insert failed. First exception on row 0; first error: FIELD_FILTER_VALIDATION_EXCEPTION, ';
            String messageValidation = 'Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, ';
            if(e.getmessage().contains(message)){
                message = e.getmessage().substringAfter(message);
                if(message.contains(': [IP_Site__c]')){
                    message = message.substringBefore(': [IP_Site__c]');
                }
                return message;
            }else if(e.getmessage().contains(messageValidation)){system.debug('++++++44++++++'+e.getmessage());
                messageValidation = e.getmessage().substringAfter(messageValidation);system.debug('++++++messageValidation++++++'+messageValidation);
                if(messageValidation.contains(': []')){
                    messageValidation = messageValidation.substringBefore(': []');
                }
                return messageValidation;
            }
            else{
                return e.getmessage();
            }
        }
    }
    
    Public PageReference cancelRecord(){
        PageReference pageRef = new pageReference('/lightning/r/Contact/'+contactId+'/view'); 
        system.debug('pageRef'+pageRef);
        pageRef.setRedirect(true);
        return pageRef;
    }

}