Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/Impellam_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RSS Global Settings</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Impellam_Settings__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/Test_ExternalWorkerNew.cls
@isTest
private class Test_ExternalWorkerNew {
    
    @testsetup
    static void createWorker()
    {   
       Account clnt = TestDataFactory.create2ndTierSupplierAccount(1)[0];
       insert clnt; 
       
       insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);     
       Contact tier2nd = TestDataFactory.createCandidate2ndTier(clnt.Id,1)[0];
        tier2nd.FirstName = 'TestManishabcd';
       insert tier2nd;
       
    }
    
    
    static testMethod void testDoGetModified() 
    {
            Impellam_Settings__c set1 =  new Impellam_Settings__c(name = 'ExternalWorkerRest', Limit__c = '40');
            insert set1;
            Integer limit1 = Integer.Valueof(set1.Limit__c);    
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
            req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/standard/v1/collect/externalworker/1069/ABCD';  
            req.httpMethod = 'GET';
            RestContext.request = req;
            RestContext.response = res;
            ExternalWorkerRest.ResponseClass results = ExternalWorkerRest.doGet();       
            System.assertEquals('false', results.success);  
            System.assertEquals('Error in querying records', results.message);  
    }  
     static testMethod void testDoGetModified1() 
    {
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
             Impellam_Settings__c set1 =  new Impellam_Settings__c(name = 'ExternalWorkerEmergencyRest', Limit__c = '40');
            insert set1;
            Integer limit1 = Integer.Valueof(set1.Limit__c);    
            req.requestURI = System.URL.getSalesforceBaseURL()+'/services/apexrest/emergency/v1/collect/externalworker/1069/ABCD';  
            req.httpMethod = 'GET';
            RestContext.request = req;
            RestContext.response = res;
            ExternalWorkerEmergencyRest.ResponseClass results = ExternalWorkerEmergencyRest.doGet();       
            System.assertEquals('false', results.success);  
            System.assertEquals('Error in querying records', results.message);  
    } 
    
    }