Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <label>Initials</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CandidateIDlegacy__c.field-meta.xml
<CustomField>
    <fullName>IP_CandidateIDlegacy__c</fullName>
    <description>this is used for candidate that are being migrated from other system but their original IDs must be preserved</description>
    <externalId>true</externalId>
    <inlineHelpText>IF a candidate must still be reference by an original ID (for payroll) used this field</inlineHelpText>
    <label>Candidate ID (Legacy)</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CategoryOfWork__c.field-meta.xml
<CustomField>
    <fullName>IP_CategoryOfWork__c</fullName>
    <description>Which business areas does the person work in</description>
    <inlineHelpText>Which business areas does the person work in</inlineHelpText>
    <label>Category of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_IsInvoicecontact__c.field-meta.xml
<CustomField>
    <fullName>IP_IsInvoicecontact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used to only bring through Invoice contacts in filters populated via workflow based on value in the Multi-picklist for Contact Type</description>
    <inlineHelpText>Field used to only bring through Invoice contacts in filters populated via workflow based on value in the Multi-picklist for Contact Type</inlineHelpText>
    <label>Is Invoice contact</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_ThirdPartyID__c.field-meta.xml
<CustomField>
    <fullName>IP_ThirdPartyID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clock number etc,</inlineHelpText>
    <label>Third Party ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_WorkerStartDate__c.field-meta.xml
<CustomField>
    <fullName>IP_WorkerStartDate__c</fullName>
    <description>Date of the workers first paid work for the Agency</description>
    <inlineHelpText>Worker Start Date which is the first day of their first shift.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Requested__c.field-meta.xml
<CustomField>
    <fullName>P45_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Candidate Requested P45?</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/PayrollLeaver__c.field-meta.xml
<CustomField>
    <fullName>PayrollLeaver__c</fullName>
    <label>Payroll Leaver</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/TestCommunityBackgroundCheckCompetency.cls
/*
* Class Name: TestCommunityBackgroundCheckCompetency
* Description: Test Class for CreateCommunityBackgroundCheckCompetency
* Date : 3/Dec/2019
*/
@isTest
public class TestCommunityBackgroundCheckCompetency {
    
    private static final string COMMUNITY_BACKGROUND_CHECK = 'Community Background Check';
    
    /*
    * Method Name: setup
    * Description: Test Data
    * Parameters : none
    * Return Type: nothing
    */
    @testSetup static void setup() {
        
        sirenum__TicketType__c CompetenceType =new sirenum__TicketType__c();
        CompetenceType.Name = 'Community Background Check';
        insert CompetenceType;
        
        RecordType accountRec = [Select Id From RecordType Where sObjectType = 'Account' And DeveloperName = 'Candidate']; 
        Account acc1 = new Account(Name='Candidates',RecordTypeId=accountRec.id);
        insert acc1;
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c(name = 'Stoppayroll', Batch_check__c = false);

        RecordType condRec = [Select Id  From RecordType Where sObjectType = 'Contact' And DeveloperName= 'Candidate'];
        
        Contact con = new Contact(AccountID = acc1.Id, 
            RecordTypeId=condRec.id,
            FirstName ='Manish',
            Salutation ='Mr',
            MailingCity='ggn',
            MailingCountry='india',
            MailingPostalCode='110092',
            MailingState='Haryana',
            LastName ='candidate',  
            sirenum__National_Insurance__c='AA323232A', 
            IP_CandidateIDlegacy__c='dsdsdsdd', 
            MailingStreet='abc',
            P45_Requested__c=true,
            PayrollLeaver__c=null,
            Title = 'TestLastName',
            Initials__c = 'TestLastName',
            Birthdate = Date.valueOf('1990-02-20'),
            Phone = '9879879877',
            IP_WorkerStartDate__c=Date.valueOf('2017-02-20'),
            EEO_Gender__c = 'M',
            IP_CategoryOfWork__c='Catering;Industrial',
            IP_ThirdPartyID__c='testpay12',
            IP_IsInvoicecontact__c=true
        );
        
        insert con;
    }
    
    /*
    * Method Name: testMethodPositive
    * Description: Test Method for CreateCommunityBackgroundCheckCompetency Class
    * Parameters : none
    * Return Type: nothing
    */
    private static testmethod void testMethodPositive(){
        List<Contact> con = [Select id from Contact limit 1];
        List<String> listCandidateId = new List<String>();
        listCandidateId.add(con[0].id);
        test.startTest();
        CreateCommunityBackgroundCheckCompetency obj = new CreateCommunityBackgroundCheckCompetency();
        CreateCommunityBackgroundCheckCompetency.sendEmail(listCandidateId);
        test.stopTest();
    }
    
    /*
    * Method Name: testMethodPositive1
    * Description: Test Method for CreateCommunityBackgroundCheckCompetency Class
    * Parameters : none
    * Return Type: nothing
    */
    private static testmethod void testMethodPositive1(){
        List<Contact> con = [Select id from Contact limit 1];
        List<sirenum__TicketType__c> communitBackGroundCompetency = [Select id from sirenum__TicketType__c 
                                                        where Name=:COMMUNITY_BACKGROUND_CHECK limit 1];
        
        sirenum__Ticket__c competency = new sirenum__Ticket__c();
        competency.sirenum__TicketType__c = communitBackGroundCompetency[0].id;                         
        competency.sirenum__Owner__c = con[0].id;
        //competency.sirenum__Valid__c = true;
        competency.sirenum__Valid_from__c = System.today();
        insert competency;                          
        
        List<String> listCandidateId = new List<String>();
        listCandidateId.add(con[0].id);
        test.startTest();
        CreateCommunityBackgroundCheckCompetency obj = new CreateCommunityBackgroundCheckCompetency();
        CreateCommunityBackgroundCheckCompetency.sendEmail(listCandidateId);
        test.stopTest();
    }
}