Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Test_UpdateDataStore.cls
@isTest
public class Test_UpdateDataStore  {
 @isTest static  void testGetCallout() {
        Set<id> conid = new Set<id>();
        Account client = TestDataFactory.createCandidateAccount(1)[0]; 
        Insert client;   
                insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
      
         Contact candidate = TestDataFactory.createCandidate(client.id, 1)[0];
     Insert candidate;
     conid.add(candidate.id);
       Test.setMock(HttpCalloutMock.class, new CandidateconsentCallMock1 ());

        Test.startTest();
        UpdateDataStore.sendconsentdata(conid);
     Test.stopTest();
     //   string s =    CandidateConsentcall.sendrequest1('tasdgw',candidate.id);
    // system.debug('string returned: ' + s);          
    }   
    
}