Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_DateAvailableforRecontact__c.field-meta.xml
<CustomField>
    <fullName>IP_DateAvailableforRecontact__c</fullName>
    <label>Date Available for Recontact</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/Test_UpdaterecontacteddateCanddate.cls
@istest
public class Test_UpdaterecontacteddateCanddate  {

    static testMethod void updateContactdate() {
       
      
        Account acc2 = TestDataFactory.createCandidateAccount(1)[0];
        insert acc2;
                insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);

         insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        Contact con1 = TestDataFactory.createCandidate(acc2.id,1)[0];
        con1.IP_DateAvailableforRecontact__c = System.today();
        insert con1;    

        Test.startTest();
        ScheduleUpdaterecontacteddateCanddate sh2 = new ScheduleUpdaterecontacteddateCanddate();
        String sch = '0 0 23 * * ?';
        system.schedule('Testcontactdtae Sync', sch, sh2);
        Test.stopTest();
    }
    }