Frankbelford/uatv1ba/force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <description>Default Account record type used throughout the system.</description>
    <label>Account</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Community_Background__c.field-meta.xml
<CustomField>
    <fullName>Community_Background__c</fullName>
    <description>Created for JPC-1957 Belfast - Recording Religion - Part 1</description>
    <label>Community Background</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Protestant</fullName>
            </value>
            <value>
                <fullName>Catholic</fullName>
            </value>
            <value>
                <fullName>Not Either</fullName>
            </value>
            <value>
                <fullName>xxxxxx</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/IP_CategoryOfWork__c.field-meta.xml
<CustomField>
    <fullName>IP_CategoryOfWork__c</fullName>
    <description>Which business areas does the person work in</description>
    <inlineHelpText>Which business areas does the person work in</inlineHelpText>
    <label>Category of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_Business_Type</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Method_of_Determination__c.field-meta.xml
<CustomField>
    <fullName>Method_of_Determination__c</fullName>
    <description>Belfast - Recording Religion - Part 1</description>
    <label>Method of Determination</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Residuary</fullName>
            </value>
            <value>
                <fullName>Not Determined</fullName>
            </value>
            <value>
                <fullName>xxxxxx</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>Last Date Worked</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/sirenum__National_Insurance__c.field-meta.xml
<CustomField>
    <fullName>sirenum__National_Insurance__c</fullName>
    <label>National Insurance #</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/SOC__c.field-meta.xml
<CustomField>
    <fullName>SOC__c</fullName>
    <description>Created for JPC-1957 Belfast - Recording Religion - Part 1</description>
    <label>SOC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOC 1 – Managers and senior officials</fullName>
            </value>
            <value>
                <fullName>SOC 2 – Professional occupations</fullName>
            </value>
            <value>
                <fullName>SOC 3 – Associate professional and technical occupations</fullName>
            </value>
            <value>
                <fullName>SOC 4 – Administrative and secretarial occupations</fullName>
            </value>
            <value>
                <fullName>SOC 5 – Skilled trade organisations</fullName>
            </value>
            <value>
                <fullName>SOC 6 – Personal service occupations</fullName>
            </value>
            <value>
                <fullName>SOC 7 – Sales and customer service occupations</fullName>
            </value>
            <value>
                <fullName>SOC 8 – Process, plant and machine operatives</fullName>
            </value>
            <value>
                <fullName>SOC 9 – Elementary occupations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/IP_JSToFrostSwtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to activate or deactivate JS to Frost Functionality</description>
    <label>JS to Frost Switch</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_JSToFrostSwtich__c/fields/IP_RunJSToFrost__c.field-meta.xml
<CustomField>
    <fullName>IP_RunJSToFrost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run JS to Frost</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/IP_PayProfile__c.object-meta.xml
<CustomObject>
    <label>Pay Profile</label>
    <nameField>
        <displayFormat>IN{00000000}</displayFormat>
        <label>Pay Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Candidate__c.field-meta.xml
<CustomField>
    <fullName>IP_Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pay Profiles</relationshipLabel>
    <relationshipName>Pay_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_CompanyRegNo__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyRegNo__c</fullName>
    <label>Company Registration No</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_PayrollID__c.field-meta.xml
<CustomField>
    <fullName>IP_PayrollID__c</fullName>
    <description>Payroll ID</description>
    <externalId>true</externalId>
    <label>Payroll ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATNumber__c.field-meta.xml
<CustomField>
    <fullName>IP_VATNumber__c</fullName>
    <label>VAT Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/IP_VATRegistered__c.field-meta.xml
<CustomField>
    <fullName>IP_VATRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Registered</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Date_by_Head_Office__c.field-meta.xml
<CustomField>
    <fullName>P45_Date_by_Head_Office__c</fullName>
    <label>P45 Emailed Date</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/fields/P45_Initiated__c.field-meta.xml
<CustomField>
    <fullName>P45_Initiated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>P45 Initiated</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_PayProfile__c/recordTypes/PAYE.recordType-meta.xml
<RecordType>
    <fullName>PAYE</fullName>
    <active>true</active>
    <label>PAYE</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/Payroll_Swtich__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payroll Swtich</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Payroll_Swtich__c/fields/Batch_check__c.field-meta.xml
<CustomField>
    <fullName>Batch_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch check</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_CommBackgroundVerify.cls
@isTest
public class Test_CommBackgroundVerify{
   @testSetup static void dataSetUp(){ 

        Account acc = TestDataFactory.createClients(1)[0]; 
        insert acc; 
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        insert new Payroll_Swtich__c (name = 'Stoppayroll', Batch_check__c = false);
        Contact c = new Contact();
        c.FirstName='Con';
        c.lastName='Test Contact';
        c.IP_CategoryOfWork__c='Industrial';
        c.sirenum__National_Insurance__c='AA123456A';
        c.P45_Date_by_Head_Office__c=system.today();
        c.AccountID=acc.id;
        insert c;
        
        insert new IP_JSToFrostSwtich__c(name = 'JSToFrost', IP_RunJSToFrost__c = true);
        RecordType rt=[SELECT Id FROM RecordType WHERE SobjectType = 'IP_PayProfile__c' AND DeveloperName = 'PAYE'];
       
        IP_PayProfile__c pay= new IP_PayProfile__c();
        pay.RecordTypeId=rt.id;
        pay.IP_PayrollID__c='Testpayrol';
        pay.IP_Status__c='Inactive';
        pay.IP_Candidate__c=c.Id;
        pay.IP_CompanyRegNo__c='12345678';
        pay.IP_VATRegistered__c=true;
        pay.IP_VATNumber__c='123456789';
        pay.P45_Initiated__c=true;
        pay.IP_LastPassedTotempest__c = Date.newInstance(2017, 01, 01);
        pay.IP_Payroll_Leaver__c = 'PL';
        insert pay;
        
        id certId = Schema.SObjectType.Certification__c.getRecordTypeInfosByName().get('Community Background Check (NI Only)').getRecordTypeId();
        Certification__c cert = new Certification__c();
        cert.Contact__c = c.id;
        cert.RecordTypeId = certId;     
        insert cert;
        
        Certification__c cert1 = new Certification__c();
        cert1.Contact__c = c.id;
        cert1.RecordTypeId = certId;    
        cert1.Community_Background__c = 'Not Either';           
        insert cert1;
       
       Certification__c cert2 = new Certification__c();
        cert2.Contact__c = c.id;
        cert2.RecordTypeId = certId;    
        cert2.Community_Background__c = 'Not Either';
       cert2.Method_of_Determination__c = 'Direct';
        insert cert2;
       
        Certification__c cert3 = new Certification__c();
        cert3.Contact__c = c.id;
        cert3.RecordTypeId = certId;    
        cert3.Community_Background__c = 'Not Either';
        cert3.Method_of_Determination__c = 'Direct';
        cert3.SOC__c = 'SOC 1 – Managers and senior officials';
        insert cert3;
        
        
        id certIdEqualOpps = Schema.SObjectType.Certification__c.getRecordTypeInfosByName().get('Equal Opportunities Question').getRecordTypeId();
        Certification__c cert4 = new Certification__c();
        cert4.Contact__c = c.id;
        cert4.RecordTypeId = certIdEqualOpps;    
        cert4.Gender__c = 'Female';
        cert4.Date_Of_Birth__c = System.today().addmonths(-3);
        insert cert4;

        
        }
        
        @istest static void BatchHeaderclassmethod1(){      
        Certification__c listcert = [Select id from Certification__c where RecordType.Name = 'Community Background Check (NI Only)' limit 1];
        listcert.IP_Status__c = 'Current';
        update listcert;
        Test.startTest();
        CommBackgroundVerifyLapseCertification.getCertificationVerified(listcert.id);
        
        Test.stopTest();
    }
    @istest static void BatchHeaderclassmethod2(){      
        Certification__c listcert = [Select id from Certification__c where RecordType.Name = 'Community Background Check (NI Only)' and Community_Background__c = 'Not Either' limit 1];
        listcert.IP_Status__c = 'Current';
        update listcert;
        Test.startTest();
        CommBackgroundVerifyLapseCertification.getCertificationVerified(listcert.id);
        CommBackgroundVerifyLapseCertification.getCertificationLapsed(listcert.id);
        Test.stopTest();
    }
    @istest static void BatchHeaderclassmethod3(){      
        Certification__c listcert = [Select id from Certification__c where RecordType.Name = 'Community Background Check (NI Only)' and Community_Background__c = 'Not Either' limit 1];
        listcert.IP_Status__c = 'Lapsed';
        update listcert;
        Test.startTest();
        CommBackgroundVerifyLapseCertification.getCertificationVerified(listcert.id);
        CommBackgroundVerifyLapseCertification.getCertificationLapsed(listcert.id);
        Test.stopTest();
    }
    @istest static void BatchHeaderclassmethod4(){      
        Certification__c listcert = [Select id from Certification__c where RecordType.Name = 'Community Background Check (NI Only)' and Method_of_Determination__c != '' limit 1];
        listcert.Verfied__c = TRUE;
        listcert.IP_Status__c = 'Current';
        update listcert;
        Test.startTest();
        CommBackgroundVerifyLapseCertification.getCertificationVerified(listcert.id);
        Test.stopTest();
    }
     
    @istest static void BatchHeaderclassmethod5(){      
        Certification__c listcert = [Select id from Certification__c where RecordType.Name = 'Community Background Check (NI Only)' and SOC__c != '' limit 1];
        listcert.Verfied__c = TRUE;
       // listcert.IP_Status__c = 'Current';
        update listcert;
        Test.startTest();
        CommBackgroundVerifyLapseCertification.getCertificationVerified(listcert.id);
        Test.stopTest();
    }
    
    @istest static void BatchHeaderclassmethod6(){      
        Certification__c listcert = [Select id from Certification__c where RecordType.Name = 'Equal Opportunities Question' limit 1];
        listcert.Verfied__c = TRUE;
       // listcert.IP_Status__c = 'Current';
       try{
            update listcert;
       }
       catch(Exception e){
           
       }
        Test.startTest();
        CommBackgroundVerifyLapseCertification.getCertificationVerified(listcert.id);
        Test.stopTest();
    }
}