Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/IP_BranchStatus__c.object-meta.xml
<CustomObject>
    <label>Branch Status List</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Status Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_BranchID__c.field-meta.xml
<CustomField>
    <fullName>IP_BranchID__c</fullName>
    <externalId>true</externalId>
    <label>Branch ID</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_Division__c.field-meta.xml
<CustomField>
    <fullName>IP_Division__c</fullName>
    <externalId>true</externalId>
    <label>Division</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_Payroll_to_Process__c.field-meta.xml
<CustomField>
    <fullName>IP_Payroll_to_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payroll to Process</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_Region__c.field-meta.xml
<CustomField>
    <fullName>IP_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_RegionList</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/UpdateDivisionOnSPlacementHandler.cls
/*
* Class Name: UpdateDivisionOnSPlacementHandler
* Description: Incident - 11081
* Test Class: TestUpdateDivisionOnSPlacementHandler
* Date : 20th March 2020
*/
public class UpdateDivisionOnSPlacementHandler{
    
    /*
    * Method Name: handleBeforeUpdate
    * Description: To Process all record
    * Parameters : Map<Id, SObject> newItems, Map<Id, SObject> oldItems
    * Return Type: void
    * Date : 20th March 2020
    */
    public static void handleBeforeUpdate(Map<Id, sirenum__Placement__c> newItems, Map<Id, sirenum__Placement__c> oldItems) {
        Map<String,IP_BranchStatus__c> mapUserIdUserProfile = new Map<String,IP_BranchStatus__c>();
        
        for(IP_BranchStatus__c branchStatus : [Select id,IP_BranchID__c,IP_Division__c,IP_Payroll_to_Process__c,
                                                IP_Region__c,IP_Status__c from IP_BranchStatus__c]){
            mapUserIdUserProfile.put(branchStatus.IP_BranchID__c,branchStatus);
        }
        
        for(sirenum__Placement__c splacement : newItems.values()){
            if(String.IsNotBlank(splacement.IP_Costcode__c) && splacement.IP_Costcode__c!=olditems.get(splacement.id).IP_Costcode__c){
                if(!mapUserIdUserProfile.isEmpty() && mapUserIdUserProfile.containskey(splacement.IP_Costcode__c) && mapUserIdUserProfile.get(splacement.IP_Costcode__c).IP_Division__c!=null){
                    splacement.IP_Division__c = mapUserIdUserProfile.get(splacement.IP_Costcode__c).IP_Division__c;
                }
            }
        }
    }
    
     /*
    * Method Name: handleBeforeInsert
    * Description: To Process all record
    * Parameters : List<sirenum__Placement__c> listSPlacement
    * Return Type: void
    * Date : 20th March 2020
    */
    public static void handleBeforeInsert(List<sirenum__Placement__c> listSPlacement) {
        Map<String,IP_BranchStatus__c> mapUserIdUserProfile = new Map<String,IP_BranchStatus__c>();
        
        for(IP_BranchStatus__c branchStatus : [Select id,IP_BranchID__c,IP_Division__c,IP_Payroll_to_Process__c,
                                                IP_Region__c,IP_Status__c from IP_BranchStatus__c]){
            mapUserIdUserProfile.put(branchStatus.IP_BranchID__c,branchStatus);
        }
        
        for(sirenum__Placement__c splacement : listSPlacement){
            if(String.IsNotBlank(splacement.IP_Costcode__c)){
                if(!mapUserIdUserProfile.isEmpty() && mapUserIdUserProfile.containskey(splacement.IP_Costcode__c) && mapUserIdUserProfile.get(splacement.IP_Costcode__c).IP_Division__c!=null){
                    splacement.IP_Division__c = mapUserIdUserProfile.get(splacement.IP_Costcode__c).IP_Division__c;
                }
            }
        }
    }
}