Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/IP_BranchStatus__c.object-meta.xml
<CustomObject>
    <label>Branch Status List</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Status Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_BranchID__c.field-meta.xml
<CustomField>
    <fullName>IP_BranchID__c</fullName>
    <externalId>true</externalId>
    <label>Branch ID</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_CompanyCode__c/IP_CompanyCode__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Brand Company Code</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_CompanyCode__c/fields/IP_CompanyCodeValue__c.field-meta.xml
<CustomField>
    <fullName>IP_CompanyCodeValue__c</fullName>
    <label>Company Code Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/IP_ImpellamGlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Global Settings Outbound Transf</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/IP_OutboundErrorEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>IP_OutboundErrorEmailAddress__c</fullName>
    <label>Outbound Error Email Address</label>
    <type>Email</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/IP_OutboundDataTransfer__c.object-meta.xml
<CustomObject>
    <description>Object that holds data for transfer out of the system</description>
    <label>Outbound Data Transfer</label>
    <nameField>
        <displayFormat>ODT-{0000000000}</displayFormat>
        <label>Outbound Data Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Data Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_BrandCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>IP_BrandCompanyCode__c</fullName>
    <label>Brand Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Consultant_Name__c.field-meta.xml
<CustomField>
    <fullName>IP_Consultant_Name__c</fullName>
    <label>Consultant Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Consultants_Tempest_ID__c.field-meta.xml
<CustomField>
    <fullName>IP_Consultants_Tempest_ID__c</fullName>
    <label>Consultants Tempest ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Email__c.field-meta.xml
<CustomField>
    <fullName>IP_Email__c</fullName>
    <label>Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_OriginRecordID__c.field-meta.xml
<CustomField>
    <fullName>IP_OriginRecordID__c</fullName>
    <label>Origin Record ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Passed__c.field-meta.xml
<CustomField>
    <fullName>IP_Passed__c</fullName>
    <label>Passed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Tempest_Department__c.field-meta.xml
<CustomField>
    <fullName>IP_Tempest_Department__c</fullName>
    <label>Tempest Department</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Tempest_Division__c.field-meta.xml
<CustomField>
    <fullName>IP_Tempest_Division__c</fullName>
    <label>Tempest Division</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_TransferType__c.field-meta.xml
<CustomField>
    <fullName>IP_TransferType__c</fullName>
    <label>Transfer Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Parallel_Payroll_Check__c/IP_Parallel_Payroll_Check__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Parallel Payroll Check</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_Parallel_Payroll_Check__c/fields/Run_Parallel_Payroll__c.field-meta.xml
<CustomField>
    <fullName>Run_Parallel_Payroll__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Parallel Payroll</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_LastPassedToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_LastPassedToTempest__c</fullName>
    <label>Last Passed to Tempest</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_PassToTempest__c.field-meta.xml
<CustomField>
    <fullName>IP_PassToTempest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pass to Tempest</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDepartment__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDepartment__c</fullName>
    <label>Tempest Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDepartment</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestDivision__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestDivision__c</fullName>
    <label>Tempest Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IP_TempestDivision</valueSetName>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/User/fields/IP_TempestID__c.field-meta.xml
<CustomField>
    <fullName>IP_TempestID__c</fullName>
    <description>ID need for passing to payroll</description>
    <externalId>true</externalId>
    <inlineHelpText>The ID needed for payroll detail passed</inlineHelpText>
    <label>Tempest ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/UserProcessupdate.cls
public class UserProcessupdate {
    public static Boolean sendMail = false;

    public static void senduserdata(Set<id> Userid){
    Set<String> branchset = new Set<String>();
    String errorFile = 'Id,Error\n';
    Map<id,String> errMessage = new Map<id,String>();
    Map<id,String> errMessage1 = new Map<id,String>();
    List<Id> errorIds = new List<Id>();
    List<Id> errorIds1 = new List<Id>();
    IP_CompanyCode__c Ccode = IP_CompanyCode__c.getValues('CompanyCode');
    IP_Parallel_Payroll_Check__c paycheck = IP_Parallel_Payroll_Check__c.getValues('RunParallelCheck');
    List<IP_OutboundDataTransfer__c> outboundList = new List<IP_OutboundDataTransfer__c>();
    List<IP_BranchStatus__c> branchlist = [Select id,IP_BranchID__c from IP_BranchStatus__c];
    for(IP_BranchStatus__c b:branchlist)
    {
        branchset.add(b.IP_BranchID__c);
    }
    List<User> Userlist = [Select id,Name,Email,IP_TempestID__c,IP_TempestDepartment__c,IP_TempestDivision__c,IP_PassToTempest__c,IP_LastPassedToTempest__c from User where IP_TempestDepartment__c in: branchset and id in:Userid];
    
    for(User u : Userlist)
    {
      
        if(!paycheck.Run_Parallel_Payroll__c)
        {
        u.IP_PassToTempest__c = false;
         u.IP_LastPassedToTempest__c = System.now();
        }
       
        IP_OutboundDataTransfer__c ob = new IP_OutboundDataTransfer__c();
        ob.IP_Tempest_Division__c = u.IP_TempestDivision__c;
        ob.IP_Tempest_Department__c = u.IP_TempestDepartment__c;
        ob.IP_Consultants_Tempest_ID__c = u.IP_TempestID__c;
        ob.IP_Email__c = u.Email;
        ob.IP_Passed__c = 'PASSING';
        ob.IP_Consultant_Name__c = u.Name;
        ob.IP_OriginRecordID__c = u.id;
        ob.IP_TransferType__c = 'Consultant';
         // ob.IP_BrandCompanyCode__c = Ccode.IP_CompanyCodeValue__c;
        outboundList.add(ob);
    }
    Database.SaveResult[] srList1 = database.insert(outboundList,false);
     for (integer i=0; i<srList1.size();i++) 
                {
                     String errMsgs = '';
                    if(!srList1[i].isSuccess())
                    {
                        errorIds1.add(srList1[i].id);
                    }
                    for(Database.Error err : srList1[i].getErrors())
                        {
                             errMsgs = errMsgs + '  ' + err.getMessage();
                        }   
                errMessage1.put(srList1[i].Id,errMsgs);
                errMsgs ='';                            
                }
        if(!errorIds.IsEmpty())
            {
                for(integer i=0;i<errorIds.size();i++)
                {    errorFile = errorFile + errorIds[i]+','+ errMessage.get(errorIds[i]) + ',' +'\n';                       sendMail = true;                    
                }
            } 
            else
            {
    Database.SaveResult[] srList = database.update(Userlist,false);
     for (integer i=0; i<srList.size();i++) 
                {
                     String errMsgs = '';
                    if(!srList[i].isSuccess())
                    {
                        errorIds.add(srList[i].id);
                    }
                    for(Database.Error err : srList[i].getErrors())
                        {                             errMsgs = errMsgs + '  ' + err.getMessage();
                        }   
                errMessage.put(srList[i].Id,errMsgs);
                errMsgs ='';                            
                }
               
        if(!errorIds.IsEmpty())
            {
                for(integer i=0;i<errorIds.size();i++)
                {                    errorFile = errorFile + errorIds[i]+','+ errMessage.get(errorIds[i]) + ',' +'\n';                       sendMail = true;                    
                }
            } 
            }
         if(sendMail == true)
         {
             String emailid = IP_ImpellamGlobalSetting__c.getInstance().IP_OutboundErrorEmailAddress__c;
             Messaging.EmailFileAttachment errAtt = new Messaging.EmailFileAttachment();
                
            blob errBlob = blob.valueof(errorFile);   errAtt.setFileName('Consultant Failed_Records.csv');            errAtt.setBody(errBlob);
    
            Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage(); 
            String subject ='Consultant - Outbound Transfer Failure';           email.setSubject(subject);           String[] toAddresses = new String[] {emailid};            email.setToAddresses(toAddresses);            email.setPlainTextBody('Hello,\n\nPlease find attached the list of failed records.');
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{errAtt});            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
         }
        }
        }