Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/IP_BranchStatus__c.object-meta.xml
<CustomObject>
    <label>Branch Status List</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Status Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_BranchID__c.field-meta.xml
<CustomField>
    <fullName>IP_BranchID__c</fullName>
    <externalId>true</externalId>
    <label>Branch ID</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_BranchStatus__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/IP_ImpellamGlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Global Settings Outbound Transf</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/IP_LastTransmissionDate__c.field-meta.xml
<CustomField>
    <fullName>IP_LastTransmissionDate__c</fullName>
    <label>Last Transmission Date</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/IP_OutboundDataTransfer__c.object-meta.xml
<CustomObject>
    <description>Object that holds data for transfer out of the system</description>
    <label>Outbound Data Transfer</label>
    <nameField>
        <displayFormat>ODT-{0000000000}</displayFormat>
        <label>Outbound Data Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Data Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_EmergencyPull__c.field-meta.xml
<CustomField>
    <fullName>IP_EmergencyPull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Pull</label>
    <type>Checkbox</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Status__c.field-meta.xml
<CustomField>
    <fullName>IP_Status__c</fullName>
    <label>Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_Tempest_Department__c.field-meta.xml
<CustomField>
    <fullName>IP_Tempest_Department__c</fullName>
    <label>Tempest Department</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_OutboundDataTransfer__c/fields/IP_TransferType__c.field-meta.xml
<CustomField>
    <fullName>IP_TransferType__c</fullName>
    <label>Transfer Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_OutboundPassedEmergency.cls
@isTest
public class Test_OutboundPassedEmergency {

    static testmethod void testoutbound1(){
          IP_BranchStatus__c b  = new IP_BranchStatus__c ();
                 b.IP_BranchID__c = '1062';
                 b.Name = 'Test';
             b.IP_Status__c = 'Active';
                 insert b;
         IP_ImpellamGlobalSetting__c setting = new IP_ImpellamGlobalSetting__c();
                 setting.IP_LastTransmissionDate__c =   Date.newInstance(2019,07,01);
                 insert setting;
        
          IP_OutboundDataTransfer__c ob2 = new IP_OutboundDataTransfer__c();
     ob2.IP_Tempest_Department__c = '1062';
        ob2.IP_TransferType__c = 'Assignment';   
        ob2.IP_EmergencyPull__c  = true;  
        insert ob2;
        
        Database.executeBatch(new OutboundDataPassedEmergency(), 10);
    }
}