Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/IP_ImpellamGlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Global Settings Outbound Transf</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/S_placement_Deletion_Size__c.field-meta.xml
<CustomField>
    <fullName>S_placement_Deletion_Size__c</fullName>
    <label>S-placement Deletion Batch Size</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/splacementDeleteSchedule.cls
global class splacementDeleteSchedule implements Schedulable{
 global void execute(SchedulableContext sc) {
      IP_ImpellamGlobalSetting__c imp = IP_ImpellamGlobalSetting__c.getOrgDefaults();
             Integer limit1 = Integer.valueOf(imp.S_placement_Deletion_Size__c);
     
        Placement_ShiftdeleteJob batchInstance = new Placement_ShiftdeleteJob(); 
        database.executebatch(batchInstance,limit1);
    }
}