Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/IP_ImpellamGlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Global Settings Outbound Transf</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/IP_OutboundWriteBatchsize__c.field-meta.xml
<CustomField>
    <fullName>IP_OutboundWriteBatchsize__c</fullName>
    <label>Outbound Write Batch size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/Schedule_OutboundPassed_Test.cls
@isTest
public class Schedule_OutboundPassed_Test {
     
        public static testMethod void testschedule(){
            IP_ImpellamGlobalSetting__c setting = new IP_ImpellamGlobalSetting__c();
                 setting.IP_OutboundWriteBatchsize__c =   2000;
                 insert setting;
                 
        Test.StartTest();
        Schedule_OutboundPassed sh1 = new Schedule_OutboundPassed();
        String sch = '0 23 22 29 * ?';
        system.schedule('Test outboundpass', sch, sh1);
        Test.stopTest();
        
        
        }

}