Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/IP_ImpellamGlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Global Settings Outbound Transf</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/IP_OutboundWriteBatchsize__c.field-meta.xml
<CustomField>
    <fullName>IP_OutboundWriteBatchsize__c</fullName>
    <label>Outbound Write Batch size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Schedule_OutboundPassedEmergency_Test.cls
@isTest
public class Schedule_OutboundPassedEmergency_Test {
     
        public static testMethod void testschedule(){
            IP_ImpellamGlobalSetting__c setting = new IP_ImpellamGlobalSetting__c();
                 setting.IP_OutboundWriteBatchsize__c =   2000;
                 insert setting;
                 
        Test.StartTest();
        Schedule_OutboundPassedEmergency sh1 = new Schedule_OutboundPassedEmergency();
        String sch = '0 23 22 29 * ?';
        system.schedule('Test outboundpass1', sch, sh1);
        Test.stopTest();
        
        
        }

}