Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/IP_ImpellamGlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RSS Global Settings Outbound Transf</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_ImpellamGlobalSetting__c/fields/IP_OutboundWriteBatchsize__c.field-meta.xml
<CustomField>
    <fullName>IP_OutboundWriteBatchsize__c</fullName>
    <label>Outbound Write Batch size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/FrankbellarrowBackup/force-app/main/default/classes/Schedule_OutboundPassedEmergency.cls
global class Schedule_OutboundPassedEmergency implements Schedulable{
IP_ImpellamGlobalSetting__c imp = IP_ImpellamGlobalSetting__c.getOrgDefaults();
             Integer limit1 = Integer.valueOf(imp.IP_OutboundWriteBatchsize__c);
     global void execute(SchedulableContext sc) {
        OutboundDataPassedEmergency batchInstance = new OutboundDataPassedEmergency(); 
        database.executebatch(batchInstance,limit1);
    }
}