Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/StagingJobOrder__c.object-meta.xml
<CustomObject>
    <label>Staging Job Order</label>
    <nameField>
        <label>Staging Job Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/Staging_Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Staging_Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging Job Application</label>
    <referenceTo>StagingJobApplication__c</referenceTo>
    <relationshipLabel>Staging Job Orders</relationshipLabel>
    <relationshipName>Staging_Job_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCandidateRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgCandidateRoleId__c</fullName>
    <label>StgCandidateRoleId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClient_Id__c.field-meta.xml
<CustomField>
    <fullName>StgClient_Id__c</fullName>
    <label>StgClient Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgClientName__c.field-meta.xml
<CustomField>
    <fullName>StgClientName__c</fullName>
    <label>StgClientName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCostCentre__c.field-meta.xml
<CustomField>
    <fullName>StgCostCentre__c</fullName>
    <label>StgCostCentre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>StgCreatedDate__c</fullName>
    <label>StgCreatedDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgCVRequired__c.field-meta.xml
<CustomField>
    <fullName>StgCVRequired__c</fullName>
    <label>StgCVRequired</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgEndDate__c.field-meta.xml
<CustomField>
    <fullName>StgEndDate__c</fullName>
    <label>StgEndDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgEndTime__c.field-meta.xml
<CustomField>
    <fullName>StgEndTime__c</fullName>
    <label>StgEndTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgFrontOfficeIntegrationSystem__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystem__c</fullName>
    <label>StgFrontOfficeIntegrationSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgHasShifts__c.field-meta.xml
<CustomField>
    <fullName>StgHasShifts__c</fullName>
    <label>StgHasShifts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgJobCat__c.field-meta.xml
<CustomField>
    <fullName>StgJobCat__c</fullName>
    <label>StgJobCat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgJobRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgJobRoleId__c</fullName>
    <description>This field is related to Booking in Evo</description>
    <label>StgJobRoleId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgJobRoleName__c.field-meta.xml
<CustomField>
    <fullName>StgJobRoleName__c</fullName>
    <description>This field is related to Booking in Evo</description>
    <label>StgJobRoleName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgJobTitle__c.field-meta.xml
<CustomField>
    <fullName>StgJobTitle__c</fullName>
    <label>StgJobTitle</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgLocationId__c.field-meta.xml
<CustomField>
    <fullName>StgLocationId__c</fullName>
    <label>StgLocationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgLocationName__c.field-meta.xml
<CustomField>
    <fullName>StgLocationName__c</fullName>
    <label>StgLocationName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgMoveOrCopy__c.field-meta.xml
<CustomField>
    <fullName>StgMoveOrCopy__c</fullName>
    <label>Stg Move Or Copy</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgPostCode__c.field-meta.xml
<CustomField>
    <fullName>StgPostCode__c</fullName>
    <label>StgPostCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgQuantity__c.field-meta.xml
<CustomField>
    <fullName>StgQuantity__c</fullName>
    <label>StgQuantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgReqPayload__c.field-meta.xml
<CustomField>
    <fullName>StgReqPayload__c</fullName>
    <description>Original JSON Payload received</description>
    <label>Request JSON Payload</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgRequiredStaff__c.field-meta.xml
<CustomField>
    <fullName>StgRequiredStaff__c</fullName>
    <label>StgRequiredStaff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgRoleRequirement__c.field-meta.xml
<CustomField>
    <fullName>StgRoleRequirement__c</fullName>
    <label>StgRoleRequirement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgSecWatchdog__c.field-meta.xml
<CustomField>
    <fullName>StgSecWatchdog__c</fullName>
    <label>StgSecWatchdog</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgSourceSystem__c.field-meta.xml
<CustomField>
    <fullName>StgSourceSystem__c</fullName>
    <label>StgSourceSystem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgStartDate__c.field-meta.xml
<CustomField>
    <fullName>StgStartDate__c</fullName>
    <label>StgStartDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgStartTime__c.field-meta.xml
<CustomField>
    <fullName>StgStartTime__c</fullName>
    <label>StgStartTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingJobOrder__c/fields/StgTransactionType__c.field-meta.xml
<CustomField>
    <fullName>StgTransactionType__c</fullName>
    <label>Stg Transaction Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/StagingShift__c.object-meta.xml
<CustomObject>
    <label>Staging Shift</label>
    <nameField>
        <label>Staging Shift</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/Staging_Job_Order__c.field-meta.xml
<CustomField>
    <fullName>Staging_Job_Order__c</fullName>
    <label>Staging Job Order</label>
    <referenceTo>StagingJobOrder__c</referenceTo>
    <relationshipLabel>Staging Shifts</relationshipLabel>
    <relationshipName>Staging_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgClientID__c.field-meta.xml
<CustomField>
    <fullName>StgClientID__c</fullName>
    <label>StgClientID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgClientName__c.field-meta.xml
<CustomField>
    <fullName>StgClientName__c</fullName>
    <label>StgClientName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgFrontOfficeIntegrationSystemEntity__c.field-meta.xml
<CustomField>
    <fullName>StgFrontOfficeIntegrationSystemEntity__c</fullName>
    <label>StgFrontOfficeIntegrationSystemEntity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgJobTitle__c.field-meta.xml
<CustomField>
    <fullName>StgJobTitle__c</fullName>
    <label>StgJobTitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgPlacement__c.field-meta.xml
<CustomField>
    <fullName>StgPlacement__c</fullName>
    <label>StgPlacement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleEndDate__c.field-meta.xml
<CustomField>
    <fullName>StgRoleEndDate__c</fullName>
    <label>StgRoleEndDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleId__c.field-meta.xml
<CustomField>
    <fullName>StgRoleId__c</fullName>
    <label>StgRoleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgRoleStartDate__c.field-meta.xml
<CustomField>
    <fullName>StgRoleStartDate__c</fullName>
    <label>StgRoleStartDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgSector__c.field-meta.xml
<CustomField>
    <fullName>StgSector__c</fullName>
    <label>StgSector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftEndTime__c.field-meta.xml
<CustomField>
    <fullName>StgShiftEndTime__c</fullName>
    <label>StgShiftEndTime</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftId__c.field-meta.xml
<CustomField>
    <fullName>StgShiftId__c</fullName>
    <label>StgShiftId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftStartTime__c.field-meta.xml
<CustomField>
    <fullName>StgShiftStartTime__c</fullName>
    <label>StgShiftStartTime</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgShiftStatus__c.field-meta.xml
<CustomField>
    <fullName>StgShiftStatus__c</fullName>
    <label>StgShiftStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgSourceSystem__c.field-meta.xml
<CustomField>
    <fullName>StgSourceSystem__c</fullName>
    <label>StgSourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/StagingShift__c/fields/StgUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>StgUpdatedDate__c</fullName>
    <label>StgUpdatedDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/VmsJobOrderRequestHandler.cls
/**
 * Created by mrahman on 2020-11-04.
 */

public with sharing class VmsJobOrderRequestHandler {
    public static String doInsertStagingJobOrder(VmsJobOrderHelper joHelper, String stgReqPayload){
        String result;
        StagingJobOrder__c sJobOrder = new StagingJobOrder__c(  StgSourceSystem__c=joHelper.StgSourceSystem
                                                                ,StgClientName__c=joHelper.StgClientName
                                                                ,StgClient_Id__c=joHelper.StgClientId
                                                                ,StgRoleId__c=joHelper.StgRoleId
                                                                ,StgJobTitle__c=joHelper.StgJobTitle
                                                                ,StgQuantity__c=String.isBlank(joHelper.StgQuantity) && String.isNotBlank(joHelper.StgJobApplicationId)?'1':joHelper.StgQuantity
                                                                ,StgStartDate__c=joHelper.StgStartDate
                                                                ,StgEndDate__c=joHelper.StgEndDate
                                                                ,StgStartTime__c=joHelper.StgStartTime
                                                                ,StgEndTime__c=joHelper.StgEndTime
                                                                ,StgLocationId__c=joHelper.StgLocationId
                                                                ,StgLocationName__c=joHelper.StgLocationName
                                                                ,StgHasShifts__c=joHelper.StgHasShifts
                                                                ,StgCreatedDate__c=joHelper.StgCreatedDate
                                                                ,StgUpdatedDate__c=joHelper.StgUpdatedDate
                                                                ,StgFrontOfficeIntegrationSystem__c=joHelper.StgFrontOfficeIntegrationSystem
                                                                ,StgRoleRequirement__c=joHelper.StgRoleRequirement
                                                                ,StgRequiredStaff__c=joHelper.StgRequiredStaff
                                                                ,Staging_Job_Application__c=joHelper.StgJobApplicationId
                                                                ,StgCandidateRoleId__c=joHelper.StgCandidateRoleId
                                                                ,StgJobRoleId__c=joHelper.StgJobRoleId
                                                                ,StgJobRoleName__c=joHelper.StgJobRoleName
                                                                ,StgMoveOrCopy__c = joHelper.StgMoveOrCopy
                                                                ,StgTransactionType__c = joHelper.StgTransactionType
                                                              	,StgSecWatchdog__c = joHelper.StgSecWatchdog
                                                              	,StgCVRequired__c = joHelper.StgCVRequired
                                                              	,StgPostCode__c = joHelper.StgPostCode
                                                              	,StgJobCat__c = joHelper.StgJobCat
                                                              	,StgCostCentre__c = joHelper.StgCostCentre
                                                              	,StgReqPayload__c = stgReqPayload
                                                             );
        List<StagingShift__c> sShifts = new List<StagingShift__c>();

        //SAVE point to rollback the transaction in the event of error
        Savepoint sp = Database.setSavepoint();
        try{
            insert sJobOrder;
            if(joHelper.StgHasShifts.capitalize() == 'TRUE' && joHelper.stgShifts.size() > 0){
                for(VmsJobOrderHelper.VmsShift s : joHelper.stgShifts){
                    sShifts.add(new StagingShift__c(Staging_Job_Order__c = sJobOrder.Id
                            ,StgSourceSystem__c=s.StgSourceSystem
                            ,StgClientName__c=s.StgClientName
                            ,StgClientID__c=s.StgClientID
                            ,StgRoleId__c=s.StgRoleId
                            ,StgShiftId__c=s.StgShiftId
                            ,StgJobTitle__c=s.StgJobTitle
                            ,StgQuantity__c=s.StgQuantity
                            ,StgRoleStartDate__c=s.StgRoleStartDate
                            ,StgRoleEndDate__c=s.StgRoleEndDate
                            ,StgShiftStartTime__c=s.StgShiftStartTime
                            ,StgShiftEndTime__c=s.StgShiftEndTime
                            ,StgLocationId__c=s.StgLocationId
                            ,StgLocationName__c=s.StgLocationName
                            ,StgCreatedDate__c=s.StgCreatedDate
                            ,StgUpdatedDate__c=s.StgUpdatedDate
                            ,StgShiftStatus__c=s.StgShiftStatus
                            ,StgFrontOfficeIntegrationSystem__c=s.StgFrontOfficeIntegrationSystem
                            ,StgFrontOfficeIntegrationSystemEntity__c=s.StgFrontOfficeIntegrationSystemEntity
                            ,StgSector__c=s.StgSector
                            ,StgPlacement__c=s.StgPlacement));
                }
                try{
                    insert sShifts;
                    //result = sJobOrder.Id;
                } catch(Exception ex){
                    Database.rollback(sp);
                    return result='Error in shift details: ' + ex.getMessage().replaceAll('__c','');
                }
            }
            result = sJobOrder.Id;
        } catch(Exception ex){
            Database.rollback(sp);
            return result='Error in Job Order details: '+ex.getMessage().replaceAll('__c','');
        }
        return result;
    }
}