Frankbelford/uatv1ba/force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate_Audit__c/Candidate_Audit__c.object-meta.xml
<CustomObject>
    <label>Candidate Audit</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Audit No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate_Audit__c/fields/Audit_to__c.field-meta.xml
<CustomField>
    <fullName>Audit_to__c</fullName>
    <label>Audit to</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Minor fail</fullName>
            </value>
            <value>
                <fullName>Critical fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate_Audit__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate Audits</relationshipLabel>
    <relationshipName>Candidate_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate_Audit__c/fields/Date_of_audit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_audit__c</fullName>
    <label>Date of audit</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate_Audit__c/fields/Name_of_auditor__c.field-meta.xml
<CustomField>
    <fullName>Name_of_auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of auditor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidate_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Date_of_audit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_audit__c</fullName>
    <label>Date of audit</label>
    <type>Date</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Name_of_auditor__c.field-meta.xml
<CustomField>
    <fullName>Name_of_auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of auditor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>People1</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/BAuatbackup/force-app/main/default/classes/CandidateAuditController.cls
public class CandidateAuditController {
    
    @AuraEnabled
    public static string createCandidateAuditRecord(Id recordId, String auditTo, String note) {
        try {
            if (recordId != null) {
                // Create the audit record
                List<Candidate_Audit__c> CAlist = new List<Candidate_Audit__c>(); 
                Candidate_Audit__c canAu = new Candidate_Audit__c();
                canAu.Candidate__c = recordId;
                canAu.Name_of_auditor__c = UserInfo.getUserId();
                canAu.Date_of_audit__c = System.today();
                canAu.Audit_to__c = auditTo;
                canAu.Note__c = note;
                    CAlist.add(canAu);
                
                Contact candidate = [SELECT Id, Name_of_auditor__c, Date_of_audit__c FROM Contact WHERE Id = :recordId LIMIT 1];
                candidate.Name_of_auditor__c = UserInfo.getUserId();
                candidate.Date_of_audit__c = System.today();
                candidate.Note__c = note;

                insert CAlist;
                update candidate;

                return 'Audited successfully';
            } else {
                return 'Audit failed: Record ID is null';
            }
        } catch (Exception e) {
            System.debug('Audit failed: ' + e.getMessage());
            return 'Audit failed: ' + e.getMessage();
        }
    }
    
}