Frankbelford/uatv1ba/force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate__c/fields/Job_Order__c.field-meta.xml
<CustomField>
    <fullName>Job_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Order</label>
    <referenceTo>sirenum__JobOrder__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Progressed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Candidate__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Contact/recordTypes/IP_2ndTierCandidate.recordType-meta.xml
<RecordType>
    <fullName>IP_2ndTierCandidate</fullName>
    <active>true</active>
    <label>2nd Tier Candidate</label>
</RecordType>

Frankbelford/BAuatbackup/force-app/main/default/classes/PortalV2MyCandidatesController.cls
public class PortalV2MyCandidatesController {
    
    @AuraEnabled(cacheable=true)
    public static List<contact > getAllSubmittedCandidates() {
         Id tier2rtypeid = Schema.SObjectType.contact.getRecordTypeInfosByDeveloperName().get('IP_2ndTierCandidate').getRecordTypeId();
         Id currentUserId = UserInfo.getUserId();
        User currentUser = [SELECT Id, ContactId FROM User WHERE Id =: currentUserId];
        Contact userContact = [SELECT Id, AccountId FROM Contact WHERE Id =: currentUser.ContactId];
        Id accountId = userContact.AccountId;
        
        return[select id,name,MobilePhone,Email,CreatedDate from contact where accountid=:accountId AND recordtypeid =:tier2rtypeid ORDER BY Name ASC];
        //return[ select id,Status__c, Contact__c,Contact__r.name,Contact__r.MobilePhone,Contact__r.Email,Contact__r.CreatedDate,Job_Order__r.name ,Job_Order__c,CreatedDate From Candidate__c 
       // where Submitted_By__r.contact.accountid=:accountId
       // ];
        
        
    }
    

}