Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/Idea__c.object-meta.xml
<CustomObject>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Category__c.field-meta.xml
<CustomField>
    <fullName>IP_Category__c</fullName>
    <inlineHelpText>Which categories does this Idea fit into?
You can add more than one category</inlineHelpText>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Improvement</fullName>
            </value>
            <value>
                <fullName>Fix a Problem</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Shift Management</fullName>
            </value>
            <value>
                <fullName>Candidate Portal</fullName>
            </value>
            <value>
                <fullName>Client Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Description__c.field-meta.xml
<CustomField>
    <fullName>IP_Description__c</fullName>
    <description>Describe your Idea in as much detail as you can</description>
    <inlineHelpText>Describe your Idea in as much detail as you can</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Headline__c.field-meta.xml
<CustomField>
    <fullName>IP_Headline__c</fullName>
    <description>Short outline of the Idea that you have must be less than 255 characters</description>
    <inlineHelpText>Short outline of the Idea that you have must be less than 255 characters</inlineHelpText>
    <label>Headline</label>
    <type>TextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Points__c.field-meta.xml
<CustomField>
    <fullName>IP_Points__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_TotalPoints__c.field-meta.xml
<CustomField>
    <fullName>IP_TotalPoints__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Trend Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Idea Submitted</fullName>
                <default>true</default>
                <label>Idea Submitted</label>
            </value>
            <value>
                <fullName>Thinking Forum</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Further Consideration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/Idea_Comments__c.object-meta.xml
<CustomObject>
    <description>Comments or recording of vote to Idea</description>
    <label>Idea Comment</label>
    <nameField>
        <displayFormat>IDEACOM-{0000}</displayFormat>
        <label>Idea Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idea Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upvoted</fullName>
            </value>
            <value>
                <fullName>Downvoted</fullName>
                <label>Refused</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/recordTypes/Comment.recordType-meta.xml
<RecordType>
    <fullName>Comment</fullName>
    <active>true</active>
    <label>Comment</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/recordTypes/Vote.recordType-meta.xml
<RecordType>
    <fullName>Vote</fullName>
    <active>true</active>
    <label>Vote</label>
</RecordType>

Frankbelford/BAProdBackup - Copy/force-app/main/default/classes/TestNewIdeaCreationController.cls
/*
* Class Name: TestNewIdeaCreationController
* Description: Test Class for NewIdeaCreationController Class
* Date : 11th June 2019
*/
@istest
private class TestNewIdeaCreationController{
    
    private static final String COMMENT = 'Comment';
    private static final String VOTE = 'Vote';
    
    /*
    * Method Name: dataSetup
    * Description: Data Created for Idea Object
    * Parameters : none
    * Return Type: nothing
    */
    @testSetup static void dataSetup() {
        List<Idea__c> listIdeas = new List<Idea__c>();
        List<Idea_Comments__c> listIdeasComments = new List<Idea_Comments__c>();
        List<Idea_Comments__c> listIdeasvotes = new List<Idea_Comments__c>();
        
        
        for(integer i=0 ;i<=100;i++){
            Idea__c idea1 = new Idea__c();
            idea1.IP_Points__c = 100;
            idea1.IP_Points__c = 100;
            idea1.IP_Headline__c = 'New Idea' +i;
            idea1.IP_Description__c = 'use the bullets button on the toolbar.';
            idea1.IP_Category__c    = 'Business Improvement';
            idea1.Status__c = 'Idea Submitted';
            listIdeas.add(idea1);
        }        
        insert listIdeas;
        
    }
    
    /*
    * Method Name: positivetestMethodIdeas
    * Description: Test Method for NewIdeaCreationController Class
    * Parameters : none
    * Return Type: nothing
    */
    static testMethod void positivetestMethodIdeas(){
        List<Idea__c> ideas = [Select id,Name,CreatedDate,IP_Points__c,IP_TotalPoints__c from Idea__c];
        Test.startTest();
        NewIdeaCreationController newIdea = new NewIdeaCreationController();
        newIdea.Save();
        newIdea.CancelIdea();
        Test.StopTest();
    }
}