Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/Idea__c.object-meta.xml
<CustomObject>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Category__c.field-meta.xml
<CustomField>
    <fullName>IP_Category__c</fullName>
    <inlineHelpText>Which categories does this Idea fit into?
You can add more than one category</inlineHelpText>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Improvement</fullName>
            </value>
            <value>
                <fullName>Fix a Problem</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Shift Management</fullName>
            </value>
            <value>
                <fullName>Candidate Portal</fullName>
            </value>
            <value>
                <fullName>Client Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Description__c.field-meta.xml
<CustomField>
    <fullName>IP_Description__c</fullName>
    <description>Describe your Idea in as much detail as you can</description>
    <inlineHelpText>Describe your Idea in as much detail as you can</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Headline__c.field-meta.xml
<CustomField>
    <fullName>IP_Headline__c</fullName>
    <description>Short outline of the Idea that you have must be less than 255 characters</description>
    <inlineHelpText>Short outline of the Idea that you have must be less than 255 characters</inlineHelpText>
    <label>Headline</label>
    <type>TextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Points__c.field-meta.xml
<CustomField>
    <fullName>IP_Points__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Responce__c.field-meta.xml
<CustomField>
    <fullName>IP_Responce__c</fullName>
    <description>Populated if the Idea is Closed, rejected, Approved, duplicated or delivered</description>
    <label>Responce</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_TotalPoints__c.field-meta.xml
<CustomField>
    <fullName>IP_TotalPoints__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Trend Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Idea Submitted</fullName>
                <default>true</default>
                <label>Idea Submitted</label>
            </value>
            <value>
                <fullName>Thinking Forum</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Further Consideration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/Idea_Comments__c.object-meta.xml
<CustomObject>
    <description>Comments or recording of vote to Idea</description>
    <label>Idea Comment</label>
    <nameField>
        <displayFormat>IDEACOM-{0000}</displayFormat>
        <label>Idea Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idea Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/fields/IP_Idea__c.field-meta.xml
<CustomField>
    <fullName>IP_Idea__c</fullName>
    <label>Idea</label>
    <referenceTo>Idea__c</referenceTo>
    <relationshipLabel>Idea Comments</relationshipLabel>
    <relationshipName>Idea_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upvoted</fullName>
            </value>
            <value>
                <fullName>Downvoted</fullName>
                <label>Refused</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Idea_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/recordTypes/Comment.recordType-meta.xml
<RecordType>
    <fullName>Comment</fullName>
    <active>true</active>
    <label>Comment</label>
</RecordType>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea_Comments__c/recordTypes/Vote.recordType-meta.xml
<RecordType>
    <fullName>Vote</fullName>
    <active>true</active>
    <label>Vote</label>
</RecordType>

Frankbelford/BAuatbackup/force-app/main/default/classes/IdeaViewController.cls
public class IdeaViewController { 

    public String body { get; set; }    
    public Map<Id,Idea__c> mapIdeaIdIdeaCommentRecords{get;set;}
    public Map<Id,Idea__c> mapIdeaIdIdeaVotedRecords{get;set;}
    @TestVisible private String UPVOTE_VALUE = 'Upvote';
    @TestVisible private String DOWNVOTE_VALUE = 'Downvote';
    private static final String OLDEST_FIRST = 'Oldest First';
    private static final String NEWEST_FIRST = 'Newest First';
    private static final String COMMENT = 'Comment';
    private static final String VOTE = 'Vote';
    private static final String UPVOTED = 'Upvoted';
    private static final String DOWNVOTED = 'Downvoted';
    public String upvotedownvote{get;set;}
    public String ideadIdValue{get;set;}
    public String selectedSorting{get;set;}
    public Map<Id,Integer> mapIdeaTotalIdeaVotedRecords{get;set;}
    
    public IdeaViewController(){
        selectedSorting = NEWEST_FIRST;
        system.debug('++++++selectedSorting++++'+selectedSorting);
        mapIdeaIdIdeaCommentRecords = new Map<Id,Idea__c>();
        mapIdeaIdIdeaVotedRecords = new Map<Id,Idea__c>();
        mapIdeaTotalIdeaVotedRecords = new Map<Id,Integer>();
        mapIdeaIdIdeaCommentRecords = getIdeaCommentRecords();
        mapIdeaIdIdeaVotedRecords = getIdeaVotedRecords();
        mapIdeaTotalIdeaVotedRecords = getIdeaTotalVotedRecords();
    }
    
    public List<SelectOption> getSortingOptions() {
        List<SelectOption> countryOptions = new List<SelectOption>();
        countryOptions.add(new SelectOption(NEWEST_FIRST,NEWEST_FIRST));
        countryOptions.add(new SelectOption(OLDEST_FIRST,OLDEST_FIRST));
        return countryOptions;
    }
    
    public void displayComments(){
        system.debug('++++++selectedSorting++++'+selectedSorting);
        mapIdeaIdIdeaCommentRecords = getIdeaCommentRecords();
    }
    
    private Map<Id,Idea__c> getIdeaCommentRecords(){
        if(selectedSorting.equals(NEWEST_FIRST)){
            mapIdeaIdIdeaCommentRecords = new Map<Id,Idea__c>([Select id,Name,IP_Category__c,CreatedDate,IP_Description__c,IP_Headline__c,CreatedBy.Name
                                ,IP_Points__c,IP_Responce__c,Status__c,IP_TotalPoints__c,(Select id,Comment__c,Status__c,User__r.Name from Idea_Comments__r
                                where RecordTypeId = :Schema.SObjectType.Idea_Comments__c.getRecordTypeInfosByName().get(COMMENT).getRecordTypeId() Order By CreatedDate desc) from Idea__c where id=:ApexPages.currentPage().getParameters().get('id') Limit 1]);
        }
        else if(selectedSorting.equals(OLDEST_FIRST)){
            mapIdeaIdIdeaCommentRecords = new Map<Id,Idea__c>([Select id,Name,IP_Category__c,CreatedDate,IP_Description__c,IP_Headline__c,CreatedBy.Name
                                ,IP_Points__c,IP_Responce__c,Status__c,IP_TotalPoints__c,(Select id,Comment__c,Status__c,User__r.Name from Idea_Comments__r
                                where RecordTypeId = :Schema.SObjectType.Idea_Comments__c.getRecordTypeInfosByName().get(COMMENT).getRecordTypeId() Order By CreatedDate) from Idea__c where id=:ApexPages.currentPage().getParameters().get('id') Limit 1]);
        }
        return mapIdeaIdIdeaCommentRecords;
    }
    
    private Map<Id,Idea__c> getIdeaVotedRecords(){
        mapIdeaIdIdeaVotedRecords = new Map<Id,Idea__c>([Select id,Name,IP_Category__c,CreatedDate,IP_Description__c,IP_Headline__c,CreatedBy.Name
                                ,IP_Points__c,IP_Responce__c,Status__c,IP_TotalPoints__c,(Select id,Comment__c,Status__c from Idea_Comments__r
                                where User__c=:UserInfo.getUserId() and RecordTypeId = :Schema.SObjectType.Idea_Comments__c.getRecordTypeInfosByName().get(VOTE).getRecordTypeId() Limit 1) from Idea__c where id=:ApexPages.currentPage().getParameters().get('id') Limit 1]);
        return mapIdeaIdIdeaVotedRecords;
    }
    
    public Map<Id,Integer> getIdeaTotalVotedRecords(){
        List<Idea__c> lstIdeas = [Select id,Name,IP_Category__c,CreatedDate,IP_Description__c,IP_Headline__c,CreatedBy.Name
                                ,IP_Points__c,IP_Responce__c,Status__c,IP_TotalPoints__c,(Select id,Comment__c,Status__c from Idea_Comments__r
                                where RecordTypeId = :Schema.SObjectType.Idea_Comments__c.getRecordTypeInfosByName().get(VOTE).getRecordTypeId()) from Idea__c where id=:ApexPages.currentPage().getParameters().get('id') Limit 1];
        for(Idea__c idea : lstIdeas){
            mapIdeaTotalIdeaVotedRecords.put(idea.id,idea.Idea_Comments__r.size());
        }
        return mapIdeaTotalIdeaVotedRecords;
    }
    
    public PageReference inserIdeaComment() {
        //system.debug('++++++++++'+body.length());
        if(String.Isblank(body)){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please correct the following error(s):Please enter a value in comment section.'));
            return null;
        }
        if(String.IsNotblank(body) && body.length()>4000){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please correct the following error(s):Please enter a value that is no longer than 4000 characters in length.'));
            return null;
        }else{
            Idea_Comments__c ideaComment = new Idea_Comments__c();
            ideaComment.IP_Idea__c = ApexPages.currentPage().getParameters().get('id');
            ideaComment.User__c = UserInfo.getUserId(); 
            ideaComment.Comment__c = body;
            ideaComment.RecordTypeId = Schema.SObjectType.Idea_Comments__c.getRecordTypeInfosByName().get(COMMENT).getRecordTypeId();
            insert ideaComment;
            PageReference pageref = new PageReference('/apex/IdeaView?id='+ApexPages.currentPage().getParameters().get('id'));
            pageref.setRedirect(true);
            return pageref;
        }
    }
    
    public PageReference updateIdeaRecord() {
        system.debug('+++++++++++++++'+ideadIdValue);
        Idea__c idea = [select id,IP_TotalPoints__c,IP_Points__c from Idea__c where id=:ideadIdValue Limit 1];
        system.debug('+++++++++++++++'+idea.IP_Points__c);
        if(upvotedownvote.equals(UPVOTE_VALUE)){
            idea.IP_Points__c = idea.IP_Points__c + 20;
            idea.IP_TotalPoints__c = idea.IP_TotalPoints__c + 20;
        }
        else if(upvotedownvote.equals(DOWNVOTE_VALUE)){
            idea.IP_Points__c = idea.IP_Points__c - 10;
            idea.IP_TotalPoints__c = idea.IP_TotalPoints__c - 10;
        }
        update idea;
        Idea_Comments__c ideaComment = new Idea_Comments__c();
        ideaComment.IP_Idea__c = ideadIdValue;
        ideaComment.User__c = UserInfo.getUserId();     
        if(upvotedownvote.equals(UPVOTE_VALUE)){
            ideaComment.Status__c = UPVOTED;
        }
        else if(upvotedownvote.equals(DOWNVOTE_VALUE)){
            ideaComment.Status__c = DOWNVOTED;
        }
        ideaComment.RecordTypeId = Schema.SObjectType.Idea_Comments__c.getRecordTypeInfosByName().get(VOTE).getRecordTypeId();
        insert ideaComment;
        mapIdeaIdIdeaVotedRecords = getIdeaVotedRecords();
        PageReference pageref = new PageReference('/apex/IdeaView?id='+ApexPages.currentPage().getParameters().get('id'));
        pageref.setRedirect(true);
        return pageref;
    }
    
    public static PageReference CancelPage(){
        PageReference ideaListPage = Page.IdeaForum;
        ideaListPage.setRedirect(true);
        return ideaListPage;
    }
}