Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/Idea__c.object-meta.xml
<CustomObject>
    <label>Idea</label>
    <nameField>
        <displayFormat>IDEA-{0000}</displayFormat>
        <label>Idea Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Category__c.field-meta.xml
<CustomField>
    <fullName>IP_Category__c</fullName>
    <inlineHelpText>Which categories does this Idea fit into?
You can add more than one category</inlineHelpText>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Improvement</fullName>
            </value>
            <value>
                <fullName>Fix a Problem</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Shift Management</fullName>
            </value>
            <value>
                <fullName>Candidate Portal</fullName>
            </value>
            <value>
                <fullName>Client Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Description__c.field-meta.xml
<CustomField>
    <fullName>IP_Description__c</fullName>
    <description>Describe your Idea in as much detail as you can</description>
    <inlineHelpText>Describe your Idea in as much detail as you can</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Headline__c.field-meta.xml
<CustomField>
    <fullName>IP_Headline__c</fullName>
    <description>Short outline of the Idea that you have must be less than 255 characters</description>
    <inlineHelpText>Short outline of the Idea that you have must be less than 255 characters</inlineHelpText>
    <label>Headline</label>
    <type>TextArea</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_Points__c.field-meta.xml
<CustomField>
    <fullName>IP_Points__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/IP_TotalPoints__c.field-meta.xml
<CustomField>
    <fullName>IP_TotalPoints__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Trend Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/Idea__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Idea Submitted</fullName>
                <default>true</default>
                <label>Idea Submitted</label>
            </value>
            <value>
                <fullName>Thinking Forum</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Requirements Gathering</fullName>
            </value>
            <value>
                <fullName>Further Consideration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/TestBatchCalculateIdeaPoints.cls
/*
* Class Name: TestBatchCalculateIdeaPoints
* Description: Test Class for BatchCalculateIdeaPointsAfterSevendays Class and ScheduleBatchCalculateIdeaPoints Class
* Date : 5th June 2019
*/
@istest
private class TestBatchCalculateIdeaPoints{
    
    /*
    * Method Name: dataSetup
    * Description: Data Created for Idea Object
    * Parameters : none
    * Return Type: nothing
    */
    @testSetup static void dataSetup() {
        List<Idea__c> listIdeas = new List<Idea__c>();
        
        Idea__c idea1 = new Idea__c();
        idea1.IP_Points__c = 100;
        idea1.IP_Points__c = 100;
        idea1.IP_Headline__c = 'New Idea';
        idea1.IP_Description__c = 'use the bullets button on the toolbar.';
        idea1.IP_Category__c    = 'Business Improvement';
        idea1.Status__c = 'Idea Submitted';
        listIdeas.add(idea1);
        
        Idea__c idea2 = new Idea__c();
        idea2.IP_Points__c = 100;
        idea2.IP_Points__c = 100;
        idea2.IP_Headline__c = 'New Idea1';
        idea2.IP_Description__c = 'use the bullets button on the toolbar.';
        idea2.IP_Category__c    = 'Business Improvement';
        idea2.Status__c = 'Idea Submitted';
        listIdeas.add(idea2);
        
        insert listIdeas;
    }
    
    /*
    * Method Name: positiveBatchClassTestMethod
    * Description: Test Method for BatchCalculateIdeaPointsAfterSevendays Class
    * Parameters : none
    * Return Type: nothing
    */
    static testMethod void positiveBatchClassTestMethod(){
        List<Idea__c> ideas = [Select id,Name,CreatedDate,IP_Points__c,IP_TotalPoints__c from Idea__c];
        Test.startTest();
        BatchCalculateIdeaPointsAfterSevendays obj = new BatchCalculateIdeaPointsAfterSevendays();
        DataBase.executeBatch(obj);
        Test.StopTest();
    }
    
    /*
    * Method Name: positiveSchedularClassTestMethod
    * Description: Test Method for ScheduleBatchCalculateIdeaPoints Class
    * Parameters : none
    * Return Type: nothing
    */
    static testMethod void positiveSchedularClassTestMethod(){
        List<Idea__c> ideas = [Select id,Name,CreatedDate,IP_Points__c,IP_TotalPoints__c from Idea__c];
        Test.startTest();
        ScheduleBatchCalculateIdeaPoints sh1 = new ScheduleBatchCalculateIdeaPoints();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Calculate Points After 7 Days'+system.now(), sch, sh1);    
        Test.StopTest();
    }

}