Frankbelford/uatv1ba/force-app/main/default/objects/BlueArrowWorkingHours__c/BlueArrowWorkingHours__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Working Hours for Blue Arrow</description>
    <label>Blue Arrow Working Hours</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/BlueArrowWorkingHours__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <inlineHelpText>Time must be in 24 hour format</inlineHelpText>
    <label>End Time</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/BlueArrowWorkingHours__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Time must be in 24 hour format</inlineHelpText>
    <label>Start Time</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/BAProdV1deploy/force-app/main/default/classes/WorkHoursCalculatorTest.cls
/**
 * @AUTHOR      Charlie Nash (RSSGlobal)
 * @DATE        11/07/2023
 *
 * @DESCRIPTION:
 *
 * ============================================== VERSION HISTORY ==============================================
 *
 * V1.0 - WorkHoursCalculatorTest.cls created - 11/07/2023
 *
 * =============================================================================================================
 */

@IsTest
private class WorkHoursCalculatorTest {

    @TestSetup 
    static void testSetup(){

        //Create a test hours setting
        BlueArrowWorkingHours__c hours = createHoursVar();
        insert hours;

    }

    @IsTest
    static void testDateTimeInWorkHours() {

        Test.startTest();
        Boolean result = WorkHoursCalculator.isInWorkHours(Datetime.now());
        Test.stopTest();
        System.assert(result != null);
    }

    @IsTest
    static void testDateTimeInWorkHoursInvocable(){

        List<WorkHoursCalculator.FlowOutputs> results = new List<WorkHoursCalculator.FlowOutputs>();

        Test.startTest();

        results = WorkHoursCalculator.isInWorkHoursInvocable();

        Test.stopTest();

        System.assert(results != null);
    }

    static BlueArrowWorkingHours__c createHoursVar (){

        BlueArrowWorkingHours__c hours = new BlueArrowWorkingHours__c();
        hours.Start_Time__c = 22;
        hours.End_Time__c = 23;

        return hours;

    }

}