Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/ImpellamCPConnect__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RSS Global Customer Portal Connect</label>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client secret</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/DocumentID__c.field-meta.xml
<CustomField>
    <fullName>DocumentID__c</fullName>
    <label>DocumentID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/ExpireAt__c.field-meta.xml
<CustomField>
    <fullName>ExpireAt__c</fullName>
    <label>ExpireAt</label>
    <type>DateTime</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/HolidaysEndPointUrl__c.field-meta.xml
<CustomField>
    <fullName>HolidaysEndPointUrl__c</fullName>
    <label>HolidaysEndPointUrl</label>
    <type>Url</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/LiveToken__c.field-meta.xml
<CustomField>
    <fullName>LiveToken__c</fullName>
    <label>LiveToken</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/PayslipEndPointUrl__c.field-meta.xml
<CustomField>
    <fullName>PayslipEndPointUrl__c</fullName>
    <label>PayslipEndPointUrl</label>
    <type>Url</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/PayslipExportEndPointUrl__c.field-meta.xml
<CustomField>
    <fullName>PayslipExportEndPointUrl__c</fullName>
    <label>PayslipExportEndPointUrl</label>
    <type>Url</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/PaySlipFolderID__c.field-meta.xml
<CustomField>
    <fullName>PaySlipFolderID__c</fullName>
    <label>PaySlipFolderID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/TokenExpiryDateTime__c.field-meta.xml
<CustomField>
    <fullName>TokenExpiryDateTime__c</fullName>
    <label>Token Expiry DateTime</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Frankbelford/uatv1ba/force-app/main/default/objects/ImpellamCPConnect__c/fields/TokenURL__c.field-meta.xml
<CustomField>
    <fullName>TokenURL__c</fullName>
    <label>TokenURL</label>
    <type>Url</type>
</CustomField>

Frankbelford/BAuatbackup/force-app/main/default/classes/Test_AuthImpellam.cls
@isTest 
public class Test_AuthImpellam {
    
  @testSetup 
    static void sSetup() {
               
        
    } 
    
    @isTest  static void dbToken_positive() {
		
        ImpellamCPConnect__c st = new ImpellamCPConnect__c();
        st.Name='ImpellamConnect';
        st.client_id__c='12';
        st.client_secret__c='23';
        st.HolidaysEndPointUrl__c='http://example.com/example/test';
        st.PayslipEndPointUrl__c='http://example.com/example/test';
        st.PayslipExportEndPointUrl__c='http://example.com/example/test';
        st.PaySlipFolderID__c='';    
        st.TokenExpiryDateTime__c='';
        st.TokenURL__c='http://example.com/example/test';    
        st.DocumentID__c='';
        st.ExpireAt__c=Datetime.now();
        st.LiveToken__c='1234567';         
        
        
        Test.setMock(HttpCalloutMock.class, new Mock_AuthImpellam());       
       	HttpResponse res = MyDemoToken.getAccessToken();
        
        String contentType = res.getHeader('Content-Type');
		System.assert(contentType == 'application/json');
		String actualValue = res.getBody();
		String expectedValue = '{"example":"test"}';
		System.assertEquals(actualValue, expectedValue);
		System.assertEquals(200, res.getStatusCode());
       insert st;          
        ImpellamCPConnect__c icpc = [select Name,client_id__c from ImpellamCPConnect__c where Name = 'ImpellamConnect' limit 1];
        
    }
    
}