testoldcopy/force-app/main/default/objects/QBO_QuickBook_Auth_Info__c/QBO_QuickBook_Auth_Info__c.object-meta.xml
<CustomObject>
    <label>QuickBook Auth Info</label>
    <nameField>
        <displayFormat>QBO-{0000}</displayFormat>
        <label>QuickBook Auth Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuickBook Auth Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

testoldcopy/force-app/main/default/objects/QBO_QuickBook_Auth_Info__c/fields/QBO_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>QBO_Access_Token__c</fullName>
    <label>Access Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

devold/force-app/main/default/objects/QBO_QuickBook_Auth_Info__c/fields/QBO_Expires_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>QBO_Expires_In_Date_Time__c</fullName>
    <label>Expires In Date-Time</label>
    <type>DateTime</type>
</CustomField>

devold/force-app/main/default/objects/QBO_QuickBook_Auth_Info__c/fields/QBO_Expires_In_Seconds__c.field-meta.xml
<CustomField>
    <fullName>QBO_Expires_In_Seconds__c</fullName>
    <label>Expires In Seconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

testoldcopy/force-app/main/default/objects/QBO_QuickBook_Auth_Info__c/fields/QBO_Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>QBO_Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

testoldcopy/force-app/main/default/objects/QBO_QuickBook_Auth_Info__c/fields/QBO_Refresh_Token_Expires_In__c.field-meta.xml
<CustomField>
    <fullName>QBO_Refresh_Token_Expires_In__c</fullName>
    <label>Refresh Token Expires In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

testoldcopy/force-app/main/default/classes/QuickBooksUtilityClassTest.cls
@isTest(seeAllData=false)
public class QuickBooksUtilityClassTest {
   /* public static testmethod void test1(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new QuickBooksHttpCalloutMock());
        QuickBooksUtilityClass.doFetchAccessToken();
        QuickbooksSendRequestAndRecieveResponse.SendRequest('{"test":"test"}','Invoice','POST');
        Test.stopTest();
    }
    public static testmethod void test2(){
        QBO_QuickBook_Auth_Info__c quickBooksSettingInfo= new QBO_QuickBook_Auth_Info__c();
        quickBooksSettingInfo.QBO_Access_Token__c = 'test';
        quickBooksSettingInfo.QBO_Refresh_Token__c = 'test';
        quickBooksSettingInfo.QBO_Expires_In_Seconds__c = 1234;
        quickBooksSettingInfo.QBO_Refresh_Token_Expires_In__c = 1234;
        quickBooksSettingInfo.QBO_Expires_In_Date_Time__c = System.Now().addSeconds(Integer.valueOf(-100));
        insert quickBooksSettingInfo;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new QuickBooksHttpCalloutMock());
        QuickbooksSendRequestAndRecieveResponse.SendRequest('{"test":"test"}','Invoice','POST');
         QuickBookAccessTokenUpdateSchedular schqb = new QuickBookAccessTokenUpdateSchedular(); 
        String sch = '0 0 * * * ?'; 
        system.schedule('AccessTokenbtch', sch, schqb); 
        Test.stopTest();
    }*/
}