DFfullcopybackup/force-app/main/default/objects/Order_Error_Queue__c/Order_Error_Queue__c.object-meta.xml
<CustomObject>
    <label>Order Error Queue</label>
    <nameField>
        <displayFormat>OEQ-{00000}</displayFormat>
        <label>Order Error Queue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Error Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DFfullcopybackup/force-app/main/default/objects/Order_Error_Queue__c/fields/Last_Retry__c.field-meta.xml
<CustomField>
    <fullName>Last_Retry__c</fullName>
    <label>Last Retry</label>
    <type>DateTime</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Order_Error_Queue__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Error Queue</relationshipLabel>
    <relationshipName>Order_Error_Queue</relationshipName>
    <type>Lookup</type>
</CustomField>

DFfullcopybackup/force-app/main/default/objects/Order_Error_Queue__c/fields/Order_Name__c.field-meta.xml
<CustomField>
    <fullName>Order_Name__c</fullName>
    <formula>&apos;O-&apos; + Order__r.OrderNumber</formula>
    <label>Order Name</label>
    <type>Text</type>
</CustomField>

DFfullcopybackup/force-app/main/default/classes/OrderErrorQueueController.cls
/**
 * @description       : 
 * @author            : avinash_s@decisionfoundry.com
 * @group             : 
 * @last modified on  : 12-30-2025;
 * @last modified by  : avinash_s@decisionfoundry.com
**/
public with sharing class OrderErrorQueueController {
    @AuraEnabled(Cacheable = true)
    public static List<Order_Error_Queue__c> getOEQRecords(){
        return [SELECT Id, Order__c,Order_Name__c,Error_Message__c,Last_Retry__c,CreatedDate,LastModifiedDate      
                FROM Order_Error_Queue__c 
                ORDER BY CreatedDate DESC 
                LIMIT 50];

    }
}