Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/IP_TopazGlobalClientInformation__c.object-meta.xml
<CustomObject>
    <label>Topaz Global Client Information</label>
    <nameField>
        <label>Topaz Global Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topaz Global Client Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Frankbelford/uatv1ba/force-app/main/default/objects/IP_TopazGlobalClientInformation__c/fields/IP_StatusID__c.field-meta.xml
<CustomField>
    <fullName>IP_StatusID__c</fullName>
    <label>Status ID</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Frankbelford/BAFullDevNEW/force-app/main/default/classes/Test_stampdate.cls
@istest
public class Test_stampdate {

    public static testmethod void  test1()
    {       
        
        IP_TopazGlobalClientInformation__c topaz = new IP_TopazGlobalClientInformation__c();
        topaz.Name='Test topaz';
        topaz.IP_StatusID__c = 1;
        insert topaz;
        
        Test.StartTest();
        
        topaz.IP_StatusID__c = 3;
        update topaz;     
         Test.StopTest(); 
    }
     public static testmethod void  test2()
    {       
        
        IP_TopazGlobalClientInformation__c topaz1 = new IP_TopazGlobalClientInformation__c();
        topaz1.Name='Test topaz';
        topaz1.IP_StatusID__c = 1;
        insert topaz1;
        
        Test.StartTest();
        
        topaz1.IP_StatusID__c = 0;
        update topaz1;
         Test.StopTest(); 
    }
   
    
}